### ISSUE TITLE
[SUGGESTION] Airtightness

### ISSUE THREAD

**Issue by TheCuriousSkeleton** [tsunamayo/Starship-EVO#1063]
### Short Description of the issue:
My basic idea is that around the mesh of the ship and child entity's will be an outline. And where they over cross will form an airtight seal.

### Additional information:

Black - Ship
Blue - Outline

A - Not airtight
B - Airtight

![skywanderers suggestion - airtightness](https://user-images.githubusercontent.com/39653820/50740129-0d9a2e00-11e2-11e9-90bf-6d2cf5b1749a.png)

**Comment by ZachZent** [comment]
I can tell you now that unless something big has changed, air pressure will not be added. It would just be way too resource intensive. Look at space engineers if you need an example of it. Not only does SkW have to consider the normal blocks, it also has to consider bricks as well which are 1/16 the size of a normal block. On top of that are the freeform stretchy-blocks which means the game would also have to map angles to determine air pressure. On top of that are the child entities.

It comes down to what you (but mostly Tsuna) wants. Do you want to have lots of ships and ai and whatnot, or do you want just a few ships at best with air pressure?

**Comment by TheCuriousSkeleton** [comment]
As you said, it would be too resource intensive but instead of it checking constantly. It could only check if a child entity is moving, and stops checking when building until either 1 min has passed or a child entity moves. And for the free-form blocks, I don't know exactly how you would do this, I do have some ideas, but as I don't know how the free-form blocks work, I don't know if it would help improve performance.

**Comment by Senakysam** [comment]
Any time a block is destroyed, it would also need to be checked. Still sounds way too intensive.

**Comment by TheCuriousSkeleton** [comment]
The new idea: it checks when pressurising.

**Comment by tsunamayo** [comment]
Air tightness might come one day, but unfortunately it is very unlikely to be compatible with children entity. If I spend time on this one day (which I would like, there is a good synergy with crew I think) , these would be the limitation (otherwise dev would be too complex):
 - use block the same way only block are blocking light (algo is actually quite similar to light diffusion algo)
 - only on main frame (no children entity)
 - I will add blast door that would be integrated to the mechanism
 - for custom large moving hangar door and such, I would provide a "force field" that would keep the interior air tight but would allow ship to pass through. Of course it would consume a bit of energy  for gameplay purpose. 
Cheers
