### ISSUE TITLE
Sliders reverse starting point(0) when alternated / Logic connection

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1359]
### Short Description of the issue:
Obviously this is a bit overkill but it turns out when you drag a slider to go on top of another slider, doesn't matter if the bottom is 16m long and the top is 3m, the top one gets it's 0 flipped to the opposite end. To make things more odd, when you simply connect logic to these broken sliders it activates ALL of the broken sliders.
...

### Environment
- Skywanderers version: 19w29a
- Graphics Card: GTX 970

### Additional information:
![20190717104136_1](https://user-images.githubusercontent.com/32974671/61390587-ad670180-a880-11e9-94e3-b29d9512dbd5.jpg)
![20190717104627_1](https://user-images.githubusercontent.com/32974671/61390592-af30c500-a880-11e9-9013-d9d16d520169.jpg)
![20190717105142_1](https://user-images.githubusercontent.com/32974671/61390713-e7380800-a880-11e9-8cef-d42d5608229a.jpg)
![20190717105147_1](https://user-images.githubusercontent.com/32974671/61390718-e901cb80-a880-11e9-89de-ee7b6589778f.jpg)

**Comment by tsunamayo** [comment]
Hi! Thanks for testing the new update!
The children grid does not rotate to get the rotation of your parent grid, so that would explain the 0 on the other side issue. I dont think it matter, except maybe in the precise case you are trying to do ;) 
You will have to rotate your slider to make sure it point in the right direction, but I totally agree I need to add some kind of HUD display of where 0 - 1 are so you get an idea.
For the all slider activate at once issue I was not able to reproduce. Am I missing some step? Could you please send me the blueprint?
Cheers
