### ISSUE TITLE
[SUGGESTION] Different Flight Control Modes

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Starship-EVO#1480]
Currently, you steer with the mouse no matter what, meaning that if you have controllable turrets on your ship, aiming with them steers the ship as well when it isn't always what you want. My proposal is have two different steering modes that you can switch between on the fly.

The first mode would be as it currently is. You steer your ship with the mouse giving you a lot of minute control over flying. This is also good for ships with spinal weapons that need the ship to be pointed directly at what they are shooting at.

The second mode would be a free look kind of mode where you use the keyboard to steer the ship, and be able to look all around you with the mouse. This would be for ships that use turrets, or for people that want to still be able to fly while getting some situational awareness.

Each mode would have it's own keybinds in the menu for people to customize. The reason it would be togglable while flying is for ships that have both turrets and a spinal gun, giving more freedom to builders.

**Comment by tsunamayo** [comment]
What about having some orientation control when you are in free view? Right now you get the same translation control when in tab, which is cool to park your ship but has no use for gameplay. Thanks

**Comment by Senakysam** [comment]
That could work.

**Comment by ZachZent** [comment]
Am I the only one that controls their ship with WASD-QE and not the mouse?

**Comment by Majikmonster** [comment]
I like the idea of having control in free look mode, although I'm not sure what keybinds would be available since the controls are set for other uses as hotkeys and the middle mouse button is taken (not everyone has a 5-button mouse). Arrow keys or numpad, perhaps?

- Having some sort of thrust override would be good for both proposed modes as well, as having ships with turrets try to lead a target as the mothership makes it more difficult by adding its own maximum velocity is a pain.
- Additionally, ships with high top speeds accelerate at an incredible pace even in WASD mode, so setting a lower top speed rather than jolting to the ship's cap would be safer for exiting hangars and navigating hazardous areas like asteroid fields or space station docks.
- It would also be good for setting cruise control when boosting.
