### ISSUE TITLE
[Suggestion] Hinge rotation speed

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Starship-EVO#1518]
### Short Description of the suggestion:

While building a mechanism that requires multiple hinges to move at the same time, I found myself frustrated with the fact that some hinges won't be in sync with the other ones if they're travelling different distances or have different masses. This has led me to believe that hinges, rails, and rotors are missing a crucial setting that can improve them tremendously: the ability to change how fast they can move.

Attached below is an image of a concept rotation speed field in a rotor's menu:
![image](https://user-images.githubusercontent.com/37738021/68532467-bdb65700-031d-11ea-800d-40f564702328.png)

It would make creating landing gear and other complex mechanisms a lot easier to make if we had the ability to change how fast a hinge could turn, a rail move, or a rotor to rotate. This could be balanced by having the child entity rotation be capped to a certain speed depending on its weight.

**Comment by Xerma** [comment]
Would it be possible to have the hinge/rotator/slider produce heat? If so players could have the freedom to increase the speed at the expense of heat. 

That being said, entities that don't increase their speed past the default setting don't get any additional heat from these blocks nor do entities that are slower than the default.

In some situations people may want to increase their entity speeds. Exterior doors/hangar doors are one example where you may want to have it close faster than grass grows. Doors that are meant to protect something will sometimes be a few meters thick and this decreases speed loads. Not to mention should players want to land their larger ships you would either need some, small, ridiculous looking landing gear to extend at a reasonable pace or you may end up waiting a hot minute. Another thing is elevators. At the current default speeds I made an elevator using block sliders and tested speeds with minimal amounts of bricks and blocks and came to the conclusion that it would be faster to use the stairs than take the elevator. It would also come in handy with cargo transports within larger vessels to move cargo around internally (basically a horizontal elevator.)

I know balance is a large factor but I think being able to not only slow entity speeds, but boost them too, could go a long way for varied builds. I personally think heat would be a great way to let players boost speeds and the values can be tested and changed until they feel right should you go for this method.

**Comment by ZachZent** [comment]
Starmade has something similar. Maybe instead of a separate block or an integrated feature, a speed control logic brick can be added.
https://starmadepedia.net/wiki/Rail_Speed_Controller

But yes, there is a big need for either speed controls and/or a separate faster rail. Elevators that are anything more then a platform is extremely slow. Stacking rails shouldn't be the only way to speed something up. Don't want more child entities then needed

**Comment by ZachZent** [comment]
Here is what people want to do which would be impossible without speed controls or using probably 50 sliders at the current speed
https://media.discordapp.net/attachments/271723356795961345/642808430704328723/InvisibleHandDoor.gif?width=320&height=137

**Comment by Dwarf-LordPangolin** [comment]
> This could be balanced by having the child entity rotation be capped to a certain speed depending on its weight.

I could be mistaken, but I believe that's what he's actually planning. IIRC, he stated previously that we'll eventually be able to make objects move _slower_ than their maximum possible speed if we want to, and that's awesome; I'd love to be able to slow some of my doors and landing gear down, so they don't look like early stop-motion animation. ;)

However, I don't think massive objects like that blast door in the gif should be able to move fast; it would look kind of silly in-game, like it does in that gif, and balancing turret speed with more heat would be **much** harder than simply making turret elevation and rotation be directly related to mass. The last thing we want is turrets that are powerful enough to one-shot fighters, and fast enough to track them. More heat wouldn't make that any less frustrating for the people getting hit by those, and the turret wouldn't actually be generating extra heat for long enough for it to make a difference; spin, pop the fighter in one shot, stop moving.

I like Popka's idea of a speed control, and I think Tsuna said we'll get that eventually, but as far as being able to "boost" the speed above its mass cap, I'd rather not go there. The current model allows the player to tweak their turrets for their ideal balance of speed, damage, or armor, which is a tried and tested method of balancing.

If things like elevators are too slow ATM, then the specific values might just need to be tweaked. And they might well need that; I can't test this yet on my auto-turrets because of the previously reported turret bug, but based on how fast the turrets turn on their rotators when directly triggered, I think even small turrets might not be moving fast enough to track fighters.

**Comment by ProPeach** [comment]
I agree with Dwarf Lord Pangolin. Additional options where it comes to slowing down moving entities to match eachother/sync up would be of great use, but boosting child entity speed becomes exploitable real fast. I do agree that the current max turn/slide speeds could be tweaked (the sliders are especially slow as Xerma pointed out), but I don't think we should be able to increase their speed at the cost of heat or another variable

**Comment by Lsutehall** [comment]
The exception I would ask for would be for some kind of "catapult" block for launching fighters, where we definitely want something that is much faster than a current rail.

Otherwise I agree with being able to change speeds. For example, I don't think you can make a cantilever mechanism work correctly at the moment due to the speed different between the parts.

**Comment by tsunamayo** [comment]
Hi, yes I want to add a speed setting. I will add more info like child mass and max speed in the setting windows also. @Dwarf-LordPangolin is right, I cant go too far up for balance purpose, although for now turrent are more a cheat than anything. But I can increase max speed for slider, slider dont really have gameplay impact. I keep you all posted when it is implemented, cheers!

**Comment by tsunamayo** [comment]
Implemented some time ago. Thanks
