### ISSUE TITLE
[Suggestion] Feedback on engine placement effect

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1528]
Following on from the November Kickstarter update, it looks like you're planning on tying thruster placement to ship characteristics. A forward placed thruster increases max speed and acceleration, while a thruster placed sideways increases angular acceleration and velocity. Please correct me if I've interpreted it wrongly, I'd hate to misunderstand.

Personally, while I support the aim of this change I don't think this is the best way to go. It seems to contradict your point that thruster placement won't have any effect on the look of a ship (The classic Star Wars only forward facing thruster look). If as I think is planned thrusters damage blocks in their exhaust plume, sideways placed thrusters will take up a significant portion of the side of a ship, forcing a particular aesthetic.

As a counter suggestion, how about a GUI similar to that of a hinge or rotor turret axis control, but in this case it brings up a slider. On one side is angular velocity, and the other is forward velocity. Or perhaps max speed/maneuverability to keep it simple. This way a player could choose the percentage of an engine block to dedicate to a particular flight characteristic, while not having the best of both worlds. A 50/50 split would deliver a balanced performance, while a 90/10 would have a heavy focus on maximum speed at the cost of maneuverability. This would be on a per engine basis, so two separate stretched engines could have two different sliders. Perhaps if this proves too awkward, a single slider in the ship core could replace these.

This stat could also be shown on the GUI menu when you look at an engine or in the ship core

I think this is the best way forward for giving players plenty of freedom in the flight characteristics of their ships, while also not forcing them to allow for sideways placed thrusters in their designs. This percentage stat would of course not be the only thing that would change how a ship flies, the ships mass and total thrust will also change things - not all 50/50 ships for example will fly the same way.

I look forward to hearing your opinions!

EDIT - Exodist made the great suggestion of a graphic to show the proposed change. Here's the Ship Core GUI with the changes applied. In retrospect I think it's a lot better to have the slider in the Ship Core rather than on every engine for reasons that Exodist points out in his comment.
![image](https://user-images.githubusercontent.com/27857711/70945783-d23cec00-204d-11ea-9f67-d6513a2fd3fb.png)

**Comment by PopkaAkula** [comment]
In my opinion having the way engines are placed affecting the way a ship behaves in terms of maneuverability and speed does make a lot of sense, it goes against the arcade and less realistic feeling that the game currently has, it would limit how people design their ships and would make many of the ships look the same because of optimal engine placement. I like Propeach's idea of customizing how an engine would behave via a menu, because then you can have as much control over the maneuverability and speed of a ship while not limiting people's creativity. 

Just as an idea (if you do add the new flight control model) maybe one can have the ability to customize which engines are for maneuvering and which are for speed in the ship core via a neat graphical representation of the ship. This way you can have it so that certain engines fire more or less depending on which way you turn. It would add some more gameplay elements, and more customization aspects to players ships.

**Comment by OverSavior** [comment]
Just as a nerd I am, today's morning I was thinking about why forward-only scheme could still make sense. The possible explanation I came up with was that such engines could function as 3d rails, if it makes sense. The engine and everything attached to it would easily move forward and backward, but moving along other axes would be a lot more difficult as let's say some field created by the engine or another module would prevent that. It's like an aircraft wing, but instead of wing there's field and instead of air there's... basically any matter. Trying to move along other axes would be the same as trying to accelerate in non-newtonian fluid. I guess you get the idea.

So, in Skw I'd imagine this as part of the way how all engines work or as a separate block/module. Let's call it a "space wing" module. While this would probably be somewhat hard to implement, this would allow for two different approaches in planning spacecrafts. With forward facing engines and a bunch of space wings the ship would function more like those in SW, while with having engines facing every direction and no space wings you'd get a more realistic behaviour model. SW-ish ships would have better maneuverability, while realistic-ish ships would have much better strafe speed and could face any direction when moving.

**Comment by ExodistSKY1** [comment]
One of the major pulls that Skywanderers currently has is its simplicity. 

    A lot of players want to make (or download) a sweet looking ship and take it on adventures, either with friends or solo... and some just want to watch the galaxy burn.

I have always viewed the Skywanderers universe as far more technologically advanced our own.  This allows for all sorts of designs and builds to be feasible and make sense in SkyW's. Old looking ships, near future, far future, possibly organic looking. Each builder has different aesthetics they like / and are good at. Allowing us the freedom to not compromise on what we want and keeping it simple is fantastic, and peaks the interest of a broader player base. I personally do not like the aesthetics of space engineers, it makes sense in reality, but is very limiting.

I would prefer the extreme simplicity of a  "**single slider in the ship core**"  as proposed by ProPeach
as it saves time from having to change each individual stack of engines. Although ProPeach's "GUI" proposal is also good counter.

**Comment by ultrak2k** [comment]
I don’t know what to contribute to this idea but if you wanted a fighter, you’d need side thrusters which would look wierd, so I gotta agree. Unless all of us have misunderstood and side thrusters just give buffs to side speed which would also be wierd, I gotta agree with this idea

**Comment by tsunamayo** [comment]
Okay I see - I will think about it more. 
A few random though:

- I am not a fan at all of the slider, I would like to make it design based if possible. I keep it as a last resort solution
- So I need a brick/block of some sort, that would increase angular speed / acceleration
- Instead of making a new block, why not using the same thruster block? It make a lot of sense to me (as it should for the player). Actualy I got this idea looking at your build, a lot of people are putting thruster on the side it seemed. I wanted to make a vernier brick for example, but I came to the conclusion that the best "Skywanderers" approach is to give the player a mini thruster and let them build a vernier looking grape of thruster if this is what they want!
- what should happen when people put thruster sideway? I dont want to prevent it, but it seems odds that they add maximum velocity. A logical answer is that they should add angular agility right!
- I have a lot of problems with plume / trail  (perfs, look). So I will remove them as they are, and work later on on a custom solution that would only add an aggregate trail for forward facing thuster.
- As opposed to space engineer, this is not newton physics all the way, you can put your thruster were you want, and you can put a lot less.
- Most importantly I will also make a smaller truster brick. It will be different, it will be a round one (that stay round when scalling), that look like a ion thruster. I think it would fit well!
- I didnt plan on having the player to put many side thruster, like a 10 to 1 forward to thrust ratio seemed like a good starting point. (for average value).
- In the worst case if you guys dont like the look of having side thruster, I can make a dedicated angular velocity brick! If you have ideas...

=> So I think at this point the best is that I give you the new mini brick thruster and the new logic, and we see if that looks okay in your build.

Cheers, thanks for the constructive feedback, I like that it helps a lot!

**Comment by ProPeach** [comment]
Thanks for the response!
I can totally understand wanting to have it design based, it does make a lot of sense and introduces a bit of fun
Using the thrusters again does seem like a simple idea, but in my opinion putting them as they are on the side of the ship is too limiting. We actually use thrusters on the side because we love the glow effect! It's perfect for heat vents and glowing accents. If we had a toggleable light block which produced a similar bloom I'm sure lots of players would use that instead.
Personally I would agree with removing the trails. They're very cool, but can look a little messy sometimes. Classic exhausts seen in most sci-fi shows would work great.

Your idea sounds similar to Reaction Control Thrusters (RCS) a bit like this?
![image](https://user-images.githubusercontent.com/27857711/70954187-07543900-2064-11ea-8173-71338908d96d.png)

I'm a little apprehensive about the idea, they seem quite hard to balance. Having such a small profile, they would need a very high heat/energy requirement to prevent players spamming them across the hull.

Ideally, thrusters should be kept at the rear like they are now. Perhaps if we could place down a block that looks like regular thruster and is placed like a regular thruster, but produces more angular acceleration than linear. That way you can configure your thruster array with the amount of angular/linear thrusters you want, while having them all visually appear to be the same.
I realise that now we have two very similarly looking thusters, but you could differentiate between them with a tooltip or hologram that's visible when you hold a thruster block in your hand.

**Comment by Garrett-C** [comment]
Perhaps it would be possible to have it both ways? Have some form of gyro block or equivalent which you can use to increase your angular velocity but if you put a thruster sidewards it would act like the gyro. Maybe you could even have them act a little differently where the gyro uses energy but the thruster uses fuel etc. Give players the option but also some reasons for one or the other.

**Comment by ExodistSKY1** [comment]
To piggy back on Propeach's counter proposal, another way to differentiate between the two thruster blocks/bricks could be to recolor the red wires to that of a different color, possibly Yellow. 

I understand why you wouldn't want the slider and I 100% back the idea of having it be design based. If the slider option is chosen making it only able to be adjusted in a shipyard could help. 

Adding, "Classic exhausts seen in most sci-fi shows would work great" as suggested by ProPeach would be a great alternative!

**Comment by tsunamayo** [comment]
Okay now that you have some experience with the new side thruster how does it feels? Thanks
