### ISSUE TITLE
[Suggestion]  Spaceship control stats & Thruster placements

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#1533]
In addition to suggestion  #1528  and the quote from the recent Kickstarter update below:

"I improved the spaceship control stats by making them thruster based. I will publish a spreadsheet full of number for people who want to geek out and help me calibrate everything, but in a nutshell thruster placed in the forward axis will provide forward thrust while side thruster will provide maneuverability and anti drift (make sense). But the things is not 100% physically accurate in the sense that the exact position wont matter, you can have more freedom in designing your ship. I also added a small thruster brick (I will add mini reactor soon also)"

I feel this would still effect and change most builders aesthetics, even with the thought of not having to worry about needing them all over. 

   I was thinking earlier and this is what I came up with that tackles both the aesthetics problem and wanting to keep the ships thrust integral with the way the ship has been designed as opposed to a slider. 

   Using tech/code (I am not sure which) you already have implemented in the game with the rail block and the rail extender block. The rail extender block can only be placed on a rail system.   

   My suggestion:  Adding a new "thruster extender block" than can only be placed (and stretched) on the backside of the currently in game thruster block. This would in a sense add a Gimbal effect to the ships engines allowing for the same system you already have implemented, just limiting the placement of the enhanced thrusters to locations that will already be dedicated for engines by the ships builders. 

Let me know yall's feedback!

**Comment by talrey** [comment]
You didn't mention the Capacitor Add-On block but I feel like this "Gimbal" block would be very similar, an add-on block that connects to a System block and modifies it. Whereas the Capacitor boosts / could boost a thruster's forward speed (is this a thing already? I don't recall), the Gimbal could improve turn rate.

The game engine already has the code in place for Add-Ons like this because of Capacitors, I think this would be a good application of that. Plus, maybe Gimbals could be added to other System blocks as well. Capacitors can be attached to Reactors or Shields, maybe attaching a Gimbal to a shield could boost one side of a shield while weakening the other? Several people on the Discord are interested in "directional shields" from what I've seen. Plus, Trench Run anyone? "Lining up for attack run. Stabilize your rear deflectors!"

**Comment by ProPeach** [comment]
I totally agree, "Gimbal" add-on like the already existing Capacitor block would be ideal for this. You can't fill your ship with them because you can only place them on the back of thrusters, and they don't alter the ships exterior look but still offer a design choice for how your ship flies. 
I think the new add-on would need to increase your maneuverability at the cost of maximum speed to give an effective trade off between speed and agility rather than a flat boost to both.

**Comment by tsunamayo** [comment]
Have you seen the new thruster design? It is more low-key. 
I cant really use the current addon tech as the thruster block re-stretch. I will think more about potential options, maybe repurpose the repulsor block?
Anyway for now you try to see how the mini thruster could fit in your design.
Cheers

**Comment by ExodistSKY1** [comment]
The update is awesome so far!  I am finding ways to implement the new thrusters into my designs. As a thought others have had balancing will need to be done as expected. But so far it is great. A question I have is will we need to have the thuster ends exposed within our designs?

**Comment by tsunamayo** [comment]
I would like to find a cheap way to implement this, but for now I wont have the time to do it.
That look a bit silly to hide it behind things for sure, but I guess who I am to judge!
What I dont want is people finding themselve forced to hide them because thats better for gameplay, but they dont like the aesthetic of it all...

**Comment by ProPeach** [comment]
I like the look of the new brick thrusters, although because they are round they can be tricky to fit into the square holes that the building system makes. 
The main problem with hiding thrusters behind hull isn't aesthetic, it's for gameplay balance reasons. At the moment, the best option for a combat ship is to place all its side thrusters underneath its hull so that they are best protected and the enemy can't see them. Some kind of cheap check to make sure that they're placed on the outside of your ship would be ideal to prevent this, although I recognize it's difficult as players like to decorate their engines with grills and borders.
The brick thrusters are also much more powerful than the block thrusters, so much so that I don't think preventing them from going into hyperspace is enough of a nerf. Making brick thrusters less powerful but increasing their effectiveness when placed sideways would help with this


This is what I imagined the add-ons would look like. 
Repulsors - Gimbals for agility
Red cylinders - Capacitors for increased speed or afterburner boost effect - Not sure this is needed as the player can just stretch the engine longer if they wanted a faster ship
Yellow circles - Unused add-on slots
![image](https://user-images.githubusercontent.com/27857711/72275730-620e8f80-3626-11ea-8824-b01863bb0fdc.png)
This is a comparable system to how you've outlined weapons to function with a core block and add-ons so will fit well into Skywanderers in my opinion
