### ISSUE TITLE
[Dev - Feedback] Hovercraft!

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#1568]
Okay guys did  some of you tried the new overcraft?
Any feedback or issues? It has the same acceleration issue as ship, I am working on it.
Also if some of you had some cool blueprint to share that would be cool!
Cheers

**Comment by Aiwii** [comment]
my rig isn't great but I have a few issues with hovercraft https://streamable.com/e140g

**Comment by tsunamayo** [comment]
Okay this looks like a bug... Could you please send me the blueprint? Not sure if it can work with asymmetric antigrav unit though, but maybe I can tweak my code a bit to make it work!
Cheers

**Comment by Aiwii** [comment]
Not the exact one in the video cause I dumped it after it wasn't working properly but this is the only save I have of it
[Bike.zip](https://github.com/tsunamayo/Skywanderers/files/4106285/Bike.zip)

**Comment by ExodistSKY1** [comment]
![20200110154717_1](https://user-images.githubusercontent.com/45324484/73042785-19c24f00-3e28-11ea-9642-8bd4a34cdc27.jpg)
![20200110154734_1](https://user-images.githubusercontent.com/45324484/73042790-1fb83000-3e28-11ea-9460-95e18c1bca62.jpg)

I like the hover craft and was going to mention the speed issues.

A thing that is kind of frustrating is when going full speed and hitting bumps I get too much air and tend to launch myself into space. I think the 1G needs to be changed a bit more to compensate for this. (this also includes the player jump height at 1G)

**Comment by ProPeach** [comment]
They're great fun! I find the swiveling repulsion and relatively smooth ride very satisfying, the simple physics involved in balancing your craft is also a nice touch.
I agree with Exodist on the gravity front, 1G does not feel as strong as it does in real life so you often get launched into the air just from a slight slope. The rate of turn/max speed also seems to be very high even with a relatively small repulsor/thruster to mass ratio but it sounds like you're already on that case.
Overall they're a really fun addition and I can't wait to see #gallery filling with hovercraft builds

**Comment by Lsutehall** [comment]
I've made a little hovercar. I found balancing the hover thrust a little tricky TBH, it kept tilting in one direction and floating off in the other!

Left-hand seat drives it like a hovercraft, right-hand seat flies it as a ship.

[Hover car 1.6.mps.zip](https://github.com/tsunamayo/Skywanderers/files/4125274/Hover.car.1.6.mps.zip)


![20200128230723_1](https://user-images.githubusercontent.com/40872394/73313583-8a4fde00-4223-11ea-90f0-fd2fb4203d9c.jpg)

**Comment by ProPeach** [comment]
Hearing more from the community and playing with them more, I do think that the balancing of a hovercraft is a bit too sensitive. Even a few more bricks on one side for an asymmetrical detail is enough to cause a list to that side. If there was a bit of a grace region for balancing, say you only need to achieve a 90% balance on your craft to keep it stable, that would help with some of the challenges with building these.

Also, can you reduce the bounciness of them a little? Some damping on the vertical movement would help with handling too on changing slopes.

**Comment by Dwarf-LordPangolin** [comment]
The short feedback is: they're **awesome**.

The longer version: the overall execution of them is excellent. The balance mechanic is a little tricky to figure out at first (not in a bad way), but once you get some idea of how it works, it's fun, and forces players to actually put some thought into their design beyond mere appearance, which is always good. So, the balance thing is fun. I think the feedback others have given about making it a _touch_ more forgiving might have merit.

The simple fact that they hover on water is _so damn cool_.

Suggestions: apart from the high sensitivity the others have mentioned, I think a small degree of pitch control would be good. It's good that players are capable of crashing, since too much handholding isn't a good thing, but ATM there's very little they can do to avoid crashing at higher speeds.

It was interesting to see others mention the feeling that 1G doesn't feel heavy enough; I thought the same thing might be true with ship's gravity as well. Regardless, they do feel a bit bouncy here.

The ability to set them right-side up once flipped, either manually or automatically, would be good.

As is true for space ships, throttle control would be nifty.

A small degree of vertical movement ability might also come in handy -- either to "jump" over obstructions, or to get them up into hangar bays, since I'm can't be alone in wanting to put a speeder bike on a ship for exploration of new worlds.

Aesthetically, they'd benefit from the option of a more motorcycle-ish seat, but I'm guessing more seat types would be something for later in development, once more core systems are implemented.

Summary: they could stand a little tweaking here and there, but as an initial implementation they're really good!

![20200202013315_1](https://user-images.githubusercontent.com/33041786/73604858-d751ee00-455c-11ea-9a7c-ee38dfcb2298.jpg)
