### ISSUE TITLE
 [Dev - Feedback] Plan to make small figthers more powerfull

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#1571]
Okay here is my plan to balance small fighters and brick sized systems and weapons.

For now it seems that smaller craft have a lot of heat to spare due to the surface heat bonus.
I could always nerf surface heat (and I will use a smarter computation as a start), but I still need to come up with a solution to make fighter a bit more interesting, as 1/64 less powerful system is never gonna cut it.
Here is the plan:
 - I make bricks massively more powerful compared to their size. Like 25% as powerful (as a start), instead of 1.5%. Ie laser damage or reactor output.
 - But I make them greatly heat inefficient (not decided yet, but several time). Okay for smaller ships as they have a lot of heat delta, but for larger ship it is gonna be a lot more interesting to use standard blocks. Larger ship have a lot of room inside, so I guess people will still want to use the bigger version (unless you want to sneaky hide systems)
 - When crafting comes the resources needed will also be scaled consequently, (at least a bit more than their power, if it is 25% ratio then crafting cost should be 50%). It is also okay because fighters are small, so overall crafting cost is gonna be quick to acquire.
 - Power requirement would scale up but be at the same ratio as larger block. I will see if I need to nerf them also later on.

Tell me if you see any drawback to this! Cheers

**Comment by ProPeach** [comment]
This is going to be quite the tough one to balance, looking forward to it!
I agree that brick systems will need some kind of edge to make up for their small size. Making them more powerful seems like the obvious choice and could well work, testing is going to be key on that one.

Heat will be integral to this for sure. I noticed that in your Excel sheet there's a flat heat dissipation gain per surface area unit. To make small ships even more heat efficient, I propose using a surface area to volume ratio with balancing constant instead. Imagine you have two identical cubes. Separately they have a high surface area to volume ratio, if you put them together the volume doubles but the surface area of the new shape does not. This would mean that smaller ships get a further buff to their heat dissipation by surface area that doesn't apply as much to larger ships.

Personally I think that as long as brick systems are more powerful than their block counterparts players who want the most out of their ships will always use them unless their high heat production makes block systems more favourable. It'll be tough, but I think using your method we can find that balance.

You mentioned a while ago that you were thinking about having small, bomber like craft play a more "disruptive" role in combat rather than being straight damage dealers. Perhaps if other weapons that played a more strategic role were only available in brick form you could achieve this play style. Ion cannon like weapons to disable or slow turrets and systems, maybe dumfire missiles with small AoE but high damage that require a close, accurate drop.

Another thing that would separate brick and block weapons is range. Say if your brick weapons could only fire at targets for example 300m away before losing the majority of their damage, that would effectively limit them to anti small craft duties like point defence or fighter mounted weapons as they can chase down a ship to get within that range. This coupled with having a high fire rate in brick weapons vs the slower, longer range fire of block weapons (we all know that fighters are so small they can evade our turbolasers!) would separate their tactical uses nicely so that spamming brick weapons on a large ship becomes borderline useless, even if in theory they do more damage.

Looking forward to hearing everyone else's views!

**Comment by ExodistSKY1** [comment]
As always ProPeach's response was very well thought out and written. I feel what he had mentioned would help to make fighters/small craft far more viable as opposed to just Novelties.

to receive the dog fights you would like to see I think the top speed is fine but maneuverability needs to be dropped and scaled in a far better way. to include the acceleration ratio and going from zero to mok Jesus in half a second is a little much and i think it would lead to an undesirable metta. 

I like the resource idea you have Tsuna, it gives a good simple fork in the road, and with Peach's idea to limit the distance (Possibly a little more than 300m maybe 500ish except for missiles and rockets those need a little bit more of a range but should be more effective the closer proximity they are used within) of brick based weapons could lead to good gameplay and a good balance (not that a single fighter/bomber should be able to take out a capital ship though) 

rather than heat inefficiency, could you use a scaling system that the more brick based systems on a build the more inefficient they become?

**Comment by ZachZent** [comment]
An issue I see with fighters vs larger ships and in some cases large ships vs large ships is the shields. Ignoring going inside the shield bubble which isn't always possible, it isn't hard to place many shield blocks in a very small space making the shield nearly indestructible, especially to fighters who use brick weapons. For example I have a fighter that shoots 8 per second automatically (two sets of four) each doing nearly 200 damage per shot, 2,400 per second assuming all hit. It took around 3 minutes for the shield to finally break on a 50m ship. Five-ish seconds later it was up to full power. If shields can get that strong in a relatively small space, missiles will be the only reasonable way to damage a large ship. A missile meta which given the limited nature of missiles will not be very fun.

I am not sure about the solution to this. Only one I can think of is rather then individual shield blocks which can be spammed, a single shield generator system similar to the gravity generator.

**Comment by Dwarf-LordPangolin** [comment]
My two cents on the conversation thus far. Peach really hit the nail on the head here:

> Personally I think that as long as brick systems are more powerful than their block counterparts players who want the most out of their ships will always use them unless their high heat production makes block systems more favourable. It'll be tough, but I think using your method we can find that balance.

Making the smaller weapons more powerful than the larger weapons is something that happened in Space Engineers, and it didn't end well. Players just took the small weapons and spammed them on the larger ships. It was basically this:
![20191010022141_1](https://user-images.githubusercontent.com/33041786/73125283-c278c780-3f6a-11ea-8b68-26b4de477fac.jpg)
The result was that [ships literally got cut in half](https://steamuserimages-a.akamaihd.net/ugc/948467829854880420/0490B1917048B896F9018267AF7361740D006B0A/). Plus, these caused huge amounts of lag.

I don't think adjusting the heat ratio of block vs brick weapons would solve that by itself; larger ships will always have a greater total heat budget to play with, and with the current values at least, heat generation really isn't a problem for either fighters or large ships. If brick weapons have awesome damage but generate lots of heat, players will just build ships with _tons_ of brick guns; heat generation doesn't matter if you end the fight fast enough, and since ATM it's really easy to get under ships' shields (more on that in a second), fights can be ended very quickly.

Peach's suggestion about range, on the other hand, is an excellent addition. It means that fighter weapons won't be useless, but would be less useful for big ships than block-scale weapons. It also means that fighter pilots get to use a fun high-risk, high-reward style of play: it'll be very dangerous getting close enough to big ships to actually be a threat to them, but if you can pull it off, it'll be worth it.

I would take Peach's range idea, and make one addition to it: make the projectiles of brick weapons (shots, missiles, anything that's not hitscan in other words) faster than those of big ships. Fighters are going to be tougher targets to hit than big ships, even at closer range. Fighters aren't the only things using brick weapons: the defenses on big ships meant to target fighters will use them too. And the point defense against fighters is going to need to have a chance of taking them out before they cross that 300m line. And since those brick weapons won't be doing 100% damage, their shots need a better chance of hitting.

But regardless of whether brick shots go faster than block shots though, Peach's idea should be implemented.

- - - - - - - - - -

One related thing that needs to be brought up is the issue of Ship Speed vs Weapon Range/Speed. In a nutshell, combat in Skywanderers currently involves a lot of accidental ramming, because the ships are so fast, but the weapons are so slow and so short-ranged, that it's impossible to fire anything that's not a turret at the target for more than a few seconds before running into them.

The reason I bring this up is that Peach's suggestion about reducing the range of brick guns is, I think, the correct one -- but it won't have the desired effect with the current values for ship speed, weapon speed, and weapon range. Making brick weapons only effective at close range won't solve the problem because currently **all** combat takes place at very close range. It's very easy ATM to get inside that 300m bubble, at which point there won't be much reason not to use brick guns. Heck, half the time I accidentally ram the enemy ship and fire my weapons **under** their shields!

A lot of the fighters that people are building go over 300m/sec easily; giving fighter weapons a 300m effective range, with Peach's sharp dropoff after that, means they've only got one second of fully effective fire on a stationary target before they've passed it. Like I said, I agree with Peach's range idea, I just feel the 300m number will probably need to be revised upwards, because the range of all weapons needs to be revised upwards. (Though as Peach noted, 300m was an example; his idea is perfectly sound regardless of the particulars.)

I would:

1. Keep ship speed where it is -- we certainly don't want it going lower, given how big the game's universe is.
2. Make hitting things viable at long range. This needs to be achieved by:
2a. Increase the range of all weapons -- the faster the ships, the longer ranges need to be, or combat gets very messy and turns into a ram-fest.
2b. Increase the speed of all shots (anything that isn't a hitscan weapon). Again, the faster the ships, the faster shots need to be, for the same reason as Item 2a.
3. Increase the _relative_ speed of brick weapon shots. Because their targets will be relatively harder to hit, and you want anti-fighter turrets to be able to at least start damaging fighters before those fighters get close enough for their weapons to be 100% effective.
4. Increase the heat of brick weapons like you were planning on doing.
5. Add Peach's brick weapon ranged damage dropoff idea. I really think that is the best solution for discouraging players from spamming brick guns.

All this together would mean that large ships can engage each other in prolonged slugging matches at long range (which we all love from sci-fi!), with the fighters zipping around in the middle dogfighting, or making daring attack runs on the capital ships.

- - - - - - - - - -

Zach also has a very good point about shields; they're a bit too good of a defense right now. I don't think they should be weaker (though I could be wrong), but I do think that the regen rates need to be lower. It's currently possible to make a 100m ship with strong shields that can come back up _really_ quickly after being brought down. In Star Trek or Star Wars, whenever anyone says "the shields are down!" it's a big deal, very dramatic. That's true for the fighters in Skywanderers right now because they have almost no hull, but not the big ships; losing your shields on a big ship ATM is no big deal because they come back up super-fast. If I remember correctly, the plan for shields was to let ships have weak shields that could regen quickly, strong shields that took forever to regen, or a compromise in the middle. The current regen rates are just too fast, at least for strong shields.

**Comment by tsunamayo** [comment]
Thanks for your contribution guys, I havent read everything yet though (thx @Dwarf-LordPangolin ) ;)
Yes limiting range could also be a valid option.
Just keep in mind @Dwarf-LordPangolin that smaller weapon will still be less powerful. You are limited to a stack of 4 for each weapon unit. So the total piercing power will be a lot smaller on brick size weapon (ie it will break a layer of hull but not go much below that) I think it is quite important as it allows you to start hitting systems beneath.
If heat is not a factor on larger ship too then I just need to up heat generation... That is a different problem.
If people really wants to use smaller brick then fine, the only advantage they have over larger one is their space footprint. I think for larger ship space wont be an issue, heat management on the other side will. On my side the only reason I dont want people to use too much bricks over block is that it will make the game lags more. But the more powerfull / costly I make bricks the less laggy I make them compared to larger one ! (because you can build less of them).
 I will make sure that you cant spam them: I was thinking of adding a base energy / heat value to them as a start, on top of the regen one.
