### ISSUE TITLE
[BUG] Cross-entity stencils

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1640]
### Short Description of the issue:
Stencils "project" their shape across entities. In the gif below you can see a black rectangle sticker projecting its shape from the child entity onto the parent entity. I did some more testing and stickers placed on the parent entity project onto child entities too, so it works both ways.
I think expected behavior in this instance is that stickers should only show on the entity they're placed on.
...

### Steps to reproduce the issue
Build a child entity, and place a sticker on it so that it overlaps on to the parent entity. You can now move the child entity and see that the sticker moves too
...

### Environment
- Skywanderers version: 20w09a
- Graphics Card: RX580 8GB

### Additional information:
![Skywanderers Cross-Entity Stickers Bug](https://user-images.githubusercontent.com/27857711/75895191-37be9e80-5e2d-11ea-9099-17456dea6acf.gif)

**Comment by tsunamayo** [comment]
Yes right it is one issue of the current tech. It will be actually quite tricky to fix... Thanks

**Comment by captain828** [comment]
Just my 2 cents on this issue: since we can't paint just a single face of a block, using the decals would have been a good workaround for this but isn't an option due to this bug in certain cases.

Even when applying decals on completely flat areas that don't have any child entities interfering with them it can still cause issues at bends and corners.

**Comment by tsunamayo** [comment]
Finally fixed for 20w29c. Thanks!
