### ISSUE TITLE
[Bug] AI targeting center of mass too much [20w12a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1665]
### Short Description of the issue:
The current targeting for automatic turrets seems to almost exclusively aim at the center of the target ship. This isn't a problem when the target is facing away from or towards the shooting ship, because the fore and aft will get hit, but when the target is broadside-on to the shooter, it means that almost nothing except the middle gets hit. The shooting ship will continue aiming at the middle even when all the blocks there are gone, wasting all those shots.

This is particularly a problem because it can be exploited by making the ship's middle very skinny. If the only part of the ship that is targeted is the middle, and if the middle has very few blocks in it, then that ship will only lose a few blocks to auto-targeting if the pilot keeps the ship broadside on (which the AI tends to do anyway). Ships with a small percentage of their blocks in the middle will (paradoxically) last longer than ships with heavily reinforced midsections.

### Environment
- Skywanderers version: 20w12a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
This ship lasted longer in a fight than it should have because the thin middle was targeted to the exclusion of the larger fore and aft. The fore and aft are also where all the major systems are, meaning they were not at much risk of being hit.
![20200319162046_1](https://user-images.githubusercontent.com/33041786/77587697-6a046e80-6eb6-11ea-8c96-fa6753d3a41c.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4383654/output_log.txt)

**Comment by tsunamayo** [comment]
Again one more issue a non voxel space game dont have to worry about ;0 !
So yes I wonder what is the best way to do.
What do you think of:
1) On each turret we get a setting like this: Target Hull / System.
2) then the turret pick either a random Hull or a System still live and shoot at it. 
3) it pick another block after X try or once it is destroyed.

So if you want to kill the ship with HP / heat you do a targetting Hull design. Othwise take down system. Might be usefull once I put a power leech addon block.

Then I guess I would need a setting so that player can override the assignment in real time? Maybe middle mouse button? 
I need more brainstorming. I guess I could go in a FTL like direction with this. Again the difficulty is the UX, not much the code behind.

**Comment by ProPeach** [comment]
The interface for this choice will be tough, but there are lots of examples in other games. Personally I think the choice of target should be made by the player in real time rather than at the ships creation in the turret core as it opens up new tactics and gameplay options. Elite has a system where you pick the intended target system through a dropdown in a holographic menu once you scan the target ship which seems like the simplest option, although it lacks flair. Perhaps if you linked a holomap to a (insert scanning system here) you could pick out the target systrm on a hologram of the enemy ship, with the hull and systems shown in different colours. Or if you don't have room for that in your ship, simply link a screen and use a dropdown to select your target.

Another thing that might help prevent this situation is accuracy. As I understand it accuracy (or innacuracy) isn't a factor yet, so weapons have no spread and turrets are always as accurate as possible. Once weapon and turret innacuracies are introduced the spread of damage should be much less artificial and more organic and "realistic" looking.

**Comment by tsunamayo** [comment]
Yes accuracy will definitely help, but for sure this is a thing I knew I needed to address.
Also yes ultimately I want to combine that with a scan ability for the gameplay progression.
I think I need to brainstorm a bit but also have more mileage with the combat system, so I guess I will do a temporary solution until we sort everything out.

**Comment by tsunamayo** [comment]
This was fixed a long time ago. Thanks!
