### ISSUE TITLE
Paint Options Again

### ISSUE THREAD

**Issue by SageThe13th** [tsunamayo/Starship-EVO#1666]
The current paint selection is overly limited and the results end up being bland. Higher saturation colors as well as having more colors to choose from isn't "intimidating" it's needed. Badly.

I'd like to point out the environments in the game both in space and the ring world don't have this problem. The colors used feel vibrant and alive making the colors on your ship feel even duller by comparison.

Honestly, this is a much more serious issue than it might seem. Because the anemic paint selection is in stark contrast to the immense freedom you're given for build the structure of your vehicles. Making building a creatively fulfilling and enjoyable experience. While, coloring feels extremely restricted and ends up being disappointing.

**Comment by PopkaAkula** [comment]
I feel like the removal and the oversimplification of the color selection is a huge step back for this game. It limits the creativity and ability to build what you want tremendously. I could understand the removal of custom colors but this just seems incredibly foolish in my eyes.

**Comment by tsunamayo** [comment]
If you guys could be more specific in what color you need and for what use that would be more helpful. The new normal color is really close to the old saturated one. In the ship I had a look at I didnt saw much use for the old faded variant, nor the two variations of pink / purple. 
Be more specific and more constructive! Send me screenshot of your "ruined" constructions (and if you have pics of before the update that would great to compare!)
Cheers

**Comment by Dwarf-LordPangolin** [comment]
I wouldn't say things are "ruined," but I would have to agree that the colors could still use some work. There are two main issues with the current paint colors:

1. Desaturation. All of the colors are too desaturated. This was my first reaction on seeing the new palette. It doesn't look as good as it could, particularly since the visual style of Skywanderers is well-suited to bright, bold colors. I agree that oversaturated colors are a problem and they should be avoided, but the same problem is true for desaturated ones.

2. Purity. The colors aren't "pure" enough. By this I mean that they have too much of other colors in them; the oranges all look too brown, the blues all look too purple. In addition to being a problem in its own right, this also makes the desaturation problem worse than it would otherwise be; what is meant to be a light blue turns out to be a very light lavender-ish color.

To give a specific example, I would use the following RGB values as a starting point for fine-tuning the blues (I used Google's own color picker that comes up if you search "color picker"):

Light Blue: 60, 112, 255
Normal Blue: 28, 65, 230
Dark Blue: 40, 85, 160

I feel that these would be an improvement over the current blues. You will notice that only the "normal" blue is an especially bold color; the rest are somewhat muted, though not to the point of excessive desaturation. And the dark blue is not too dark, since darker colors don't look as good in computer games as they do in real life, particularly with regard to losing detail on textures.

**Comment by ultrak2k** [comment]
I have to agree- the destruction of the color palette is currently the greatest step back the game has done - things like 
![colours](https://user-images.githubusercontent.com/43084360/77705096-a73a3f00-7023-11ea-9213-21ee204bd8ff.jpg)

This was **ONLY** possible with the custom colors. Even the old palette couldn't do this. Losing colours loses potential to build replicas, funny weeb mechs, and all the wacky shit people came to this game to do. We either need a massive colour palette, not the tiny ass shit we had before, or the return of custom colours - the current and even the former colour palette is unacceptable.

All the browns, the skin colour browns, far more shades of each of the main colours, etc
I remember playing starmade, and being frustrated when the specific colour I want didn't exist. A lack of colour is far more restricting then you think, tsuna, its actually very bad for the creativity for any game. The more colours, the more free people are to build the whatever they want to build. 

The current colours are desaturated, with nowhere enough vibrancy, are pretty impure, and really


What the hell did we gain from losing colours? 
I doubt anything we did gain was worth the massive loss of freedom. It may not seem important, but the reality is that a big colour palette is intrinsically linked to creative freedom perhaps more then any of the other building mechanics.

So please, either expand the colour pallete to something with around 80 colours, like (as an example) 

<img width="327" alt="etc" src="https://user-images.githubusercontent.com/43084360/77705498-b077db80-7024-11ea-893f-893a627cb6d1.PNG">
![colours](https://user-images.githubusercontent.com/43084360/77705501-b1107200-7024-11ea-8146-59c430564570.jpg)

**Comment by ultrak2k** [comment]
> If you guys could be more specific in what color you need and for what use that would be more helpful. The new normal color is really close to the old saturated one. In the ship I had a look at I didnt saw much use for the old faded variant, nor the two variations of pink / purple.
> Be more specific and more constructive! Send me screenshot of your "ruined" constructions (and if you have pics of before the update that would great to compare!)
> Cheers

(above)

**Comment by SageThe13th** [comment]
Guess I'm just posting this again.
![73131888-6f3d5e00-3fd8-11ea-82bd-ef8d567908a1](https://user-images.githubusercontent.com/58193603/77709008-b2e02400-6f97-11ea-83cf-2670d2747beb.png)

**Comment by SageThe13th** [comment]
Note the array of light, dark, high, and low saturation colors. We need variety not a pallet of all lackluster colors.

**Comment by SageThe13th** [comment]
Solution #2 is to bite the memory bullet and just add a color wheel again. I'll state again that we have these impressive freefrom building tools. Yet the paint system doesn't nearly match in terms of freedom and creativity.

**Comment by Aiwii** [comment]
#1473

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin thanks a lot for your constructive comment.
So to give you my value:

LIGHT_SATURATION = 0.55f;
LIGHT_VALUE = 0.8f;
BASE_SATURATION = 0.82f;
BASE_VALUE      = 0.77f;        
DARK_SATURATION = 0.8f;
DARK_VALUE      = 0.6f;

Blue hue = 0.625 (or 222 deg)

So to talk about your point:
1) Saturation => I could indeed increase a bit. I felt it was too much before!
2) I guess it is a mixed problem? 
For the orange it seems like a brightness one, you get brown with lower brightness orange. 
For the blue, I am not sure to understand: my blue is actually more green than red. Lavender or purple is more red than green. Your color suggestion hue is actually at 229 deg, which is actually close and more purple than mine! 
Now in a HDR game like mine brightness depends massively on how you looked at the color in game, how perpendicular to the light source was your color? If I put them too bright then it will get picked up by bloom.

This is almost perpendicular to the sun:
![image](https://user-images.githubusercontent.com/6604318/77712848-553fec00-7018-11ea-8c8b-f42d073ef4d5.png)

On top of that there is the PBR engine that kicks-in, painted color have still a bit of metallic color in them so it make them look more washed down like in real life, in exchange for brighter highlight.

I think the most constructive approach would be to work on a ship fully painted, and then I will tweak value a bit to get something attractive.

I agree the best would be a come-back of the custom color. I could make that work with a completely different approach compared to before to not have the nightmare of bug (like no custom for light, weapon ect) and also to make it more seamless for the player. But I dont have time for this atm, that would be post-early access.

Cheers

**Comment by SageThe13th** [comment]
I understand if new a color system takes time. But, reducing the colors when people were asking for more felt like a step backwards. So I felt compelled bring up the issue again.

**Comment by ultrak2k** [comment]
> @Dwarf-LordPangolin thanks a lot for your constructive comment.
> So to give you my value:
> 
> LIGHT_SATURATION = 0.55f;
> LIGHT_VALUE = 0.8f;
> BASE_SATURATION = 0.82f;
> BASE_VALUE = 0.77f;
> DARK_SATURATION = 0.8f;
> DARK_VALUE = 0.6f;
> 
> Blue hue = 0.625 (or 222 deg)
> 
> So to talk about your point:
> 
> 1. Saturation => I could indeed increase a bit. I felt it was too much before!
> 2. I guess it is a mixed problem?
>    For the orange it seems like a brightness one, you get brown with lower brightness orange.
>    For the blue, I am not sure to understand: my blue is actually more green than red. Lavender or purple is more red than green. Your color suggestion hue is actually at 229 deg, which is actually close and more purple than mine!
>    Now in a HDR game like mine brightness depends massively on how you looked at the color in game, how perpendicular to the light source was your color? If I put them too bright then it will get picked up by bloom.
> 
> This is almost perpendicular to the sun:
> ![image](https://user-images.githubusercontent.com/6604318/77712848-553fec00-7018-11ea-8c8b-f42d073ef4d5.png)
> 
> On top of that there is the PBR engine that kicks-in, painted color have still a bit of metallic color in them so it make them look more washed down like in real life, in exchange for brighter highlight.
> 
> I think the most constructive approach would be to work on a ship fully painted, and then I will tweak value a bit to get something attractive.
> 
> I agree the best would be a come-back of the custom color. I could make that work with a completely different approach compared to before to not have the nightmare of bug (like no custom for light, weapon ect) and also to make it more seamless for the player. But I dont have time for this atm, that would be post-early access.
> 
> Cheers

oh thank god, even if its post release, as long as custom colours for specifically blocks comes back, then all goods my guy

**Comment by tsunamayo** [comment]
Yes I would do something more seamless code wise and player wise, base on virtual color mapping.
Each ship will get 256 colors max (the limit of my engine).
Then player get to create their own custom color palette, as many as they want.
When a ship gets over 256 colors you get a warning, you need to get rid of a color.
All weapon / system get a hue base system, which is okay as glow color have full brightness / saturation.

**Comment by ProPeach** [comment]
Thanks again for the in-depth reasoning and explanation of all the factors at play Tsuna, it's as valuable as ever.
The system you out like for custom paint sounds excellent, it's awesome that you've improved to the point that you're in a position to reintroduce a more powerful version of a feature that caused problems in the past.

In the meantime I support Dwarf Lord Pangolin' points concerning saturation and "purity" as the current colours appear washed out, and Sage makes a great example in how vibrant and lively the ringworlds environment is compared to ship paints. If the paints shared similar saturation levels and values as their environmental counterparts I think that could go a long way in improving their look. Some accent or supporting colours like tans or browns would help the selection too, as well as doubling the number of greyscale colours for a finer gradient.

Adding custom colours post EA would be really awesome, but the current pallete needs to be robust and varied enough to make sure that new players hoping to build their dream ships aren't turned away when they first join the community.

**Comment by ZachZent** [comment]
https://cdn.discordapp.com/attachments/271723356795961345/692925443245867098/unknown.png

Though I am glad we are getting the custom colors in the future, there still needs to be a decent number of basic colors. MS paint actually starts with 48 basic colors and allows for custom after that. Every single one is the most basic form for every color. You have your browns, reds, yellows, etc. If you want something more specific you use the custom colors.

I'd argue the basic colors are more important then custom colors, especially for new people. To have a selection of simple yet numerous colors from the start to use. Especially since custom colors will come later and all we will have to start with is the basic colors

**Comment by tsunamayo** [comment]
@ZachZent yes I do agree it is important for newcomer, that is why I wanted a selection that make more sense and not too intimidating. Honestly palette people have been shoving at me after a google search are just terrible. MS paint palette is also terrible, it might make sense for what they are doing, but look at all those super similar color... Also no organization. Buts that coming from Microsoft so I am not surprised ;) 
Actually funny thing MS Paint was my first interaction I had with computers as a child, I was drawing AT-ATs at my aunt home, it bring back memory lol...

Aslo yes I do wanted to add a line of browns and maybe some blueish grays... Some color that do not fit in a hue-based palette but that are useful to build ships.

**Comment by ZachZent** [comment]
Oh MS paint pallet is less then stellar and extremely poorly organized, but the point was more about how all the basic colors are covered. I don't have a good pallet to share, but just wanted to make sure of the need for enough of the basic colors before the custom ones come in. If MS paint can get it done in 48, I'm sure it can be done with less (though more then 18)

MS Paint and Space Cadet Pinball was my childhood

**Comment by ProPeach** [comment]
This is the only example of a before/after I could put together as I haven't taken too many pictures recently, notice the orange.
Before - Bright, lively, high contrast 
![image](https://user-images.githubusercontent.com/27857711/77779450-70c3ea80-704a-11ea-9231-698d763487ea.png)
After - Dull, muddy and blends with the grey of the rest of the ship
![image](https://user-images.githubusercontent.com/27857711/77779845-05c6e380-704b-11ea-9839-edbd3fab94d5.png)

**Comment by Dwarf-LordPangolin** [comment]
Hey @tsunamayo!

First, thank you for the in-depth answer! Thank you as well for the info on custom colors potentially coming back later in development; I think most people will be happy to use the current palette if custom colors will be an option in the future.

Second: I'm starting to think that one of the overall issues here may be that peoples' displays are calibrated differently. The reason I'm thinking this is that my blues and your blues don't look entirely alike:

![Color Comparison](https://user-images.githubusercontent.com/33041786/77835459-c9fb4f00-711a-11ea-9a5a-c7854578695a.png)

It's not a huge difference, but it's enough to noticeably change the look. Using the eyedropper tool on your screenshot, your light blue has a hex code of #6F97D9 (RGB of 111,151,217; Danube blue, [apparently!](http://chir.ag/projects/name-that-color/#6F97D9)). But the light blue from my screenshot has a hex code of #7593ED (RGB 117,147,237, or [Cornflower blue](http://chir.ag/projects/name-that-color/#7593ED)).

While both of these colors are definitely closer to the blue area of the wheel than they are to the purple one, the light blue in my screenshot has more red and less green than yours -- this makes me suspect that a lot of the discussion in this thread over colors may be due to some kind of difference in how the game is being displayed. I actually really like the light blue in your screenshot; but for some reason, that's not how it looks on my monitor. The two other colors are different as well, though not by as great a margin. I'm going to go ahead and check my monitor's calibration, since there's definitely a visible difference.

All of that said: if custom colors are coming back at some point in the future, then the current palette doesn't really need to be changed. Default colors with the option to customize them is the same setup Space Engineers has, and I've literally never seen anyone complain about the palette in that game; if folks don't like it, they just tweak the colors to their satisfaction. :+1:

**Comment by tsunamayo** [comment]
Okay I see I think I might had a bit of green leaking from my interior.
![image](https://user-images.githubusercontent.com/6604318/77838513-9fa7a100-71af-11ea-86ff-29a1208f385d.png)
I will bump up the saturation, and shift the blue a bit more to the green. Build is coming very soon as I want to fix the torus issue.
Thanks @ProPeach that was useful indeed
Thanks all, I feel we had a productive discussion.

**Comment by tsunamayo** [comment]
Okay I made the change, dont hesitate to tell if we need further tweak. Thanks

**Comment by ProPeach** [comment]
Following the changes made in the most recent update (20w13b) I was taking another screenshot to add to the comparison below, and it looked like the orange and other colours were a lot nicer.
![image](https://user-images.githubusercontent.com/27857711/77921813-25068080-7298-11ea-876c-f1dadf3dadfa.png)
However, I realized that this comparison isn't actually very fair. In 1# and 3#, the player is close to the ship, whereas in 2# where the colour looks more washed out, the player is a little further away. I noticed that at around 25m distance from the ship when the first LOD changes, there's a significant difference in the colour of paints
![image](https://user-images.githubusercontent.com/27857711/77921127-41ee8400-7297-11ea-93b0-4b9a4ba9243a.png)
While the example given with the blue earlier in the thread is still very valid as the screenshots are taken at the same distance, this change in colour could be contributing to the worse look of paints.

Tsuna, is there anything that can be done to reduce the difference in paint colour between LOD levels? I'd guess this has to do with the reduced lighting computations when the player is further away influencing the hue, but the difference is big enough that it is very noticeable. You can also clearly see the sphere around the player inside which the LOD changes, if this could be smoothed over and the difference in paint colours reduced I think that could that help with the players perception of colour ingame
![image](https://user-images.githubusercontent.com/27857711/77923042-c215e900-7299-11ea-86b7-8debe817c4f1.png)

**Comment by SageThe13th** [comment]
Interesting. Good find ProPeach.

**Comment by tsunamayo** [comment]
Yes good spot ProPeach, it is an unfortunate artifact linked to the shadow mapping. I will see what I can do about it. I can still boost saturation a bit also.

**Comment by SageThe13th** [comment]
The new colors are much improved. I'd suggest adding a brown between the red and orange. That should cover all basic colors.

**Comment by ProPeach** [comment]
Glad to hear you're on the case! I agree with Sage, the new saturation levels are great, and the suggestion of the browns would be ideal too. I'm not as talented in Photoshop as Sage, but a finer gradient of the grayscale would be awesome (one colour in between each of the existing greys ideally), as well as a column of tans in between the existing orange and yellow columns
![image](https://user-images.githubusercontent.com/27857711/78206892-fd7e0680-7497-11ea-9aaa-ada3a72740bc.png)
![image](https://user-images.githubusercontent.com/27857711/78206902-040c7e00-7498-11ea-88dd-e0c71d683ab6.png)
![image](https://user-images.githubusercontent.com/27857711/78206936-1981a800-7498-11ea-8d43-1d4f9b34a7b4.png)

**Comment by BrickMacklin** [comment]
@tsunamayo you previously asked for examples of ships that have been affected by the change in color palette. Below I have a picture of a ship I was working on before you first implemented custom colors that utilized a variation of brown. next to that is a picture of it in the background after  the custom colors and the final picture is of it now after it was carried over to the current build.

![711980_20181127161413_1](https://user-images.githubusercontent.com/37836252/84573718-54de0400-ad70-11ea-85b4-f088381703fb.png)
![20190609131634_1](https://user-images.githubusercontent.com/37836252/84573749-8656cf80-ad70-11ea-9995-16b207721bdd.jpg)
![20200613121000_1](https://user-images.githubusercontent.com/37836252/84573758-953d8200-ad70-11ea-9782-2e3c0c35631d.jpg)

This is my favorite build I've had in the game but currently I won't work on it since I do not have a brown of any kind to use on the hull. So it is at present staying dormant. I concur with above posters asking for some browns until we have a more expanded color palette. I think some lack of colors are holding us back.

**Comment by tsunamayo** [comment]
Okay, brown and tan added for 20w26c. Cheers
