### ISSUE TITLE
Mass of different hull shapes

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1674]
### Short Description of the issue:
While this might not be a bug as such, the mass of each stretched block/brick is constant and only dependent on its overall bounding box, not it's apparent volume. A cubic block weighs 200kg, and a wedge block weighs 200kg as well rather than 100kg. This makes a huge difference as you stretch blocks/bricks out, as the mass is calculated as a cube rather than the actual shape.
So a 4x4x4 cube weighs 200x(4x4x4)=12,800kg as it should, but a wedge follows the same calculation even though half the shape is empty. Ideally a modifier for each shape should be used that calculates the accurate mass of the stretched block, so for a wedge it would be 200x(4x4x4)x0.5=64,000kg, where the 0.5 is the modifier for the wedge as it is half the volume of a full block -- for a Tetra it would be ~1/6, for a Tile Thin 0.25 etc.

Improving that calculation for all hull and brick shapes in the codex (not decorations etc, just basic shapes) will have a large impact on the mass of most ships, which is why I think it would be better to make that change now rather than later as it will influence any system balancing has been done before it.

I also think that the current brick mass of 25kg is too large as it's almost impossible to make a brick ship faster than a few hundred km/h, and both thruster types need a buff to their forward thrust values as all ships have slowed down drastically to sub-300km/h after the mass re-balance. Either that or a mass reduction across the board, but the main point is ships are very, very slow now

**Comment by Aiwii** [comment]
I agree ships have gotten a lot slower with the new updates. it seems very difficult now to fly faster than 300km/h with a smaller 15m brick ship of mine only hitting 65km/h with boost and a larger 80m ship only getting around 200km/h with boost. It probably is possible to get ships to fly faster than 300km/h but that results in a decreased experience while building. I do agree that ships needed to be slower but maybe we need throttle control over the speed of our ships so we can still hit ridiculously high speeds but not all the time.

**Comment by ProPeach** [comment]
Throttle control is absolutely essential yeah, it's pretty much impossible to properly fly without it unless you're just doing small maneuvers in non-boost mode.

**Comment by ZachZent** [comment]
We have seen the two sides of flight the last few updates, extreme speed that is very unwieldy and the current very slow speed which though is more manageable is still painfully slow. Let me make a proposal between the two.

For the proposal, the max speed would be leaning to the faster side, though not as fast as the previous update's speed. In this, the faster you go, the less maneuverable you become. This means combat and general maneuvering will become a balancing act of speed vs maneuverability. Players can manage this however they choose and due to the faster speeds, they are able to do so. Sacrifice maneuverability for speed to run away from a pirate or lose speed in favor of maneuverability to more adequately fight another fighter. Players have a wide range of options as to balance their unique ship’s speed vs maneuverability and their personal tastes. This also makes ships/pilots more unpredictable as you wouldn’t be able to know their top speed for they may be not flying at 100% thrust. A smaller ship _may_ be able to run away from you even if not immediately apparent.

Of course, this requires the addition of throttle control and the exact speeds/maneuverability must be balanced, but something like this would make flying more dynamic as speed is no longer a constant. Perhaps the best benefit of all is that if handled properly, it will remove the ability for the largest ships to fly and maneuver like a fighter. A major problem in many other space games.

**Comment by tsunamayo** [comment]
Yes I will see the best way to fix the first bug, my preferred solution would be a smarter voxel occupancy algo. I need to check more pro and cons.
Also for the speed, I will increase the max speed at first, so that acceleration stay the same. Before it was just accelerating too much.
If you could give me some reference ship (small, med and large) so I can calibrate them to get a good feel for it!
Now, for the the large ship get super maneuvrable => this is why I made the small thruster only give some agility. As they are heat inefficient (like other small system), you will have to place a lower % on large ship, making them naturally less agile. I am likely to decrease the Lightcruise thruster normal thrust value also.
Thanks!

**Comment by tsunamayo** [comment]
Mass has been re-balanced a few updates ago. Thanks
