### ISSUE TITLE
Streamline Balancing

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#1690]
On a note for balancing, would it be possible to put in a GUI to allow the players to toy with balances for stuff like block HP/armor, shield amount, system heat/power consumption, etc. and have people submit their balance 'cases'? I feel that something like this could really benefit everyone. It would save you some time for starters and allow people to freely mess with their own values. I also feel that this could help players advocate for why X thing should be a higher or lower value and could greatly speed up the balancing phase.

**Comment by ultrak2k** [comment]
Huh, that sounds like a pretty good idea actually, I wonder if its as simple though, as isn't calculations of all the balance related stuff wacky math problems? or would it be more simplified and just be flat numbers on what does what

**Comment by Xerma** [comment]
Wacky calculations is a good point. I'm more so just curious if it's a doable thing overall.

**Comment by ProPeach** [comment]
This could be a great tool, but I also think it might be a bit of a nightmare to regulate and compare different players stats if everyone has their own ideal numbers that they're trying to push. To be used most effectively this tool would have to be used as a group, all working off the same stat sheet. Ideally it would be in the form of a .txt or config file that can be easily passed between players like a blueprint and read by the game to apply those stats.
I do realize that this would be a pretty sizable investment in time though to both implement and maintain, but it would enable us as a community to work in parallel on balancing which has to potential to speed up the process greatly as we can iterate quickly and be flexible . We could put forward whole builds with our experience in other games for you to test and tweak before being implemented into the core game whilst you are free to pursue other projects.

**Comment by SabreMania** [comment]
I believe it would be an amazing tool, however I disagree with ProPeach on it's implementation. Everyone should be able to modify the stats of their respective worlds, with the tool 'remembering' the default stats of everything. In that sense, the modified stats would be a modifier, rather than straight up changing the core statistics.

This however could also lead to another cool tool for future servers, the ability to customize your blocks. Not as an individual on the server, of course. But if someone wants to make a server where making a high tech ship is 10x more expensive than normal, but also makes them 10x more powerful, or if they want to make gatling barrel weapons have 2x the fire rate they currently have, or any other change, they will be able to.

But to come back at the original idea. While this tool could potentially take a great deal of time to be developped, I think it would be a worthwhile investment, especially since we have apparently entered the game's early balancing stage.

**Comment by tsunamayo** [comment]
Yes I get the idea, but for now I cant just have people coming back at me saying "this needs to be 100hp damage" or things of the like. I need to own each and every design decision, understand the impact ect. 
So if something feels off, tell me what it is, tell me what is wrong ect, and I will tweak the balance. 
For example, get back to me with feedback of the like: "ship overheat too easily, whereas Hull kill are too rare", "beam are too op compared to laser, I am using 100% beam", "Gatling is way too op". Then I will tweak things, knowing that as it is early it might be beyond simply tweaking value (need to add laser precision mechanic to nerf gatling for example).
There is not a single way to address an issue, everything is connected and I must have the full picture in mind at all time, not just blindly input value given by other otherwise it will never works.
I feel I need to have a stronger base before going this way. And also it is highly dependent on the ship used...

But this will be on my to-do at one point once all the main values will settle a bit.
But I have this in mind, the whole gameplay is actually a single class, with very few "true" variables, most of the value are just ratio between a few fundamental constant.

For now I will need some ships and some feedback! I did a big pass on turret, I just added beam, I am adding more addons soon (not barrel, but side addons), and I am also working on AI logic. Then I will move on auto spawn. So I am fully concentrated on combat!

There is the balance spreadsheet but I need to update it.
https://docs.google.com/spreadsheets/d/e/2PACX-1vTLwAU9wrXylPiSYnrL8Gr25Fybrc35n4vh2uiKBOWG6IL7H280Whvc4FOOCwE29ys6FwReJGbL1K4K/pubhtml

Cheers

**Comment by ProPeach** [comment]
@SabreMania just wanted to clear that up, I was suggesting that everyone should be able to change their clients personal stats in a txt file but it could result in a mess of non-productive chatter if not coordinated in a group.
I agree Tsuna, you should absolutely have a hand in the overarching control of the balancing. This tool would be useful for testers or groups of testers experimenting with values quickly so that they can pitch a more complete and proven model to you to consider and change if necessary before implementing for the actual game.
I also agree that it might be a little too soon as we only have a fraction of the combat components available to us, but I still think this could be a really valuable and time efficient method for sorting the final balance.

**Comment by tsunamayo** [comment]
Yes, but like I said I dont need people to come back to me with a "model to be implemented", thats my job and responsability... 
I just need you to come up with with feedback and issue to address.
