### ISSUE TITLE
[Question]What is your vision on the features of the game at initial steam release?

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#1694]
Dear tsuna

If you don’t mind me asking and if it isn’t a can of secrets being held for later -

 I have a simple question, since I’m curious on if the game will be appealing enough for the average steam dude to the point where I can freely reccomend  the game to people when it does eventually release. 
I believe a few people do have concerns, but I think that’s due to the simple thought of the game being released in a similar state to how it is now, and lack of knowledge of how exactly the game will look like at the initial steam release, so 

What is your vision on the state of gameplay, combat, maybe the ringworld, perhaps NPCs - general gameplay things when the game comes out?

**Comment by tsunamayo** [comment]
You mean steam early access right? Or final 1.0 release?
For early access it will be pretty close to what we have here, except with a stable fun combat experience, and some NPC ship spawning to poke at the player (with an option to toggle them off if you want to play alone).
Tag line will be: Creative Battle.
I wish I had more things and a proper career, but the technical bar to get there was massive, and I need more testers / builder also so I think the early access at this point is the right thing to do.
Cheers

**Comment by ultrak2k** [comment]
> You mean steam early access right? Or final 1.0 release?
> For early access it will be pretty close to what we have here, except with a stable fun combat experience, and some NPC ship spawning to poke at the player (with an option to toggle them off if you want to play alone).
> Tag line will be: Creative Battle.
> I wish I had more things and a proper career, but the technical bar to get there was massive, and I need more testers / builder also so I think the early access at this point is the right thing to do.
> Cheers

Steam initial early access

**Comment by JustAnApple** [comment]
Can you make another update video? For a moment I thought the project was dead... my heart dropped. Glad to see it is still alive!

**Comment by tsunamayo** [comment]
yes if you dont have access to the build then you must have been in limbo. I will do a video, then once my steam early access page is up I will do more as I will ramp my PR effort.
@ultrak2k so what do you think, about creative + battle? 
It seems that other games managed to do an early access with limited content also, but I havent played them, so I am not sure.

**Comment by ultrak2k** [comment]
> yes if you dont have access to the build then you must have been in limbo. I will do a video, then once my steam early access page is up I will do more as I will ramp my PR effort.
> @ultrak2k so what do you think, about creative + battle?
> It seems that other games managed to do an early access with limited content also, but I havent played them, so I am not sure.

I'm conflicted. I did think we would get basic resource harvesting, and other survival mechanics - having just creative and fighting isn't enough to sway enough people to make a dent in skywanderer's popularity in my opinion, many other games have done the same with at least that. Granted, they didn't have anything to fight when say SE or starmade started, but having at least some survival would help skywanderers secure a better portion of the market. This is what I believe the common consensus of the skywanderers discord is, but you may need to ask more broadly.

**Comment by SabreMania** [comment]
> @ultrak2k so what do you think, about creative + battle?
It seems that other games managed to do an early access with limited content also, but I havent played them, so I am not sure.

If I may put in my grain of salt here, I would have to say that while creative-building + battle would be great, it seems a bit lackluster for an early access release. Even Starmade (the game that is quite possibly compared with your game the most) already had, when it hit public access, mining, randomly-spawning stations that could be salvaged, and even AIs that were already trading in convoys, as well as randomly-spawning pirates and galactic 'Stick shops' that you could buy blocks from.

As a reference, this video. https://www.youtube.com/watch?v=YZ0qTeXjeT4

**Comment by ultrak2k** [comment]
> > @ultrak2k so what do you think, about creative + battle?
> > It seems that other games managed to do an early access with limited content also, but I havent played them, so I am not sure.
> 
> If I may put in my grain of salt here, I would have to say that while creative-building + battle would be great, it seems a bit lackluster for an early access release. Even Starmade (the game that is quite possibly compared with your game the most) already had, when it hit public access, mining, randomly-spawning stations that could be salvaged, and even AIs that were already trading in convoys, as well as randomly-spawning pirates and galactic 'Stick shops' that you could buy blocks from.
> 
> As a reference, this video. https://www.youtube.com/watch?v=YZ0qTeXjeT4

When starmade hit public access it didn't have trading convoys, it only had police that would react if you shot a shop, and pirates, that would come 4 years later

Those planets don't really count, since our ringworld is already far more impressive and larger - starmade planets were flat disks with a diamater of 300m or less

**Comment by ultrak2k** [comment]
> yes if you dont have access to the build then you must have been in limbo. I will do a video, then once my steam early access page is up I will do more as I will ramp my PR effort.
> @ultrak2k so what do you think, about creative + battle?
> It seems that other games managed to do an early access with limited content also, but I havent played them, so I am not sure.

Another question I had tsuna, a question i've had for over a year is - how will the game be pushed/advertised? The PR thing.

**Comment by ultrak2k** [comment]
The reason the creative and battle part is concerning is that first impressions matter - it would be harder to gain a foothold in the market with a meh first impression - do note that there was alot promised in the kickstarter for release, and if people find out about that, it might not end well if the release version isn't up to standard.

**Comment by SabreMania** [comment]
> When starmade hit public access it didn't have trading convoys, it only had police that would react if you shot a shop, and pirates, that would come 4 years later

That is my mistake, yes. Actual convoys weren't a thing yet, However there was already a faction system in place that even players could participate in, that is, create a faction, and invite other people into them

**Comment by Xerma** [comment]
I feel as if the faction system wouldn't be overly complicated to implement for EA release but with multiplayer being in a semi-chaotic state there isn't too much of a point for that just yet. But yes I would have to agree by saying that for EA release there should be some placeholder pirate station with some ships - which I think you might have talked about that one already. It may also be worth the time to stabilize multiplayer just so that's a thing people know is already there but it just needs Unity's networking upgrade. Which now I do have to ask, is there any word on the multiplayer part?

**Comment by ultrak2k** [comment]
Multiplayer I feel would be crutial

**Comment by tsunamayo** [comment]
@ultrak2k I know I know, this is why I want to rebrand the game. I was not satisfied with a lot of aspects of the game, and I wanted to address them in order to build on a stronger basis.
The idea is I am not trying to compare with Starmade / SE, ie trying to catchup on features. 
I think I need to have some very unique elements to make it meaningful for player to try out.

**Comment by ultrak2k** [comment]
> @ultrak2k I know I know, this is why I want to rebrand the game. I was not satisfied with a lot of aspects of the game, and I wanted to address them in order to build on a stronger basis.
> The idea is I am not trying to compare with Starmade / SE, ie trying to catchup on features.
> I think I need to have some very unique elements to make it meaningful for player to try out.

Rebrand to a creative builder? Id hope that would be temporary as survival shit comes in though, right?

**Comment by tsunamayo** [comment]
Yes I will do another push on multi. Have you tried out recently guys? I did some fix the other day, building should be fine. I need to fix combat though.

**Comment by tsunamayo** [comment]
@ultrak2k yes I mean I need to be clear on what the current state of the game is. Also as the artstyle changed dramatically, and a few features are removed (until I put them back), like holomap / space travel and mechs. Also the name sucks hard...

**Comment by Xerma** [comment]
I have not recently tried out multiplayer but I'll see if I can try it out sometime soon

**Comment by tsunamayo** [comment]
yes and I will hop on the discord also, I will need a few people to shoot some basic trailer.

**Comment by ultrak2k** [comment]
> @ultrak2k yes I mean I need to be clear on what the current state of the game is. Also as the artstyle changed dramatically, and a few features are removed (until I put them back), like holomap / space travel and mechs. Also the name sucks hard...

Wait, a rename of the entire game?

**Comment by tsunamayo** [comment]
@ultrak2k yes I have talked about that for months

**Comment by ultrak2k** [comment]
ah

**Comment by Xerma** [comment]
When were you planning on dropping by?

**Comment by SabreMania** [comment]
I have to disagree, Skywanderers is a great name. It's simple, easy to remember, and unique.

I would have to say however, perhaps a few more things mentionned in the kickstarter should make their comeback before early access comes out. You did mention that you would eventually put them back in, yes, however it might not be looked upon well by new people coming in from the early access release. They may look at the Kickstarter, compare the promised features and everything that there was shown in the youtube videos, then compare it with what the game has now, and realize that a lot of things are missing. This could lead to a massive sense of distrust amongst new players, and could damage the game's reputation.

**Comment by Xerma** [comment]
Going on that Sabre, a good thing, at least from my point of view, would be to have a devlog at launch talking through it all and why things are the way they are - and perhaps link it on the steam page. A dev that keeps the community updated is already light years ahead of most other game devs out there

**Comment by ultrak2k** [comment]
> Going on that Sabre, a good thing, at least from my point of view, would be to have a devlog at launch talking through it all and why things are the way they are - and perhaps link it on the steam page. A dev that keeps the community updated is already light years ahead of most other game devs out there

Even that might not be enough, I feel
Its a start, but would that be enough?

**Comment by SabreMania** [comment]
It's true that it would help. However, it would only act as a mitigator, and not as a solution. There has been many. Many games in the past who promised quite a bit, but ended up not delivering for various reasons. Distrust in early access games has never been higher. I have all of my trust in this game, I believe it is a blooming flower. 

But a damaged reputation can follow a game for a while. This game coming out as early access wouldn't be comparable to No Man's Sky's fiasco, of course, nowhere near. But I still believe it could damage the game a bit on the short term.

**Comment by ultrak2k** [comment]
> It's true that it would help. However, it would only act as a mitigator, and not as a solution. There has been many. Many games in the past who promised quite a bit, but ended up not delivering for various reasons. Distrust in early access games has never been higher. I have all of my trust in this game, I believe it is a blooming flower.
> 
> But a damaged reputation can follow a game for a while. This game coming out as early access wouldn't be comparable to No Man's Sky's fiasco, of course, nowhere near. But I still believe it could damage the game a bit on the short term.

Exactly.

**Comment by ultrak2k** [comment]
I must ask, what's the rush on releasing the game? Are funds running dry?

**Comment by tsunamayo** [comment]
@SabreMania Hence why the rebrand is necessary. I am doing whats best for the game and for its future.
I am sure people are understanding about that. Now for sure there always gonna be people that says that once a dev says something it is engraved in the marble like the 10 commandments and if you deviate from that you are a gready dishonest person. But truth it is just a minority of people, people understand making game is hard. 

I had to dig way deeper in the tech side that I originally though. Custom rendering engine, custom collision engine. Also the switch to the stretch tech was a huge undertaking, but I feel it was the right thing to do. And the art style took much more time than anticipated, because I had to do many thing myself as it was too tricky because of the stretch tech.

And again I still want to do all these things, at the end it is just a time issue...
For backers => they have the game, it dont matter to them if the game is in ea or not.
For new player => they can choose to buy and start to build on ea or wait for more content. They dont really care about the kickstarter.

Yes I will do more devlog! I wanted to do one very soon. Next build is for the backers ship.

**Comment by ZachZent** [comment]
He is my suggestion a basic launch

There are two modes. Creative and (proto) survival. Both of them operate the same way, build stuff in shipyards, fly out and destroy other ships. Bonus if the entire galaxy is open for travel in a way like before, can travel there but in the grand scheme of things not any different. However in survival, you start with a "budget." Each block is worth some value and you can only build within that budget. This would be a 20m ship or so. You then go out like creative and hunt ships, maybe even some simple missions like save the civilian ship. Anyway every ship you destroy or mission completed, you gain a certain amount of money. More for pirates, less for civilian. You can use that money to go back to the dock and can upgrade or build an entire new ship using that money, an increased budget. A simple but effective gameplay loop that allows players to not only build but use their ships in actual gameplay

**Comment by ultrak2k** [comment]
> He is my suggestion a basic launch
> 
> There are two modes. Creative and (proto) survival. Both of them operate the same way, build stuff in shipyards, fly out and destroy other ships. Bonus if the entire galaxy is open for travel in a way like before, can travel there but in the grand scheme of things not any different. However in survival, you start with a "budget." Each block is worth some value and you can only build within that budget. This would be a 20m ship or so. You then go out like creative and hunt ships, maybe even some simple missions like save the civilian ship. Anyway every ship you destroy or mission completed, you gain a certain amount of money. More for pirates, less for civilian. You can use that money to go back to the dock and can upgrade or build an entire new ship using that money, an increased budget. A simple but effective gameplay loop that allows players to not only build but use their ships in actual gameplay

@tsunamayo even something that basic would go along way to convince people to get the game

**Comment by ZachZent** [comment]
Also a question. Awhile back you said you were delaying development on multiplayer because of a impending update to the Unity servers. Uplay to Multiplay. I looked up Multiplay and it seems to be fully operational. It was used to power Apex Legends which if I recall had no problems with their servers.
So the question is what is the status of adding multiplayer into SkW? Doesn't have to be full Minecraft server style, but at least working P2P as in my opinion not having any sort of multiplayer on any Steam launch would be a mistake

**Comment by tsunamayo** [comment]
Yes that is exactly what I want to do, but it will likely take a bit of time to get there, likely post ea but not that far away. Things is there is plenty of things to sort out, between PR, store setup, having a decent combat system, spawning ship ect. 
Pushing myself to ea has a lot of positive aspects, the game looks much more presentable now with sfx, vfx, clean UI ect.

**Comment by ultrak2k** [comment]
> Yes that is exactly what I want to do, but it will likely take a bit of time to get there, likely post ea but not that far away. Things is there is plenty of things to sort out, between PR, store setup, having a decent combat system, spawning ship ect.
> Pushing myself to ea has a lot of positive aspects, the game looks much more presentable now with sfx, vfx, clean UI ect.

That is very reasonable. To be honest though, why do you think the name sucks hard?

**Comment by talrey** [comment]
A pretty game is good, but I agree with Zach here - multiplayer was _the feature_ that drew me into Minecraft so long ago. Even if it's just creative combat, being able to fight other players would make it much more fun and interesting - I'd try to convince friends to buy the game so they can dogfight with me or build a big ship to crew together.

A game needs a point, a goal, and if there's no survival or economics then the goal defaults to players fighting each other... and if it doesn't have that, it's no more a "game" to me than Microsoft Paint.

Pushing yourself forward may have a lot of positive aspects in terms of polish and presentation, but an art gallery isn't a game, and rushing to announce Early Access may waste the opportunity for the biggest PR wave since the Kickstarter.

**Comment by ultrak2k** [comment]
Back to the original question, what would weapons look like in the initial release @tsunamayo

**Comment by tsunamayo** [comment]
The name Skywanderers sucks hard:
- Very little tie to what the game is
- Mouthfull, especially for non english native
- Finish in ers.
- and again I think I need to change it. It is neatier to change it, as the game evolved too much. If someone picks up a 2 year old video it would be completely misleadind.

Weapon wise there is only laser and beam, but with tons of addons: 4x barrels and 3 (maybe 4) side addons (in next update). So a lot of possibility. I think thats unique!
Yes I will fix combat for multi!

**Comment by ultrak2k** [comment]
> The name Skywanderers sucks hard:
> 
> * Very little tie to what the game is
> * Mouthfull, especially for non english native
> * Finish in ers.
> * and again I think I need to change it. It is neatier to change it, as the game evolved too much. If someone picks up a 2 year old video it would be completely misleadind.
> 
> Weapon wise there is only laser and beam, but with tons of addons: 4x barrels and 3 (maybe 4) side addons (in next update). So a lot of possibility. I think thats unique!
> Yes I will fix combat for multi!

But surely, the game will fit more with the name later on right? You explore around in space, finding things to do. I get the other points, though

**Comment by FelixGold** [comment]
So since its very little tie to what the game is, does that mean the focus is shifting away from exploration and survival to just be a creative combat sim?

**Comment by ultrak2k** [comment]
Also, hold on, there aren't any beam barrels @tsunamayo

**Comment by ultrak2k** [comment]
Balance issues include gatling barrels being far superior to every other option anyway, so is there a point in using other barrels right now? especially since you can't combine them.

**Comment by tsunamayo** [comment]
Yes I am currently working on the gatling, it will be a different logic. Yes beam dont have barrel, it dont make sense, but they have side addon. Likewise projectile gun will only have barrel, no side addon as they will be ammo based.
Barrel => the way the payload is fired 
Side addon => characteristic of the payload (laser or beam)

@FelixGold nope I still very much wants to make a survival and exploration. Here is my mini roadmap:
- space combat 
- npc spawn
- light survival (same system, cash only)
- galaxy back with interstellar travel and holomap.

Holomap was too bugged, new one will be faster and easier to use. Also no point in exploring at this stage, so I preferred to unplugged that for the moment.

**Comment by ZachZent** [comment]
For money, someone suggested Clips as a name. Not units or credits which is painfully overused

**Comment by tsunamayo** [comment]
Clips is not bad!

**Comment by tsunamayo** [comment]
I could say to the old-timers I put clip back in the game!

**Comment by ZachZent** [comment]
Exactly, it is a funny insider reference and sounds good. Also it was Xerma who made up the name

**Comment by ExodistSKY1** [comment]
My two cents for EA:  (please keep in mind these are my opinions)

-Multiplayer... I have 12 friends not including myself who stopped playing/do not want to play because multiplayer does not work  

-All building materials including blocks bricks, those hoses that everyone loves and wants back in game, the adding of the simple chair (having the chair and couch that are in game bothers me because I cant build on to them and they just look out of place in most areas)  the quality of life enhancements can come later.

-Combat:    (just needs to be simple that can be expanded on)

-Weapons:  I am not a huge fan, but they work and that is okay. I would want a slider to allow for a one time change of rate of fire to damage so we can adjust our weapon systems ourselves. the extendable barrel is cool in all, but I feel extending should only impact the spread/precision of the weapons (mainly talking about Gatling barrel for reference) I want to see missiles (balance later)

-MECHS!   You had one of the most Unique things that was in and then was taken out, MECHS! Everyone wants mechs, it does not need to be perfect it just needs to function Fix it as you go! People have and will purchase this game simply because they can make their own MECH!

-The faction system:  You asked for our help with building you ships and then kinda went MIA on us.

-Color pallet: Everyone wants more colors, not less, I still think the pallet Xerma suggested a few months ago would be perfect

-A place holder for cargo/fuel/what even is going to be implemented for the vehicles??? I have backed the game since the kickstarter, read through the faction build, and I still do not know how I can future proof my ships. So much so to the point that I got frustrated and stopped building entirely. 
               If you do this to brand new players or even returning kickstarter backers (most have stopped playing) they will be unforgiving and give a very bad review, asking why the game was rushed. 

in conclusion:

-Multiplayer
-All building materials
-Combat
-Weapons
-Mechs
-Faction ships?
-Color pallet (more not less)
-Placeholders (Cargo,Fuel)

Most of these are nearly done (This is also my ignorant opinion on the matter)


A few of us in the community have tried to give you ideas that we feel would help make the game better and more enjoyable as we love your game and want to see it succeed, its not that we are trying to say you could not have thought of our idea. For the most part the suggestions have been bounced around between many members of the community that are actually active and play/build in the game a LOT! 

My suggestion, open another backing wave but for an entire week, there are plenty that want the game that are waiting in the discord, I would not go Early Access before the game is ready or else the bad reviews will bring it down. If a game has mixed reviews I wont give it a second look. I hope I am wrong but the game will be picked apart if it goes to EA rushed.

Please do not take this personal, I want the best for the game as I have spent more time on this game than anything else I have owned.

**Comment by ultrak2k** [comment]
@tsunamayo (^)

**Comment by tsunamayo** [comment]
Okay now this is becoming something different. 

I do not want backers to come in and say it is a crappy game, dont buy it. That would be the end for me, and a missed opportunity to see the game achieve greatness. I have tried to increase the quality of the game, not cram feature. A lot of the work where behind the scene stuff, refactoring in order to have less bug. I know it is not sexy, but it is of the utmost importance.
So I would like to see who wants to put a review and what kind or review they want to leave. If I need to address something better it be now.

On other points:
- Multi: have you tried recently? I made a big session fix a couple build back. Combat is still bugged. Will fix it before ea.
- Yes I am about to resume to work on faction - sorry I am just super busy as you might guess.
- I unplugged mech because that was too bugged and needed a complete overhaul. I dont want to release a feature, then nuke all player mech because I changed the tech. I know it sucks but thats the only call. 
- I cant just cram nonsensical color palette that you google on the net. I want to put custom color back. But feature creeping in the direction of creative building is one of the reason I am running late.
- Seat, hose and so on. Again I want to add these things but in the case of hose I need to make sure it run smoothly. I know now that I need to account for the fact some player will put 100s of them. I was naive to that before.
- I dont really like placeholder. But I can add try to add cargo before ea.
- Weapon, so the update is coming soon. There is spread now, and gatling are reworked. There is addon, options to fire in volley with the charge addon ect. I feel it is not that bad. Yes it would be better with missiles...

**Comment by ultrak2k** [comment]
> Okay now this is becoming something different.
> 
> I do not want backers to come in and say it is a crappy game, dont buy it. That would be the end for me, and a missed opportunity to see the game achieve greatness. I have tried to increase the quality of the game, not cram feature. A lot of the work where behind the scene stuff, refactoring in order to have less bug. I know it is not sexy, but it is of the utmost importance.
> So I would like to see who wants to put a review and what kind or review they want to leave. If I need to address something better it be now.
> 
> On other points:
> 
> * Multi: have you tried recently? I made a big session fix a couple build back. Combat is still bugged. Will fix it before ea.
> * Yes I am about to resume to work on faction - sorry I am just super busy as you might guess.
> * I unplugged mech because that was too bugged and needed a complete overhaul. I dont want to release a feature, then nuke all player mech because I changed the tech. I know it sucks but thats the only call.
> * I cant just cram nonsensical color palette that you google on the net. I want to put custom color back. But feature creeping in the direction of creative building is one of the reason I am running late.
> * Seat, hose and so on. Again I want to add these things but in the case of hose I need to make sure it run smoothly. I know now that I need to account for the fact some player will put 100s of them. I was naive to that before.
> * I dont really like placeholder. But I can add try to add cargo before ea.
> * Weapon, so the update is coming soon. There is spread now, and gatling are reworked. There is addon, options to fire in volley with the charge addon ect. I feel it is not that bad. Yes it would be better with missiles...

I think most of us appreciate the push to make the game of quality instead of feature cram. I kinda did make a mistake by mentioning starmade as even today that game is a feature cram hellhole - and personally I don’t think there will be a negative review wave, most likely then not people will be understanding (well at least backers anyway). In my opinion I think the timeline of the good shit coming right after release has its perks in its own way, because prior I was thinking “oh no what if the game doesn’t have enough features”, but rolling out somewhat major updates after a release can give the feel of a game that’s being actively worked on. So to be honest, I personally everything will be okay, and for me the original question has been awnsered in more ways then I thought possible. Just gotta hope for good name options :P

**Comment by ZachZent** [comment]
> I dont really like placeholder. But I can add try to add cargo before ea.
Just a reminder of this post which even after all the updates still can work if not work even better with the new systems in game.
https://github.com/tsunamayo/Skywanderers/issues/1292
Summary: A shelf block, probably something similar to the scaffolding we have now, is used to hold physical cargo containers which act similar to Minecraft chests

**Comment by FelixGold** [comment]
I do agree that cargo/fuel systems need to be something implemented before Early Access that way we can get working on those backer ships that you will want in before the game launches to Steam.

**Comment by tsunamayo** [comment]
@FelixGold I can make some simple cargo block (not an evolved solution like of Zack though), and by fuel that depend on what you expect. I can give a tank shaped like stretchable block I had in mind (a sphere that stretch into a rounded box), but that wont be functional for a while, up until I get proper mining / harvesting.
For cargo though, just be aware that cargo will require some power for storage. I feel this is needed for gameplay balance - as mining ect will be pretty much unlimited given the size of the rings ;)
Which means I need to restrict this in some way, but that would give one more dimension for ship design, ie is the build cargo oriented or not.

**Comment by ProPeach** [comment]
Even if these fuel systems aren't fully functional (i.e. you can't fill or empty them, they're an infinite source), it might be worth having that and some other very basic placeholders so that all the backers ships don't need to be refitted when the systems are eventually being reintroduced. Refitting the thousand or so ships would be a nightmare.

**Comment by ExodistSKY1** [comment]
On other points:

    Multi: have you tried recently? I made a big session fix a couple build back. Combat is still bugged. Will fix it before ea.

Multi:   I had tried to set my game up so others could connect late last year, I will try again 

Faction:   Awesome, looking forward to it.

Mech:   Understandable, and I agree (I had thought it was just the animation you wanted to rework)

Color Pallet:   Custom colors > Pallet 

Seat, hose, so on:  Yeah... when you give us something as awesome as the hose builders will be placing that thing everywhere!
 
    I dont really like placeholder. But I can add try to add cargo before ea.

I understand not liking placeholders but it allows us builders to visualize the way you want something to be implemented a little better and prep for it.

Weapons:  looking forward to it, and yes, everyone loves missiles (even placeholder missiles!)

Ultra and Xerma brought up a good point about a steady stream of updates and communication between the Dev and the EA backers. An update every 2 weeks to a month or communication on what is being done is huge and appreciated!

Just an idea... but as opposed to having cargo require power for storage why not make it have a mass? The more you have the more mass is added to your ship... making massive freighters slower as a freighter should be.

**Comment by ProPeach** [comment]
I agree with Exodist on all the points he addresses.
Concerning cargo, I agree that a mass based system is the most logical, and balanced in its own way. The container itself has a mass, but then each item/fuel/ore/material put inside it should add to that mass. As you say Tsuna unrefined ore is easy to get a hold of, so if it requires very powerful engines to ship around because the ore is so massive the balancing factor is in the extra energy used to power those thrusters.

**Comment by Xerma** [comment]
I personally feel that mass would make more sense than power. Cargo ships in every movie, show, game and even IRL are much slower than non-cargo ships. 

I would also like to know if you have any plans or concepts in mind when it comes to harvesting and how the harvested materials make it from lets a laser to the cargo area. Will it just be magical and appear there or will we need some sort of transfer system (a la pipes)? And then how will players move cargo from ship to ship/station/ground? Will this be a function for mechs/hovercraft/crew? Or will it again be magical and just transfer?

Magical transfers may be much easier to implement, however, it's also pretty bland.

**Comment by ultrak2k** [comment]
For the point of a stready stream of updates - even if people see that the game doesn't have too much gameplay to it, whamming updates like a survival update soon after launch will give people the idea that the game is actively being worked on, so in reality, it might not be bad at all to push things to post release

**Comment by Xerma** [comment]
One thing I keep forgetting to bring up is how the game saves and loads games. I really think the save system needs it's own overhaul before EA release otherwise players will immediately be confused and possibly frustrated by the need to press F1 to manually save every so often.

To lay it out simply, this is what I think needs to happen for saving (You may or may not already be aware of these but may as well bring it up just in case):
- Remove manually saving with F1 and replace with automatic saving on force closing, exit to menu, crashing, etc.
    + Regular saving intervals could work and an option to change that interval would be brilliant
- Ability to create new 'worlds' or 'games'
    + Minecraft style where players can have separate games
- Ability to create new characters
    + I'm unsure if having the ability to create more than one character is necessary considering players would then be able to create a new player for each singleplayer and multiplayer game as they saw fit, however its also not a huge deal

**Comment by tsunamayo** [comment]
@Xerma yes that was on my to-do list before release, there is plenty of un-neat stuff like this to address. Dont hesitate to add anything if you see other elements.

**Comment by Xerma** [comment]
One other thing we will need for early access is building on the torus again. Mostly for a new tutorial building(s). Was only just reminded of that by watching the old kickstarter trailer :^) To go along with that, perhaps a block we can set our spawn to?

**Comment by tsunamayo** [comment]
So this is will be problematic tbh. I need to think on the best approach, ideally I want to have 3d deformable terrain. So my roadmap was:
1) collision asteroid
2) deformable 3d terrain
3) building on terrain.
Worst case I can tweak the starting block a bit so you can make a build aligned to the torus surface.
I needed to tweak it so dont fall for Hovercraft, ect.
I dont know how SE is handling terrain building, with the planet convexity and such?
Also I wont go the old tutorial way - I will put an help in the menu with a few screenshot of how you build stuff. 
Hopefully my system is a bit straightforward and dont need too much explanation!

**Comment by Xerma** [comment]
An easier solution might just be the starting point at a small station above the torus for any tutorials if there will be any but adjusting the starter block could work just fine as well. In SE people build on the ground by having blocks in hand and hover over the ground where you visually see it clip into the ground and has a green highlight indicating you can place there and red for when you can’t. It has to be connected to the ground or else the block just falls and it makes its own grid for you to build off of based on the block you just placed(the one that’s clipped into the ground not the one that fell)

**Comment by Xerma** [comment]
And if you want, whenever you stop by next myself or someone else could livestream SE on discord and show you how it works firsthand. But there’s also likely YouTube videos on it as well

**Comment by ZachZent** [comment]
1. collision asteroid
2. deformable 3d terrain
3. building on terrain.

With your three step plan laid out, which elements are you planning to do before EA and which after? I hope at least the asteroids will have collisions before EA. Would be weird being able to fly though asteroids

**Comment by tsunamayo** [comment]
@ZachZent yes I wanted 1) before ea otherwise it looks silly, but honestly I will see how it goes...

**Comment by FelixGold** [comment]
I really liked the old tutorial building, people get a lot more out of doing than just looking at a picture. Nothing wrong with having pictures in the menu as refreshers, but I am sure people in the community would be happy to build the tutorial building for you if you don't want to put one together yourself.
