### ISSUE TITLE
[Question] Combat Vision and Early Stage Balancing

### ISSUE THREAD

**Issue by SabreMania** [tsunamayo/Starship-EVO#1695]
Greetings. 

As the Early Access release comes ever closer, many people seem to be a bit out of the loop concerning your vision for the game, as this https://github.com/tsunamayo/Skywanderers/issues/1694 thread suggests. You mentionned in it, for example, discussing about a name change for the game for months, yet, the community as a whole was surprised to hear this, as no one was informed of it. 

Nevertheless, this is just one of the many things that we seem to be slightly disconnected about. We lack the knowledge of your vision for the game. But to focus on this particular threat's subject, the more specific aspect would be combat.

So far, we know that you want fighters to have a role, this is perhaps the only absolute that the entire community can agree on. But on every other issue surrounding combat, or just about, we all have our own variants of what we think would be implemented in the game, some more extreme than others.

With that being said, what is your vision for combat? What kind of engagement ranges do you want to offer for the game? And should we already be reporting balance problems at this early a stage of the game?

**Comment by tsunamayo** [comment]
First sorry for the name change, actually I remember I only shared that with the mods, asking them to not share it as it was just not sure back then. I will do a name reveal soon, but maybe steam will spoil me as I will need to update the name in the store also...
Anyway next update is combat focused. AI will be a bit better, and addon more balance, with more side addon. 
At that point yes, I will want a lot of report on the balance! 
Having a fun and engaging combat experience will be important.

First what you guys will want to see in combat? I am willing to hear people opinion.
Now I try to focus on having several way to destroy enemy ship. Ie destroying systems, making a Hull Point kill, or a overheat kill. Hopefully the game is balance enough so that no option is being too good compared to the other vs a balanced ship, so that people can experiment it their design. 
Also it will allows us to make un-balanced NPC, ie ship that would be easier to take down a way or another, adding a layer of analysis decision making during combat.
Ultimately I would like to make it more strategic, with scanning options and precise target assignment (ie that sub-system over there).
Also my end-game will be game progression and crew management, so a lot of current parameter will become things that will be leveled-up in-game: turret precision, turret fire economy (only fire on target) ect.
For engagement range I am not sure to understand exactly, I mean it could be 10m or 2000m depending on your style...

Also I dont want people to read this as "the dev commit itself", I mean you cannot complain that dev dont communicate enough and then complain when things changed after they did communicate some elements... So this is my current plan, and the plan is always evolving with feedback from gameplay and what worked and what didnt!
Cheers

**Comment by SabreMania** [comment]
In that case we will begin working on real ships and testing them!

Another important point I forgot to mention was, how big do you wish to limit ships? Namely, we know that you wish people to build at shipyards alone, and said shipyards have specific maximum sizes. But we do not know what is the biggest ship you want us to be able to build? This is an important factor.

On the subject of engagement ranges, my question was aimed more towards what you want the meta to be focused around. Different ships (destroyers, cruisers, battleships, etc) have different engagement ranges, but that is only true in real life. Still though, I digress. What I really mean is, are the current weapon's ranges final, or close to what you ultimately want? For example, would you leave maximum ranges at around 2 to 5 kilometers, or would you make them longer, so instead of 2 to 5, make them 20 to 50 kilometers?

**Comment by tsunamayo** [comment]
So for the size we will have to playtest this. I had some issue with the Whirlwind, as it has a tons of small turrets. I did a lot of optimization, now it is still a bit laggy but playable. It really depends on how many turret you have, and how many ships. Two large ship with a few big-ass turret will actually be better than a mini fleet for smaller ship with a lot of action going-on.

From my experience it was impossible to target anything beyond a few km, but I guess it depends on the size of the target and could be tweaked with higher projectile velocity.

**Comment by SabreMania** [comment]
These problems (Two big ships being better than ten tiny ships) seem to repeat themselves from different games. Starmade had the same problem (though optimization was bad enough that having lag-bombs consisting of instantly undocking a hundred tiny core-drones was enough to crash everyone in a given sector).

As for targets and their range, I was rather asking what you wanted the game to be like. Having fights occur at 50 kilometers between each party is doable if you take current projectiles and accelerate them so much that they cross such a space in just a few seconds. 

But that goes back to what I am asking. Did you not have a vision for engagement ranges? Any kind of inspiration for how you wanted battles to look like when they unfold? 

There's a hundred ways to skin a cat, and there's a hundred ways to make a game. If we take World of Warships, they designed their game in a way that makes shooting and waiting around 15-20 seconds before your shells land on target possible, and viable. Though it's a class-based game where you don't get to build and modify your ship how you want like you can in Skywanderers.

If it was just from me, I would allow ships up to about a kilometer to be built in survival, and produced, and have maximum engagement ranges between two non-carrier ships be around 15 to 20 kilometers.

However, this all ties to the only point that the community knows you are fixed on: You want fighters to be viable. So then, perhaps the best way to determine engagement ranges is... Fighter speed. Do you want fighters to go around flying at faster than sound speed like modern jets? Or do you envision more fighters that are more around WW2-era speeds? Or perhaps somewhere in between? If we figure out what the (meta) fighter speed is supposed to be, then we can guestimate what ranges a carrier is supposed to be able to engage safely from, and from there we can work the rest of the weapons's ranges.

**Comment by tsunamayo** [comment]
Nobody has the time to build a 1km ship. Especially for survival! I mean if you do good for you, but I wont balance my game with unpractical scenario. So "massive" ship are gonna be more like 300m I think. And dont expect to see a fighter take down a big one.
Ideally I would like to player to be able to take down a slightly larger ship. Ie a 100m taking down a 150m. Maybe a 50-75m taking down a 150m if you have very good mods and crew level.
Figthers will be harder to pin-point, so I plan to have turret speed taken into account. So you will need small defensive turret for them, and larger one for your main target.

I dont think it would look like World of Warship (But I didnt played that game so I dont know for sure.), spaceship will be much more maneuverable and it is 3D so trajectory are impossible to predict over 20 sec.

And yes I prefer starwars WW2 style combat for figthers. But we will see, for sure jet like is more missile based so cant do that for now.

**Comment by SabreMania** [comment]
1km ships as the maximum limit is reasonable I believe. It doesn't mean everyone is gonna build up to that! But you would be surprised by how long ships could get back in the days. Having 600-700-800 meter long capital ships in Starmade was pretty common, hence why a 1km upper limit would be, in my humble opinion, greatly appreciated. Unlimited would be even better, but it is incompatible with your system of pre-spawned shipyards being the means of building a ship

You are correct in your assessment that space is a 3 dimensional space, it makes things harder to predict, however I don't think it means that it's impossible. Especially since you seem keen on implementing a system that discourages players from building ships that have equal thrust and acceleration in every direction, according to the changes you have made to thrusters.

The fastest WW2 fighter could go at 660 miles per hour, or 1062 kilometers per hour (259 meters per second). Which is about a hundred meters below the speed of sound. If we take the american P-51, this goes down to 437 miles per hour, or 195 meters per second. 

Taking this in consideration, if we want to keep the current fighting distances and keep our hypothetical carrier safe, so let's say 3 kilometers outside of maximum theoretical enemy range, being 5 kilometers at this stage of the game, this would mean that it'd take about 35-ish seconds for the fighters to go from the carrier to the enemy ship, do their buisness, and then another 40-ish seconds for them to come back to the carrier, assuming that it is not actively fleeing the enemy ship nor chasing it, and that said ship is standing still.

Are these the kinds of numbers you think would be good for the game? There are so many more factors that we can put into this, like how much time our meta-fighters should be able to fly on their own without needing a refueling or a re-armament, but they are not as important as, I believe, the waiting times of just flying to their target and back to the ship, as these are the most boring moments and therefore the ones that you probably want to limit the most.

**Comment by ultrak2k** [comment]
For the topic of engagement ranges, the whole thing with being hard to hit things at multiple kilometres is close to what I personally believe may be a good idea, combat ranges for the norm at under 10km. Though perhaps we may want the occasional big long range weapon that can fire beyond that, but could be relegated to specialised ships or big ass planets guns

**Comment by Xerma** [comment]
The thing with starmade vs this game though is starmade has zero requirement and/or use for interior space plus you could essentially just stack your ship full of systems. Yes I know now that starmade has a different way it does systems/power but you also have to take into account that this game is much larger in terms of scale. Plus in terms of what the game has planned then you have to realize that smaller max ship size means that the game can handle more of X feature vs just big laggy ship battles. I would personally rather have limited ship sizes to experience a bigger fight and more things that add to the experience. The largest ship that I have being built right now is the 250m diameter "sphere" and I genuinely don't know what all to fill it with. It's hardly built at all and it can already hold a large amount of cargo/ships/fighters/hovercraft/mechs. Probably beyond the point the game could even handle. So it's either more cargo room that is unlikely to get used all the way or add in a bunch of rooms and halls to wander around it but also have little to no purpose because I still have plenty of room to house all the crew members I'll ever need and more.

**Comment by Sei-Neko** [comment]
Definately do go with the ww2 fighter combat idea. Also consider a way to limit 6-dof movement during fighter combat to discourage starmade-style hoverfights.

**Comment by ultrak2k** [comment]
Actually, when I think about it- long range combat would look very visually unappealing, while the weapon ranges and projectile velocities as of right now are a good compromise between seeing the enemy, and distance. Though I think smaller weapons should have smaller ranges to encourage closer in combat between smaller vessels, and also fighters can still have the time everyone wants as carriers don’t need to be in firing range- we can keep decent fighter speeds.
