### ISSUE TITLE
[Suggestion] Preventing beam hitscan

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#1724]
A common problem with beamers (laser beams) in many games is that they can be hitscan weapon. A weapon that you simply click on the enemy ship and it will hit no matter what. As long as your mouse is on the target, it will take damage.

A solution to this would be making beam blocks weigh more. That way when on a turret, they are unable to perfectly track targets. Still can hit, but can't keep hitting as a fighter is maneuvering. If they are standing still for flying in a straight line that is their fault. Now they shouldn't weigh too much so they are practically immobile, just enough that they can't murder your less armored and shielded fighters.

**Comment by ProPeach** [comment]
I disagree that adding mass is the best option to nerf beams. Accuracy should be enough to ensure that the beam cannot hit a target 100% of the time, especially if the beam moves around it's firing cone when the beam is active.
Given that they are hitscan weapons and you can't really change that fact seeing as it's a beam, I suggest that the beam be given a damage falloff over distance. This means that while you're able to hit a target instantly at maximum range, you're not doing max damage to it. This balances out the increased time on target gained by being easy to aim at range with the lowered damage, so your DPS isn't much higher than other weapons.

**Comment by tsunamayo** [comment]
So for now my plan was to have the beam with less DPS compared to the laser, and have a smarter tracking speed on the turret. I really need that anyway, so that longer barrel will be slower to aim at.
But I dig the idea of a decreasing DPS with distance, it is a smarter version of simply lower DPS.
So that it still make laser + sniping barrel intersting vs pure beam.
For now they are perfectly accurate, I could add a bit of accuracy also, will see how it goes.
