### ISSUE TITLE
[Suggestion] Weapon Rate of Fire

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#1727]
Just a quick one, I think that the larger you stretch the weapon core block, the longer the reload time of the gun should be. This is because longer cores also increase the damage per shot of the weapon but as it stands the largest gun fires at exactly the same rate as the smallest gun which feels odd, and doesn't offer you much of a choice in how long you stretch your gun - a longer one is better in every way.
If the RoF also increased with the gun length, you're able to make a decision between a higher damage slow firing gun or a faster firing lower damage gun depending on your preferences and what targets you think you'll be facing. It also makes the smaller guns more useful.

As an extension of this, I think that brick weapons should have their base reload rate decreased for the same reasons. They're much smaller than block weapons but at the moment they fire at the same rate.

**Comment by tsunamayo** [comment]
@ProPeach if I make them fire slower I think it would be frustrating. Also people are pushing me to make the gatling continuous fire, which would not fit in this plan...
Yes of course a longer weapon is better in (almost) every way, how could it not be ;) ? A bigger reactor is better in every way, a bigger shield ect. At the end it is a matter of heat / power balance, if you can affort a bigger weapon please do!
Is said almost because there is a drawback: turret speed will be slower for longer and heavier gun.
Brick base weapon are just less powerfull, at 25% of DPS of the larger one.
I would prefer to have to leave firing / charge time modification to the addon, hopefully that make sense!
Cheers

**Comment by ProPeach** [comment]
I actually think it would be much more satisfying rather than frustrating. Frustration usually occurs when things don't work as they appear they should, or perhaps the player is forced to do something that doesn't make any sense without good reason. Landing a high damage, slow reload shot is a really great feeling in any game (playing as a sniper, a battleship, a tank etc). Reload rate is one of the biggest things you notice the moment you start firing, and if all sized guns have the same reload rate as they do now, that feels a bit boring to me. It's a huge missed opportunity to make each size gun feel more unique and personal to the builder and operator - take any FPS game for example, no two guns have the same reload rate so each gun feels like a different experience.

I actually think this would work fine for a continuous fire Gatling barrel. A longer core would just mean that the time between shots is longer, maybe a spool up time for the gatling gun before it starts firing too? With this system a long core, long barrel will create a high damage heavy feeling gun while a shorter core with a long barrel would create a gun which fires faster, feels lighter and has lower damage per shot. Both of these guns are important, especially for fighters shooting at other fighters. It is very difficult to hit a fighter in that circumstance when you only fire every 2 seconds or so, or you're limited to a burst of only a few shots at once.

**Comment by Aiwii** [comment]
Instead of a cool down having a spool up would be very interesting. Possibly having the gattling generate more heat so that the player won't be motivated to hold it and the pauses in fire being due to the gatling spooling up again could be another way to tackle it.

**Comment by ultrak2k** [comment]
I don't think it would frustrating at all, having more beefy low fire rate long weapons actually is far more satisfying then having a normal fire rate beefy gun. Weight alone is not enough balance against large weapons, and having the principal of "of course larger = bettter"is what lead to the general mess that is the balance in some other games @tsunamayo

**Comment by ZachZent** [comment]
I was testing my shuttle vs Tsuna's shuttle in basic combat and the brick weapons are unbearably slow. Not just gatteling, but normal brick bolters. The delay between shots were so large that it would take minute just to lower the shield on the shuttle from a similarly armed ship. Part of that is because of the shield balance, something I plan to make a full post about in the future, but having that delay is just frustrating. High rates of fire of the most basic guns are much more enjoyable for the players. The balance can be generally lower damage per shot equaling the same DPS, but faster rates of fire is always more fun.

**Comment by tsunamayo** [comment]
So in the last build I actually increase the rate of fire to 1 per second, much better than every 2 sec. Gatling will get continuous fire.
I am not sure if you are seing those value in the build you used.
Shuttle vs shuttle the shield was not that bad, but each engagement were definitely a bit long - but my shuttle are not system stacked either.
I think I will increase the Hull kill threshold also, it will make each fight faster.

Please continue to get feedback!
Cheers
