### ISSUE TITLE
Missing Thrustoutput

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1728]
### Short Description of the issue:
The animation of the thrustoutput is missing for some time.

### Steps to reproduce the issue:
Build something with shipcore, generator and engine and fly it. My friend has the same problem (also Nvidia-Card)

### Environment
- Skywanderers version: 20w15d
- Graphics Card: gtx 1070 mobile

### Additional information:

![Skywanderers_2020_04_11_15_02_22_562](https://user-images.githubusercontent.com/43222403/79044544-f8425980-7c05-11ea-9730-46a09bd9006e.jpg)
(>300km/h but no output animation)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4464642/output_log.txt)

What you can also see on the picture, ist that no hullpoints for smallBlocks are calculated. But this is only because its not yet implemented right?

**Comment by tsunamayo** [comment]
Not sure to understand, are you talking about the thruster trail we had before? If yes they are gone for now! I will some other effect in the meantime. 
Also yes there is no hull point for small blocks, they are not hull. It is an old debate, I wont get started again ;) Damage and hull point system is voxel based. Your ship cannot be destroyed because of low HP, but it will just be weaker, which is balanced by the fact that it is faster and harder to hit.

**Comment by Battlepixel** [comment]
Yes i meant the thruster trail.
Thanks for the quick answer. (:

**Comment by tsunamayo** [comment]
Okay it was not really a bug, but they might come back one day ;) Cheers
