### ISSUE TITLE
Heat mechanics need a huge change

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Starship-EVO#1742]
As it stands now, getting "heat kills" will be the meta of the game, get a quick heat kill and don't waste your time trying to do anything else.

   Trying to work around the current heat system is not fun, its frustrating, it limits the creativity of the builders, and led to me to stop building in the game for the past few months. 

My ideas to help tweak the heat system for the better:

   - Heat threshold and dissipation NEEDS to be increased by a lot

   - Heat "destroying" the ship should be removed 
           in its place heat overload should shut down all control and systems for a set amount of time
           this would make combat more dynamic and much more enjoyable than a simple heat kill, also           allows different tactics and ship uses/roles

 This will still allow heat to be a viable mechanic, i like the heat it just needs to be changed a bit for a more unique and what I feel to be a much more rewarding system.

**Comment by ProPeach** [comment]
While the specific stats of heat are still yet to be perfected which explains some of the problems with the current heat model, I do agree that some more fundamental changes might help too.

As it stands brick systems are not effective enough to justify their very high heat production. Either they need to be more powerful, or their heat production needs to be lowered. Right now brick based ships are under-performing as you can't fit enough systems in them to bring their performance in line with what you'd expect without them overloading due to heat. This means that a brick ship with proper heat balance is slow, under armoured and can afford very little shielding if any. Increasing the heat dissipation you gain by having a high surface area to volume ratio could also help with this.

I also agree that a heat triggered disabling mechanic might be a bit more interesting and less frustrating that a heat triggered destruction mechanic. Of course if you stray too close to the sun you should blow up due to heat anyways, but right now heat damage has a much larger impact on combat that it should have in my opinion.

This is definitely an issue caused by a lot of different numbers, but I do think that making these changes to the heat system specifically is a great first step as it is a big part of ship building.

**Comment by tsunamayo** [comment]
Okay I need a more precise description of the ship you used, as it seems it as much related to brick and small figther (which is a whole design problem to address in itself), as heat.
I already made a few big tweak on the small figthers brick side (before this post but not yet live), boosting surface a bit (+50%), dropping massively weight, and decreasing repulsor power and heat requirement for Hovercraft.

On the heat side yes it will definitely needs more tweak, but I would need you to send me the ship you were having difficulty so I can see for myself.

I can tweak a lot of parameters: 
- hull / system ratio
- flow / stock ratio
- HP damage / Heat damage ratio for weapon
- ect

Before giving up on a mechanic I would prefer to fix it, otherwise I would have give up on this game a 1000s time mate ;)
Not saying that ultimately I will have to drop the heat kill as do as you suggest (which was my backup solution from the start).
Also I will make sure that unbalanced ship cannot explode during building.
thanks

**Comment by ExodistSKY1** [comment]
the BP's you requested
[Blueprints requested.zip](https://github.com/tsunamayo/Skywanderers/files/4467485/Blueprints.requested.zip)

The non exploding during building will be fantastic.

Looking forward to seeing the changes.

**Comment by tsunamayo** [comment]
So I had a look at your ship, first they look amazing! Definitely trailer material! Not sure about the balance yet though.
Heat wise you are good on the new update, the Berserkir is a bit tight though. Other are largely overcooled.
There is some issue with the amazing opening of the figther, I dont know if it was working on your side or not (it dont close 100%)
Cheers

**Comment by ultrak2k** [comment]
> Okay I need a more precise description of the ship you used, as it seems it as much related to brick and small figther (which is a whole design problem to address in itself), as heat.
> I already made a few big tweak on the small figthers brick side (before this post but not yet live), boosting surface a bit (+50%), dropping massively weight, and decreasing repulsor power and heat requirement for Hovercraft.
> 
> On the heat side yes it will definitely needs more tweak, but I would need you to send me the ship you were having difficulty so I can see for myself.
> 
> I can tweak a lot of parameters:
> 
> * hull / system ratio
> * flow / stock ratio
> * HP damage / Heat damage ratio for weapon
> * ect
> 
> Before giving up on a mechanic I would prefer to fix it, otherwise I would have give up on this game a 1000s time mate ;)
> Not saying that ultimately I will have to drop the heat kill as do as you suggest (which was my backup solution from the start).
> Also I will make sure that unbalanced ship cannot explode during building.
> thanks

@tsunamayo  I  believe that we should have some of those heat overload mechanics though - right now it’s a wall between dead or alive, but having intermediate debuffs would make combat interesting and turn heat focused weaponry into weapons that too can help weaken a ship similar to how normal damage weapons can weaken a ship by destroying turrets and systems better

**Comment by Battlepixel** [comment]
I think the heat overload mechaic is great in principle because heat dissipation is the only reason why it makes sense to build space fighters with wings ( as long as there is no drag or buoyancy calculation in atmospheric flight, ->what in my opinion would be very unnecessary^^). But wings look pretty on most fighter-models.
