### ISSUE TITLE
[Dev Brainstorm] Better Starter Block

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#1769]
So before ea I want to improve the building experience by making it more advanced ;)

Just a question, how do you start a build on Starmade / SE?
In SE, to start to build on the ground, you can place any block or a specific block?

I want to make the block anti-grav so you can build Hovercraft easily, with a menu to increase / decrease height. Also maybe putting the loading feature in this block, not sure yet.
And maybe allow building on the torus surface, or maybe allow it with any block? I am not sure if that would be confusing or not, as that would mean that two separate block would be on separate grid.

Thanks!

**Comment by Aiwii** [comment]
I'm pretty sure in SE you have to place a landing gear on the ground to start a build at least on a planet's surface that's the case...

**Comment by Xerma** [comment]
Starmade and Space Engineers are fairly similar to what we have now. In Starmade you need at least 1 ship core in your inventory, press X and a new ship entity will spawn in front of you (which is the ship core block in your inventory). In Space Engineers you can just place a block if you're in space otherwise you'll want to place their landing gear because they can lock on to objects that are directly beneath them. What we currently have could work but it would help if the block is aligned to the player's orientation when placed or if it aligns to some preset static grid (this option would help when wanting to build within smaller areas or if you want to build everything in a line)

**Comment by Sullos** [comment]
I like the idea of the hovercraft starter block. Having it height adjustable with antigrav features. It seems like it would work well for all vehicles built near a source of gravity. Perhaps making the starter block needs to be removed before the ship can fly.
So for example place, the antigrav starter block, interacting with it allows for 1m directional adjustment. 
You can build your vehicle off of it, and once you have all components on it like the hovercraft repulsors, the power source, etc, you must remove the antigrav starter block before controlling it would work. Kind of like how when a ship has been destroyed, it won't fly anymore.

**Comment by ProPeach** [comment]
Building on a planet in SE:
You can start by placing any block, but it must intsect the ground otherwise it falls and becomes a ship. The block automatically aligns itself perpendicular to the gravity direction, but you can still rotate it smoothly on the horizontal plane by holding the rotate key - it doesnt rotate in 90° increments so you can angle a grid any way you like.
If you start building in a separate area but still close to the first structure, you can choose to either align the grid of the new structure with the first so you can connect them later or start at a different angle which is a nice feature to have. I think the way they toggle that is with a tooltip and a key press, it says "press x to align to current grid" or similar.
As Xerma said if you want to build a ship on a planet you first place a landing gear which locks onto the ground so it doesn't fall over, but really that landing gear almost always gets replaced by something else later, I usually build up a few blocks and then start building the ship so the gear doesn't get in the way.
An antigravity starter block would solve this quite well, although would it need to be removed before trying to fly as it locks the ship in place otherwise? Sounds like another use for your new warning system!

**Comment by ultrak2k** [comment]
I think it would be nice if you could also somehow adjust rotation of the anti grav starter block too

**Comment by Xerma** [comment]
Made a little gif file for you to see firsthand what it's like to build on the ground in SE

![SEBuildGif](https://user-images.githubusercontent.com/32974671/79522774-35518600-8022-11ea-812b-5b3382e6a9b8.gif)

**Comment by FelixGold** [comment]
I think you should pivot from the shipyard idea, do like SE/avorion/SM/empyrion and allow for placing blocks in space or on the ground and building off of them, and then using shipyard just to build saved blueprints in a quick fashion.

For Space engineers when you build on a planet or asteroids you slightly intersect your block with the ground and that locks it in place, and you build off of it from there and it works really well.

**Comment by ExodistSKY1** [comment]
I think having a universal starting block would be best for simplicity.

Looking at Xermas GIF I like the idea of the placing location moving with the cursor. 

In contrast with FelixGold, I think having a specific place like the shipyards, the landing pads, and possibly an expandable construction platform to allow building of ships, mechs and hovercraft on planet/ring based areas. Possibly being able to enter a console and build it in a virtual/ hologram type first and then providing the resources to the construction platform to build the ship (I do not think building ships should be instant, and should take time, making people more cautious)

I personally do not like the idea of building anywhere, but that is just my thoughts and understand the merits of both.

**Comment by Battlepixel** [comment]
Is the possibility planed to build something like own bases later in the game? If it is: For example it will not be possible to build a HomeBase in an Asteroid crater or in  free Space if you make building only possible on predetermined locations.

**Comment by tsunamayo** [comment]
Thanks for the great contributions! And super thanks for your vid @Xerma it was super useful.
So here is what I have in mind

- Single block for all use.
- Menu with various tool, like loading a blueprint, tweaking height or rotation, or lock radius.
- Preview of where it is placed
- can lock to terrain => will align to terrain normal (normal to center of torus, not local normal) for base building
- rotate smoothly (not in 90deg increment as it has no use). But will come aligned in all axis to torus terrain by default.
- Anti-grav, so we can build Hovercraft or even just ship on the torus
- can be added to an existing build so we can use anti-grav for touch-up. Super important as Hovercraft needs a lot of tweaking!
- need to be unbuild to start flying.
- Build radius for terrain: => once a starter block has been constructed we can put any block on the ground and they will align the grid. We can configure that grid radius or shape (default is sphere, but we can make it a cube for tight building) or desactivate the grid.

Okay I think that cover all we need! Feel free to add anything I missed.

And yes I want people to be able to build anywhere. But in career you will need to be close to a station to be able to buy blocks ect. But like in a km radius or something like that. We will shall see I might change my mind again after first play-test.
Cheers
