### ISSUE TITLE
[Suggestion] Cockpit glass brick stretching to 16 meters

### ISSUE THREAD

**Issue by Starwhip** [tsunamayo/Starship-EVO#1773]
As of the latest build, the large cockpit glass was removed from the codex, making canopies larger than around 4 meters difficult. Allowing the canopy bricks to stretch to 16 meters or reintroducing canopy glass blocks would be nice.

[Canopy Comparison (Imgur)](https://imgur.com/a/Y3g2F2T)

**Comment by tsunamayo** [comment]
Thanks for the screenshots! So what I would prefer to do for super large canopy is to make large wedge/tetra matching the transparent cube - with 1m thickness. Would that fit your need?
Thanks

**Comment by ProPeach** [comment]
For me a thinner glass like the current canopies would be much better, interior space is important in a cockpit even at the sizes Starwhip is talking about and above, so a 1m thick pane wouldn't be ideal for that especially when you're stretching a wedge.
The border on the canopies is also a really nice thing to be able to play with and really sells the idea that they are in actually canopies rather than large single slabs of glass. It feels weird to look through something so thick and unwieldy. If stickers could be placed on transparent blocks it would help with that, but I understand that won't work with your tech. Perhaps a happy middleground could be achieved at 0.5m thick.
Out of curiosity, are there any tech problems with upping the stretch limit of the current canopies? That really would be the ideal result, the community loves those new bricks on the Discord server.

**Comment by tsunamayo** [comment]
Yes max scale is 16 x time the base size of 0.25cm.

**Comment by tsunamayo** [comment]
Now you get grid-scalable canopy! Thx
