### ISSUE TITLE
[Balance Suggestion] Reload/Recharge time scaling

### ISSUE THREAD

**Issue by SabreMania** [tsunamayo/Starship-EVO#1798]
As it currently stands, it's no secret that weapons are not exactly in their final stage when it comes to stats. Some weapons are more powerful than others, and some just straight up do more damage than others. However, that's for another post.

In this post, I would like to focus on reload times, and how they could scale up. Right now, other than the gatling barrel, the only way to increase fire rate is to have the Supercharge Addon. If you have a brick weapon, there is no way at all. (Again, excluding the gatling barrel.)

What I would suggest is to make the guns's reload/recharge time increase the more you stretch the 'core' block, so not the barrel, but the weapon itself­. For example, right now, if you take a laser block, and you stretch it to it's maximum, the only downside you get from it is an increase in heat and energy requirements, but that's it. A ship using smaller guns will fire at the same rate, for weaker shots.

If the base reload time was to increase with the length of the laser/beam weapon, it would allow for greater choices and variety to be added to the gameplay. This would mean that you could have the choice between having small weapons that fire quickly and don't deal too much damage, or larger weapons that deal considerably more damage, but have a slower reload. 1 block long laser, 1 second reload. 4 block long laser, 4 second reload (for example.)

**Comment by ProPeach** [comment]
Absolutely, I created #1727 with the same suggestion and I still agree with everything I said there.

With the constant fire rate we have now all the guns feel the same when you're using them. This feels very strange, especially given the amazing potential of the add-on/barrel system which is there to make every gun unique. Big guns fire slower, that's always been the rule in games to keep things exciting, satisfying and balanced.

The base reload of the block guns should also be increased, or the reload of the brick guns decreased again for the same reasons. They shouldn't fire at the same rate because they're different sizes and do different amounts of damage.

**Comment by tsunamayo** [comment]
I think atm our vision is distorted by the fact we are building in creative.
I did not made the gun rescale to give more variety to the weapon design: I created the addon system for that.
Rescaling is needed because ships have different size, thats it. I dont want people to use 4x laser instead of 1 laser of 4 long as it would make the game lags more.  Longer laser are more costly and more powerful, why would you want to add a downside? 4 blocks is always better than one, a ship 4x time bigger is always gonna be better.
If you have the power / heat to spare, go for the 4 long!
Plus there is actually a few difference but you need to use them in combat instead of just comparing stats:
the longer laser have more powerfull shot. It means that it will penetrate deeper into the hull once it hits. It means it is the perfect anti-system weapon, as it will break the hull and take down a few system on hit.
Instead if you put 4 lasers side by side for example, they will each hit a contiguous hull but wont go as deep as the 4 long. So thats make it better for hull kill instead of system sniping.
Aslo longer block will have more inertia for turret but this is not yet implemented.
Thanks

**Comment by SabreMania** [comment]
> Longer laser are more costly and more powerful, why would you want to add a downside?

The truth is, it is much more cinematic. Coming from Starmade, one of the things that I very much disliked was how the meta had always more or less been around having a ton of high-damage, high-rate of fire spinal guns that allowed you to machinegun your way through the toughest shields and armor in the game. 

Having lasers that are 4x long, with 8x long range barrels, so essentially this game's equivalent of a 16 inch gun, fire at the same rate as a much smaller gun, is a little bit of a dissapointment. Especially given how you can reduce that rate of fire even more, and have your big Space Battleship fire it's deadly shells once every .5 seconds if you take the Supercharge addon and crank it to the max, too. 

Nobody is disagreeing that bigger guns should be more powerful. But the current rates of fires, except for the gatling barrel, are perhaps a bit fast, and they lack variety, since the only way to change this rate of fire is with the Supercharge addon, and all it does is increase the rate of fire even further.

**Comment by ultrak2k** [comment]
> I think atm our vision is distorted by the fact we are building in creative.
> I did not made the gun rescale to give more variety to the weapon design: I created the addon system for that.
> Rescaling is needed because ships have different size, thats it. I dont want people to use 4x laser instead of 1 laser of 4 long as it would make the game lags more. Longer laser are more costly and more powerful, why would you want to add a downside? 4 blocks is always better than one, a ship 4x time bigger is always gonna be better.
> If you have the power / heat to spare, go for the 4 long!
> Plus there is actually a few difference but you need to use them in combat instead of just comparing stats:
> the longer laser have more powerfull shot. It means that it will penetrate deeper into the hull once it hits. It means it is the perfect anti-system weapon, as it will break the hull and take down a few system on hit.
> Instead if you put 4 lasers side by side for example, they will each hit a contiguous hull but wont go as deep as the 4 long. So thats make it better for hull kill instead of system sniping.
> Aslo longer block will have more inertia for turret but this is not yet implemented.
> Thanks

bigger = better is what caused gigantism in starmade and other games, larger weapons need a downside that is balanaced in a way that makes it so that bigger weapons aren't an absolute, but still as a general rule are good. Sure, smaller weapons do more damage and whatnot, but its uncinematic, unsatisfying, and unbalanced for larger weapons to have the same fire rate as a smaller weapon.

The entire concept of bigger better can and might lead to a balance tragedy later on and somewhat contridicts the idea of fighter/smaller ship viability imo. energy costs, ammo costs, heat alone can't balance larger weapons alone, we NEED lower fire rates for them. Lower fire rate, but hard hitting guns that are accurate still mean people will use them over lots of smaller ones, because small guns aren't used for that anyway, so adding more won't do anything -  you still can incentivise that with other ways, bur we really just need lower fire rate big guns man.

**Comment by ZachZent** [comment]
Think of this from a logic standpoint. You have a say, a large combat ship. On it you have a turret with small lasers and a turret with big lasers. The small lasers are weaker, but can turn faster. They would be taking down fighters and incoming missiles.
![](https://cdn.discordapp.com/attachments/406664114249793536/702674741802172476/latest.png)
Now the larger turret would be for taking down the larger ships. More powerful, turning slowly, heavy hitting. They would be for taking down the larger ships with the slower speed/turn speed.
![](https://cdn.discordapp.com/attachments/406664114249793536/702674582800433203/latest.png)

Both on a cinematic and logical level in both gameplay and cinematics, would it really be right for a heavy gun to just keep shooting at the generally same speed as the small guns with a much larger damage per shot? The larger guns in the Expanse and in real life (for the most part) have the slower rate of fire due to the time it takes to reload or recharge and make up for it in a powerful shot. Small guns in comparisons would be very quick, as they need to be to take down fighters. It also matches up with their large and small turning speeds respectively. Plus seeing a large cannon shoot one massive shot with heavy recoil just looks good.
https://media.giphy.com/media/WO5b7mUbbvBFbSAYvk/giphy.gif
(Gif won't embed)


Fire rate based on size also makes weapon placing and using a bit more dynamic and interesting. You can go for a machine gun like turret to take down fighters or a large heavy hitter for blasting though armor. Or you can go for something in between depending on your needs.

And finally mechanics wise the DPS doesn't necessarily have to scale up with size as it does now given the same fire rate with higher damage. A large gun is in general supposed to place one powerful shot doing large amounts of damage but at a slower rate while a smaller gun does damage at a faster rate. Both have their place and purpose

**Comment by tsunamayo** [comment]
I have post saying gun fire too slow, now it is too fast ;)
You think about the cinematic feel and thats great, but I want to keep in mind the balance of the game.
I can also think about making things cinematic, but _I have to_ keep in mind the balance of the game all the time.
If I scale all the system and weapon linearly, if I balance the game for a 50m ship combat it means it will be balance for a 150m ship combat.
As soon as I deviate from this, now I have to balance for 50m, 150, 200m, 250m and so on.
This is exactly what I did for the smaller brick ship - that makes things harder to balance, I want to avoid this for the full spectrum as much as possible...

I would prefer to add an addon to deal larger shot at a lower rate - will keeping DPS constant (important for balance). I will need a rename as I have too much things named "Charge" but thats not a big deal ;)

**Comment by ZachZent** [comment]
Also as a quick aside, there has been a few comments on how bright the current weapons are. A very bright glow. Would it be possible to tune that down a bit BUT when it fires have it glow bright again?

**Comment by tsunamayo** [comment]
I see, yes I could do that.
I could change the overcharge to longer cooldown that would be more logical.
I could also have the recoil fire bigger shots. That block will be hard to balance, it is a bit useless. Also it is the kind of block that looks good on big battleship like build.

**Comment by SabreMania** [comment]
Perhaps mentionning the cinematic aspect was a mistake on my part. Though it is true, it is by no means the main argument.

I'll admit I am a bit confused by your statement. Namely;

> If I scale all the system and weapon linearly, if I balance the game for a 50m ship combat it means it will be balance for a 150m ship combat.

Which I dare say, isn't true. Differences in ship design philosophy for different ship sizes, as well as how every other stat scales up, will make different ships stand out more or less, and reveal that what might be balanced for a certain size, isn't for a larger size. Which is why these types of games usually have non-linear scaling that make it harder and harder to build big ships (Not that they're always successful, due to other, unrelated problems, but everything is relative.)

On a side note, I have to disagree with the recoil barrel. I haven't been able to test them in a real combat environement yet, but I have them on my latest destroyer, and i'll be ready to test them soon. I think the accuracy it has over the Heat and Gatling barrel make it well-worth the investment, and though one could argue that the range barrel makes more sense, since it gives longer range on top of that, the reduced recoil makes it perfect for smaller, destroyer-sized ships that don't have too much mass to them and still need to go fast.

**Comment by ultrak2k** [comment]
> I have post saying gun fire too slow, now it is too fast ;)
> You think about the cinematic feel and thats great, but I want to keep in mind the balance of the game.
> I can also think about making things cinematic, but _I have to_ keep in mind the balance of the game all the time.
> If I scale all the system and weapon linearly, if I balance the game for a 50m ship combat it means it will be balance for a 150m ship combat.
> As soon as I deviate from this, now I have to balance for 50m, 150, 200m, 250m and so on.
> This is exactly what I did for the smaller brick ship - that makes things harder to balance, I want to avoid this for the full spectrum as much as possible...
> 
> I would prefer to add an addon to deal larger shot at a lower rate - will keeping DPS constant (important for balance). I will need a rename as I have too much things named "Charge" but thats not a big deal ;)

the addon deal is ok i suppose

**Comment by tsunamayo** [comment]
> Perhaps mentionning the cinematic aspect was a mistake on my part. Though it is true, it is by no means the main argument.
> 
> I'll admit I am a bit confused by your statement. Namely;
> 
> > If I scale all the system and weapon linearly, if I balance the game for a 50m ship combat it means it will be balance for a 150m ship combat.
> 
> Which I dare say, isn't true. Differences in ship design philosophy for different ship sizes, as well as how every other stat scales up, will make different ships stand out more or less, and reveal that what might be balanced for a certain size, isn't for a larger size. Which is why these types of games usually have non-linear scaling that make it harder and harder to build big ships (Not that they're always successful, due to other, unrelated problems, but everything is relative.)
> 
> On a side note, I have to disagree with (edit: your comment on them being useless) the recoil barrel. I haven't been able to test them in a real combat environement yet, but I have them on my latest destroyer, and i'll be ready to test them soon. I think the accuracy it has over the Heat and Gatling barrel make it well-worth the investment, and though one could argue that the range barrel makes more sense, since it gives longer range on top of that, the reduced recoil makes it perfect for smaller, destroyer-sized ships that don't have too much mass to them and still need to go fast.

Gimme that destroyed ;) Seriously I need quantitative feedback to base my decision on.

**Comment by SabreMania** [comment]
Maybe it's a bit soon tbh. Not a lot of people are actually doing heavy balancing tests between ships, since multiplayer is still a *little* wonky and nobody has actually build ships with actual ingame combat in mind. I have been, though i'm a very slow builder.

Basically, what I was saying earlier is that linearly scaling everything doesn't mean ships of all sizes will be balanced. There will be adjustements to make that will require a non-linear scaling of stats. But regardless, I think you're right, we need more balance tests to actually show you what combat looks like on a larger scale.

> Gimme that destroyer ;) Seriously I need quantitative feedback to base my decision on.

Hahahah, well, I would, but it's nowhere near finished, all I have is a half-baked hull and a little over half the main guns. I've yet to put any systems in it, besides the turrets's weapons, and i haven't even put any anti-fighter armament. 

Speaking of anti-fighter armament, I tried to make a very small AA platform, inspired by the quad BOFORS that the americans used during WW2, using beams as the base weapon.

![AAgun](https://user-images.githubusercontent.com/52141971/80049657-7d205380-84e1-11ea-90d1-35bb6ab2f787.png)

While I will admit I have not looked at heat and energy consumage in the slightest, I have witnessed that these can actually go through about 3-6 blocks of armor, every single shot. I used the damage-addon along the entire length. This is quite a bit more powerful than I wished them to be, but one stat remains...

Is there any reason why the beams outrange every weapon in the game, except the long range barrel?

**Comment by tsunamayo** [comment]
@SabreMania of course, but if keep things linear it would make it _more_ true than false. Good thing is the recoil barrel is used. But again I dont really have feedback, only system replacement suggestion so I dont know these things...
At this stage I kinda have to iterate and balance the game the best I can with my 20m shuttle and hope that it will scale well enough...

**Comment by ultrak2k** [comment]
Another thing to note @tsunamayo is that even if larger guns had more heat consumption, energy use, etc
if the ship is litteraly just larger, then you get all of that covered, since the reactors and heat scale up too, so then you just have a gun that has all of the benefits of being larger then a smaller gun, with the same downsides, if its purely linear, and without reload/recharge scaling whatsoever

**Comment by tsunamayo** [comment]
Yes I do have to balance with hull strength. But on the other side the is the first tier of hull, I will add more tier for survival.
Nope no reason for the beam... I might go toward the range decrease with length route, what do you think?

**Comment by ultrak2k** [comment]
Hull tiers? Is it gonna be static tiers or will we have idk, chemistry for hulls like you've planned for fuels in the past

**Comment by tsunamayo** [comment]
> Even if a turret turned slower, this would still make larger ships just flat out better then smaller ones

Yes of course bigger ship will be flat out better. Should it be not the case?

**Comment by ultrak2k** [comment]
> > Even if a turret turned slower, this would still make larger ships just flat out better then smaller ones
> 
> Yes of course bigger ship will be flat out better. Should it be not the case?

I uh... no? Big ships should exist alongside smaller ships, not replace them - otherwise you just have a war of gigantism instead of actual gameplay with dynamic ship sizes. Big ships should be better in some ways, and of course be worse in others, like speed, or whatnot. But flat out just
Big ships better? 

That is a death sentence that has guillotined many games in the past

**Comment by SabreMania** [comment]
Personally, I think we should perhaps reduce the range of the beam altogether, or increase the range of the other weapons. 

It's honestly difficult to say, because while I could make a million tests with all sorts of different ships and weapons, and then come with all of those balance suggestions, ultimately I don't know what you want your game to look like.

For example I can easily say that beams should have their range halved. But I don't know what place you want beams to occupy in your game. Is their hitscan capability more important than their range? Or is the opposite true? (These are rhetorical, example-questions).

Personally, I think the damage drop-off at a distance would be good. 



On the note of bigger ships being flat out better than smaller ships, while it is -technically- true to an extent in real life, even the real nations that participated in WW1 signed a treaty to limit tonnage of a ship, in order to stop the ever-increasing sizes of Battleships. Of course some nations dropped out of the agreement before WW2, which gave birth to ships like the Yamato. 

But that's besides the point. In a game like Skywanderers, if bigger ships are just flat out better, you will have factions who's mining power will allow them to just flat out mass produce the biggest ship size that can be mass-produced, since there won't be a reason not to. Different ship sizes should all have a reason to exist, an incentive for them to be built, rather than them being a temporary waste of ressources on the road to having fleets of nothing but 300 meter long battleships.

**Comment by ultrak2k** [comment]
I agree wholehartedly with the idea of small ships not being some annoying roadblock to power - small ships need purpose too, as sabre said

**Comment by tsunamayo** [comment]
of course I want to make small ship interesting, I have done many update and change in the past. But dont expect to take down a a 300m ship with your 10m fighter. Thats just the way it is.
Then we can debate on whether power output should increase linearly, but whether it is linear or logarithm, power should increase with size (I mean what are you proposing @ultrak2k ? to have a 20m ship have the same power output as a 300m?  hell yeah the 300m will have more powerful weapon)
It is balanced because you start at 10m then work your way toward bigger more resource intensive things. 
Then as you can craft higher level blocks (addon, better hull, better mods, better crew), you can have your high level 50m ship take down a 150m base level.

**Comment by SabreMania** [comment]
We're not arguing that a 20m fighter should be able to take down a 300m ship on it's own, of course not. What we're trying to say is that every ship class should have a purpouse. 

Fleet battles will be a thing, right? We have to think, what would motivate a faction to not just spam battleships and nothing else? Other ship classes need some kind of edge, too. 

For example, a Battleship might have a lot of armor, be fast, and have devastatingly-hard hitting guns, but it needs some kind of drawback that other ship classes can negate, for example, low rate of fire for the main guns. 

Fighters on their own can't do much, but in swarms? They can be a danger to a Battleship, flying under it's shields and taking out what little armor it's anti aircraft weaponry has, or it's secondary guns, which allows for the bombers and the smaller, but still sizeable, vessels to come in for a kill.

What the community wants, for the most part, is for fleets to be composed of many different vessels that fulfill different roles. We can't have ships so much better at everything than everything else that it's pointless to build anything but

**Comment by ultrak2k** [comment]
> Of course I want to make small ship interesting, I have done many update and change in the past in that regard.
> But dont expect to take down a a 300m ship with your 10m fighter. Thats just the way it is.
> Then we can debate on whether power output should increase linearly, but whether it is linear or logarithm, power should increase with size (I mean what are you proposing @ultrak2k ? to have a 20m ship have the same power output as a 300m? hell yeah the 300m will have more powerful weapon)
> It is balanced because you start at 10m then work your way toward bigger more resource intensive things.
> Then as you can craft higher level blocks (addon, better hull, better mods, better crew), you can have your high level 50m ship take down a 150m base level.

my point is not that small ship should be exactly as good as big ship, that feels like a strawman argument tbh
My point, as mat/sabre said is that every ship should have its role, big ships shouldn't be absolute dominance, sure, the 300m can have a stronger weapon, but that still needs to be balanced, stronger doesn't mean stronger in everything. That is where slower fire rates come in. It can still have the same DPS as it has now, but it just shoots slower, making it feel like a chunkier gun. That's what i'm trying to convey. 

Smaller ships shouldn't directly destroy a bigger ship, but they can contribute to it with their own unique reason to exist. But the flat out idea of bigger = flat out better sounded to me like that smaller ships would be less worthwhile - flat out better tends to mean better in everything. But I see what you mean if you want smaller ships to have a purpose - that's obviously a good thing

But something to make big weapons feel chunkier and have its own quirks... like fire rate I think is extremely important. Again - obviously a larger gun should be better, but it should have its own drawbacks - not enough drawbacks to make it worthless, and not enough to make it on par - larger guns should be somewhat saught after, it makes sense, but something just as simple as a scaling of fire rate would be nice.

**Comment by ExodistSKY1** [comment]
I have some time tomorrow to mess with the weapons completely and I will spend extra time on how I present it here to hopefully get my ideas on improvements to the balancing understood.

**Comment by tsunamayo** [comment]
> I have some time tomorrow to mess with the weapons completely and I will spend extra time on how I present it here to hopefully get my ideas on improvements to the balancing understood.

Thanks mate thats appreciated. Remember, I am the game designer, so what is useful for me is not a  straight out list of suggestions / value to change, but more a description on how bad things went in combat.

Overall I get your point all, I see only one reason (beside the cinematic effect), which is bigger weapon being less efficient vs small fast moving target, as they have less shots.
My final take on this:
pros:

- Feels good
- make small fighter better

cons:

- add complexity
- is redundant with addon, thats more an addon task
- break the stack is linear implicit rule for the player
- can easily be worked around, you put 4 blocks instead of stack of 4 then you get the full advantage and big DPS. Some not really solving anything meta-wise

At the end, I feel it is too soon to change and add complexity to the mechanism, I now want to base my decision making on actual data and actual dog-fight feedback, trying to solve real issues.

**Comment by ultrak2k** [comment]
> > I have some time tomorrow to mess with the weapons completely and I will spend extra time on how I present it here to hopefully get my ideas on improvements to the balancing understood.
> 
> Thanks mate thats appreciated. Remember, I am the game designer, so what is useful for me is not a straight out list of suggestions / value to change, but more a description on how bad things went in combat.
> 
> Overall I get your point all, I see only one reason (beside the cinematic effect), which is bigger weapon being less efficient vs small fast moving target, as they have less shots.
> My final take on this:
> pros:
> 
> * Feels good
> * make small fighter better
> 
> cons:
> 
> * add complexity
> * is redundant with addon, thats more an addon task
> * break the stack is linear implicit rule for the player
> * can easily be worked around, you put 4 blocks instead of stack of 4 then you get the full advantage and big DPS. Some not really solving anything meta-wise
> 
> At the end, I feel it is too soon to change and add complexity to the mechanism, I now want to base my decision making on actual data and actual dog-fight feedback, trying to solve real issues.

couldn't you just de-linearise the damage so that 4 smaller guns isnt as good as a 1 4 long gun - isn't that what you did with reactors anyway
or perhaps longer guns have less spread, which would make more sense

**Comment by tsunamayo** [comment]
No reactor are linear like all systems. And longer barrel have less spread alread, make sense!

**Comment by ultrak2k** [comment]
> No reactor are linear like all systems. And longer barrel have less spread alread, make sense!

oh ok thats fine then

and whoops, thought reactors had scaling bonuses or unbonuses, sorry

**Comment by ProPeach** [comment]
> pros:
Feels good
make small fighter better

RoF scaling with the core size also makes fights much more interesting, is more logical/widely accepted and it gives an attacking ship an idea at how powerful the guns are on another ship. If the lasers come at you slower, the'll be more powerful.

> cons:
add complexity

It's not complex, it's logical. It doesn't take much thought to realise that a bigger gun means it fires slower, and it's no secret because you have the handy menu in the gun.
>is redundant with addon, that's more an addon task

Stretching the core already changes stats like power/heat generation and damage, why not rate of fire? We're suggesting that the *base* rate of fire change, then you can still tune it with more addons if you like. That exact system is already in place with damage - stretching the core adds damage, and you can add more damage by using a damage module
>break the stack is linear implicit rule for the player

Once we got to this stage, I was going to suggest that the RoF increase linearly too. That's just a matter of fine tuning the values later with more balancing.
>can easily be worked around, you put 4 blocks instead of stack of 4 then you get the full advantage and big DPS. Some not really solving anything meta-wise

If players do this (not all will), then there's no reason to stop them. They'll have a gun array that does lots of damage, but produces lots and lots of heat and requires plenty of energy. I don't see why this is a problem.



Separately if you want to reduce lag, lets reduce the amount of guns on a ship. If all guns had their Heat/power consumption and damage gain buffed by say 3x for example, you only need 1/3 of the current number of guns per ship to do the same job as they do currently. Then the game has a lot more room to make each gun distinct and exiting - fast firing small guns, large damage slow guns, specialised guns with different addons. With fewer total guns each individual gun becomes more valuable, and it also reduces the number of turrets and therefore child entities too.

Look at the Whirlwind for example. It's a great ship, but it has many, many turrets which all cause lag. If the ship had 4 times fewer turrets but some guns fired 4 times faster, some guns fired slower and some were even more specialised you result in a much more interesting ship to fight and build, as well as a less laggy ship.

You can use this method with any systems really, you make them all "denser" in terms of stats and then you don't need as many to do the same job.

**Comment by ExodistSKY1** [comment]
I wanted to post this so you know I did not forget, I am in the process of finishing up the writing and then editing on the weapons testing/dog fighting I did today. I will be looking it over again tomorrow, and then posting to a new issue ticket.
