### ISSUE TITLE
[Dev Asks] Please order the following goal:

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#1807]
Okay funny mini poll: please order the following goal according to their importance in your opinion!
In general and how you would like to see Starship EVO.

1 - Game should be balanced
2 - Game should have depth
3 - Game should be easy to pick up and predictable.
4 - Game should feel cinematic / immersive
5 - Game should be fun

There is now right or wrong, it will help me to see each people bias (and mine ;) )

**Comment by Garrett-C** [comment]
5,2,4,1,3 I mean all are important in the long run but if we are talking about the immediate future that’s how I see it. Fun is by far the most important for now and while balance is a parr if that and is important it just isn’t as important now because there is still so much to change.

**Comment by Sullos** [comment]
I believe it should go as follows
2
3
1
4
5

As from my perspective, the game is already quite fun, and you can make a lot of fun for yourself.

**Comment by SabreMania** [comment]
1
5
3
2
4

All of these are important, of course, but if I went to develop a game like Skywanderers, this would be the order I would use.

**Comment by Xerma** [comment]
It could even be argued that the other 4 make the game fun in general. If I were to put them in order though, I'd have to say 2, 5, 1, 4, 3

**Comment by Aiwii** [comment]
5
2
3
1
4

**Comment by tsunamayo** [comment]
Okay if you guy could copy paste the full name, it is complicated to go back to main post each time ;)

**Comment by tsunamayo** [comment]
> Edit: With that being said, I think, surprisingly, that #5 would deserve a higher spot right now. Not in the sense that the game needs to be more fun, but in the sense that we need people to have fun when they join in for the first time in Early Access, which, as it currently stands, is very... lackluster. We don't have a lot of things to do, and expectations from the new people will be high.

Yes 100% correct, this is why I want to make a starting point building with a few ship / overcraft, and add a few more funny things to do. I will need some builder help.

**Comment by Aiwii** [comment]
What kind of help do you need from builders? I could probably help

**Comment by ExodistSKY1** [comment]
5 - Game should be fun            (I want to continue coming back)
2 - Game should have depth    (gameplay loops, exploring w/friends, mining, building, etc.) This might go with immersive gameplay
1 - Game should be balanced   (its not fun when you have one way that is the best way)
3 - Game should be easy to pick up and predictable. 
4 - Game should feel cinematic / immersive   (it is always nice to have graphics but having fauna and flora to help immerse yourself in as always a good addition.)

Let us know what kind of things you would like for us to build and I am sure we can knock it out relatively fast with multiple options for you to choose from!

**Comment by ultrak2k** [comment]
5 - Game should be fun ( Obvious - i'd want to play it)
2 - Game should have depth (More elements, strategic and tactical, deeper building with reactors and weapons, crew, gameplay loops, factories, etc)
1 - Game should be balanced (this will save the game - rather not have a game killed by bigger is best)
4 - Game should feel cinematic / immersive (Needs to have beautiful terrain and scenery - actually this is very important but everything else is just slightly important-er)
3 - Game should be easy to pick up and predictable. (Not sure about this one, a balance between depth and simplicity is nice)

Honestly the first 4 on my list I'd rate nearly as important as eachother.
5th one might conflict a tiny bit with 2 but not by much, so its still somewhat important

**Comment by schlid** [comment]
1 - Game should be fun
2 - Game should be balanced
3 - Game should have depth
4 - Game should be easy to pick up and predictable.
5 - Game should feel cinematic / immersive

Was a tie between the last two for me. Balance is an important one and ties into the fun or enjoyment, and so does depth as if there's not a long term goal it doesn't give you much to work towards. 

Keeping features predictable and easy to pick up is really important too as you don't want to be in the situation where you've put the game down for a month and have to relearn everything.

**Comment by ProPeach** [comment]
1. Game should be fun
2. Game should have depth
3. Game should be balanced
4. Game should be easy to pick up and predictable
5.Game should feel cinematic/immersive

Fun should obviously come first, but I think one big thing that isn't included on this list is the the game should not be Frustrating. Frustration is one of the biggest things that will turn someone away - maybe that's because they experienced a nasty bug, or had to spend hours figuring something out that should be documented or maybe it's not clear why they can't do something that seems simple. Unfair balance can also be a cause for frustration.
We're working on all these things with bug reports and suggestions so I think we're ok for that, but I thought it might be useful to keep in mind.

To round up - the base game should be fun, easy to start and deep enough to stay interesting, looking pretty can come later

**Comment by Dwarf-LordPangolin** [comment]
1 - Game should be fun
People will play a game that's unbalanced but fun, but very few will play a game that's perfectly balanced but no fun. Ideally, the game should be both -- and a lot of fun comes from trying to win either against NPCs or players in a well-balanced setting-- but fun should be a higher priority.

2 - Game should have depth
I was going to put this 3rd, but I feel Peach and a bunch of the others are correct; a balanced but shallow game would be less fun than an unbalanced but deep game. I feel like the game is pretty well on its way to having depth: building and design are very deep ATM, resource gathering/processing is planned, trading is planned, combat is present and being more fleshed out, and exploration is planned as well. Once those are all implemented, that's a ton of things to do, and all of them relate to each other in one way or another, which helps even further.

3- Game should be balanced
Because there are so many options and ways to build in this game, this is going to require a lot of fine-tuning. However, a rough balance should be done (and should be doable) fairly early; I think your role card plan is a good one, and I need to finish writing my suggestions for that.
There are definitely some general things that folks do **not** want to see happen in the game -- for example, a single fighter taking down a big warship all by itself, or really big, heavy ships that can outrun much smaller craft. As long as egregious things like that are avoided, I think people will be patient with the fine-tuning process.

4 - Game should be easy to pick up and predictable.
The game should definitely not be frustrating or confusing; I think a good word for it would be "approachable." The build system is really good at this; Starship EVO has probably the most comfortable build system I've used yet.
I'm not sure I'd say "predictable" is precisely the right word; pirates, for example, should be an occasional surprise for the player. However, it should be clear to the player when entering systems where that might be an issue.

5 - Game should feel cinematic / immersive
While it's always nice when games look and feel pretty, most players tend to prefer gameplay over graphics. Also, I think the game looks awesome already.
Regarding immersion, that's sort of a separate category that's kinda hard to define. One area that you've already got planned that I feel will help with immersion is having ships constructed at shipyards, as opposed to being plunked together manually by players in some random spot in their backyard.

**Comment by Servomotor** [comment]
**1 - Game should be fun** 
Fun means different things to different people so this is a hard one to measure or even place in a hierarchy. For example. I like to build things first and foremost. I dont mind mining to get my materials, but I dont want to be forced to PVP to get materials (I have PVP'd most of my gaming life. I have a 16 year old High Warlord from vanilla wow). Being forced to PVP would not be fun and all the immersion and depth and balance can go out the window if the game becomes more frustrating than fun.

**2 - Game should feel immersive**
I am gonna cheat here because cinematic means something different to me than immersion. I think a lot of what you are doing is already immersive. Being able to build the way we can and make our own world is immersive. However, I like things to be a bit deeper. I want to store food in my cupboards and in a refrigerator. I want my character to get weaker over a 20-30 minute day/night cycle where eating gives me energy. I want my character to walk slower and slower throughout the day until he uses a toilet to get back up to speed. I want the things we build to have purpose in game. This is one of the best ways to balance PVP and PVP builds in a building game. Force the PVPers to use mechanics that PVEers want to use. Much of what players want in building games is not just to create their fantasy ships, but to recreate what we know in the real world. I want to sleep in a bed and get a buff. I want to sit in a chair to eat. Eating on the fly should give less energy recovery. Eating in a chair gives more energy for the same food. etc. 

**3 - Game should have depth**
Depth in crafting, depth in lore. The story told to us should feel real and something we immerse ourselves into. Depth and Immersion are similar in some ways. 

**4- Game should be balanced**
Game has to be balanced or it can lead to frustration instead of fun. So this directly ties into #1 on my list.

**5 - Game should be easy to pick up and predictable.**
The best games are the ones that are easy to pick up, but have depth. Minecraft is an excellent study in that it gets so many things right. The issue with Minecraft for me is NPC immersion in that there is none. Villagers feel like AI, not a character in game. Cats, rabbits, dogs they all work for me, but the humans in Minecraft are boring and make the game feel lonely. 

The reason I put this in 5th place is because it helps to keep a community moving. I have asked so many questions and met some great people, many in this thread. I think people needing help in game helps to foster a strong community, at the minimum it helps people reach out.

**6 - Game should feel cinematic**
When I think of cinematics, I think of being told someone elses story. I don't care about someone elses story. I care about the story my character is going to experience in their adventures. So cinematics means little to me. But if I need to bring up immersion again. One of the things that can bring me back to a game time after time is my relationship with my character. If they are just another ho hum character like an FPS game, I am less likely to come back after some time off. But in games where I have a unique character. Unique look, unique armor, unique name and they are someone I can identify with, then I will and HAVE come back to many games just to see my characters again. This has often lead to a re-sub. 

I love No Man's Sky, but one of the issues is that my avatar just feels like everyone elses avatar and because of this I never get fully pulled into the game and I quit playing because of it. I have many times gone back to wow just because I miss my characters. I even loaded up SWTOR a few weeks ago just to check out my characters, same with Elder Scrolls Online. 

My wife is a traditional feminine woman. She likes to dress up her characters, she likes to make nice kitchens and have food to eat in them (although IRL I do much of the cooking). She loses interest fast if she can not make her avatar look cute or feminine. This means hair styles, outfits, different faces, etc etc. Good old fashioned character customization.

**Comment by Brushes2** [comment]
5 - Game should be fun
2 - Game should have depth
4 - Game should feel cinematic / immersive
1 - Game should be balanced
3 - Game should be easy to pick up and predictable.
