### ISSUE TITLE
[Suggestion]  No excessive micromanagement

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#1819]
This contribution is more of a request or expression of opinion that is very important to some of us.

Tsuna please do not base your survival elements too much on space engineers, because the game is more a survival simulation in space and has little to do with action-packed space battles or the endless building possibilities of your game.
StarshipEvo can offer to re-enact every conceivable space combat scenario and build any spaceship you want, from the small fighter to the carrier ship.
It would be wonderful if the game could combine the endless creativity that it allows with impressive and fast space action.
In addition, the idea is fantastic, to be able to fly every star or nebula that you see when you look out the window of your spaceship. 

But please please please, limit neither creativity nor fast space action through micromanagement. Who wants to spend hours between battles repairing their ship or flying their large combat ship to the gas station every 20 minutes. What do I get from a pressure system if I can't build all the cool spacefighter designs because I have to install standard cockpits or blastdoors.
What it feels like to breathe, refuel or repair something is best experienced in real life. But very few of us can fight exciting space battles in real life or explore distant stars together with their friends. 

Please consider the aspects mentioned when integrating the survival elements.

An example: It is no fun having to refuel each vehicle individually. Taking Npc-Wingmans with you on combat missions would be super cool, but if you have to keep an eye on the fuel gauge for 5 NPC ships, it's no longer fun. Yes, in reality we need air and our devices need fuel, but in reality there are no NPCs and everyone takes care of the oxygen and fuel in their own tank. If I have to take care of 5 tanks as an individual because I have 5 NPC Wingmans it is no longer fun, it is just caustic.

None of us write English well, but I hope that the core ideas of the opinion and concerns are reasonably readable.

I am aware that there are certainly other opinions on this than ours -> that's why the contribution

**Comment by Arschpollo13** [comment]
I share the same opinion as Battlepixel, you can definitely do a few things in this direction like survival, but you shouldn't overdo it.

For example, I've always built my cockpit myself and never used the prefabricated parts. if air systems are added now, my own cockpit will most likely not work anymore because they are not sealed when I see it from space engineers, for example.

I find survival aspects not bad either, but I hope that these don't come at the expense of building creativity and action. Or if these aspects stand in the way of automating your npc fighters, carriers and fleets.

For example space engineers doesn't have real npc's or interesting battles with npc's, or npc crew but a lot of micromanagement.

**Comment by Garrett-C** [comment]
To be fair I don't think tsuna is angling in that direction. I mean he has always aimed for the flight to be arcadey so I imagine that most of the gameplay will be similar.

**Comment by tsunamayo** [comment]
I dont really want to go in the micro management style, at least it depend on how you define it.
I am more about fun, and I wont push player into menial tasks.
I see a lot of fun and interesting possibility with air-tightness. For fighter we will find a solution, I mean real world fighter are not pressurized too, so it make sense to just be in your spacesuit flying the fighter.
I want fast paced actions for the space combat, and go in the epic direction rather than the realistic one...

**Comment by Battlepixel** [comment]
Thank you for your prompt reply. Nice to hear that.
Regarding the depth of the game, many ideas such as factions and faction wars(Ki fractions can conquer the territory of other fractions), fleets, player stations, player factions (such as shipyards) Carrierfleetcommands (you can order your carrier ship to send its fighter automatically and call it back) are really fantastic and could give game motivation for ages. In my opinion, there are two reasons why Starmade disappointed despite its depth of play:

1) Unfortunately, building in starmade is very limited and lengthy (->no fun). The construction options in Starshipevo are easier, far faster and incredibly more detailed and beautiful.

2) In addition, for various reasons, space fights in starmade unfortunately do not offer any action and are not a bit epic.

An example: all ships, whether fighter or battleship, orbit in lateral flight with the front pointing towards the target. 
And ship effectiveness in all matters=f(Volume)> Small ships have 0 uses.

**Comment by tsunamayo** [comment]
Yes this is something I want to address. I want epic space combat and also have smaller ship take on bigger one.
One big factor to achieve this will be progression elements, you will earn mods and crew, better weapon and better hull. So a ship of the same size could be at very different level depending on how it is fitted.
