### ISSUE TITLE
[Bug?] Half-corner brick missing [20w17c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1842]
### Short Description of the issue:
Not sure if this is a bug or not, but since I couldn't find anything in the patch notes about its removal, I'm figuring it's a bug. The half-corner brick is missing from the codex.

### Steps to reproduce the issue:
Brick not present in codex; middle-mouse clicking-over existing instances of this brick says "No block Targeted."

### Environment
- Skywanderers version: 20w17c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20200424170419_1](https://user-images.githubusercontent.com/33041786/80260946-b6c29d00-864e-11ea-814f-676ceda6763a.jpg)

![20200424171130_1](https://user-images.githubusercontent.com/33041786/80260951-b9bd8d80-864e-11ea-830c-88b3706b4f83.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4531784/output_log.txt)

**Comment by ProPeach** [comment]
I believe they were removed because they were unique in that they required two different models/collision meshes to mirror properly, and the current mirror system can't handle that yet.

I really hope they make a comeback in the future as they're an awesome shape and actually reduce the need for child entities. Even if they returned with a warning in the codex that they don't work with mirroring/collision yet, that would make a lot of players very happy.

**Comment by Dwarf-LordPangolin** [comment]
Fair enough. I'd love to have them back, since some of the shapes I was using needed them, but it's not a major issue either way, and optimizing those game systems is more important ATM.

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin welcome back ;) So yes my preferred solution would be through modding - there is quite a long road ahead for that, but that would be much better overall. Cheers
