### ISSUE TITLE
[Bug] Lightcruise now exists on press of L key, not on release [20w17e]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1863]
### Short Description of the issue:
Previously, the L key made the ship leave lightcruise when it was released; this was helpful in allowing for precise jumps. Currently however, the ship is exiting lightcruise when the key is pressed.

### Steps to reproduce the issue:
Enter lightcruise, press L to exit.

### Environment
- Skywanderers version: 20w17e
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4534741/output_log.txt)

**Comment by tsunamayo** [comment]
Yes it is more natural to handle this way. Otherwise code would be a bit more complicated, now the autopilot and the NPC are sending commands exactly like the player does, and a release command would be a bit more tricky.
I dont really plan on fixing this for the following reason: I want to switch to an auto-dropoff. Once you get close to any object you will exit lightcruise automatically. Easier for noobs, but also doing otherwise would expose some of the game tech weakness (like high-speed collision), so it is a bit of strategical move...
Now there will still be a manual drop-off possible of course, it just timed drop-off wont be necessary.
Cheers

**Comment by Majikmonster** [comment]
As of build 20w17e the lightcruise drops off automatically with autopilot quite far away from the target. I'm not sure if it is relative to target size or universally distant from it, but perhaps making the drop-off point a bit closer might make trips shorter and not need micro-jumps or lengthy boosting to correct.

**Comment by tsunamayo** [comment]
@Majikmonster it depends on your speed, and there is a bit of margin so you are not too close, but I can tweak the margin. Thanks!
