### ISSUE TITLE
[Suggestion] Practical square engines

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Starship-EVO#1885]
### Short Description of the suggestion:

As much as I like the round engines, I struggle to find a use for them stylistically and I would say that I speak for a good bit of people that it would be nice to have square engines that have the same capabilities as the round engines because the current square lightcruise engines are too slow for normal flight.

**Comment by tsunamayo** [comment]
Not sure about this, from what I have seen people have been doing an amazing job at integrating them at their design. Not too much of a fan of having two system block for the same use, but if more people jump in I could be convinced ;)

**Comment by ProPeach** [comment]
The thing about skilled builders is that they can make incredible things out of anything 😝
As nice as the round thrusters are they don't leave you with many options for decoration - round is always round, but a rectangular thruster like the block one can be reshaped into anything, or used with a grill or nice border. When all we have is the round thruster many different styles can all look very similar, so a rectangular thruster would be sweet!

**Comment by ExodistSKY1** [comment]
Would it be too much to have two variations of both Thrusters? It would be nice to have a choice with our builds for a little more flexibility as opposed to just the same. (I know we build around our thrusters)

Could you also reinstate Z axis scaling on the brick thruster? I think the model looked just fine when scaled that way. (Does it affect performance on the game?)

**Comment by ProPeach** [comment]
Z axis scaling is a must for sure! Otherwise we have to stack the thrusters which is counter intuitive and won't work when thrusters damage blocks behind them

**Comment by ZachZent** [comment]
I don't really have an opinion on the engine models, probably since I have gotten used to it. The thing I do is multiple engine blocks connecting with other engines to form a singular engine block. When creating big ships with big engines, 16x16x16 can be too small and you get engines with lines. 

On the mechanics side, what if you want to make an engine that is more than 16 deep? For now you can stack them, but when engine damage comes you will be stuck with the 16 deep engine. There is also the problem if you want to design your engine with blocks, chances are you will have a good segment hiding behind blocks. Finally there is the idea of a wedge engine block for some cool looking engines.

And yes, please bring back brick thruster Z scaling

**Comment by tsunamayo** [comment]
Okay I have made this squared mini thruster and added z-scaling to the normal small thruster. Hope you like it ;) Available now in 20w18b. Cheers
