### ISSUE TITLE
[Suggestion] Mirror/Sym Tool Optional Split Mode

### ISSUE THREAD

**Issue by EndoSkull** [tsunamayo/Starship-EVO#1897]
### Short Description of the issue:
Many games such as starmade and stormworks allow you to build block odd - starting off with a single center block.

Currently, you must use the off set block to build an ODD mirror. Doing so causes the game to alerts about failing to mirror.

The Sym/Mirror tool needs to be able to split on a small cube in order to mirror out oh each side from the center block
...

### Steps to reproduce the issue:
Simply enter mirror mode - you can't not build odd only even outward.
...

### Environment
- Skywanderers version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
I am not sure 100% to understand your suggestion.
You can use a symmetry in the middle of a block - it should work.
What you cant is put a symmetry in the middle of a 0.25cm brick. Because with such a symmetry plane you could  not mirror a large 1m block.
So you can put symmetry like this.
0m /  0.5m / 1m / 1.5m / 2m ect

What are you asking? 0 / 0.25m / 0.5m ? Or something else?
I cant say for Stormworks but Starmade dont have bricks, only blocks.

Cheers

**Comment by EndoSkull** [comment]
I believe you understand - IReason being is when you build a tiny ship you use the small cubes - you want the cubes to be an odd number because you'll have a middle fin usually and vehicles usually (in for example stormworks) have a center - This video of mine may show an example better? https://www.youtube.com/watch?v=yWE-PyihEN0&list=PLXE0HAcS1gvSDnbyyeqImcYVCJvJOxfYZ

**Comment by tsunamayo** [comment]
Hum I see, I have to think more about this, I understand your test case now.
Btw how do you think the game building system compare to other game (stormworks included, current testers dont talk much about that one)? 
Cheers

**Comment by EndoSkull** [comment]
For me, I've tried every sandbox building game - all of them have pretty much lost my interest quickly except stormworks. 

1. The game is updated nearly every week
2. major updates come out every couple months that expand the game
3. game editor is very clean and the tools are easy to access
4. part browser is easy find what you're looking for
5. the building controls are set up to fly around what you're building and add and delete blocks
6. Environment wise - stormworks had a nice art direction and a huge world to explore - but no dynamic NPCs and feels empty 

As compared to your current build - I would say features that are missing or make it difficult for me to adjust in Starship Evo are
1. When building you don't go into an edit mode - so I tend to have difficulties moving around my build - not able to move around easily like (have to tried stormworks editor? i change the camera into FPS mode)
2. both stormworks and starship evo do not have a flat lighting mode so you can see your build from all sides evenly (starmade does have  this)
3. Tools must be added to the tool bar rather than on screen accessibility when editing

Starship Evo Innovations:

1. Metal Paint Finishes
2. Logic setting options on blocks
3. Dynamic block sizes/shapes
!!! However, one thing that immediately frustrated me after the excitement is there is no way to save the custom wedges/block shapes etc for later use and easy placement

Anyway, these are my thoughts so far I haven't put time into Starship yet as my Youtube channel currently revolves around Stormworks - but would like to start doing builds in Starship Evo.

**Comment by tsunamayo** [comment]
Thanks sorry @EndoSkull I missed the answer. So yes for the "edit" mode that was a conscious decision, I am not a fan of editor like stuff (but I totally get it works for other games).

For the dynamic block size it is an interesting one, as I noticed on your B-25 that you seems to not like the stretch feature and like to place block 1 by 1. 
Now a lot of people actually prefer to drag their shape instead of having to open the editor and equip a shape, it is just so much faster! That was the reason I put them in the game, so that I dont have to have a massive number of shape with slope of different length that would clutter the codex.
I wonder what is your feedback on that: do you think dragging your block feels cumbersome - or unnatural? Typically for stretching vertically yes you need to press the rotate button while stretching, which  is a bit cumbersome (I havent found a better way). Did you notice you can bridge too (you simple target two point on perpendicular plan and you will build a 3d stretch, not just a 2D one).
Cheers

**Comment by EndoSkull** [comment]
> For the dynamic block size it is an interesting one, as I noticed on your B-25 that you seems to not like the stretch feature and like to place block 1 by 1.

I was attempting to learn your building system by seeing how building B25 would work in your game - I did like the drag feature - however, I could not figure out a way to "smooth" the lines between blocks that are not part of the initial drag to size.

> Now a lot of people actually prefer to drag their shape instead of having to open the editor and equip a shape, it is just so much faster! That was the reason I put them in the game, so that I dont have to have a massive number of shape with a slope of different length that would clutter the codex.

This is the best part of your system that you have the drag to size - especially when i start doing the fuselages - However, the one thing that was difficult was that rotating the block appears  to be locked to where you are placing the block - stormworks allows the use of (h) (j) (k) (l) (u) keys to rotate block different axis and (u) is used to mirror the block

> I wonder what is your feedback on that: do you think dragging your block feels cumbersome - or unnatural? Typically for stretching vertically yes you need to press the rotate button while stretching, which is a bit cumbersome (I havent found a better way). Did you notice you can bridge too (you simple target two point on perpendicular plan and you will build a 3d stretch, not just a 2D one).

The dragging works very well - sometimes it's hard to see which way the block is facing (example the inverted cube i t think it's called) 
I didn't try pressing rotate while stretching - I'll try that.
I think i did bridge.

I think the two big missing features for me right now 
- Save custom stretched blocks which can be added to the tool bar and used later
- select part or all of the build structure - which can then be saved as a template and or rotated placed and added to the current build (a welding tool i guess would be needed)

I think the most exciting part of your editor is the stretch sizing functionality - I feel like that really sets your editor apart from  others. Since many other block building games - even Brick Rigs - are limited to the part sizes available.

Hope this helps
-Endo

**Comment by tsunamayo** [comment]
Okay thanks for the feedback! I am indeed thinking about adding copy/paste of player prefab, and the repeat lock of custom shape, with maybe adding them temporary to the tool bar.
Cheers
