### ISSUE TITLE
[Suggestion] Spotlights/Floodlights

### ISSUE THREAD

**Issue by Alkaliii** [tsunamayo/Starship-EVO#1898]
The new lighting system is very nice and leads to sick screenshots like this
![Skywanderers 2020-04-15 12_19_08 PM](https://user-images.githubusercontent.com/53021785/80568618-a09d3f80-89b4-11ea-8988-cbd690e45cd6.png)

But this also means that it's difficult to light up large enclosed spaces with the current lights in-game.
![Starship EVO 2020-04-29 12_57_36 AM](https://user-images.githubusercontent.com/53021785/80568717-bc084a80-89b4-11ea-83e1-16a37d3e7535.png)
![Starship EVO 2020-04-29 12_57_45 AM](https://user-images.githubusercontent.com/53021785/80568720-bd397780-89b4-11ea-8186-c73b42cac9c4.png)
![Starship EVO 2020-04-29 12_57_14 AM](https://user-images.githubusercontent.com/53021785/80568721-bdd20e00-89b4-11ea-8714-e51c66f47be6.png)
![Starship EVO 2020-04-29 12_57_24 AM](https://user-images.githubusercontent.com/53021785/80568724-be6aa480-89b4-11ea-9e10-fc4cdb94e918.png)

Therefore I suggest adding spotlights/floodlights to the game that light up a larger radius of things.

thank you for coming to my ted talk

**Comment by tsunamayo** [comment]
Light radius is a very sensitive performance hitter. I cant really increase it without impacting many other of the game. What you need to do is put light on the floor and the ceiling for large space...
Thanks

**Comment by Servomotor** [comment]
Chiming in here. 

Based on what little I know about rendering performance, a spot light or directional light should be easier on the engine to render. The current lights are omnidirectional which means if they overlap the engine should be trying to render both lights in the scene. A spotlight that only shines light in an area (not omnidirectional) would not interact with other lighting unless the builder overlapped them. 

If I recall correctly when Spotlights were introduced into landmark, we could place more lights than before with increased performance, because they were not interacting with each other. If you can make a spotlight that has its arc of light emission set up in a sequencer from 180 to 1/0 it would not only allow for more photographic/photogenic scenes and atmosphere, it should increase computing performance. If you can also set the light emission distance, that can help to keep the light from being shown through blocks below the floor.

Resizable lights by themselves could be bad, but spotlights that can have a set distance should improve performance. 

One thing I have learned about building games, is that its still a new frontier. Most games can create their art assets based on what they need and build them to suit a desired performance. There is only so much a game designer can do though in building games. At some point the persons computing performance will be based on their machine and their building habits. This is something that simply has to be accepted until computers get stupidly powerful. 

In landmark there was a huge tutorial community that spouted up and helped with building techniques. The same will happen here.

**Comment by Servomotor** [comment]
Here is an example of a room using spotlights. The second one is just drawing from their light source. You can see how the roof/upper areas remain dark and how the spotlight affects mood.
Think of the spotlight as an upside down ice cream cone. The tip is where light emits, the large part its surface area. 

![spotlight](https://user-images.githubusercontent.com/65745916/83707403-8c65e700-a5df-11ea-88af-e320a4756474.jpg)
![spotlight2](https://user-images.githubusercontent.com/65745916/83707417-92f45e80-a5df-11ea-83ff-a034eb5c82ba.jpg)

**Comment by Servomotor** [comment]
Also, if you want to reduce the amount of lights being used (because they are the number 1 FPS killer in most building games), being able to paint some things with a luminescent paint can help. Using luminescent in hallways to give guidance to a path can help reduce light usage. 

I understand your reasoning for not wanting to use luminescent textures/paint, but I have never seen it be an issue in other games. If you are concerned that people will paint their entire hull with luminescent paint and look terrible (I agree) try just allowing luminescent paint on the stickers/decals.

just a thought

**Comment by tsunamayo** [comment]
@Servomotor actually they are not traditional spotlight, they are more voxel floodlight like minecraft, giving it a soft ambient appearance. But I might switch to conventional light in the future, but I would really like to keep the ambient component.

**Comment by Servomotor** [comment]
I agree ambient lighting has use. I was wondering if we could get both types of lighting. I would not want spotlights to replace ambient lights. 

If blocks could actually block light, I could make my own spotlights with angled bricks, but right now when blocks have light around them, they look like light shining through your hand.

Get a flashlight and shine it through your fingers in a dark room, this is what blocks/bricks look like right now in game when there is a light source next to them. Spotlights if used correctly can eliminate this, that is why I ask for spotlights.

Is it possible for rendering to have blocks/bricks block out the light like in minecraft?

**Comment by tsunamayo** [comment]
In minecraft there is only voxel. My voxels (hull blocks) also block the light, but not the bricks, as the algo is voxel based. I will give a shot at baking some shadowmap - in wich case I could use a spotlight like you requested, but for ambient it will always be voxel based.

**Comment by AlienXtream** [comment]
having 2 different lighting systems is fine. vocel lights are ok for things like ambient light but having raycast lights (which unity natively supports) allows for more realistic lighting setups. i think both should exist. you could also include "volumetric lights" which would function like how grav fields currently do but instead of gravity it fills an area with the defined lighting value with no or very sharp falloff. another optional lighting thing could be hybrid ray-vox lights. in minecraft lighting is... limited. raycasting is better looking but more expensive. hybridizing them could possibly yield a mid ground. idk how exactly that would work at all though, im just spitballing ideas. honestly i think just having 2 seperate lighting systems for 2 seperate usages is the way to go but either way i think we need raycast lights.

**Comment by Servomotor** [comment]
Thank you Tsuna. 

Here is a picture describing what I am talking about when I say the blocks do not block light (player light). The light shines through the blocks which makes the blocks look like "glowing skin". 

![servolightmockup](https://user-images.githubusercontent.com/65745916/88091613-ed785880-cb54-11ea-9518-78d04537b259.jpg)

**Comment by Servomotor** [comment]
and here are farther away pictures for reference
![20200721125112_1](https://user-images.githubusercontent.com/65745916/88091690-084acd00-cb55-11ea-9f7e-b4518e67292e.jpg)
![20200721125055_1](https://user-images.githubusercontent.com/65745916/88091694-0a149080-cb55-11ea-8202-2a79ce44b37c.jpg)

**Comment by tsunamayo** [comment]
We have now the new light tech, it still need some refinement though. Thanks
