### ISSUE TITLE
[Bug] Docking bug [20w18c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#1907]
### Short Description of the issue:
Sadly, the [bouncing docking pad bug](https://github.com/tsunamayo/Starship-EVO/issues/1821) refuses to stay dead.

### Steps to reproduce the issue:
Attempt to dock.

### Environment
- Skywanderers version: 20w18c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
https://gfycat.com/sophisticatedliquidarchaeopteryx

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4556438/output_log.txt)

**Comment by tsunamayo** [comment]
Okay it seems it is a bug with the collision system. Is it your shuttle submission? I havent answered yet but it looked amazing... If you can send me the bp so I can reproduce (it was fine on my lil shuttle).
Cheers

**Comment by tsunamayo** [comment]
okay I test the shuttle from the other post, culprit is that guy:
![image](https://user-images.githubusercontent.com/6604318/80712725-5c817a80-8b2d-11ea-97f0-638d73cebd1a.png)

That point on the wedge wants to push in two different direction because.
Will try to find the best way to get rid of those points, I keep you posted.

**Comment by tsunamayo** [comment]
So I have dealt with those points, here is it if you are curious:

![image](https://user-images.githubusercontent.com/6604318/80769433-202f3800-8b88-11ea-855a-aca654f59a04.png)

Your ship now lands fine (always a bit bumpy, this will have to wait for a proper damper/spring block)
Available in 20w18d. Thanks!
