### ISSUE TITLE
[Bug] Bluescreen when attempting to delete block

### ISSUE THREAD

**Issue by FlyingDebris** [tsunamayo/Starship-EVO#1961]
### Short Description of the issue:

I went to delete a beam weapon, full size, with the max amount of charge addons. I bluescreened when attempting to delete the block.

### Steps to reproduce the issue:

Unsure, cannot reproduce. Also would prefer not to. However, the blueprint is attached. The gun can be found in the forward section of the ship. I believe it was the middle one.

[Assault Ship 1.zip](https://github.com/tsunamayo/Starship-EVO/files/4572889/Assault.Ship.1.zip)

### Environment
- Starship EVO version: 20w18f
- Graphics Card: GTX 1050 Ti

### Additional information:

![](https://cdn.discordapp.com/attachments/271723356795961345/706720067127345183/20200504_001129.jpg)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4572887/output_log.txt)

^Unsure if this log is from the time my game crashed, since I don't know if it would have saved from the bluescreen.

**Comment by captain828** [comment]
High-level software, such as a game or typical windows software, that doesn't have access to the low-level windows kernel is very unlikely to be the root cause of a BSOD.

If this only happened once then you can just ignore it.
If it keeps happening then I would recommend following the guide here https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-stop-errors#general-troubleshooting-steps to figure out what caused it.

Especially important is to get the STOP error code and/or the name of the file that caused the BSOD.

**Comment by tsunamayo** [comment]
@FlyingDebris I dont see any gun on that blueprint... Thanks
