### ISSUE TITLE
[Suggestion}] Make Hovercraft Simpler

### ISSUE THREAD

**Issue by SageThe13th** [tsunamayo/Starship-EVO#2058]
The current hovercraft system has a number of issues due to its complexity above what's required to build a spacecraft. It being hard to work with is not solely due to being more complex however, as there are things about it that are just just inconsistent and unintuitive.

Unlike thrusters, repulsors need to be balanced and placed in a way where their force acts against each other. Say I place the thrusters I need to move forward all on the right side of the vehicle away from the center. That vehicle, be it a hovercraft or spacecraft, would move forward just fine. If I place a larger number of repulsors on the right than I do on the left, then the hovercraft would drift left or be forced to turn left. Also odd, if I use a ship core the repulsors act as the side thruster I need and I get full 6DoF and there’s no drift. Even for the exact same design. This behavior is very confusing and required testing to figure out. The fact that only repulsors act this way and only if you're using a hovercraft core is very inconsistent.

Worse yet the way this works hugely restricts freedom of design. Hovercraft flip over easily meaning you have to build wide bases to get the best results. This makes thin bike-like designs hard to build and some designs are just impossible to keep upright. Center of mass being so important makes asymmetrical designs hard to deal with. Say I wanted to make a hoverbike with a sidecar. That design would not be able to move in a straight line.

Another big issue is that ships work nothing like this. When building a ship I can do just about anything I want with very few restrictions. In my mind this means the current hovercraft system fails to be in line with the game’s core design principles. As it stands I can’t make any sort of hover vehicle I want and I have to stick to stock cookie cutter designs that follow certain principles otherwise the vehicle becomes hard or impossible to control.

I understand that a hovercraft has to account for terrain movement in a way that spacecraft don’t. But, even if hover movement has to be more complicated than flying, building a hovercraft should ideally be as easy as building a ship. The way repulsors work right now is not fun to think around while designing your hovercraft. They shouldn’t calculate for the center of mass the way they do now. It makes hovercraft extremely easy to flip and it’s unintuitive as thrusters don’t work this way at all.

**Comment by Dwarf-LordPangolin** [comment]
I agree with Sage. Right now hovercraft are extremely challenging to build in any shape that isn't wide, flat, symmetrical, and with a very low center of gravity. This prevents players from building hovercraft like those seen in movies and games; perhaps more importantly, for new players that haven't had to deal with center-of-mass or balance issues in building games before, they might conclude that their design isn't working because of bugs, instead of realizing that their design is unbalanced. At the moment, even for a player like me who's played a lot of Space Engineers and is used to taking center-of-mass and balance into account, the current system is very tricky to manage, and most popular sci-fi hovercraft would be basically impossible to build.

The hovercraft system is not bad -- but it is extremely unforgiving and requires great precision. Moving a repulsor even a single brick can make the difference between a balanced and unbalanced design, and since hovercraft have no ability to right themselves, flipping them upright requires placing an actual lever on them and using the push tool on it to bring them upright again.

![20200512222224_1](https://user-images.githubusercontent.com/33041786/81860331-3a73f900-952c-11ea-9a5f-b19cc3e0ea51.jpg)

A simplified, much more forgiving system for hovercraft would be an improvement, and would make the system more similar to the ship building system and the rest of the game's mechanics.

**Comment by ultrak2k** [comment]
I completely agree - as someone who made a hovertank it was quite hard to even actually make it hover, and although I think everything has already been said, I also don’t want complexity to be a precident for other vehicles, especially mechs.

**Comment by tsunamayo** [comment]
I have fixed a lot of this already for next patch 20w20c, and I will add settings to the computer and repulsor. So matching the center of gravity will be easier. I had a few build that where topping easily (like the small speeder), and now I just cant get upside down - so its much better. But I need more blueprint to be sure.
Now why I want physics and not cheated physics like spaceship mind you?
To me hovercraft are closed to car than to ship.
When I add cars, you will need to put wheel at the right place. Dont expect to put wheels in random place and in random orientation and have a working car. Same things apply here.
I am fine with that because unlike spaceship hovercraft are not really essential to gameplay. They will be good for surface exploration - but a ship would get you there faster. They are really there for fun and experimentation.
Lets have this discussion after next update lands.

**Comment by SageThe13th** [comment]
Not only do my points with constancy stand. These mechanics only matter with repulsers and only repulsers operating via a hovercraft core. You are also expecting the player to learn mechanics with a thrust based vehicle that then don't apply to ships which are also thrust based. The learning curve is backwards. You start the player out with mechanics that are then dropped for a vehicle that operates under the same core principles. Engines providing thrust.

**Comment by ultrak2k** [comment]
The point of using presumably hovers to start in survival is a good point though - since I assume you wouldn't start off with a working space ship, so surely it would make sense to make it easier in some way, no?
Or they could just use cars, to be fair, which sound easier

Also - speaking of ships being faster, that's obviously fine, but the idea that hovers are pure experimentation is kinda scary, ground combat with ground vehicles is a must, or they will seem pointless - there in the future, has to be some restrictions placed on ships around planets, because simply saying it's just a fun feature isn't enough

**Comment by SageThe13th** [comment]
Here's a visual example of what I'm talking about.

This hovercraft moves 100% fine.
![Hover1](https://user-images.githubusercontent.com/58193603/81875429-dbbb7900-9545-11ea-9bff-f92e01691da7.png)

This hovercraft drifts slight to the right because the mass has shift, but thruster doesn't cause it to turn left.
![Hover2](https://user-images.githubusercontent.com/58193603/81875519-102f3500-9546-11ea-98c1-181a9e95fbde.png)

This hovercraft drifts hard to the left and it's difficult to make right turns.
![Hover3](https://user-images.githubusercontent.com/58193603/81875584-31902100-9546-11ea-9903-bb2ea58b9024.png)

This spaceships flies straight and its top speed is twice as fast as the hovercraft above despite having the same thrust to mass ratio.
![Ship1](https://user-images.githubusercontent.com/58193603/81875682-6d2aeb00-9546-11ea-93a3-d165eec4cbfa.png)

I find this very confusing. It's definitely inconsistent. Hovercraft aren't on wheels. They use thrust to stay above the ground. The fact they suffer from ground friction is confusing. The fact that replulsers with look like thrusters (and in fact you can even use them like thrusters on your ships) behave so differently, but only if you're controlling them through a hovercraft core is confusing.

**Comment by tsunamayo** [comment]
I can remove the repulsor ability to give agility with spaceship core indeed this could be confusing. I just added that so you dont need to put more thruster on your hovercraft, but I can desactivate them with the spaceship core, it makes a lot of sense.
As for the slight imbalance you will be able to tweak that. As for the one with the big imbalance, it is acceptable to me if it behave not okay, I mean if you build a car like that it will be undrivable also.
What do you mean they suffer from ground friction?
I am not sure what you are proposing in fact, how are hovercraft are supposed to levitate? With a physics completely fake? Like you spawn your repulsor all around the place and the things maintain itself above the ground? Then what happen when you fly inside a ship, which direction is the ground?
There is a lot of issues with going toward a fake approach believe me, a lot of inconsistency will creeps in.
Repulsors are just like wheel, I will try to make that clear in the description. I tried to give them a wheel like design.
Anyway I am not gonna change that atm, I am satisfied with the current behavior (which you havent tested yet). If there are design you think should be legit but dont work well, please send it my way - this is how this whole thing progress.

**Comment by ultrak2k** [comment]
fair enough for the testing part

**Comment by SageThe13th** [comment]
Repulsors aren't wheels that makes no sense.

**Comment by ultrak2k** [comment]
> Repulsors aren't wheels that makes no sense.

eh at this point this is just nitpicking reality isn't it? I think its best to see how the game is first

**Comment by SageThe13th** [comment]
![Hover_Effect](https://user-images.githubusercontent.com/58193603/81879131-779db280-954f-11ea-9810-0c941123fdf6.png)

If they're going to work that way. They need some effect like this to make it clear they work by pushing off of things and are not thrusters.

**Comment by ultrak2k** [comment]
> ![Hover_Effect](https://user-images.githubusercontent.com/58193603/81879131-779db280-954f-11ea-9810-0c941123fdf6.png)
> 
> If they're going to work that way. They need some effect like this to make it clear they work by pushing off of things and are not thrusters.

good point, actually

**Comment by ProPeach** [comment]
Aren't they called "Repulsors?" That implies that they push things away, I'm not really sure what that achieves

**Comment by tsunamayo** [comment]
> > Repulsors aren't wheels that makes no sense.
> 
> eh at this point this is just nitpicking reality isn't it? I think its best to see how the game is first
> and it makes sense gamewise, as long as it works properly which im hoping this update fixes

Thanks for the wise works mate ;) btw your tank is now hovering very nicely, if you add a bit more repulsor.
That effect looks cool indeed, I could change it to something like that to make clear that repulsor != thrusters.

**Comment by ProPeach** [comment]
A down arrow in the placement preview like on the rails could also help out a player who is struggling to orient them correctly

**Comment by tsunamayo** [comment]
yes @ProPeach  this will be 100% needed now, as they no longer push sideway but downside, I will also update the 3d model.

**Comment by ProPeach** [comment]
Awesome!
Will they still give agility to a hovercraft, but not a spaceship? I don't think it makes sense for a hovercraft to need side thrusters as well as the repulsors which appear to gimbal

**Comment by tsunamayo** [comment]
Yes they give agility. They dont really gimbal, I might add a rotation on a single axis for the show.

**Comment by Aiwii** [comment]
![image](https://user-images.githubusercontent.com/53021785/81882482-14605000-9550-11ea-850c-38b95da343a3.png)
another hovercraft blueprint
[Hover.zip](https://github.com/tsunamayo/Starship-EVO/files/4625556/Hover.zip)

**Comment by SageThe13th** [comment]
I guess I need to repeat myself. Repulsors both look like thrusters and act as thrusters. That's the problem. It's two fold.

**Comment by ProPeach** [comment]
I don't see the problem, surely their dual use makes building a hovercraft simpler, which was the goal of this thread? Fewer things for a new player to think about and remember, and fewer things to go wrong

**Comment by SageThe13th** [comment]
They're confusing because they look like another component (thrusters) they even act as thrusters if you control them with a ship core. If you use them with a hover core they act like wheels. There's no logic there. That just how they're coded.

**Comment by tsunamayo** [comment]
@SageThe13th no need to repeat yourself, I said I will remove their thruster (give agility rating) while activated with the spaceship core.

**Comment by Sei-Neko** [comment]
From a different perspective, I quite like how hover vehicles work atm. I was able to get one up and working pretty quickly and while it wasn't the most beautiful of vehicles, it performed well and was fun to drive.
However, I felt as if the heat generated from the repulsors was a bit much. This was likely my fault due to their size, but I had to add a lot more hull than I originally intended just so to drop the heat below 100%. 
Perhaps have heat calculated differently for vehicles using a hover core?
I've attached a picture of it anyway for the sake of it.
![image](https://user-images.githubusercontent.com/59953658/81898529-27c8f500-95fc-11ea-9147-e54b7beda39c.png)

**Comment by tsunamayo** [comment]
okay guys I dont know if you had time to try out the new system, I hope it feels better. If not, please send blueprint my way so I can have a look at it. Thanks!

**Comment by SageThe13th** [comment]
As it stands I've gotten things working eventually. The key word there being eventually. Some designs work fine by default while others, even simple ones, require hours of tweaking. Keep is mind this after two days of playing with the system to figure out what it wants from me. I can't reset my brain and approach the system fresh again. There's all sorts of little things I find myself doing to avoid problems.

By contrast ships work pretty much by default and with any shape. With hovercraft don't really experiment. It feels very restricted. I have no real desire to try anything exotic or complex. I just don't like working with them. And I don't really feeling like pushing it to find a design that I do waste hours tweaking only for it to never work.

That said this is a big improvement because some designs do work right away. I haven't found any serious bugs.

**Comment by tsunamayo** [comment]
@SageThe13th yes I understand you have grown frustrated by that. What could be great for me is you to send me the design in which you lost hours trying to make, so I can see for myself and improve what need to be improved. Like the turret you send me, that was a novel design and that will make the game progress once I make it work.
Expressing frustration is fine, I want to know what part of the game are frustrating, but at the end I want to see your ship to really make that baby move forward.
Thanks

**Comment by SageThe13th** [comment]
[Hover Trike.zip](https://github.com/tsunamayo/Starship-EVO/files/4632496/Hover.Trike.zip)

Technically I got this design "working" by switching the back from the one repulsor to two. The three replusor design always leans right. If you bring up the center of thrust you can see that it's off center. But, it shouldn't be.

**Comment by SageThe13th** [comment]
[Hover Scooter.zip](https://github.com/tsunamayo/Starship-EVO/files/4632525/Hover.Scooter.zip)

After there hours the final design ended up like this. The larger repulsors just made it ride too bouncy no matter what settings I changed. So this one has eight small repulsors in a more stable formation.

**Comment by tsunamayo** [comment]
@SageThe13th this is a proper bug... I keep you posted.

**Comment by tsunamayo** [comment]
@SageThe13th okay bug fixed, the force was not applied at the center of repulsor for stretched one, which led to an asymmetry. Fixed for 20w21b. Thanks!
