### ISSUE TITLE
[Bug] Turrets do not work on child entities

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2060]
### Short Description of the issue:
If a turret is built on a child or granchild entity, it will not function - the turret does not respond to mouse movements

### Steps to reproduce the issue:
Build a turret on a child entity
Control it and try to move it

### Environment
- Starship EVO version: 20w20b
- Graphics Card: RX 580

**Comment by Dwarf-LordPangolin** [comment]
Confirmed. The only part of a turret built onto a child entity that will work is the weapons via hotkeys; the rotators/hinges do not respond to player input.

The turret on the left does not work because its platform is on a child entity, but the turret on the right is built on the ship's main entity and does work.
![20200513201904_1](https://user-images.githubusercontent.com/33041786/81881917-03670d00-9557-11ea-850c-262f6550c43f.jpg)

**Comment by tsunamayo** [comment]
Fixed for 20w21b. Thanks!
