### ISSUE TITLE
[Feature request] Separated mouse sensitivity options

### ISSUE THREAD

**Issue by nokturnihs** [tsunamayo/Starship-EVO#2093]
### Short Description of the issue:

I'd really love to see mouse sensitivity split out between character mode and in-ship flight. I use a trackball and piloting ships is nearly impossible at sensitivity higher than like 15. If I set it that low however, it becomes painful to build things and run around

### Steps to reproduce the issue:
Try using a trackball and piloting a ship at high sensitivity.
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by tsunamayo** [comment]
Yes it makes sense. I also want a separate 3rd person toggle for ship, I play in 1st person but use 3rd person for ships.

**Comment by tsunamayo** [comment]
okay actually I am not sure to understand:
=> you set a lower sensitivity to ship in order to be able to fly well
=> so you get a low sensitivity for looking around with the character?

Which is weird because atm the sensitivity of the mouse was not read for spaceship control.
Now I made a change and the mouse input are read for 20w20b, which might help you. Thanks

**Comment by tsunamayo** [comment]
Also I have added the separated sensitivity settings for 20w20b. Thanks!
