### ISSUE TITLE
[Dev Asks] Boat blueprint

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#2107]
I havent really tried to do a boat, I wanted to know if you guys tried in the latest build. If you have a small blueprint to share that could be cool also!
I wont have time dig much into detail, but I could always make a small boat computer with basic control.
Thanks!

**Comment by ultrak2k** [comment]
Okay here's a stupid idea, no idea how possible but
What if there was a torus spawning menu? And you could somehow customize how much land vs water it had, so we could have water torus?

Far off idea, but would make sense judging from this
(maybe it could help test general terrain gen too)

**Comment by Aiwii** [comment]
[SX105 Esulion (2).zip](https://github.com/tsunamayo/Starship-EVO/files/4648461/SX105.Esulion.2.zip)
Doesn't balance in water currently but is a boat
![image](https://user-images.githubusercontent.com/53021785/82289568-4dd6f800-9962-11ea-8073-bd0dbe2ab966.png)

**Comment by tsunamayo** [comment]
@Aiwii looking great!

**Comment by jimmybub** [comment]
Is there a specific block that is more buoyant than others, or do all blocks have the same value?  Really interesting addition by the way!

**Comment by JRL101** [comment]
[JRL101-Test Boat - 001.zip](https://github.com/tsunamayo/Starship-EVO/files/4652845/JRL101-Test.Boat.-.001.zip)

![image](https://user-images.githubusercontent.com/33255536/82372850-493c3d80-9a4f-11ea-9c19-63b32818a2a2.png)
![image](https://user-images.githubusercontent.com/33255536/82372967-71c43780-9a4f-11ea-9aa0-460b9023f044.png)

**Comment by DioTheCreative** [comment]
So wait, if you have the hovers high up then you can actually make a boat?

**Comment by tsunamayo** [comment]
Yes I would need to add a low density block... problem is why people would use the normal brick if I give this? I kinda need for thinking on this.

**Comment by JRL101** [comment]
@tsunamayo you could make the starter block align to the waters surface when placed in water or "float" so as you're building you can see the different of weight and boyency, but the starter block needs to resist completely rolling, so you dont end up building upsidedown, just a slight indicator that its gonna roll/sink

**Comment by JustHappened** [comment]
> Yes I would need to add a low density block... problem is why people would use the normal brick if I give this? I kinda need for thinking on this.

You could make the normal block better at handling heat?

**Comment by Dwarf-LordPangolin** [comment]
First, the buoyancy system is really cool! Coming from Space Engineers, where all the water was frozen lakes, this is fantastic to play around with.

Second, I was playing around with a boat to see if I could get it to float. I wanted it to float like this:
![20200527131054_1](https://user-images.githubusercontent.com/33041786/83059941-4e395800-a020-11ea-89dc-da1f3da63b93.jpg)

But it was doing this:
![20200527131604_1](https://user-images.githubusercontent.com/33041786/83059960-572a2980-a020-11ea-9565-d642a888a0c2.jpg)

I figured buoyancy was comparing the ship's volume and mass, and just added some rods to increase the volume while not increasing mass, and then it floated at the right level:
![20200527132712_1](https://user-images.githubusercontent.com/33041786/83060032-6f01ad80-a020-11ea-8aa1-94ba87573e30.jpg)

So instead of adding a lower-mass block, maybe the formula that buoancy uses to compare volume and mass could simply be tweaked?

**Comment by piotmetans** [comment]
I made a replica of [Dasnewten's wonderful Draken](https://www.flickr.com/photos/dasnewten/2503187439/in/photostream/) in game. When I shared with the discord, they suggested I post it here.

[Draken.zip](https://github.com/tsunamayo/Starship-EVO/files/4698683/Draken.zip)

![Draken](https://user-images.githubusercontent.com/660015/83201860-71453400-a114-11ea-8e28-e973aebd224d.png)

**Comment by tsunamayo** [comment]
Okay amazing build all, let me check this out! Yes I might have to cheat a lot on the water density (already cheating quite a bit...) Thanks

**Comment by JRL101** [comment]
as long as it LOOKS like physics, does it really matter if you cheated? as long as it does the thing right?
