### ISSUE TITLE
[Bug] Block HP same regardless of shape [20w21c]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#2138]
### Short Description of the issue:
All blocks have the same hitpoints regardless of their shape, even though they have different masses to match their different shapes.

### Steps to reproduce the issue:
Create two new entities, and place a 1x1x2 cube hull block on one, and a 1x1x2 wedge hull block on the other. Compare their hitpoints; both will have the same.

### Environment
- Starship EVO version: 20w21c
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
Two blocks, one half the volume of the other:
![20200520115732_1](https://user-images.githubusercontent.com/33041786/82720021-618da180-9c75-11ea-8818-af753c8ae480.jpg)

The solid one has 280 HP:
![20200520120242_1](https://user-images.githubusercontent.com/33041786/82720025-65b9bf00-9c75-11ea-9336-055045cb908d.jpg)

But so does the one with half the volume:
![20200520120250_1](https://user-images.githubusercontent.com/33041786/82720027-681c1900-9c75-11ea-9204-578f009dfa9c.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4671031/output_log.txt)

**Comment by tsunamayo** [comment]
Not really a bug as it was by design - but do you think that some people would want to exploit that? Worst case I would have to bump back up wedge and stuff. I have a limited number of hull ids as it is all stored in an expensive Voxel data structure. And I will need those precious hull id for more hull variants.

**Comment by Dwarf-LordPangolin** [comment]
It's not so much an exploit as it is just a spatial geometry kind of thing. These two shapes have the same HP; but one of them is a **much** easier target.
![20200523143108_1](https://user-images.githubusercontent.com/33041786/82739041-1bcaea80-9d02-11ea-8d2e-6a058083ecd3.jpg)

The shape on the right is half the surface area as the one on the left, and is a much harder target to hit. Sleeker, angled ships will be harder to hit -- both in PvE and PvP -- but will have the same HP as blockier ships. This penalizes players that want to build blocky ships: they're bigger targets without being any tougher. To use a comparison with Overwatch, this is as if Tracer was buffed to have Reinhardt's HP, while keeping her smaller hitbox; everyone would pick Tracer, and nobody would pick Reinhardt.

If you need block HP to be the same regardless of block shape, the only solution that I can think of is for weapons to treat blocks on _other_ ships as if they all used the hitbox of the full block. Guns on the player's ship would use the full, precise collision detection, which would let the player build precise guns and turrets that fired close to the hull, but guns on other ships would use simplified collision detection that treated all blocks as if they had the cube shape.

So using the example in the picture above, guns on other ships would see the two ships like this:
![20200523151807_1](https://user-images.githubusercontent.com/33041786/82739827-b6c6c300-9d08-11ea-80f0-c069d3558441.jpg)
With gray representing the shape of the ships, and the red additional area representing the hitbox guns on enemy ships see for calculating if they hit or not. The HP of the two ships would be the same, and they would be equally easy targets to hit. Then the mass of the blocks could be made the same too, so everything would be balanced.

Importantly, this would still allow players to make ships that were harder to hit by making shapes that were thin or flat; they just wouldn't be able to exploit the extra thinness and flatness of the wedges to make smaller targets with the same HP.

**Comment by Senakysam** [comment]
Hmm, this could be an issue since you can have two wedges in the same voxel space.

**Comment by Autarch-Conne** [comment]
A strange idea that may need tweaking. But what if a certain number of turrets were made to target slopes over blocks? Perhaps an algorithm that is triggered whenever a turret starts shooting. The algorithm would decide which and how many turrets had a targeting priority for slopes rather than blocks. This way, there would always be turrets targeting slopes, and the number of them doing it would be random, so it would be hard to exploit it.

**Comment by Dwarf-LordPangolin** [comment]
> Hmm, this could be an issue since you can have two wedges in the same voxel space.

That is actually not an issue; I tested it earlier today, and two wedges in the same voxel space requires the same number of shots as a full block in the same voxel space. HP seems to be per voxel, not per block; if a voxel has a hull block in it, it has a hull block's HP, regardless of whether it's one block or two stretched into it. So thankfully, that's one exploit we don't have to worry about.

To give a better illustration of what I meant by my idea:

This is the shape the player's guns would see for collisions when firing:
![20200523155032_1](https://user-images.githubusercontent.com/33041786/82740325-6a31b680-9d0d-11ea-8b91-cda247919539.jpg)


This is the shape other guns would see for collisions when firing:
![20200523155027_1](https://user-images.githubusercontent.com/33041786/82740322-61d97b80-9d0d-11ea-9746-abb1595f69db.jpg)

**Comment by tsunamayo** [comment]
I dont think this will be much of an issue honestly, it just means the most optimum design is to use wedge around the corner and thats it. It wont bother too much people that dont want to do it - it seems like is a small tactical advantange. 
Yes the whole system is per voxel, hence the limited number of available blockid. It is a design choice that I made some time ago, the full destruction system is per-voxel, as otherwise it would have much much bigger repercusion on ship design (it would have mean that 16x16 large hull section would have been much stronger to get through compared to a 1x1, severly limiting creative freedom).
Thanks

**Comment by Dwarf-LordPangolin** [comment]
Okie dokes. You're probably right; taking another look at my own pictures, this is only really an issue at the ship's edges, the rest is just as large a target as ever.
