### ISSUE TITLE
[Suggestion] Pre-fab copy/paste system

### ISSUE THREAD

**Issue by esauftgz** [tsunamayo/Starship-EVO#2184]
A possible QoL improvement would be a copy/paste system.

I've realized the need for such a tool due to mirror mode not working well with building on two separate child entities. Furthermore, with the amazing detail possible, it might be shame to not being able to take certain design elements from other builds to yours if you like them and are feeling a bit lazy.

**Comment by tsunamayo** [comment]
Yes it was requested and discussed quite a bit. Only issue for now is engine wise, I feel I need more optimization to not shoot myself into the foot at you could spawn an ungodly amount of detail easily. Then if the lags player would say game is unoptimized! Problem is with the brick system you can really cram a lot of details. What if somebody wants a fancy wall instead of the basic hull one? It could potentially be over 100x worse perf wise compared to a regular hull.
Thanks
