### ISSUE TITLE
[Suggestion] Folders for Blueprints and Teleport locations

### ISSUE THREAD

**Issue by ChuckieGee** [tsunamayo/Starship-EVO#219]
Suggestion: Allow users to to group together blueprints and teleport locations via the use of Folders.

This will help users to have an interface that isn't cluttered and is easy to use, Users will be able to create folders based on their projects that they're working on, for example if they're building a large ship, but have multiple versions of the ships progress saved as different blueprint names e.g. 
"Ship v0.1
 Ship v0.2"
etc..
then the blueprint menu can become cluttered and sometimes tedious to scroll through when searching for a specific version of a ship, with the facility of folders, users can better oragnise they're ships and the versions of their other creations.
A similar scenario presents itself in the case of teleport locations as well, due to some users wishing to have multiple teleport locations on Torus, or within large individual ships, e.g. One teleport location for the bride, and another location for the Escape Pods. The ability to organise these locations within folders will be beneficial for the reasons explained above.

**Comment by tsunamayo** [comment]
Both blueprint and teleport location will be re-organized, but most likely a bit different than what you are suggesting.
Teleport: Single entry per ship - then on ship button click another windows appears with the several locations. Location could be named via the block - ie medbay, bridge, ect.
Blueprint: Filter options, and native versioning / backup per ship, so that only a single entry appears - but then have the ability to roll back to an older backup via a different button. 
I will open a discussion on the forum, as it is truly needed, especially the blueprint one.
