### ISSUE TITLE
[Suggestion] Ship core orientation

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2210]
I've noticed a bit of confusion with some of the new players in the Discord about ship orientation. It gets even more confusing when players put their yokes on child entities or non-standard directions such as with Expanse like "skyscraper" ships and try to fly requiring a non-child entity yoke to be placed out of sight connected to the core. Rather redundant and not everyone who plays is in the Discord. Since the gravity generator got its directional arrow, maybe the ship's core can have a similar system. Same restrictions of course

**Comment by Servomotor** [comment]
Although the yoke issue is an issue with child entities (I had that issue on my first ship and you guys helped me) its still more obvious than the ships core. Secondly, the ships core currently allows for any placement which makes building easier and it can be used as part of the decoration. Making it mandatory that it faces a specific direction is less intuitive than the yoke by a large factor. Everyone has experienced a "yoke" in life (steering wheel) to point a vehicle in the direction they want to go, its humanly intuitive. Placing your computer in the direction you want to go is not. I feel this would be an "out of the frying pan and into the fire" scenario if it were changed.

Would it make more sense to create a brick that is called "Flight Direction Orientation" or something that is put down with an arrow on it indicating  the direction of flight? I'd hate to suggest anything that is not "necessary" for the sake of performance, but there has to be a better way than using the ships core/computer.

**Comment by ZachZent** [comment]
Perhaps I didn't make myself clear Servo because that is exactly what I'm suggesting. As referencing the gravity block, you once had to place it face down on a surface and gravity would generate in that direction and that direction alone. Thankfully that was changed to what it is now with directional arrows letting you direct gravity on both the x and y axis while on a wall. The child entities should be getting directional arrows soon themselves.

Long ago we actually had this system where the core dictated the orientation, at least sort of. It was intuitive (more or less) but it was also the size of a 1m block. What I'm basically saying is return the directional functionality of the old core with the features and the smaller size of the new one so that all players can easily see where the orientation is and can place the yoke how they wish. Directional arrows are always good

You know I was going to make a drawing/edit a picture buuuuuuuuuutttttttt it was like 1am. Whoops

**Comment by ProPeach** [comment]
I also think that the current yoke derived ship orientation is superior to the old ship core method. A lot of the time players don't even think about it, they just put their yoke down facing forward because that's the way the vast majority of ships need it. The added customisailbilty with linking a yoke to a yoke is also great and makes sense given how logic works.

I do think that it could be slightly more clear what the yoke does as I'm sure many players correctly oriented their ship without even knowing. Perhaps giving it a placement guide like the repulsor or gravity block could help with that, where the placement hologram shows the outline of a basic ship pointing forwards along the yoke when you go to place it. More information in the codex would also help, but that goes with any block

**Comment by tsunamayo** [comment]
yeah I think we all agree, yoke is the right solution but it needs a small gizmo. I just recently added a workflow to do just that with the turret (I hope you like the link visualization), and I will extend that to basically everything. Will be especially important for mech.

**Comment by tsunamayo** [comment]
We now have this !
