### ISSUE TITLE
[Suggestion] Logic linking improvement

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#2220]
The current linking has some handling problems that can be improved. Dragging a single link halfway across the ship is a little inconvenient on the finger. Additionally when there is a lot of logic gates and child entities clustered in one area, it isn't uncommon to accidentally link to the wrong output. Instead, why not have a simple click system rather than drag? Right click to set source, left click to set destination. Simple and easier on the finger.

That is the main suggestion, but there is a layer deeper. When a person wants to link one input to lots of outputs such as a switch to a set of doors, the player must go back and forth to each one. To expedite this, a player would press and hold [shift] and left click to set destination. Not only will the logic link, but it will allow the player to link to additional outputs. For example a button in the bridge to lock down or override all doors.

**Comment by tsunamayo** [comment]
How does that works in Space Engineer / Starmade else? I know my system is similar to Scrap Mechanic, but truth builds in SEVO are much bigger than in Scrap.

**Comment by ZachZent** [comment]
I'm not sure about either of them, but I bet someone will come along and explain it better than me searching on the wiki for 5 minutes.

The first part is more like a QOL feature than a new system. Click instead of drag. The second part would just make life easier especially for larger ships or large logic machines *cough Talrey cough*

**Comment by ProPeach** [comment]
In SE its very different, all systems in the ship appear in one big list in a GUI a bit like a file system. Light 1, Light 2, Light 3, Reactor 1, Reactor 2... They're all just named in the order that you place them. To "link" two systems you have to find your first system in the menu, click an icon, then find the second system. You can also rename systems and group them together, again like a file system. 
To be clear this is not how SE does actual logic gates, it has a programmable block in C# for that. The method above has for thinks like linking a timer to a light, par a button to a door.

If we're talking link tool improvemts, how about the ability to hold shift when drawing a link so that you can link multiple systems to the same source? Say you're linking  a switch to multiple lights, you can drag from your switch and hold shift then click on all of your lights without having to go back to the switch to draw each link individually.

**Comment by tsunamayo** [comment]
@ZachZent so yeah I go there from time to time, when you want info on a block or a think like that it is easy to get, but question like mine are just a pain to find info on.
@ProPeach thanks, I see it is a completely different approach...
What about use the action key (rotate - pick paint) to lock on to the selected tool. It would pick the link (so no hold button), and not close it once you clicked a taget.
So that two bird one stone: you dont need to hold the mouse over a long distance, and you can link as much stuff you want without loosing your link.
Press button again to stop the link.
I could go to Zach suggestion too, but what is not clear is how to break the link. Left click again? I think when you want a small assignment it feels right.
Ho also I think X-ray and system highlight and being able to assign through wall would help, right?

**Comment by ProPeach** [comment]
Using the action key works great as that's not in use, I realised after commenting that shift is used to "sprint"...
Yes, that could work nicely. I think it would need quite an obvious indicator on the GUI to explain it to players, but it would be much more convenient to use.
An X-ray would be great! Especially if paired with a much longer reach for the tool

**Comment by tsunamayo** [comment]
also what do you think of the smoothed curve for the link? I want to get rid of it, especially if I display more links.

**Comment by ProPeach** [comment]
It looks more polished than a straight link, but I don't think it matters much what shape they are as long as they're easy to read

**Comment by tsunamayo** [comment]
multi link was implemented some time ago.
