### ISSUE TITLE
[Suggestion] Brick voxel hp

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Starship-EVO#2279]
### Short Description of the issue:

Currently, any voxel containing only brick elements (including brick systems) has 0 hp, so that a single laser bolt from the weakest gun can destroy it. This means even a player with a handheld pistol or the tiniest of ships can do incredible damage to any ship or structure with brick-only voxels, including destroying fighters and turrets with ease.

This is incredibly unbalanced and exploitable in regards to how ships are mostly built (with the exception of Pangolin who has worked around this issue by including hull in most voxels with bricks).

Instead of making voxels require block hull to have any hp at all, I suggest that there be some amount of hp given to voxels occupied by bricks. I don't have an exact system in mind, but something similar to how even the thinnest parts of stretched block wedges have hp seems nice.

**Comment by Dwarf-LordPangolin** [comment]
I support this suggestion, for another reason: currently, most hover-bikes have no HP, since almost none use any blocks in their construction.

I'm not sure what the best method of doing this would be, but the nature of some vehicles (hovercraft, boats, etc) is such that many of them aren't going to be able to get a useful amount of HP from blocks alone, since they typically don't have space for any blocks.

**Comment by tsunamayo** [comment]
So there is two things at play here, the ability to absorb some damage before being destroyed, and the Hull Point score that count toward ship destruction.
Yes I will need to address both, I have a few options to explore.

**Comment by tsunamayo** [comment]
No longer applicable!
