### ISSUE TITLE
Important: Scrubbing Stations Tech!

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#2305]
Okay guys after a couple of day of experience with the system I think what was a good idea on paper will prove to be a real pain to make it work correctly.

x4 tech is mostly fine, but the interior / exterior mechanic is gonna be a real pain to deal with. Blueprint load / multiplayer...
 Plus the learning curve and UX player side is a huge pain.

It really sucks to trash a few days of works in the garbage bin but the sooner I take this decision the best it is - especially with some of you working on that too. I really hate myself atm...  It is really really hard to not succumb to the sunk cost fallacy... 
I have way too many bug to focus on already, this would add a ton more.

=> What does it means?
I still want to keep the docking modular design for NPC stations. So I still really really need you guys to work on that! Here is what I will do:
1) I will make the docking block compatible for the normal grid, with the eyelid mechanism of Womble. This wont be a two way connector, just a docking port, and it will be 2m wide, so you can use it on ship. You will be able to dock your ship with that block, so ship-ship, ship-station, and station-station. I keep the docking tool also.
2) Shipyard block will also be compatible with the normal grid size
3) 4m grid block disappears.

So sorry to nuke your build! I really love the style of them, if you could reproduce that on a normal entity, accounting for a 2m wide docking port that would be fantastic. The build will be coming in soon. Again really sorry for that - I had to take a hard call, I am too close to release I cant loose more time with this.

=> What about big ass stations?
It means that our stations are not gonna have a huge size, at least for now...
I think the best way for me is instead to spend time on deeper optimizations on the engine. I should have spend the time on the rendering tech instead! The docking approach alleviate a few bottleneck though, like the light volume memory size (which is the biggers offender memory wise).

**Comment by Aiwii** [comment]
So all the station blueprints will shrink or will they just break?

**Comment by ultrak2k** [comment]
The biggest tragedy here is the loss of megastations, hope some work around let’s them come back. We *need* something in this game to be large, even if it isn’t ships, which I don’t mind keeping small - stations should be bigger then them.

**Comment by ZachZent** [comment]
Remember to scale up the connector block to be used on ships

**Comment by Dwarf-LordPangolin** [comment]
Speaking for myself at least, I didn't lose much time at all working on this, since I'd already designed similar stuff in Space Engineers. So, don't feel bad on my account. :+1: 

Plus, I can _definitely_ reproduce my stuff 100% on a normal entity. By a happy coincidence, that will also work perfectly with a 2m docking port, so you should see my station modules rolling off the assembly lines with the new system very shortly after this change goes live. I was going to rebuild them from scratch anyway; I realized I was basing my standard grid that I was using on a smaller measurement than I should've been using. I do have one question: will the docking port be able to extend outwards a bit like a piston, as was suggested in one of the docking threads? That would make docking differently shaped ships much easier.

I'm very glad to hear that the modular, docking mechanic is staying; that's the best feature of the station mechanic. On the Discord, people have been very excited about how easy it is to build stations rapidly with the system. I'm a little sad about losing the larger scale, but we're keeping the thing that was most important to me.

**Comment by ultrak2k** [comment]
Question if stations Be comprised of lots of modules - wouldn’t that cause entity lag?

**Comment by Sei-Neko** [comment]
Don't be so hard on yourself, Tsuna. This is what pre-alphas are for.

**Comment by ProPeach** [comment]
That's a real shame, the idea of the 4m exterior and un-loaded interior was an amazing one. But I'll trust you when you say it's not worth it, congrats on not falling into the sunken cost fallacy! It's important to fail often and fail quickly while learning from them in my opinion. Better optimisation for the whole game is always nice! Especially as these stations will have to be quite large even when built out of 1m blocks to accommodate most ships comfortably

**Comment by tsunamayo** [comment]
Yeah it sucks really hard, thats not the first I have to trash something, and not the last. But this time you guys where in the loop, because I need you to give the tech asap...

**Comment by ProPeach** [comment]
Is there a chance that this tech could be made to work if you had a bit more time? The benefits of the 4m tech are huge, maybe if you put stations aside for now until after EA you might be able to spend the time on the problems you're facing now without feeling so rushed

**Comment by tsunamayo** [comment]
yeah but in the long we will all be dead like said Keynes ;)

**Comment by ProPeach** [comment]
I was thinking next 6 months rather than next 60 years 😋

**Comment by Servomotor** [comment]
Don't feel bad Tsuna. Anyone helping to make assets, or who is invested in the game knows its a pre-alpha state and that bugs will happen, and that things will change and that they may need to start over or scratch their own work. In art or design "one shots" rarely happen and sometimes the best action is to start over. The important thing is that you understand the cost sunk fallacy, most people do not and will continue working that turd until its finely polished, but in the end its still a turd.

**Comment by Servomotor** [comment]
Also as a side note. I initially clicked to read this thread based on its title. But I thought we were getting some kind of medical tech facility blocks and the first ones made were scrubbing stations. LOL

**Comment by stratometal** [comment]
Yeah. The concept is interesting, but you needed to make a call and I believe it was the right one. Concentrating on optimizing what you have right now so that you can release to a wider audience is good. I like that you are keeping some of the idea, the easier to implement part should be priority. 

While I was working on a few station modules I thought it would be cool to have some sort of way to convert ship to station and back a la Space Engineers eventually (unless I missed it already). Speaking of SE, I noticed your project thanks to EctoSage a few years ago.

I'll go back to working on a few station stuff now. 

Don't get disheartened Tsuna!

**Comment by tsunamayo** [comment]
Thanks for your support all!
@ultrak2k good question, first the modular approach was also core to the scrubbed approach, so it is not worse on that regard.
Then it is actually not that bad, if you compare it to en entity with a lot of children entity the total number of modules will be reasonable. 
On the collision side it is actually faster as the bounding box are tighter compared to having a bigger single one.
On the rendering that will be a bit slower, but soon I will refactor this so the impact will be negligible. 
Honestly after a few days with the new system its a 100x better! I had such a bad code smell with the old system...
