### ISSUE TITLE
[Question]What is going to need crew, what won’t, and what will have it as an optional benefit?

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#2365]
After long debate in the discord, combined with the seeming nearing of crew’s addition to the game, a simple question remains: what will actually NEED crew to function, what won’t, and what may have crew as a benefit but not mandatory? The line here is blurry between members of the discord, as some want crew to be entirely optional but give you a buff, and people like me want them to be as much of a buff that they are basically needed.

**Comment by tsunamayo** [comment]
Crew would be needed for turrets and drone operating.
It wont be needed to man system, although they would give significant bonuses.
It wont be needed to repair your ship inside, although this would be highly desirable.
It is all subject to change obviously...
What people dont want to have crew?

I need to absorb a few technical improvements first before putting crew though, as they will use  a bit of resources...

**Comment by ZachZent** [comment]
I assume that turrets and drone operating were just examples of possible crew types.

> Pilot
Gunner
[Science]
Maintenance
Engineers
Medics
Menials (cargo pushers)
Security/boarders
[Traders] (send them out to get stuffs?)

Just some that I plonked down in Discord. I also remember something about a FTL style leveling up system. Maybe some categories for level up rather than one for each of the above (or types you plan to add)

**Comment by tsunamayo** [comment]
So fighter would need a crew in the fighter, drones will need a crew but onboard the mother ship.

**Comment by tsunamayo** [comment]
okay I wanted to wait for ea as I am pretty busy atm to follow a discussion but I am gonna give you my old doc, I need to re-read it I might have changed my mind on some stuff...

https://docs.google.com/document/d/e/2PACX-1vSQ_hZTEnH5mW9pqqaVCba5ST6YWoJ0Sts5Z6HMoQ7XOx0rVo33wNmye2WcilFZtVRUbin7tx7cB_1g/pub

**Comment by Majikmonster** [comment]
### Regarding AI vs. Crew-Operated Turrets

From feedback on discord regarding **crew manned turrets**, it seems that making turrets (of any kind) depend on a secondary system (crew member) to operate the primary system (turret computer) is cool, but unnecessary for basic operation. Some people are a fan of it for role play or added complexity to basic game play, but others have brought up that it's a little ridiculous to need a crewman to do what the turret AI (and AI in general) and WWII-era technology can already achieve (reference: automatic ammunition loaders).

As an extension of that, a crewless ship whose weapons are essentially defunct without NPCs is a huge disadvantage for any design that doesn't have enough room to house crew. This mechanic favors larger ships and inevitably leads to a minimum ship size requirement (and minimum design/layout depending on how crew quarters is implemented), as any practical vessel will need crew to operate its offenses/defenses (This isn't referring to fighters, as they don't usually house crew anyways).

The role of crew as buffs rather than requirements was thoroughly discussed, but a clear consensus was not reached. Your mention of crews giving systems buffs is the baseline for this system, one which is universally supported. However, crew should not be required to do what players (with the assistance of turret AI) can already do, as it penalizes independence and creates an arbitrary barrier of minimum function.

One such game that added arbitrary restrictions and learned from that experience is Starmade. Mechanics like system integrity (not what it sounds like), distance-based reactor stabilizers, the dreaded "power sausage" (a vulnerable link between reactor parts and stabilizing elements), shield node coverage, volume-based reactor efficiency, etc all contributed to the tedium of ship creation and ultimately resulted in "wedge ship" meta, and later "stick ship" meta gameplay. One of the very few saving graces that kept it afloat was its automation. Factories, turrets, ships, and fleets would work without crew to achieve a variety of relatively simple tasks and some more complex ones like combat, albeit not in the most graceful manner.

Crew requirements likely won't create many exotic design cases like it did with Starmade (with the exception of 'apartment building with guns' designs that I pray never come into existence), but it will severely restrict combat and defense function of ships, stations, and bases. The game will essentially become Crew Simulator 2020 if game play, especially combat, becomes too crew-dependent.

I know much of this system is based on FTL. I also know StarWars is a huge inspiration. I like those franchises too, but they lack the nuance of automation that makes game experiences smooth. The most automation FTL has is in the form of little drones, and Star Wars has droids yet no ship autopilot. Whatever canonical reason they have for these strange inconsistencies is not designed for or ideal to games with as much build freedom as SEVO.

It really makes no sense why automation cannot be extended to turrets, as even the need for human operation of modern turret weapons is more a matter of technology that hasn't been developed rather than by principle. Any way you look at it, requiring crew for basic turret functions is a taped-on mechanic. If we can pick a landing pad or shipyard and let autopilot take us there, shouldn't we be able to pick a target and have the turret AI shoot at it? Crew might give it a _buff_, but the **builder** should give it the ability to _function_.

draft v1

**Comment by ultrak2k** [comment]
I have to massively disagree with the above combat, tbh. As outlined in the former discord discussion, more crew is best was my viewpoint

**Comment by Majikmonster** [comment]
Adding an extra step to any process or system is the definition of complication.

Automation involves the decrease of manual (human) intervention. Since players manage crew, and crew then manages a system (turret), the level of intervention is in fact double that of current, and more so if you include specializations and leveling of crew.

Crew requirements simultaneously decrease the level of automation, and increase complexity. While this may be an intriguing and deep mechanic, it should not at all interfere with the fundamental operation of a ship. To improve it? Sure. To gate-keep it? No.

Redstone is a deep and enabling feature of Minecraft. You do not need it to play the basic game loop or 'finish' the game, and no other feature is locked down if you don't use it. Ad-lib in Crew and SEVO to those sentences, and you have your answer to "should I need crew to operate turrets?".

Gameplay should not under any circumstances be compromised by a single feature. Features should synergize with each other, not lock the other away, especially not when freedom of play-style is a goal for the game. Given that turrets are and will more than likely be the backbone of any defense system (an unavoidable requirement), it is imperative that they function with as few requirements as possible. A ship core gives you automatic mobility (autopilot), so should a turret core give you automatic defense. Those are, after all, the most basic functions of the entities.

**Comment by SageThe13th** [comment]
Tsuna stated that crew would give bonuses, not be a requirement for the system in question, turrets, drones, or whatever else to function. The idea is to give walkable crewed ships and edge over vehicles that are only filled with systems.

My concern would of course be the amount of complexity and computing resources involved.

**Comment by ultrak2k** [comment]
> Adding an extra step to any process or system is the definition of complication.
> 
> Automation involves the decrease of manual (human) intervention. Since players manage crew, and crew then manages a system (turret), the level of intervention is in fact double that of current, and more so if you include specializations and leveling of crew.
> 
> Crew requirements simultaneously decrease the level of automation, and increase complexity. While this may be an intriguing and deep mechanic, it should not at all interfere with the fundamental operation of a ship. To improve it? Sure. To gate-keep it? No.
> 
> Redstone is a deep and enabling feature of Minecraft. You do not need it to play the basic game loop or 'finish' the game, and no other feature is locked down if you don't use it. Ad-lib in Crew and SEVO to those sentences, and you have your answer to "should I need crew to operate turrets?".
> 
> Gameplay should not under any circumstances be compromised by a single feature. Features should synergize with each other, not lock the other away, especially not when freedom of play-style is a goal for the game. Given that turrets are and will more than likely be the backbone of any defense system (an unavoidable requirement), it is imperative that they function with as few prerequisites as possible. A ship core gives you automatic mobility (autopilot), so should a turret core give you automatic defense. Those are, after all, the most basic functions of the entities.

Level of intervention? Wha? Your general gameplay experience isn’t made more complex, you likely aim turrets as usual, while adding to the gameplay experience in the form of needing crew

**Comment by ultrak2k** [comment]
> > Adding an extra step to any process or system is the definition of complication.
> > Automation involves the decrease of manual (human) intervention. Since players manage crew, and crew then manages a system (turret), the level of intervention is in fact double that of current, and more so if you include specializations and leveling of crew.
> > Crew requirements simultaneously decrease the level of automation, and increase complexity. While this may be an intriguing and deep mechanic, it should not at all interfere with the fundamental operation of a ship. To improve it? Sure. To gate-keep it? No.
> > Redstone is a deep and enabling feature of Minecraft. You do not need it to play the basic game loop or 'finish' the game, and no other feature is locked down if you don't use it. Ad-lib in Crew and SEVO to those sentences, and you have your answer to "should I need crew to operate turrets?".
> > Gameplay should not under any circumstances be compromised by a single feature. Features should synergize with each other, not lock the other away, especially not when freedom of play-style is a goal for the game. Given that turrets are and will more than likely be the backbone of any defense system (an unavoidable requirement), it is imperative that they function with as few prerequisites as possible. A ship core gives you automatic mobility (autopilot), so should a turret core give you automatic defense. Those are, after all, the most basic functions of the entities.
> 
> Level of intervention? Wha? Your general gameplay experience isn’t made more complex, you likely aim turrets as usual, while adding to the gameplay experience in the form of needing crew? How does needing crew for turrets remove freedom of choice you just plonk a guy to operate the turret, while increasing overall game immersion. IMO that’s like saying fuel for ships is gatekeeping moving around because it’s an extra step to do things

Plonking down crew somewhere is *minor* complexity at best, but with that definition, anything is complexity- detailing a ship is complexity, or needing to go to a factory or station to refuel is complexity, and yet those are relatively minor things that help with immersion.

**Comment by SageThe13th** [comment]
Understand that assigning crew is a task that gets more complex with ship size. FTL limits you a half dozen crew members, usually you need less, and your weapons office controls all you weapons. Try to think about a ship that requires a dozen NPC crew or two dozen. What about managing multiple ships? It's a system that adds minor complexity at first, but may become needlessly tedious depending on how many NPCs there are and what tasks they doing. Putting too much much effort into the operation of a single ship kills fleets. But, devil's largely in the details. You could have a fleet made up mostly of uncrewed "robotic" ships. However, depending on how great the crew bonuses are these ships could prove more a waste of resources than anything.

Regardless, how crews work the inclusion of NPC crews is extra computing resources the game is using to keep track of them. Crews in any form reduce the size of space battles. To me it's question of  how much streamlining should be given up for the sake of immersion.

**Comment by ultrak2k** [comment]
> Understand that assigning crew is a task that gets more complex with ship size. FTL limits you a half dozen crew members, usually you need less, and your weapons office controls all you weapons. Try to think about a ship that requires a dozen NPC crew or two dozen. What about managing multiple ships? It's a system that adds minor complexity at first, but may become needlessly tedious depending on how many NPCs there are and what tasks they doing. Putting too much much effort into the operation of a single ship kills fleets. But, devil's largely in the details. You could have a fleet made up mostly of uncrewed "robotic" ships. However, depending on how great the crew bonuses are these ships could prove more a waste of resources than anything.
> 
> Regardless, how crews work the inclusion of NPC crews is extra computing resources the game is using to keep track of them. Crews in any form reduce the size of space battles. To me it's question of how much streamlining should be given up for the sake of immersion.

Depends on how much computing resources, and it’s not like you have that many crew. I think it’s fine

**Comment by Majikmonster** [comment]
> Level of intervention? Wha? Your general gameplay experience isn’t made more complex, you likely aim turrets as usual, while adding to the gameplay experience in the form of needing crew? How does needing crew for turrets remove freedom of choice you just plonk a guy to operate the turret, while increasing overall game immersion. IMO that’s like saying fuel for ships is gatekeeping moving around because it’s an extra step to do things

If you have to do something actively rather than let it happen passively or interject yourself in a situation that should not need your direct input, that is called _intervening_. If you need to intervene in a system that otherwise could be automated or done by another party, this is called _micromanagement_.

Tedium ensues with each and every single system or process you have to manage. If for every turret on your ship, you need a crew member (that might have an officer, as read in Tsuna's document), those are crew members to keep alive, healthy, leveled up, paid, and accounted for after each battle. That might be good for say, a 2 dozen turrets on a well-crewed ship. It would definitely be immersive, and very much seem alive. Guess what? Now that you have your 24 gunners, handful of engineers, and posse of navigators and pilots including officers, you have to go to your crew terminal or walk up to them and check their stats regularly. That's if your ship is already built, fully repaired, not in under any threat, stocked, and fueled up for travel or trade or whatever it is you're doing. Think about that for a minute. 24 loose "living" elements that account for your ship's survival under direct threat to go with your already 24 loose elements in the form of your guns. (this is a theoretical case, so don't even try to go "but _my_ ship doesn't have 24 turrets!" or "but pirates aren't a thing yet!")

Wouldn't matter how well you made your ship or how much you have invested in it if the gunners are in any way damaged or under-performing, because you'd need them to fire your guns at all. So much for that ammo and those nice barrels and/or addons. Looks like you need to spend more of your time and resources on gunner TLC! Try having that in any other game. _ANY_ other game. Even FTL would become a hot mess with that many crew, let alone just gunners to manage. You still have to worry about yourself, your ship, and the rest of your crew/fleet/corporation. There's a reason why turrets in almost all space-age games are automated, and it is that they have _no reason_ **not** to be, and any reason to **not** be automated needs to be a pretty good reason, not just "muh immersion" or to superficially make gunner crews valid. Immersion and superficial needs aren't an excuse for imposing such impactful restrictions. You can ask any Elite:Dangerous player about asteroid mining and get an idea of how tedious that gets when you need to not only blow the rocks up, but also manage your stock of limpid drones that occasionally break. That's with just 1 ship. Forget fleets.

Fuel is to engines as water is to plants. Nobody would contest the need for such a thing.
Turrets don't need people to man them, because we have something called computers.

> Plonking down crew somewhere is minor complexity at best, but with that definition, anything is complexity- detailing a ship is complexity, or needing to go to a factory or station to refuel is complexity, and yet those are relatively minor things that help with immersion.

Detailing a ship isn't a requirement to operate the ship, and once you build that detail, you don't need to maintain it. Refueling is as I've explained above: a universally accepted and completely expected mechanic that would be strange to lack. It doesn't just help with immersion. it is the primary element of any technological system in any game: power generation. Crew isn't either of these things. If it were, you're just playing Colony Survival in space. Mind the gaps.

**Comment by SageThe13th** [comment]
It's pretty clear NPC crews will be implemented. If they prove to be unworkable like the build drones the feature will be altered or removed. Arguing against the feature in it's entirety before we've even seen a single version of it doesn't seem like it would go anywhere.

**Comment by Majikmonster** [comment]
_Turrets_, Sage, turrets. I'm talking about gunners being required for basic turret function, not crew as a whole.

**Comment by tsunamayo** [comment]
We will see if it is too tedious and I need to give a full auto option - it is too early at this point to make a definitive judgment.
As for adding artificial restriction, thats the goal of the gameplay loop. If you dont like superficial restriction, then creative is for you. My goal is to design system that will make the game fun and enjoyable, and provide some depth - if the turret gunner fails to do that then I will scrap it no pb.

**Comment by SageThe13th** [comment]
I still wonder about having a ship with a lot of NPCs. When I stated a crew of two dozen or more that's because I can imagine a ship with that many controlled systems. Between drones, turrets, and whatever else.

I imagine a less intense solution would be to have an NPC bridge crew, but not a ship that's full of NPCs. A hand full of NPCs that boost the most vital ship functions. That way you can become invested in a few NPCs rather than just auto-filling you ship with what's essentially just bunch of expendable "parts" providing buffs.

**Comment by ultrak2k** [comment]
thank you tsuna laying down the fax

**Comment by tsunamayo** [comment]
@Majikmonster okay thanks for your contribution. It seems you are making a lot of assumptions on how the thing will works. I dont want to do something tedious, beside hire, assigning a bed (even that could be auto as soon as you have free beds, and maybe no bed at all), and assigning it to a task you would not have any more things to do.  They would level automatically. It will have to stay pretty simple, I dont see it being harder than making the actual turret itself, and it would be definitely less time consuming.

**Comment by SageThe13th** [comment]
I find myself agreeing with Majikmonster on turrets. Requiring an NPC to operate a turret. Not having a way for a turret to operate by itself is a bad system. I'd rather if any system could run by itself. This would be a level 0 version of the system. Having a crew member would then improve the system starting at level 1 and capping at whatever the max level is. Requiring crew is restriction for the sake of restriction and hurts both small designs and fleets.

**Comment by ultrak2k** [comment]
no, having turrets need crew sounds good to me. Fuel is a restriction, fuel tanks and calculating it can dampen performance, and yet we aren’t trying to remove it.

**Comment by ZachZent** [comment]
> This would be a level 0 version of the system. Having a crew member would then improve the system starting at level 1 and capping at whatever the max level is

FTL does the same thing. The systems work on its own, but are buffed when a crew is manning the station.

**Comment by SageThe13th** [comment]
Going back to your last two points Ultra. You're just completely wrong.

Ships wouldn't have that many turrets? Wrong. Ships can have as many as the builder can make up to the child entity limit. You are not the final arbiter of what number is too many or too few.

NPCs won't be that much of a stress on performance? First they're addition stress regardless of how much that is or not. Being unable to avoid the system means paying that cost. Assuming they are somehow going to be an extremely light weight system given the realities of A.I. and the computer resources they cost is just incorrect. Based on wishful thinking not facts.

Ships have fuel because the game is in need of a system of up keep cost to balance large ships to small. With that system already in play do we then need a second system that does the same job? No. But, adding in second system isn't problem either. 

What I have a problem with is crew being a requirement. And yes, having turrets require NPC gunners makes them requirement on "larger" ships even something as small as a 50m corvette with only a few turrets. This means that I am then unable to make "robotic" uncrewed support ships or have a ship with unmanned point defense turrets that are designed to work via quantity over quality because the system just doesn't allow for it. Things that people could be reasonably expected to want.

A robust system is never designed assuming the exact behavior of how the end user will approach the system. A robust system designed to be abused and continue functioning regardless.

**Comment by ultrak2k** [comment]
> Going back to your last two points Ultra. You're just completely wrong.
> 
> Ships wouldn't have that many turrets? Wrong. Ships can have as many as the builder can make up to the child entity limit. You are not the final arbiter of what number is too many or too few.
> 
> NPCs won't be that much of a stress on performance? First they're addition stress regardless of how much that is or not. Being unable to avoid the system means paying that cost. Assuming they are somehow going to be an extremely light weight system given the realities of A.I. and the computer resources they cost is just incorrect. Based on wishful thinking not facts.
> 
> Ships have fuel because the game is in need of a system of up keep cost to balance large ships to small. With that system already in play do we then need a second system that does the same job? No. But, adding in second system isn't problem either.
> 
> What I have a problem with is crew being a requirement. And yes, having turrets require NPC gunners makes them requirement on "larger" ships even something as small as a 50m corvette with only a few turrets. This means that I am then unable to make "robotic" uncrewed support ships or have a ship with unmanned point defense turrets that are designed to work via quantity over quality because the system just doesn't allow for it. Things that people could be reasonably expected to want.
> 
> A robust system is never designed assuming the exact behavior of how the end user will approach the system. A robust system designed to be abused and continue functioning regardless.

when the hell did I arbit how many turrets should exist, but if you’re gonna comment about performance, then reasonably having lots of turrets would be worse then lots of crew. Also, surely maintaining crew is maintenance for larger ships

**Comment by SageThe13th** [comment]
> Depends on how much computing resources, and it’s not like you have that many turrets anyway. I think it’s fine - pretty sure I’ve heard of ways to do NPCs with little cost, and it’s a small price to pay for a good system of needing NPCs for turrets. Plus, it already seems to be set mostly in stone.

All three of these statements are wrong. And your argument is based on the number of turrets always being low.

> when the hell did I arbit how many turrets should exist, but if you’re gonna comment about performance, then reasonably having lots of turrets would be worse then lots of crew. Also, surely maintaining crew is maintenance for larger ships

If you don't understand how a system that merely aims doesn't require as much computing power as a system that aims, has path finding, and has other behaviors, then you pretty much lack the technical understanding to be taken seriously.

**Comment by tsunamayo** [comment]
yeah one my hidden goal for crew on turret was also to limit the number of them. That would force player to make less of them, turret are really really ressources intensive - I optimized them a lot already but people were talking about like two dozens (for one ship... argh). Turret in SEVO are not like in other game as they are made the player, so they are more costly to run.
I know people are into massive ships (and fleet), but the game engine was not design to do that best. I would have done voxel only (no bricks), no custom turrets ect.
On the other side I think that the defining feature in SEVO is the fact that it is a 1st person game, aka you do not play the ship. When you play the ship it is easier to spawn massive fleet ect, but when you play 1st and every ship has an interior I think it is a real shame to not play the crew card: I mean you will have your big ship but it would be empty and lifeless.

@SageThe13th during combat the perf impact of the crew should be inferior to the perf impact of the turret itself. The crew is just there sitting, if you dont see it the animation wont be playing.

**Comment by SageThe13th** [comment]
I'm not opposed to crews existing. I'm opposed to them being a hard requirement. Given a more flexible system where I have the option to deploy vehicles, ships or otherwise, without crews and a very limited number of turrets I have the ability to fill out my forces with "fodder" and conduct larger scale battles. While, crews existing allows me to man my flagship with elite high level staff turning it into a "hero" ship.

Having crews as a requirement makes this process needlessly tedious. I'll just start with the construction process. If I have a ship constructed at a yard based on an existing blueprint it's not too hard to imagine that the fuel cost of the ship could be part of the build cost. The ship would come into existence with it's fuel tanks full and ready to go. Except with a crew being required, now I have to staff it. And staffing it not as simple a process as just fueling it up.

**Comment by tsunamayo** [comment]
So it seems we have a conflict between crew and fleet.

**Comment by SageThe13th** [comment]
It's something to consider. I know the general consensus is that people would like the game to have battles between small fleets of specialized ships rather than 1 on 1 duels between mega ships and some fighter craft they might launch. FTL's a great game, but it only concerns itself with operation of single ship which only engages one other ship at a time.

I can think of the ship's crew in SEVO more like equipment. Something you assign, then sit back let it do it's job. As opposed to FTL where you have to micro manage your crew. However, especially with a system of leveling, crew might a resource that's too valuable to lose frequently. Meaning mid tier support ships either need to be able to operate uncrewed or they may just prove to be more hassle than they're worth. Leading to fleets of nothing but large drone carrying "battle carriers" and nothing else.

**Comment by ultrak2k** [comment]
> > Depends on how much computing resources, and it’s not like you have that many turrets anyway. I think it’s fine - pretty sure I’ve heard of ways to do NPCs with little cost, and it’s a small price to pay for a good system of needing NPCs for turrets. Plus, it already seems to be set mostly in stone.
> 
> All three of these statements are wrong. And your argument is based on the number of turrets always being low.
> 
> > when the hell did I arbit how many turrets should exist, but if you’re gonna comment about performance, then reasonably having lots of turrets would be worse then lots of crew. Also, surely maintaining crew is maintenance for larger ships
> 
> If you don't understand how a system that merely aims doesn't require as much computing power as a system that aims, has path finding, and has other behaviors, then you pretty much lack the technical understanding to be taken seriously.

I know you’ve already been wandered but I was thinking that turrets have collisions, aiming,etc, while a crew member can just sit in a place stationary? Chill, man, being all“hoo boy you don’t know anything I must be right”  is going to make you the one taken less seriously dude

**Comment by ultrak2k** [comment]
you know what, this is getting pretty heated, might as well close this lol

**Comment by Majikmonster** [comment]
> you know what, this is getting pretty heated, might as well close this lol

So after the shortest poo-flinging contest I've ever seen between someone exasperated at how many times and angles of approach they had to explain a feature's merits, and another so desperate to argue the losing side of a (dare I say) debate they'll hide the entire discussion in the closed issues pile, I think I'll just make a new thread specifically about turret mechanics. I hope it won't get bogged down with emotional appeals and non-points by a single person like this one did.

**Comment by tsunamayo** [comment]
@Majikmonster please keep it civil then, I think you had a valid point and I definitely understood it, I will be careful at not making a painful mechanic. If its gets in the way I will have many option to propose an fully automated way or entirely scrap it. Cheers
