### ISSUE TITLE
Internal collisions with cargo

### ISSUE THREAD

**Issue by T00Code34215** [tsunamayo/Starship-EVO#2379]
### Short Description of the issue:
Weapons in stands, pods attached to module doors displaced and collide with bricks, get stuck in the middle of objects. Stops ability to move and makes ship lag and bounce around. 
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:
Idea. Make docking bay module doors a bond so you attach them with tools and then you have to detach them for any chance to float away.
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

**Comment by Sullos** [comment]
I've noticed similar variations of this. Sometimes as of late, I can still move my ships, but there's basically loose cargo flying around my ship making the collision effect at various points as I turn and move.

**Comment by tsunamayo** [comment]
So for the docking it is normal at this point as the feature was not added yet (working on it).
Regarding the weapon this should not happens. Do you have a character save where this happens so I could investigate? Is this happening all the time? Thanks

**Comment by Sullos** [comment]
I'm hoping you can see it on the screenshot, at the front corner of the ship, there's a collision damage spark effect visible. I had to take a few screenshots to finally capture it, but you should be able to see it.
![711980_20200611123858_1](https://user-images.githubusercontent.com/33239800/84338999-dbfc7200-abe0-11ea-973e-032ceee890a7.png)

Heres my character folder. I had to fly around a little bit and keep an eye out for the effects of the collisions to be visible, but it definitely happens fairly consistently. I found that by simple flying up and down in 6dof mode, if I flew up the spark appeared on the underside for a moment, then flew back down it would appear on the top of the ship for a moment. If you actually start carving the hull away trying to find the 'entity' causing all the collisions, you cant find it. But if you go around and remove all the weapons from items stands, then they disappear.

[sullos character folder.zip](https://github.com/tsunamayo/Starship-EVO/files/4762271/sullos.character.folder.zip)

At times, a ship won't fly at all due to the collisions, I believe this happens if the invisible entity appears within the solid hull and doesn't have room to bounce around inside an actual compartment.

Let me know how else I can help!
Thanks

**Comment by tsunamayo** [comment]
@Sullos thanks for the detailled test case, so it means that when an weapon is on an item stand at reload it will be free and collide with the entity? Thanks

**Comment by Sullos** [comment]
It seems that way, a weapon on an item stand is still technically in the item stand, however, it creates a sort of ghost version of itself which doesn't stay in the item stand. The ghost version is what floats around in a ship and collides. That's my best guess.

**Comment by tsunamayo** [comment]
Okay thanks to your help issue is fixed in 20w24b. Thanks!
