### ISSUE TITLE
[Progression Request] A couple things to make updates/content smoother.

### ISSUE THREAD

**Issue by nokturnihs** [tsunamayo/Starship-EVO#2419]
Hope this doesn't bug you bud - These are just a couple suggestions/requests to make future power/shield/engines and ESPECIALLY blueprints and UGC (User generated content) more useful for you in your progress towards release:

- If you add fuel requirements to reactors/engines, make your old reactors/engines Tier X engines, and fuel-consuming versions Tier Y,Z,etc - this reduces the need for EVERY ship that's been submitted so far needing an overhaul (sometimes a MAJOR overhaul or complete abandon in certain ships).
- If you want the non-fuel consuming systems at the top end of the "tech progression" - just adjust their output up (keep their heat output similar) and then the fuel-consuming systems can be lower.
- The more functional blueprints (original creations donated to you that don't violate copyright law) you have, the less work you have to do when it comes to bringing the galaxy to life - hull changes, shield, reactor, engine changes are just numbers and can easily be adjusted without breaking the blueprints you have now - changing absolutes (example: ALL engines need fuel, etc) the more work you or a backer will have to do to update every blueprint you can use - some ships that are extremely complex or large will take considerably more time, and very tight/small blueprints might need to be completely scrapped in those cases. 
- You probably should put in your changelogs (at least in this stage of development) when you add a new system that will DEFINITELY break ship blueprints -it will increase the likelihood of people who've submitted useable BP's to you to fix their ships and re-submit. For example, a (long) while back you changed hinges and slide-rails -that change nuked half of a ship for me as the slide-rails and hinges disappeared on the whole ship. I know you try and avoid stuff like that, but it's gonna happen here and there - not a problem, but give your peeps in this early/contribution stage a little heads up so they can export if needed and repair as necessary.

These are all just opinions/observations. I'm really digging the changes/improvements you've been making bud! Keep it up!

**Comment by tsunamayo** [comment]
I try to put in my changlelog all the change, especially breaking one too. I think I will add a little icon so people really read them.
The regarding fuel, how about the opposite? Making fuel a entry level tech for survival, void reactor / thruster being more a late game kind of things? So no blueprint are squashed, fuel being more interesting for survival anyway.

**Comment by nokturnihs** [comment]
Love it - also Probably adds feel goods for the backers as their creations will be "top tier" in survival.

**Comment by ExodistSKY1** [comment]
"Making fuel a entry level tech for survival, void reactor / thruster being more a late game kind of things"

    YES! I like this!     I think it is the best direction to go without making it too complicated, causing every ship to be remade, and giving a late game goal while not being too overpowered.

**Comment by ProPeach** [comment]
In terms of pure gameplay, I'd much prefer that all tier reactors required fuel rather than some simply not needing anything to run. Fuel is an interesting and challenging gameplay component, and is a smart way of scaling the cost of running a fleet/larger vehicle. Unless these no-fuel reactors offer a terrible power to volume/mass ratio, I think they'll make the game less fun.

**Comment by tsunamayo** [comment]
@ProPeach and if they are made of unobtainium? 
A lot of people were thinking that fuel get in the way and would drive the fun out of the game...

**Comment by ProPeach** [comment]
Unobtainium quickly becomes obtainium past a point, diamonds are supposed to be the top tier in Minecraft but players often have hundreds very quickly. Personally I haven't seen much hate for fuel, the vast majority seem to really like the idea of different tier fuels like metallic hydrogen you mentioned that would require large amounts of energy to produce, but be very energy dense. Perhaps those people didn't like idea of very complex fuels that would require many different components for no real gain in enjoyment, but in a survival game you've got to have consumables to keep the game interesting even at the higher levels.

**Comment by ExodistSKY1** [comment]
I see your point ProPeach.  

Just a few quick thoughts: 

-Having reactors/Thrusters have a base fuel capacity per block? Can add dedicated fuel storage to extend range
-Have the end game reactor/thruster be very efficient 4x? 

-I think for 6dof and normal boost the fuel should extremely efficient but still something to worry about (how would this work with mechs?)

-OR  possibly only having fuel for lightcruise (not sure what it was renamed), different fuels could be more efficient, which is a huge advantage, and will be a massive part of survival and exploration

**Comment by nokturnihs** [comment]
I can understand your arguments @ProPeach  but need to point out a few things - there's already games with complicated fuel systems that are very similar here - space engineers and empyrion just to name a couple. Starship EVO stands out for its build system and I think that is one of the big draw factors. Grind mechanics don't actually add that much balance in most games, just time-gate content. While some people like grind, the same games offering those mechanics already exist as competitors. 

And finally, accepting/requesting blueprints before forcing changes that invalidate said blueprints is discouraging and frustrating for some of those designers. It also discourages further submissions because  "what will break the thing next" in beta/alpha. Those blueprints the community submits saves @tsunamayo tons of time.

Personally, I don't like (exclusively) fuel mechanics for space building games all that much. It's unnecessary grind for games that lean towards heavy grind to begin with. 

I'll be up front and honest and suggest we probably need to know if @tsunamayo intends to make any changes that are gonna break our builds. I don't have so much time as to rework each one multiple times so if there are updates/changes coming that will invalidate a build, the only practical solution for me would be hold off until there's a content freeze just prior to release and then start building my submissions. I hate that idea because it screws @tsunamayo though.

**Comment by nokturnihs** [comment]
Just had a thought that could leave both sides of the argument happy and functional.

So fuel adds "balance" as it costs resources, storage space, etc. While I think the same balance could be achieved without fuel systems but in regards to weapons cost or repair, shield, or engine costs, there's an alternative that does what you want @ProPeach but doesn't introduce game-breaking bugs or require @tsunamayo or any builders to massively gut and rebuild their submissions.

Regardless of which tier the current reactors and engines end up becoming, add a slow decay to them, where they wear down to minimal functionality (not completely break) - this will avoid those situations where you run out of fuel on a long trip and are completely screwed (Especially in single player) or make RNG On resource acquisition especially brutal and tank a world in early game. But it does mean that these reactors and engines will require repairs over time, which will simulate the same kind of fuel balance without taking more space on small ships or requiring all submitted blueprints to be reworked from the ground up.

Mind you I'm still in favor of these "fuelless" units being low tier to help with early game and having fuel consuming units be more powerful and offer better ratios for things like heat, energy consumption/production or efficiency modifiers to connected systems like thrusters and shields but that's my take.

If you ever played empyrion a few years ago, getting a seed where you weren't lucky enough to get decent fuel veins or any fuel veins, it sucked. And both space engineers and empyrion are so incredibly Grind I don't play them because it takes hours to accomplish anything in single player (which is where I play).

**Comment by Battlepixel** [comment]
I agree with nok. 
I personally would find a tank system terribly unnecessary and cumbersome. For me there are really many good ways to keep long-term motivation high for Starshipevo, but a repetitive gameplay element like refueling is definitely not one of them for me.

- It would be really cool to have a combat rank / level system that, depending on my rank level, allows me to peg npc pilots. These could e.g. Cost wages or get a percentage of every profit.
- There could be certain systems or asteroid fields in which it is possible to mine the rarest and most expensive resources, but which is being hit by increasingly strong alien or pirate waves of attack, so that it is not possible to survive there long enough without large combat ships or fleets to mine resources.
There are so many other not too difficult to implement content that would bring tons of motivation and challenges in the lategame and that are not contained in any other competing game. 
There is so much competition in space survival games. Players who are keen on micromanagement are sure to have heard of Starbase even if they are not playing SE or Empyrion. I personally couldn't get excited about any of these games for a long time because a bit of spaceaction means far too much preparation and micromanagement for me.
When people compare the games Starbase and Starshipevo, Starshipevo stands out because it offers NPCs and currently requires much less micromanagement. For me these are e.g. the two points that make Starshipevo better. But that is my personal opinion or the opinion of the 2 people with whom I play Starshipevo more often. I don't know how many people think like that. This discussion is only very important to me because I don't like playing any of the named survival games for the reason that I hate Micromanagement that causes the lack of action and the lack of NPCs (which are essential for regular action). 
I imagine it very hard to program NPCs to fly into my hangar and refuel. And for what added value? The alternative would be that own Npcs are simply not possible or never have to refuel. 

If I need weeks to build a large combat ship in loving detail, I don't want to need weeks to scrape the fuel together to make it fly for a limited time, what I want is to experience fun and action with the cool things that I can build in Starshipevo. 
I would like to emphasize again that this is only the opinion of the three people with whom I play. 
I don't know if or how many others think that way.

**Comment by Servomotor** [comment]
I like the idea of fuel. What I do not like are ships that run out of fuel fast. I think fuel is a necessity, but should not run out after 15 minutes of even 4 hours. Small vehicles or vehicles that players would start making should be able to be fueled manually, but as the ship gets larger I think it should have to fuel at a fuel depot. 

Fuel introduces a grind, ALL GAMES need a grind, even if players do not like them. If there is no grind, content is consumed too fast and players get bored. Imagine if you got all your loot off a boss drop in an MMORPG only after 1 kill. Instead of playing the game for months on end, the player would be done in a single weekend. Fuel is a necessity as a grind, but does not need to be mundane. 

Fuel is also a gold sink, a way to take money out of the game. If there is a money system in game, there has to be money sinks to take it out of the game. 

Adding fuel to a spaceship is an immersive element that makes the ship feel believable. Even a nuclear reactor needs fuel, although it can last for years. Fuel opens up trade possibilities, slows game play and increases immersion. But, I cant state this strongly enough, there needs to be some form of fuel depot, or fuel ship. Dry Dock stations could be used for fueling. Fueling needs to be more engaging than just moving an item from inventory to ships fuel tank. I don't think pipes or conveyor belts are necessary, but residing inside of an area at a dry dock or attaching a refueling spaceship could work. 

Also I cant state this enough, fuel should last longer than most games. If you have to fuel all the time, every 15 min or even every couple hours it does get old. It should last a few days of long hour game play, maybe even a week or so on large ships. Space stations should last indefinitely with solar power. Ground bases should be similar, but spaceships, hover cars etc should need some form of fuel. 

Fueling depos also open up the opportunity to get an "oil change" on your spaceship. Maintenance that is required but not something the player can do themselves. This could cost gold/credits/money, be used as a currency sink along with the fuel. 

Fuel can also be used for game play balance and to force certain desirable outcomes. 

For example. We all know lighting is a large chunk of required computational power. Too many lights on = low FPS and unhappy customers. To curb people from leaving lights on, you incentivize the player by making their fuel last a long time if they do not have many lights on at the same time, just like real life electricity bills. Keep lights on and pay a lot, everyone knows to turn lights off.

If a player uses area triggers to turn lights on and off as they walk through their ship, then no real penalty to the fuel usage, but if they leave a lot on, make it cost more fuel so that they learn to turn lights off. It can be used to help drive your desired building goals. 

Anyway, just my thoughts on fuel.

**Comment by nokturnihs** [comment]
I would agree stations shouldn't expend fuel, and I'm not saying fuel shouldn't be one option for ships but the main thing here is blueprints - if ALL levels of engines/reactors require fuel then @tsunamayo is rejecting every submitted blueprint he's received. That's a lot of work for him or people who've been donating builds to help him out with the game (or both).

As far as other forms of grind, I'm pretty sure there will be plenty.

I look at this game as a great building game. I love building games, especially those set in space. There's a lot however I just don't play for long because for some reason most of the space building games are so obsessively focused on grind they're just not fun for me and my passion for building. I play other building games with decent grind as well - Conan exiles, minecraft, etc. The more commonly referenced games like empyrion and space engineers I can't really get into for long because the grind is excessive and the hours it takes to manufacture and build anything are too high and the ships are either paper thin and subject to destruction the first time you land poorly or only usable for very small periods due to fuel constraints. 

In addition we also have several things currently limiting build styles that are released/planned and complex fueling/refueling systems add more limitations, pushing small ships further away from being possible.
Heat
Air tightness
Piped inventories
(some) ammo consumption
hull strength per block

I think most these systems are fine, but I also play exclusively in single player and have seen almost every single game in this genre balance grind towards multiplayer and leaving the single player experience a grinding, boring, frustrated mess. But to cycle back, I know all the diehard grinders out there hate the idea of a single tier of reactor and engine being a fuel-free experience but maybe concessions can be made along these lines. I don't believe the existing reactors and engines will make content consumption a problem, especially if the fuel-consuming tiers offer significant advantages (especially if balanced with building styles in mind.)

**Comment by Servomotor** [comment]
This is why I suggested that fuel last a long time. So we get the flavor of interaction, the believability of a machine that needs fuel but without the constant grinding for fuel material. 

I desire fuel more for the immersive aspect, that fuel stations would need to be created, its another tradable item and it presents a challenge when building plus fuel tanks often just look cool (if done right).

AS far as blueprints go. I will make the statement right now. I Servo will personally retrofit every single packaged ship in game that requires fuel tanks to ensure all old blueprints in the game work. For free of cost and in a timely fashion with up to 40 hours of my time freely given per week until all the ships are updated. 

Outside of that, the ships made for the game right now are not numerous enough to leave out a mechanic for the fear of blueprints not being useful. Also if Tsuna decides to add fuel all designers have to do is leave some space in their ships for them. I understand the concern, but its really a non issue in the bigger scheme of things.

**Comment by nokturnihs** [comment]
It's a nice offer and would be great but there's a couple problems:

- people submitting blueprints right now are mostly backers and so having other people mess with their aesthetics to accommodate an immersion system isn't gonna float well with some of them (I for one would rather not have others retrofitting my backer submissions - no offense).
- there's very few reasons we can't have a fuel-free tier of engines and reactors - some people will gravitate towards them sure but if fuel-consuming tiers offer significant performance improvements or less heat adjustment then combat ships and other roles will be used by a lot of people.
- by forcing EVERY Ship to require fuel it makes fuel kind of trivial in the sense that it's a commonplace item. It might be a trade item but not overly valuable. If it's not exceedingly easy to obtain it causes lots of other problems, including game-breaking situations (especially in single player)
- existing reactors and engines can have a fuel mechanic if absolutely necessary in the form of slow degradation without the need to refit the numerous blueprints that have been submitted (I've submitted several alone and I'm just one of many backers)
- we already have a heat system that ties into combat and adds a lot of flavor there. The heat system effects the performance of the ships, survivability and build balance. Too many "balancing" systems can make a game unwieldy and costly for performance. 
- I think a fuel tier is great. I'm not sure why people are opposed to having a tier that doesn't require fuel (you say immersion for you - but can't you get that immersion AND have a fuel-free tier that allows the submitted builds to remain functional?) For PvPers or grind hard guys - if fuel tiers are geared for performance it shouldn't matter and grind hard guys... Don't use the fuel-free tier or grind for something else - it's a building game and content consumption isn't the same as an MMO.
- It may not seem like a big deal but making a single ship that looks good takes hours (tens, hundreds maybe) - if @tsunamayo has to do even 25% of that for all the NPC factions, pirates, etc to make a rich world, that's hundreds of hours going towards something his backers could be doing to help him. That extends significantly the time it takes for systems like mining, survival, missiles, enemy stations, missions and quests, etc to get developed (something only he can do). But as most of these are volunteered submissions, or in some cases people paying to submit blueprints, the more they have to go in and refit them the less likely they are to contribute down the road. Some might because they really want to and have time, and some will just hand it off to @tsunamayo or someone else to do the refit, which either removes them as an asset he can use or someone else doing the refit and perhaps causing contention there as whomever did the refit may break an aesthetic or a logic or just do something the backer/original builder doesn't like. That's not ideal and we've seen the kinds of problems it's caused in other games (starmade's fleet contest is a good example). I know I'm advocating for this pretty hard but I want to see starship EVO hit full release and his backer community can help him save a lot of time with these submissions. The downside is that every BIG Blueprint breaking change (like mandatory fuel in all ships/etc) puts a serious bump in that road.

Still, it's amazing to see people being so supportive of Francois!

**Comment by nokturnihs** [comment]
Oh and on leaving space for fuel - I've sent in several blueprints but at least 3 would be rendered completely unusable should fuel become a requirement, all three have no room to add fuel and several of my other submissions don't really have room either without massive overhaul.

**Comment by Servomotor** [comment]
I am always glad to help although I don't really see any problems as many of your concerns are easily to remedy. 

- The game is in pre-alpha and every backer should be hyper aware that things will change. So far that I have seen some things have already changed that will require many builds to be revisited, for example docking ports. Per your own admission these will not be easy to retrofit due to their nature of needing pathways. I submit to you that retrofitting fuel tanks will be much easier than a docking port. 

I design professionally. I have been creating art for the better part of my 50 years on this planet. I will continue to create a portfolio in Stevo and my offer still stands. If any of those backer content creators do not want to retrofit their work due to time, I will gladly do so. If they feel my work is not up to par with their design visions or aesthetics then they will simply have to make those changes, just like docking ports. 

- Fuel is a commonplace element in most survival or exploring games. I find it difficult to believe that most players would feel "forced" into using fuel when so many have already willingly done so. Minecraft requires tons of fuel for cooking and food for eating. Its a common element that adds to the game play and is in part of what makes the game fun. Fuel is really no different here. 
Part of game design is adhering to industry set standards. For example what color is common? Green. What color is rare. Blue. What color is legendary. Purple. Using fuel to fuel a spaceship or vehicle is not only something a player would expect to see, its common place. Its a well documented element that adds to the game play. 

- Placing fuel tanks inside of reactors and engines reduces the ability to make a strategically sound design. If we are getting atmosphere/oxygen or life support systems, it would behoove players to not only separate their fuel from their reactor/thrusters, but to have redundancy. Your proposal does away with this making builds more homogenized. As far as backers needing to change things out, that has already been discussed. 

- Fuel can still be used to balance the game without any additional number crunching. Part of that balance is discussed In the paragraph above. 

- Fuel requires fuel trucks/spaceships. Fuel could require filling stations. It would be a reason to explore and visit a space station. 

- I fully understand how long it takes to make ships. I have literally over 10,000+ in building games spanning six years outside of my design career. That is still not an excuse to forgo important game elements this early on in game. If adding fuel tanks and a fuel system means retrofitting ships, then that is what needs to be done. I don't say this to be rude, but to be quite frank with you. the retrofitting that you assert will break the game is a literal non issue. It wont take as long as you suggest. 

Ultimately, fuel is a core element to a spaceship game. Its so foundational to the genre that NOT having fuel will make the game feel incomplete to many customers. People are conditioned to needing fuel, to grinding etc. They are not conditioned to fuel being a free thing. If I am to be completely honest, not having fuel would make this game feel very amateur in it's design and that is the CORE reason why I am here, because I do not see amateur at all in Tsuna, in fact I see him as one of the best developers I have worked with, regardless of title. I wanted to back this game years ago but I missed the kickstarter. I have asked Tsuna if I could back him financially because I believe in his vision, like you I want to see the best for this game and I can tell you that not having some form of fuel element is a huge mistake. 

If you would humor me. I'd like to prove to you that the three 3 builds you say have no space for fuel, could in face be reworked with fuel tanks. Share them with me, give me your requirements for fuel size in the cubic area, be realistic and allow me to try. If I fail its no loss to you. No harm, no foul.

**Comment by nokturnihs** [comment]
Go ahead two are in the backer github and one is in the main I believe, the goldbug the blackbox and one other tiny ship I posted. That said to be proven "right" the ships need to maintain the EXACT dimensions and functionality. Good luck, they're literally microbuilds. Which is the point. Also take into consideration that fuel tanks will probably be full block sized, not microblocks. They're not part of my backer submissions but are themed for them but dunno if Francois is gonna want them in game or not.

I still fail to understand why a tier of reactor and engine is so dramatically unacceptable? We have fuel-free vehicles NOW and we can barely get out of our own atmosphere. Yes they run on batteries but still. 

I also will say that your whole thing about adhering to industry standards - well, frankly if you've played that many hours why would you want another clone of the same mechanics in almost every space building game? And then there's the fact that almost all of them have a fuel free option for power, be it solar, "void reactors" or whatever. If you play modded minecraft there's many fuel free options and in real life we have solar, wind, water power. There's theories for harnessing gravity, solar winds, the ionosphere to generate power. There's even new supermaterials that produce power in novel ways. It's not a stretch, not game breaking.

I'll see how you do on those refits and good luck - each of the ships that will be rendered obsolete with mandatory fuel at all stages is under 10m squared which is why I make the claim. Two also fold up into a "box" but to be fair one might have room enough for it. Maybe.

I guess I'm just boggled as to why some folk are so obsessed with forcing everyone into more grind and limiting build options. I wonder why they don't play the games that require all that. I enjoy the building in starship EVO but to be frank, if the survival mechanics are loaded up with grind, I'll have a hard time sticking with the game - mainly because we already have space engineers, empyrion, EVE, and so many others to fill that void. I didnt think we needed another of those. And SEVO Has an amazing building system and sits somewhere between SE And starmade for feel in my mind. I'm an older guy myself, and have played a lot of these games as I am disabled and it helps distract from chronic pain. That said, I don't think there's anything wrong with having both options and feel like forcing one particular mentality on all the players has killed most of the better building games or left them stuck in early access oblivion for years longer than they should have been. 

Gonna stop arguing this point though. I'm sure it's irritating @tsunamayo and both sides have been presented with a lot of alternatives and options. We'll see what he picks.

**Comment by Servomotor** [comment]
"Go ahead two are in the backer github and one is in the main I believe, the goldbug the blackbox and one other tiny ship I posted. That said to be proven "right" the ships need to maintain the EXACT dimensions and functionality. Good luck, they're literally microbuilds. Which is the point. Also take into consideration that fuel tanks will probably be full block sized, not microblocks. They're not part of my backer submissions but are themed for them but dunno if Francois is gonna want them in game or not.

- That is not how revisions or changes to design works. There are always concessions. Asking me to implement changes but with no changes being made is not a realistic request. I briefly went over this when I said "be realistic.  I also fail to understand the logic that Tsuna would use to implement large block only fuel cells when he has small reactors and small capacitors. It makes sense for shields as they are not a requirement for a build to work, fuel is. 

"I still fail to understand why a tier of reactor and engine is so dramatically unacceptable? We have fuel-free vehicles NOW and we can barely get out of our own atmosphere. Yes they run on batteries but still."
- Running on batteries is not fuel free. Batteries are fuel tanks, electricity is the fuel. My reasoning for fuel tanks and a fuel requirement has to do with balance (fuel tanks) and game design psychology. If large, open world games only let the player focus on the fun meaning destroying, fighting, etc, they quickly get played through. The way a game keeps up its monetization is thoroughly lengthy play sessions (keeps the player coming back which leads to referrals/purchases) and or microtransactions. A game without some form of grind, or a bunch of little grind elements placed into it allows the player to consume content too quickly. Part of game design is slowing down the content consumption. Adding fuel as a requirement does a number of things, some of which I discussed. It suggests that players could create their own fuel stations, or fuel modules, it requires exploration to find fuel or visit stations with fuel depots. It allows for scenarios to be played out for example a refueling ship/role play company that helps out stranded explorers, think AAA (automobile club). Fuel tanks allow for more flexibility in the design of the craft and for redundancy should life support require fuel (which it should), or shields. If fuel tanks absolutely can not be implemented, then reactors should absolutely consume fuel. Fuel is also part of the gold sink. EVERY game that has a currency must have a gold sink. That is why MMORPG's have repair bills, reagent costs, expensive mounts/houses/outfits etc. Fuel in a building game is a gold sink or time sink. These elements MUST take place for a healthy game. 

"I'll see how you do on those refits and good luck - each of the ships that will be rendered obsolete with mandatory fuel at all stages is under 10m squared which is why I make the claim. Two also fold up into a "box" but to be fair one might have room enough for it. Maybe."
I can't work on your ships without your understanding of concessions. I already detailed this in my OP. Its part of the design process. 
I mean look, I too have small builds that would absolutely not work with a full sized block as a fuel tank, but that is (as I already pointed out) not even remotely realistic. Things have to be logical and easy to understand for new players to pick up. Large reactor/large capacitor already exists, small reactor/small capacitor already exists, logically a player would expect to see a large fuel cell, and a small fuel cell. This also correlates with the games core design philosophy of blocks and bricks (which is also why we need block glass architecture).

"I guess I'm just boggled as to why some folk are so obsessed with forcing everyone into more grind and limiting build options. I wonder why they don't play the games that require all that. I enjoy the building in starship EVO but to be frank, if the survival mechanics are loaded up with grind, I'll have a hard time sticking with the game - mainly because we already have space engineers, empyrion, EVE, and so many others to fill that void. I didnt think we needed another of those. And SEVO Has an amazing building system and sits somewhere between SE And starmade for feel in my mind. I'm an older guy myself, and have played a lot of these games as I am disabled and it helps distract from chronic pain. That said, I don't think there's anything wrong with having both options and feel like forcing one particular mentality on all the players has killed most of the better building games or left them stuck in early access oblivion for years longer than they should have been." 

I am older as well, into my 50's. I would not say the requests for these mechanics are "forcing" anything on players, but part of game design and the tenants required to make a fun, long lasting game. Sandbox building games are still somewhat of a new genre due to the computational requirements, especially with higher fidelity building like Starship Evo. I worked with Sony Online Entertainment devs for 3 years helping them build assets for Everquest next, much like you are doing here. The difference with that game and this one is that they had the core of the game already established before asset design was being created. Due to Tsuna creating this by himself, he needs the assets earlier on, but along with this comes the understanding that the asset creators may need to modify their works as the game progresses in development. 

When I am approached by a client, I will always go through a number of revisions. These can be due to my mistakes, engineering changes, art/graphic changes or user interface changes. The list is long but the point is nothing is every "one shot", just like when Tsuna reworks something to make it better. Some things can be predicted, others cant but the bottom line is that revisions are always part of the design process. You created an art asset, and they may need to be revised. 

I know its tough to throw away or have to change your work, trust me I do this daily but its simply part of the process. As is often taught in art/design school, you don't have the luxury of "marrying" your art. You have to let it go, that is part of being artist or designer. I feel you are too married to your work to consider changing them, even if something beneficial is added to the game that will help to ensure a healthy game play loop and customer satisfaction. 

"Gonna stop arguing this point though. I'm sure it's irritating @tsunamayo and both sides have been presented with a lot of alternatives and options. We'll see what he picks."
No need to stop discussing. My approach here is not to be a burden or force my desires onto your play style, but rather to help the game reach its fullest potential and part of that are the discussions with both sides brining their experiences to the table. Brainstorming is a good thing, learning is a good thing. I learn from you, you learn from me. In fact of one my longest philosophical traditions is a simple one, but often overlooked. And that is, "Everyone can learn from everyone else" Meaning even the billion dollar CEO can learn from a bum. You are the million dollar ceo (established in this community) and I am the bum (new). We both have experiences to offer.

**Comment by Servomotor** [comment]
I should also note. I would love to see the game play elements that fuel requirements bring to the game, I would be sad if they did not happen but regardless of Tsunas choice I will still support his vision because StEvo, in my opinion, is a bit of a pioneer. This game offers game elements I have been dreaming about for at least a decade. I grew up on Legos like Tsuna and video games and always wondered why no one had "done it" yet, he is and I am super excited to be here making things that I hope people find enjoyment in.

**Comment by tsunamayo** [comment]
Okay guys I am a bit under the water here, if someone could do a quick recap that could be cool!
Right now I would say me preferred option regarding fuel would be:
1) no fuel for mini thruster
2) fuel for interstellar jump
3) then either fuel for lightcruise or fuel for power.
4) Late gate higher tier tech with no fuel (whether it be reactor or thruster)
5) when fuel is needed the block will be able to store a basic amount of fuel. Like the reactor can store a bit of power.
=> 4) and 5) should guarantee minimum impact on current build.
But I havent put more though than that, it will likely change...

**Comment by nokturnihs** [comment]
Sounds like you have the core of the debate figured out @tsunamayo 

@Servomotor we can move this to discord where it may be more appropriate, unless @tsunamayo wants this here... Sounds like he doesn't.

Basically though the debates are around how much grind is too much, more specifically how fuel will effect submissions, and whether it's required in all tiers of ship systems or the existing reactors and engines are going to become a survival tier needing no fuel or not. There's also some debate as to whether build mechanics and grind are needed to prevent content consumption like an MMO or whether content consumption is different in a building game of this kind. 

But yeah, servo I'm gonna reach out to ya on discord in DM. Should not I'm not officially attached in any capacity to Starship EVO outside of backing it on kickstarter and being around a while (mostly dormant until recently). Sorry if there was some confusion there.

**Comment by Servomotor** [comment]
There is no need to take this into discord. I am not debating for the sake of debating, I am debating to help the design of the game. I have some experience in this, specifically in building games with small voxels. 

I will part with this. If the fuel system is being designed around pre-existing art assets instead of a logical grind or progression system, then this is the wrong and backwards approach.

**Comment by ProPeach** [comment]
I'm with Servo on this - The current "void reactors" are good for a *Creative game mode* like what we have at the moment, but have absolutely no place in Survival/Career mode progression. They're a convenient stop gap until Survival is implemented, but should not be shoehorned into the future Survival system.

I completely sympathise with you Tsuna - it seems you want us to build you hundreds of ships for NPCs with the blocks we have now and don't want to have to update them later which would be a *huge* task for anyone.
But the infinite power no-fuel generation reactors we have now is *completely* incompatible with any future plans. Survival at its core is not about infinite resources, it's about earning those resources through play - that's where the satisfaction comes from (for most people). This is how almost any game with in this genre works, you need to keep your ships fields for them to keep working. With many fuel types and horizontal tier sidegrades, fuel becomes a interesting mechanic rather than a nothing chore.

There are other solutions however. Space Engineers use to have infinite generating reactors back when it was a Creative only game too. When Survival was implemented and reactors needed fuel, NPC ships simply spawned with a little fuel in their reactors inventories with no need to change the blueprint. Of course, I'm not saying this is the route you should take, but it shows that there are many ways to handle the transition between Creative and Survival.

I'm sure this topic will come up again in the future so I'll wait around till then, in the meantime I hope this has been helpful to think about.

**Comment by nokturnihs** [comment]
So I feel there's only so much need for grind and time-sinks but I am in the vocal minority it seems. If so, Then let's go full on grind I say - air is expendable, jet packs need fuel, energy and beam weapons should require ammunition and all weapons and systems on the ship should constantly be degrading on use. I mean, despite the fact we have fuel-free alternatives to power in the present and we somehow cracked blasters and deep space flight in this game, let's assume all of that doesn't matter because it'll break the game if we don't have to spend hours monotonously trying to gather/obtain supplies to go around the block no matter the type of ship we use or the role it plays in the game world. We also need to add grind mechanics like sewer systems, water and food, temperature, pressure. Don't forget there's a ton of radiation in space so each block should provide a certain amount of resistance to the background radiation in space and either way we need a system to account for the depletion of the bodies minerals in space and those atmospheric entries are gonna raise hell on our ships. I'm not sure how shields should work but I'd definitely say they should burn out after a few hits and need repairs or crystals to replenish them. Sounds great doesn't it, not only from a development perspective but to fill one's hours with endless amounts of entertainment?

There's obvious sarcasm here but I'm done worrying about it. I find the notion that having a tier that doesn't require fuel a game breaking element ridiculous as it exists in some capacity in most other games in this genre, but that's probably just me.
