### ISSUE TITLE
Question/ do we really need a fuel system?

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#2434]
I read about it in the post #2419  and would like to know whether there will be a fuel system? If there is still no answer to this question, I would like to add my opinion and a few arguments.

I personally would find a tank system terribly unnecessary and cumbersome. There are really many good ways to keep long-term motivation high for Starshipevo, but a repetitive gameplay element like refueling is definitely not one of them for me.

- It would be really cool to have a combat rank / level system that, depending on my rank level, allows me to hire npc pilots/wingmen. These could e.g. Cost wages or get a percentage of every profit. The ship category that my npc pilots can control may depend on their own rank / level, so it is important to keep your wingmen alive in order to level them
- There could be certain systems or asteroid fields in which it is possible to mine the rarest and most expensive resources, but which are being hit by increasingly strong alien or pirate waves of attack, so that it is not possible to survive there long enough without large combat ships or fleets to mine resources.
- the possibility against imense sums or resources, to get control over areas or systems, to build own stations which may even spawn their own NPCs(If enough ressources are stored) with the faction designs.
in Starmade there was a resource bonus for the players of a faction in every occupied system. Faction wars against players and Npcs factions would be very exciting and only realizable in lategame or/and together witth other players
- a Mission rank that determines the difficulty of the offered missions and quests
- ..

There is so many other not too difficult to implement content that would bring tons of motivation and challenges in the lategame and that are not contained in any other competing game.
There is so much competition in space survival games. Players who are keen on micromanagement are sure to have heard of Starbase even if they are not playing SE or Empyrion. I personally couldn't get excited about any of these games for a long time because a bit of spaceaction means far too much preparation and micromanagement for me.
When people compare the games Starbase and Starshipevo, Starshipevo stands out because it offers NPCs and currently requires much less micromanagement atm. For me these are e.g. the two points that will make Starshipevo better. But that is my personal opinion or the opinion of the 2 people with whom I play Starshipevo more often. I don't know how many people think like that. But this discussion is very important to us because me and my friends don't like playing any of the named survival games for the reason that we hate the micromanagement that causes the lack of action and the lack of NPCs (which are essential for regular action 
and enliven the universe).
I imagine it very hard to program NPCs to fly into my hangar and refuel. And for what added value? The alternative would be that own Npcs are simply not possible or never have to refuel.

If I need weeks to build a large combat ship in loving detail, I don't want to need weeks to scrape the fuel together to make it fly for a limited time, what I want is to experience fun and action with the really cool things that I can build in Starshipevo.
I would like to emphasize again that this is only an opinion of me and the two people with whom I play/build/test regularly.
I don't know if or how many others think that way.

**Comment by tsunamayo** [comment]
Okay I will let you guys discuss I wont have time for theoretical discussion at this stage. But for sure I wont force people to pipe things into the mini-thruster, that would be insane. It would make more sense for warp-drive and maybe lightcruise, or maybe just the bigger thruster?

**Comment by Battlepixel** [comment]
Fuel for the Warpdrive makes sense for various reasons and has nothing to do with micromanagement. Definitely!

**Comment by Garrett-C** [comment]
I don’t see fuel in general as a massive issue. It gives you a reason to build stations, ground bases and to move with a proper fleet including carriers or support craft. It could also add some extra tactics to fleet battles where maybe you go for the enemy support craft to limit their escape options etc. 

As long as it isn’t something that requires piping the existence of fuel sounds fine to me.

**Comment by ExodistSKY1** [comment]
@tsunamayo I think that is a good idea to have fuel be for warp and light-cruise! The larger thrusters should be able to hold a base amount of fuel, then you can also add tanks to your ships to increase its fuel capacity.   I like it this way because it is simple, does not break any ships currently, and has gameplay/strategic elements within it if implemented!  I think most will like this approach

**Comment by ZachZent** [comment]
I can see both sides for normal thrust fuel. For one it could get burdensome to carry around fuel with you and running out means you are dead in the water. But on the other side, it makes a good trade commodity, adds a relatively uncomplicated gameplay element, and distress beacons can come from being adrift in space.

However for warp a fuel is absolutely required. It prevents players from just popping into star system after star system (generally) free of cost. It also adds an element of progression. Start in your system gathering resources until you can craft or buy warp fuel. The system for this should be a one use item. Think a ball of antimatter or a whatever crystal. You craft or buy it, slap it into your warp drive, and warp away. Of course this includes recharge times and other balances.

**Comment by Calvert4096** [comment]
I like ZachZent's take.... there should be a fuel mechanic, but it should be balanced carefully so that the punishment for running out or failing to plan is neither too great nor too small.

Take the example of kerbal space program... some of the most fun to be had in that game (depending on your tendency towards masochism) is when you have to launch a rescue mission when the primary mission ran out of fuel.

A few thoughts for features:

-Some simple flight planning system that will warn a player when a trip is not likely to be successful due to lack of fuel

-A distress signal mechanic: a procedurally generated NPC ship can respond for a variable fee (make it interesting: some % chance that a pirate response instead, and you're worse off!)

-"Town portal" (like Diablo) mechanic that uses the teleporters to return to home base, whence you can launch a "rescue" to retrieve your ship.  If you've prepared adequately (e.g. have a specialized tanker vessel in docked at home), this could cost you little except extra time and fuel.  Maybe make the "emergency 1-way teleporter" a mid or late game technology item; an earlier game item could be something like an "escape pod" which accomplishes the same thing, but you have to pay a fee after getting picked up by an NPC.

**Comment by Dwarf-LordPangolin** [comment]
My own two cents:

1. Fuel for traveling to other systems is absolutely necessary, because otherwise there's very little incentive to explore and build.
2. Fuel for normal flight _can_ be a fun mechanic to design around, but it needs to be balanced carefully so as not to be either too frustrating, or too easy.

If running out of fuel is a concern, one solution is something the old Escape Velocity games (and their successor, Endless Sky) used: a "Ramscoop" item. This lets you recover fuel very slowly; it's too slow to let players ignore buying or making their own fuel, but it does let them recover if they run out of fuel in a system where they can't otherwise get any. In Escape Velocity this was a special item that was optional, but basically everyone used it, so Endless Sky made it a basic feature of every ship (their wiki entry for it is [here](https://endless-sky.fandom.com/wiki/Ramscoop), if you're interested).

As others have noted, there's no reason for these to necessarily be the same type of fuel.
