### ISSUE TITLE
[SUGGESTION] Add glass blocks

### ISSUE THREAD

**Issue by Brushes2** [tsunamayo/Starship-EVO#2473]
So glass tiles and 'blocks' match hull and small blocks (block, wedge, tetra at least).

**Comment by tsunamayo** [comment]
okay, the problem with that is as block stretch in this game I am always drawing the inner face, so it wont look goods like that (you would see the inner face)...

**Comment by Servomotor** [comment]
Perhaps we can get some "block" versions for glass then. Basically similar to the brick glass, but block sized and with hit points. 

I started on my first block ship build about a month ago or so. I had a REALLY hard time getting started because I wanted my ship to be durable, but most of the glass options are for bricks with no hit points. I had a mental block (no pun intended) that I could not get passed because I wanted the durability of blocks but was forced to have the weakness of bricks for the cockpit. 

It would be nice to have block glass and maybe more cockpit options like something curved and have block versions so we can stretch them farther. 

I asked in discord if anyone else had this mental block issue of trying to blend blocks with bricks in regards to making cockpits with glass, and a lot of people responded with similar feelings.
