### ISSUE TITLE
[Bug] Steam Upload Popup 

### ISSUE THREAD

**Issue by CreepoBeepo** [tsunamayo/Starship-EVO#2555]
After uploading your ship to the steam workshop a window pops up that you cant close because you cant access your cursor instead controlling the player and menus like the codex over lay above the popup preventing access from it.
![20200627131758_1](https://user-images.githubusercontent.com/37814990/85928113-aa3e0900-b878-11ea-8748-79134cf1d912.jpg)

**Comment by Kaiser-Indrasil** [comment]
The workaround for now is to exit to the main menu.

**Comment by tsunamayo** [comment]
I am not sure to understand, I dont have this problem.
What are the exact step you did to reproduce that issue?
Thanks

**Comment by CreepoBeepo** [comment]
I opened the menu and uploaded a ship to steam via the button in the save screen
![image](https://user-images.githubusercontent.com/37814990/85934967-81d5ff00-b8b8-11ea-8f95-67ab8bd19242.png)
It puts up the pop up and you cant close it

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil do you reproduce this also? It works fine on my side...

**Comment by Kaiser-Indrasil** [comment]
Yes, the "Upload successful." prompt is unclickable for me, too. It shows up behind the Codex/TAB menu and my guess is, it should've been in front of it, remaining clickable. Might be a resolution- or aspect ratio-related bug since everyone that had posted a screenshot in this thread uses a 21:9 ultrawide screen, and I am, too.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil @CreepoBeepo can you try with and without UI Post Effect in graphics options? Thanks

**Comment by Kaiser-Indrasil** [comment]
Yeah, looks like this is the culprit. I could even see the loading bar. Nice catch

**Comment by tsunamayo** [comment]
Okay I have a tentative fix for the upcoming version - you will tell me if that fixed it. Thanks

**Comment by Kaiser-Indrasil** [comment]
Thanks! I'll let you know once it drops

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil @CreepoBeepo build is live if you guys can test!

**Comment by Kaiser-Indrasil** [comment]
According to my test, the bug is still present. I can click the Upload button if I access the pause menu but the prompt window is underneath the pause menu window. As before, this seems related to the UI Post Process setting.
![image](https://user-images.githubusercontent.com/63756057/86087045-20ba5100-ba9b-11ea-9455-b87ecd49a5f8.png)

**Comment by tsunamayo** [comment]
So it is still showing beneath the Codex? I havent seen a screenshot of that btw, if you could send me that...
Thanks

**Comment by Kaiser-Indrasil** [comment]
When I click Share on Steam, it goes like this
![image](https://user-images.githubusercontent.com/63756057/86164365-90ffbb80-bb09-11ea-9480-0783cb4a3b50.png)
![image](https://user-images.githubusercontent.com/63756057/86164433-abd23000-bb09-11ea-8f2f-5dfaff44a35f.png)
As you can see, it just dims the screen and displays the pop-up window behind the Codex window.

The only way to be able to click it without changing the resolution or disabling the UI Post Effects, is to access the Pause Menu. It lets me click the button because it display the mouse cursor.
![image](https://user-images.githubusercontent.com/63756057/86164578-e5a33680-bb09-11ea-9b24-3e167d812561.png)

My resolution is 3440x1440.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil okay tell me how it is, for the character save selection, the tooltip and the workshop interface in 20w27b. Thanks!

**Comment by Kaiser-Indrasil** [comment]
Thank you! The Workshop interface and tooltips are now both working flawlessly. As for the character save selection, I haven't experienced that bug myself but whatever it was, it's probably no longer an issue.

**Comment by tsunamayo** [comment]
Okay great to hear!
