### ISSUE TITLE
[Suggestion] Paint colour reflectivity

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#2594]
![image](https://user-images.githubusercontent.com/27857711/86272581-b3a3da00-bbc6-11ea-982b-c901d47385eb.png)
Light coloured paints like White, Light Grey or Tan appear blindingly bright when you're close to a surface painted in that colour with the character Light switched on. Reflective materials like silver are still bright but not blinding.

This same effect also happens with player built lights as well, light generated by these and reflected off of lightly coloured paints is blinding.
![image](https://user-images.githubusercontent.com/27857711/86272908-43498880-bbc7-11ea-989e-c3a913fe7b41.png)
This is your area of expertise so I can't really speculate whether it's the reflectivity of the paint that is causing the issue or the type of light -  regular sunlight doesn't produce the same effect - but I think this bright reflection should be reduced

**Comment by tsunamayo** [comment]
No I think this is just because they are light (English language make it confusing). If you ever looked a large white surface on direct sunlight you basically cant watch for too long, it hurt too much. I could make the white less white...

**Comment by Kaiser-Indrasil** [comment]
I'd suggest leaving the white dye (and all other bright colours) as they are. I think the problem lies in over-exposure to otherwise perfectly fine surface. That could be remedied with setting a hard limit for the character's flashlight that would cast very little light upon already well-lit objects but would also cast lots of light upon poorly-lit areas. That might require a shader rework, I'm not sure.

**Comment by tsunamayo** [comment]
Yeah thats not really possible as there can be part in shadow and part lit. How about just having the player simply not activate the light when in the light ;)? I am honestly okay to leave it as it guys - it is not really a bug. Cheers
