### ISSUE TITLE
[Suggestion] add borders to Tetra glass blocks

### ISSUE THREAD

**Issue by StarrKiss** [tsunamayo/Starship-EVO#2619]
### Short Description of the issue:
Currently, the tetra glass blocks have no borders, and so they look weird when placed next to the wedge glass tiles (seen in attached screenshot.
...

### Steps to reproduce the issue:

Use Tetra blocks and wedge tiles together.

### Additional information:

![windows](https://user-images.githubusercontent.com/13007697/86499978-982eff80-bd7d-11ea-890e-be1f38edfa9b.png)

**Comment by ProPeach** [comment]
I disagree, the borders on the wedge and flat canopy blocks are already really thick. If the tetras had a border too, the canopy as a whole would suffer from reduced visibility.
In a similar vein though, a glass hepta to complement the tetra would be greatly appreciated

**Comment by StarrKiss** [comment]
> I disagree, the borders on the wedge and flat canopy blocks are already really thick. If the tetras had a border too, the canopy as a whole would suffer from reduced visibility.
> In a similar vein though, a glass hepta to complement the tetra would be greatly appreciated

What about an option for both borders and unborders? At least tsuna should make the wedge canopy and the tetra consistent

**Comment by Aiwii** [comment]
I agree if the boarders are reduced to half their width so adding borders to the tetra would make no conceivable difference to what we have now. The added consistency between the design of the glass canopy will make a good touch.
Should add that getting a square version of the glass tetra like the corner brick would be epic

**Comment by ProPeach** [comment]
More options is always nice, I agree there. Thinner borders would be brilliant, but I think that would mean that the transparent half wedge would also need to be thinner and it's placement grid even smaller. If that were possible I'd be very happy, especially if there were a rectangular shape to go alongside it.

Speaking more broadly though a thinner border on all canopy shapes would be the best bet, as that could mean all the pieces could start out as 0.25m bricks rather than the current 0.5m. It doesn't sound like much of a change, but that alone would be a *huge* improvement.

**Comment by ExodistSKY1** [comment]
I like the idea of thinning the borders

**Comment by tsunamayo** [comment]
We now have border and borderless version. Thanks
