### ISSUE TITLE
[Dev Asks] Feedback on basic walking mode

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#2620]
Okay so it seems we have quite a few issues / unpolish going on with the normal walking mode.
I guess we never really took care of that because I guess people use anti-grav a lot (I certainly do, and just never walk), but newcomers dont and they run into problem.
So to all the experienced player here, if you could switch back to normal mode for sometime and tell me whats wrong according to you! Thanks!

**Comment by Kaiser-Indrasil** [comment]
Heh, "they **run** into problem." Get it? Because it's a walking-related issue. Haha! ... I'm gonna shut up.

On a serious note, there's 2... three main issues with walking right now:
- feels like the character is sliding a bit after stopping. Moving needs to be more snappy.
- animation speed doesn't change or slow down along with moving speed. Stride should look different than stroll.
- The sound of the steps are super loud (we need them toned down a lot or an audio slider in the settings for them) and they don't sound natural. Take a few steps on different surfaces like grass, water, wooden floor, and metal, and listen closely to how they sound when you stroll, stride, and run on them.

**Comment by StarrKiss** [comment]
There is delay when pressing the walk button that shouldn't be there, makes it feel sluggish.

**Comment by ExodistSKY1** [comment]
-When standing on an uneven surface you tend to slide/walk down as opposed to your character compensating. (Im thinking these animations will be similar to mini-mechs as well?)

-We use the 6dof because its easy to build and maneuver, hopefully in gravity on survival this will be taken out. 

-Smooth transition between walking jogging and sprinting would be nice (would be cool if player had a weapon it would change this movement look slightly!)

So far this is what I have come up with I will be paying attention more from now on

**Comment by FlyingDebris** [comment]
I think the "snappy movement" as mentioned previously is pretty much the biggest thing I can think of, but personally I think the actual motion involved is pretty good. I remember booting up the game for the first time since the overhaul however long back, and the first thing I noticed right away was how it actually felt pretty good.

**Comment by ZachZent** [comment]
The problem I have is just how inconsistent it is. The jump height seems to be super small or sometimes launches you into space. The walking speed can still be changed with [ and ] and (imo) the perfect walking speed is between two speeds. Walking on angled surfaces is a crap shoot at best.

I made an old post a few months ago
https://github.com/tsunamayo/Starship-EVO/issues/1784

1. Lock in a walking/sprinting and jumping speed. Don't let people change it like one does with anti-grav. In the future there can be say "running boots" to increase speeds. This will also help with the animation
2. Remove the jetpack movement option. Make it a suit item/option when survival is added. It really doesn't have any good use right now
3. This is more of a pet issue but related. Tone down the idol animations. They shoot off one after another when standing still with no break

**Comment by tsunamayo** [comment]
Yes I also noticed the jump issue. Walking on angle surface is actually very hard to because of the way the collisions system works, this collide badly with moving entity that are supposed to push you...
Thanks all, I have quite a hefty list already...

**Comment by CurioInventorium** [comment]
As a newcomer to the game I found the lack of a crouch ability to be awkward when building. I'd have to switch to 6dof just so I could angle myself correctly to add blocks to the underside of something.
So maybe have crouch and crawl as options. Or something akin to the way a car mechanic will be on their back when working underneath a car.
