### ISSUE TITLE
[BUG] Moving between Gravity Fields on a Ship in Lightcruise Dumps the Player

### ISSUE THREAD

**Issue by Kadzar** [tsunamayo/Starship-EVO#2674]
### Short Description of the issue:

When walking around a ship moving at lightcruise, a player trying to move from one gravity field to another will immediately be left behind.

### Steps to reproduce the issue:

Board an AI controlled ship with multiple gravity generators (such as the Kuroshio), try to pass the border between two gravity fields of the ship as it travels at lightcruise, immediately get dumped behind. (Will probably also work to use a ship traveling at lightcruise on autopilot, but I haven't tested that yet.)

EDIT: Confirmed. It happens with ships traveling on autopilot as well.

### Environment
- Starship EVO version: 20w29b
- Graphics Card: NVIDIA GeForce GTX 1080

### Additional information:

![20200715223237_1](https://user-images.githubusercontent.com/66035211/87624065-678b8600-c6ec-11ea-8fd3-c267322860fd.jpg)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/4929174/output_log.txt)

**Comment by greyseer** [comment]
Was going to submit this as a bug, but found that this already existed here.

Can confirm. Player is ejected from the ship and the ship (apparently) continues forward. This seems to happen when the player leaves a gravity field, period, regardless as to whether there is another field right next to it. It also happens if there is a gravity field overlap, too.

**Comment by tsunamayo** [comment]
@Kadzar This bug was fixed a few patch ago in 21w02c (still in experimental)
