### ISSUE TITLE
Copy-Paste Functionality Requested

### ISSUE THREAD

**Issue by godsgopher** [tsunamayo/Starship-EVO#2793]
At present there is no way to Copy and Paste an existing feature repeatedly onto a building project. This is a major issue when you wish to repeat a complex object with many parts like a turret. At present every item on the ship has to be laboriously recreated if you want more than one of them. 

Uses.

Greebling surface common surface features onto a hull.
Building common internal features such as beds, chairs, doors etc...
Building Turrets and other multipart logic systems like sliding doors.
Repeating major structural features used on "Faction" ships. 
Creating and pasting complex decal patterns onto a ship or station hull. At present these have to be hand created every time.
Moving ship features because of hull changes during the building process (Woops bathroom is in the wrong place now)

Frankly this is a speed issue and a frustration issue. Starship EVO is an amazingly fun game. But building the same complex feature again... and again... and ... well you get the idea. Is NOT FUN. We do not enjoy repeating ourselves. Once we build something we should be able to rebuild it without spending the original five hours we took to do it the first time is utterly demoralizing and it means we do sub-standard work in the name of expedience. 

Oh... and regarding things like turrets, it would also be nice to be able to blueprint them and then add them to a different ship. Turret design is one of the more iconic features on a faction ship style! This means we need a way to link two separate objects into one object.

**Comment by PFSCommissar** [comment]
like many others from SE, I think copy/paste is the #1 thing that I miss most when coming over here. I ran into this when working on my latest ship:

![image](https://user-images.githubusercontent.com/67161181/90989429-b63c0380-e567-11ea-86b3-216557c621e3.png)

You can see here that the dorsal turrets are all the same model. It got very tedious while building to constantly fly back and forth and ensure that everything looked the same. In fact, I had must less motivation to do this after, and opted for much simpler ventral turrets.

In SE, I used copy/paste to make custom turrets and line my ships. It was also immensely useful when loading a ship full of missiles. As I understand it, in SEVO the idea has been tossed around that we may build our custom missile models. If that's the case, copy/paste will be a necessity if we are to ever build missile boats and not just strap on or two onto our fighter wings. 

I understand the idea of keeping away trolls, but I can't remember copy/paste trolls really being a problem in SE. I will grant that I never played multiplayer much, but I would think admin controls or max grid sizes could fix any issues that might arise. Some people like myself never really play a game like SE or SEVO with others. We are only there to build, upload, and move on to the next one. So on behalf of those players, this feature would be a great boost to our creativity.

**Comment by Drillz007** [comment]
i support copy and past for the game and if they only argument against it so far is that it will impact performance because it will make it easier to repeat complex designs... well a determined person will do it anyways i know i have build many doors by hand just cause its more fitting for the design than the standard sliding door block (not saying the design is bad) it also is a bit of human fear in with it though i would rather a thick door that can take some fire then a simple door that can easily be bypassed

**Comment by tsunamayo** [comment]
@5URG3 thanks for the detailed explanation - I think I will do this. I could do something more streamlined but again that would be too risky - it would give the impression that this thing could be valid substitute to blocks. Also yes I would give a copy/paste tool with a stretchable box.
I would also have to improve the blueprint system with custom folder for easier navigation.

@PFSCommissar it is not trolls, a lot of people will be genuine it their use.
@Drillz007 no. Almost all the massive ship I saw had no interior, for a reason. With this you will be able to spawn massively detailed generic corridor and room in no time, and people will do it for sure.
FYI your custom door wont be compatible with crew and air tightness when those features will be implemented (if ever), it also make the game lag more collision wise (rendering has now no impact since the latest patch though)

**Comment by BrickMacklin** [comment]
For what it is worth I have added detailed hallways to my interior and have not had a performance hit

**Comment by tsunamayo** [comment]
@BrickMacklin interesting to hear given the size of your ship, how detailed they were? Is it on the last you sent me I dont remember.

**Comment by BrickMacklin** [comment]
Nope I have been hard at work on the interior. It utilizes a good combination of blocks and bricks. 

This hallway spans roughly 120 meters. 
![20200823194118_1](https://user-images.githubusercontent.com/37836252/90991679-138c8080-e579-11ea-9a73-9eed53f45f5e.jpg)
![20200823194140_1](https://user-images.githubusercontent.com/37836252/90991684-23a46000-e579-11ea-9949-a9c06d9fdfcd.jpg)

I will be making more like this that lead to other rooms.
![20200823194130_1](https://user-images.githubusercontent.com/37836252/90991689-28691400-e579-11ea-8d77-33b5241933da.jpg)

There's also the two main airlocks
![20200823194158_1](https://user-images.githubusercontent.com/37836252/90991697-361e9980-e579-11ea-9eeb-b06156f26065.jpg)

And my ODST Pod bay
![20200815135217_1](https://user-images.githubusercontent.com/37836252/90991711-4898d300-e579-11ea-9484-03559f0c8f73.jpg)

Visual of the hallway length
![image](https://user-images.githubusercontent.com/37836252/90991753-7d0c8f00-e579-11ea-8a92-659fd2e013b0.png)

Copy and paste would have made this a lot easier. But I'm making it without it. Just a lot longer. Committed to seeing the ship through. And then I have two others just like it to work on.

**Comment by tsunamayo** [comment]
@BrickMacklin amazing! Those interior are legit block interior, my fear is that instead of doing them like that you would use brick based prefab that contains 100x more geometry. And lets face it people would totally do this with a prefab / copy paste... Thats why I think I cannot skip the PCU implementation.

**Comment by BrickMacklin** [comment]
Thanks! I would much rather do it with copy and paste. It would save me several hours. But if I did it and the bricks caused a performance issue I would immediately remove them and find another way. I am doing my best to utilize both to maximize performance. There are already plenty of bricks on the outside detailing and bridge has a ton of bricks. 
![image](https://user-images.githubusercontent.com/37836252/90991976-da551000-e57a-11ea-912d-26ad107e5fc4.png)


Is there away that we could try a copy and paste with both to see what the performance hit would actually be?

**Comment by tsunamayo** [comment]
yes I will do a dirty implementation just to check the impact, on a special build. I just want to finish that medbay update, I am near the end of that.

**Comment by CaptainKronos** [comment]
@tsunamayo this going to be for all to test, limited to certain people, or just a devbuild for you to test?

**Comment by Aiwii** [comment]
#2796

**Comment by BrickMacklin** [comment]
@tsunamayo Medbay sounds like so much fun! Looking forward to it, I'll need to build one now. Regarding the linked post I loaded that mansion into the game. Allegedly 31.5k all bricks. Not a performance hit to speak of.

**Comment by Starwhip** [comment]
I don't know if anyone has explained the PCU system yet. The short, less technical definition is that a server has a number value at which no more blocks can be placed, and while hull blocks have a value of 1 PCU, functional blocks like cargo containers, refineries, thrusters, etc have higher costs depending on performance impact. Players/Factions of players can only own so many blocks in the world.

Here's a post from a developer of Space Engineers explaining basically the same thing.

_PCU (Performance Cost Unit) Limits are the next iteration of block limits. Its purpose is to keep server performance in a more effective way than just limiting block types. Every block has its own defined PCU value, which says how much performance impact a block has under full load (when all its systems are activated). More PCU, more performance heavy the block is. PCU can be defined per world, as a pool, which can be used for building. This pool is then split per player, per faction, or global. Limits per faction are also a new feature introduced in this build. Please note, that you can change the default PCU limits in the Experimental mode._

**Comment by Servomotor** [comment]
I am posting this for those who may not understand geometry calculation in games. 

Tsuna is well aware of all the various uses for copy paste. He fully comprehends how useful it can be, but he also understands how it allows people to "spend polygons" quickly, which is the crux of the issue. 

As I stated previously I would love copy paste myself and have championed for it before, so I am not arguing against it, but rather trying to help others to understand Tsunas dilemma. 

We can not compare Starship Evo to Space Engineers or Empyrion. Both of those games use blocks that are 64 to 128 times larger than the brick system in Starship Evo. If you made a giant detailed ship in Space Engineers or Empyrion, it still pales in comparison to the detail you can make in Starship Evo.  Outside of the observable proof of this, you would not be here if it were not for bricks and rotor/rails etc. Starship Evo allows for unprecedented amounts of detail. But with great power comes great responsibility, sadly when it comes to video games no developer that has ever existed, nor any game that has ever existed has had a player base who exercised this responsibility....in fact its the opposite. 

This game is Francois livelihood. Its how he pays rent, how he provides for his family. how he eats, how he keeps a roof over his head, and how he funds this game. If we all want him to continue to do the amazing work he has done, we have to allow him the freedom and flexibility to do things as only he can understand. Its one thing to present an idea to him and another to keep pushing him for something he knows will not help the game. 

That being said. Attached is a BASIC understanding of polygon geometry used in games. I am not 100% sure what kind of system Tsuna is using (full voxels, or hybrid voxels), but this should help those who do not understand how amazingly and exponentially fast bricks add up in polygon count. 

My goal in this post is not to point fingers, it's not to incite, it's only to help shed some light for those folks who may not understand how fast bricks can cripple this game if they are allowed to get out of hand. 
![poly count tsuna](https://user-images.githubusercontent.com/65745916/90996301-f6a97a80-e583-11ea-8a14-aa28ecf64543.jpg)

**Comment by ultrak2k** [comment]
h

**Comment by AlienXtream** [comment]
i think instead of restricting what players are permitted to do you should instead warn them. the "PCU" system or "build budget" as i would call it is a good way to limit "damage". so, for instance, a clipboard can be limited to the volume of one large block (which is a compromise im sure many would be in favour of). on top of that some means of determining "complexity" of the selected area. the most basic i can think of would be to count the total verts or faces the region has. this is fair enough but i suggest some other things to limit over use while also maintaining creative freedom. the biggest problem you fear is performance yes? well, who does rendering performance affect the most? the client. so, rather than out right preventing overuse put in place "guard rails". 

1)warn players of large creations before loading them in and give them the option to cancel the load.

2) similar to SE, allowing singleplayer games and servers to define their own limits

3)warn players when they are getting close to the "build budget" limit

4)when spawning ships for NPC's from workshop content (assuming this will be a feature down the line) have a hard coded limit of the size and complexity of ships that can spawn. for instance say you have 3 classes of ship that spawn randomly (small, medium and large) a large ship is defined by its size and its complexity or "build budget" is set to something reasonable for that class. same with small and medium.

5)having admin/debug options to ignore these limits in the debug menu but still provide the HUD warnings.

these things then mean that any "lag" the player has from overdoing it is their fault BUT they are adequately informed of the potential impact beforehand.

**Comment by 5URG3** [comment]
Regarding PCU:

In Starwhip's comment above there is a direct quote from KSWH regarding PCU in SE so I won't explain it again unless you need clarification on specifics.

–

Some ideas about PCU in Starship EVO.

First of all, I'm not a game dev, so this might not be of any use, but I had some ideas about limiting complexity to maintain stability so I thought I'd share.

Secondly, PCU is a SE term, and this is not SE. For the rest of this comment I'm going to refer to the hypothetical Starship EVO equivalent of PCU as the Starship EVO Complexity Unit or SECU.

--

I've heard a single Brick of 1m x 1m x 1m requires more system resources than a single Block of the same size. Is this correct?

Each Block and Brick type could be given a SECU value based on:

A: The number of polygons that need rendering.
B: Any features that require additional processing (Thrusters, weapons, grav fields etc)
(C: If it is a brick, a multiplier to account for the additional system resources)

Using Servomotor's information graphic as a guide, here are some examples.

A Cube Hull Block = 12 SECU
A Cube Brick = 12 SECU (x Multiplier)
A Block pipe = 48 SECU
A Brick pipe = 48 SECU (x Multiplier)

Given that a Blocks can cover way more area than a Brick, this system seems like it would naturally incentivise using Hull Blocks over Bricks for the main structure. I also promotes Brick optimisation by rewarding efficiency. Since each individual Brick carries a hefty SECU cost, this should also prevent excessive greebling.

There could also be a flat SECU value added to each entity and child entity to prevent the spamming of low effort entities.

–

Limiting SECU

In SE, PCU can be limited Globally, by player and/or by ship. The maximum PCU can be edited or disabled in Settings during the creation of a new World. It can also be edited or disabled later by editing world settings.

This kind of system would probably also work in SEVO, but you could instead use ship categories to define limits.

Any potential SECU limits would need to be tested by the community, preferably after we have survival. A common complaint in SE is that the PCU limit is too low. Once the community has played Survival for a while, we should have a rough understanding of what the average player needs in terms of ships/bases etc.

Adding a Polygon Count and other useful metrics to the Ship Codex might help source data on average numbers. The Workshop is also starting to pick up a bit, should be plenty of ships to test there soon.

There should also be a way to disable these SECU limits if the player chooses to. I think the best place would be F3 Debug Menu. Disabling limits should have a disclaimer in a pop up window.

–

Regarding the Merge Block

In SE there is a block called the Merge Block. The Merge block is used to fuse two entities into one and, if no blocks aside from the Merge Blocks are touching, split them back into two entities.

Here is a video of the Merge Block when it was introduced:
https://www.youtube.com/watch?v=cEqRgWWzrZA

I would absolutely love a merge block in SEVO, it has many uses, but it is not really a substitute for Copy + Paste.

**Comment by tsunamayo** [comment]
So I finally found a bit of time to work on this, the copy-paste is available in the new EXPERIMENTAL build 20w36c.
You can test it in your construction, I expect quite a few bug at first, and for now it wont work with logic and children entity.

@5URG3 Thanks for detailed explanation. Yes I would have to do something like that.
Yes for the merge block, it might be the way to do prefab, or I might do something more powerful where you build the prefab like a block basically. The big advantage of the merge is that you can select your application point as you want, whereas with the copy paste it is centered.

Cheers

**Comment by BrickMacklin** [comment]
@tsunamayo love it! A few things. Is it intended to not copy the colors and stickers at this time? Can we have a way to orient it on more axis? Right now I need to build a box around what I want to copy so it can be oriented the right way.

**Comment by Calvert4096** [comment]
@tsunamayo you rock dude!

**Comment by tsunamayo** [comment]
We have copy&paste since a while now!
