### ISSUE TITLE
Copy Paste Tool Thoughts

### ISSUE THREAD

**Issue by MrNobodyX3** [tsunamayo/Starship-EVO#2883]
Notes:
- It's un-intuitive with the selection box and where it pastes from
- Tho it seems to stop clipping it still occurs from time to time
- Sometimes it off sets the grid
- Doesn't copy decals
- Doesn't copy paint
- Doesn't copy wire connections
- Doesn't copy logic states
- Doesn't copy children

**My ideas of how it should function**
- Paint the blocks you want to copy
- Painted blocks highlight (paint again to deselect)
- Confirm selection
- Select face to weld from when pasted
- Then paste away
- hold right click (like it is now) to stop

**Future Features**
- Save copies
- Load copies

**Comment by tsunamayo** [comment]
@MrNobodyX3 the paint system could work, except that sometime you have hidden brick. Also it would take a lot of time for large portion. So I dont think it could replace the drag selection.

**Comment by tsunamayo** [comment]
by the way I am not sure to see why it is unintuitive, as copy-paste works the same in windows, you drag your selection and then you are good.

**Comment by ultrak2k** [comment]
hm it seems rather intuitive for me, I've seen much worse copy pastes in other games

**Comment by 5URG3** [comment]
The selection system is inaccurate, but otherwise fine IMO.

**Comment by tsunamayo** [comment]
@5URG3 thanks for the feedback.
Yes it is not clear for now: the basic rule is the clipboard base plane is the first plane you stretch. Which means it will rotate along the vertical axis.
So for now the way you drag your copy selection box will have an impact on how it is built.
For the last point the issue is that you want a different center point than the one currently selected.

I will add way to visualize this so hopefully it will be more clear, and I think I will have to add a way to offset the center.
Of course I will deal with paint and decals. 
And I will add that switch plane key for copy/paste and blocks!
The block that gets copied also is an issue, I will fix it.

Cheers

**Comment by StarrKiss** [comment]
@tsunamayo  You should be able to offset the copy/paste location from the default position by 1/2 blocks in order to surface mount things, as right now, it's pretty annoying to do so.

**Comment by MrNobodyX3** [comment]
@tsunamayo "by the way I am not sure to see why it is unintuitive, as copy-paste works the same in windows, you drag your selection and then you are good."

I just meant it's hard to control where it'll be pasting from and still get everything you want to be copied

**Comment by SirBrott** [comment]
an additional option would be to copy all connected blocks and have the anchor point be where you're pointing. Thus you can copy a group of blocks, place it in the world and then choose an anchor point. This is a workflow that I used in space engineers

**Comment by tsunamayo** [comment]
@SirBrott So you mean you place it in the void, then you pick up some anchor?

**Comment by SirBrott** [comment]
@tsunamayo for an example of what I’m thinking: I build a turret as a new structure and when I copy the turret  I aim at the bottom of the turret where it's going to attach to the ship so when I paste the turret then it's lined up correctly to the ship. Or when aiming at a face of a cube that face is the point that attaches to the ship

**Comment by tsunamayo** [comment]
We now have most features.
