### ISSUE TITLE
[SUGGESTION] coolers and heatsinks

### ISSUE THREAD

**Issue by bruhmoment39** [tsunamayo/Starship-EVO#2916]
### Making small ships is harder if you want a lot of weapons because you need hull blocks just to disperse the heat.

There could be like a cooling block or pipes that disperse the heat out, it would be nice to have something that gets rid of heat other than the hull blocks.

**Comment by tsunamayo** [comment]
Hum no, because they have a big surface heat bonus, whereas large ship dont. 
Cooler would completely nuke the current balance, making ship about who can pack as much system in their design, negating the very reason the heat mechanism was introduced.
=> coolers / heatsink makes the heat mechanism useless.
Thanks
