### ISSUE TITLE
cant get to the game to launch

### ISSUE THREAD

**Issue by DeafeningDragon** [tsunamayo/Starship-EVO#2939]
### Short Description of the issue:
i get 
![image](https://user-images.githubusercontent.com/71092799/92770198-5020f000-f35f-11ea-8335-f74e8a00051a.png)

...

### Steps to reproduce the issue:
just luanch the game after installing the game
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
as you can see i didnt get the above mention
[Untitled document.docx](https://github.com/tsunamayo/Starship-EVO/files/5203627/Untitled.document.docx)
  
![image](https://user-images.githubusercontent.com/71092799/92770689-d3424600-f35f-11ea-8112-dad7c7030308.png)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Hi, sorry to hear that!
So it seams it more an issue on the steam side, could please try to re-install the game?
Check out a guide here:
https://appuals.com/fix-application-load-error-30000065432/

What is your OS?

Please check some related issues:
#2899 (<- it was linked to his anti-virus software)
Thanks

**Comment by DeafeningDragon** [comment]
i have reinstalled the game 4 times and it has nothing to do with my ati virus all i need is the missing files and then i should be fine but i cant get the game to get them and steam says that it got all of the files that it needed. so what do i do next?

**Comment by tsunamayo** [comment]
Hi, it is a steam related issue.
The file are created when you launch the game the first time, so it is normal that you dont see anything at this point.

Could you try this:
https://windowsreport.com/application-load-error-65432/#:~:text=4.-,Turn%20Off%20Antivirus%20Software,Steam%20might%20fix%20the%20issue.&text=Then%20add%20the%20Steam%20and%20game%20folders%20to%20the%20exclusion%20list.

https://appuals.com/fix-application-load-error-30000065432/

Thanks

**Comment by DeafeningDragon** [comment]
hi so i have tried everything and have gotten no where is there any chance that you can sen me the missing files or the complete game that i paid for.

**Comment by DeafeningDragon** [comment]
so seeing as how you dont want to send me the files or the full game i will be requesting a full refund of this game as you are no help to getting this fixed

**Comment by tsunamayo** [comment]
@DeafeningDragon , I am sending you the files as you want, but that is not the problem.
Those file are automatically created when you launch the game for the first time.
The problem is that steam messed up with something, so you cant launch the game.

Please understand that this is a Steam issue, not a Starship EVO issue. The correct support would be the Steam support...
[Moonfire Entertainment.zip](https://github.com/tsunamayo/Starship-EVO/files/5211916/Moonfire.Entertainment.zip)

Did you tried to deactivate your antivirus during the install / launch?
Thanks

**Comment by DeafeningDragon** [comment]
nvm im just going to get a refund for the game

**Comment by tsunamayo** [comment]
@DeafeningDragon sad to hear that but if you tried your best and the issue is not fixed then dont hesitate to get a refund.
I understand your frustration but I have done my best, please keep in mind that this is not a Starship EVO issue but an issue with your Steam Client. As the developer there is little I can do, I have not control on how Steam is working.
Thanks
