### ISSUE TITLE
Copy&Paste "Alien Code"

### ISSUE THREAD

**Issue by MrNobodyX3** [tsunamayo/Starship-EVO#2969]
### Short Description of the issue:

Constant error after pasting
...

### Steps to reproduce the issue:

I believe this occurred when trying to place a block on the mirror plane with a pasted selection

...

### Environment
- Starship EVO version: 20w37b
- Graphics Card: GTX 1070 ti

### Additional information:

https://youtu.be/-DanG7i219w

**Comment by AlienXtream** [comment]
i have no idea what i just witnessed but i assure you im NOT responsible XD.

in all seriousness though have you tried reloading the game and see if it persists?

**Comment by Cheackraze** [comment]
looks like the same issue I'm having here https://github.com/tsunamayo/Starship-EVO/issues/2936 I don't think it's rotating that's the issue any more, I think it's placing things that have an animation tied to the placement, since it seems to happen with weapons/attachments/prefab doors and a few other things

**Comment by tsunamayo** [comment]
Okay I see, there was some serious message spawning here. Thanks
