### ISSUE TITLE
Symmetry not working with hinges

### ISSUE THREAD

**Issue by sjpateys10** [tsunamayo/Starship-EVO#2974]
###symmetry not working for blocks paced on top of small  hinges. haven't tried larges.

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by AlienXtream** [comment]
this is intentional. hinges work by creating a child grid that is rotated. this is true of all other moving parts like pistons, sliders and rotors. this is done because calculating where and what should mirror is no trivial task and it uses the grid to calculate it. because of this it does not look at any other grid and only the grid you are working on. mirroring will probably get a bit of a rework soon some level of child mirroring MIGHT be implemented but even if it is dont expect to be able to mirror complex moving systems as if any form recursive mirroring is done it would probably be only 1 or at most 2 recursions. any more than that and the calculations would become noticeably slow on even small ships as it has to check every time you update the grid for child grids and that takes time.

**Comment by tsunamayo** [comment]
Yes @AlienXtream is correct - not really a bug atm. It would be a pain to add and a bug nest, but it would make a lot of sense, especially with things like mech... Thanks
