### ISSUE TITLE
[BUG] Decals disappearing again 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#2981]
### Short Description of the issue:
sometimes when placing decals on child entities they will disappear 
...

### Steps to reproduce the issue:
try putting lots of decals on a child entity I don't know if that how i did it but it seems like it 
...

### Environment
- Starship EVO version: 20w37a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:

![ezgif com-optimize (5)](https://user-images.githubusercontent.com/56371294/93670768-a45c5c00-fa52-11ea-9f40-fc33a8cde780.gif)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5250108/output_log.txt)

[ICD-1421-01.zip](https://github.com/tsunamayo/Starship-EVO/files/5250109/ICD-1421-01.zip)

**Comment by Servomotor** [comment]
Also referenced here. #2963

**Comment by NEURALDELVERM** [comment]
I too have recently had this issue. I don't think it is solely related to child entities, as I have had it happen while using the mirror tool, and even without. This time it has happened on a child entity, though. It could be related to garbage collection, occlusion culling, or something related to  rendering like that.

The issue resolves itself when reloading the world, and is likely caused by having it open for a while. A lot of bugs I see are directly related to how long the session has gone on, which is why I pointed out garbage collection. The cache could be overwriting old data, but I don't know anything about gamedev so excuse my uneducated guesses.

![image](https://user-images.githubusercontent.com/23009112/94614627-5407aa00-025b-11eb-9c14-de99d36bdf33.png)

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5301797/output_log.txt)

**Comment by NEURALDELVERM** [comment]
I lied, restarting the world does NOT fix the problem- it simply persisted as soon as I tried to add another decal. Here is another log.
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5301857/output_log.txt)

**Comment by Gliese-832-c** [comment]
Sometimes it happens to me too. For me simply reloading the world (the most reloads I've had to do in a row so far are 2.) helps, though.

**Comment by tsunamayo** [comment]
@TIKIRobo Hi, sorry to necro this, do you had this in recent update too? Thanks

**Comment by Servomotor** [comment]
I have not seen this bug in a long time and have not seen it with the recent update.

**Comment by TIKIRobo** [comment]
@tsunamayo i haven't seen this bug recently

**Comment by tsunamayo** [comment]
Okay thanks both, glad to hear that!
