### ISSUE TITLE
Character cannot leave a 50m~ spherical area without teleporting back to 0m point

### ISSUE THREAD

**Issue by Regnion** [tsunamayo/Starship-EVO#3012]
### Short Description of the issue:

Rarely, I will be building around a ship just fine. Upon trying to back away to look at it from a distance, at normal speed, I will suddenly be yanked back to a random but arbitrary point near the ship. I can move approximately 50-60 meters away, in a spherical area, before I am suddenly yanked back to that point. If you try to fly out of the area, the ship will vanish, yet function. If you "get out" of the invisible seat, you will once again be immediately and instantly placed back at that initial point within that circular area.

...

### Steps to reproduce the issue:

Unknown. Appears to happen rarely, randomly, but on more than one occasion.

...

### Environment
- Starship EVO version: 20w36B
- Graphics Card: Nvidia GeForce GTX 970

### Additional information:

Gif of bug [here](https://gyazo.com/bb4834b79a3240da491b2d15fff2d03a)
(too big to put in a zip, 1min gif)

**Comment by StarrKiss** [comment]
@Regnion  that is a very out of date version- switch the branch to experimental

**Comment by Regnion** [comment]
> 
> 
> @Regnion that is a very out of date version- switch the branch to experimental

Experimental is the dev branch, the live branch shouldn't be "out-of-date" when it's literally the one meant for use.

**Comment by Gliese-832-c** [comment]
It's the one that is usually confirmed to be stable (as we can see, it's not always the case). The experimental branch is just where Tsuna puts new stuff to test out, and once he is sure that it works, he pushes it to the official branch. Most of the time it works fine though. In fact, I have heard, that the experimental branch is actually more stable. Just try switching to that and see if it fixes the bug.

**Comment by tsunamayo** [comment]
@Regnion Hi, could you please send me the output.log? Thanks!

**Comment by Regnion** [comment]
@tsunamayo I'm sorry, I had tried attaching it when I made the post and thought it had worked. I've since played the game and the log is no longer reflective of this incident.

Restarting your game will fix this bug.

**Comment by tsunamayo** [comment]
Yeah I think there was another issue that basically broke your game. The teleport was just the origin recenter not doing its job correctly, but it was because the game was broke. Tell me if you ever see that issue again! Cheers

**Comment by greyseer** [comment]
I have seen this happen as well, but I have yet to try to focus on reproducing it.

Basically, after either a long play session, or a play session with a lot of elements (multiple ships with a high number of blocks / bricks), the game will display certain anomalies: 

- Sometimes blocks will vanish: their bounding outline and collision detection is still there, but they no longer render. They can be destroyed and re-created, and sometimes the re-creation allows them to be seen again, but sometimes it does not.
- Sometimes decals will vanish: same as with blocks, there is a visible outline, but no actual visual rendering of the element.
- Sometimes the player will rubber-band back to an origin point per the original bug description.
- Sometimes certain bricks will become "indestructible". They do not ever "select" and are not recognized by the engine, despite being rendered correctly.
- Sometimes spawning in a new entity will spawn in an incomplete version of that entity.

A restart of the game usually clears these all up. However, I have noticed that one has to fully exit the game entirely in order for the issues to be resolved. Leaving the world, going back to the title screen, and then re-entering the world usually allows some combination of these issues to persist through to the new gaming session.

Note: all these issues cannot be reproduced reliably. They just happen after a certain threshold is reached, which is why I have not submitted a bug report. If I can pinpoint a consistent method to reproduce them, I will submit a bug report for each that I am able to reproduce. Until then, I usually just restart the game.

Also of note: I have not yet had an opportunity to see these bugs manifest in the latest build.

**Comment by Kaiser-Indrasil** [comment]
Sometimes I had this bug occur on a fresh world. I don't have the slightest idea what's causing it.

**Comment by tsunamayo** [comment]
@greyseer Yeah it means the game is broken. What happen after the game is broken is of little use to me, what I really need is the log file as soon as you notice something strange, and a description of what you did just before it broke.
It is okay if you cant reproduce them, just the log file would be of great help!
Cheers

**Comment by greyseer** [comment]
@tsunamayo I will keep an eye open and try to capture the log as soon as I notice oddities!
