### ISSUE TITLE
[Dev needs helps] Testing Kaiser's Turrets

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#3051]
Hi guys,
So I am having a hard time reproducing Kaiser issue with turrets.
His ship seems to work just fine on my side, but the turret dont work for him.
If some of you guys could do the following:

1) load the ship
2) enter commands
3) spawn a npc with F8
4) tell me if turrets works or not!

I see this:
https://youtu.be/8zhYVdo_LB0

The blueprint:
[SoE.Astero.-.turret.test.41C.zip](https://github.com/tsunamayo/Starship-EVO/files/5344566/SoE.Astero.-.turret.test.41C.zip)

Cheers

**Comment by Asnro** [comment]
Tested with a few npcs, can confirm turrets are stuck. Beam turrets only started working on auto and direct yoke control after removing as many obstructions as I could find:

https://cdn.discordapp.com/attachments/762428614833602560/763562746615693332/unknown.png

https://cdn.discordapp.com/attachments/762428614833602560/763562788517445662/unknown.png

Turrets could not rotate, but did fire at npcs whenever one happened to cross their sights.

However, accessing hinges/rotators directly (setting angle in F menu) did work despite obstructions. After leaving controls turrets also returned to resting position from manually entered angles despite not being able to move while in control.

I remember turrets having a samplified collision model, could something be interfering with that?

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5344791/output_log.txt)

**Comment by CurioInventorium** [comment]
I've found with my own turrets that when they collide with other parts of the ship they stop completely, but it seems that the angle I'm turning them still increases. So that I have to move the mouse back the same distance after they stopped moving, before the turret will move again.
And I have had a turret get stuck on my Triavrium ship during development (It's on the workshop). I had to spend a little while in external view with tab toggled so I could view all round the ship without moving. It was like I was unwinding a twist on the turret until it moved again.

It's like the rotator or hinge angle is allowed to carry on moving/changing after the turret has locked.
You get a similar effect when rotating objects in blender that have rotation limits set.
Example;

- I set a -45 to 45 degree rotation limit on a object.
- I then rotate that object, with the attempt to go past 45 degrees and see it stop at 45 as intended.
- But if I look in the info panel for that object, I see that I've gone past 45, to say 60, due to just moving the mouse.
- So when I go to move the object back to somewhere between the limits, there's a small delay while the angle is reduced to the maximum limit again before allowing the object to rotate.
- 

It could be that Kaisers turrets have reached an angle limit due to collision, but the rotators still record changes in their angles as the mouse or view changes. So the turret could look like it's sitting at 120 degree vertical, but the rotator is actually at 2034 or something and needs to be unwound to below 120 again.

Hope that all makes sense, I've not long woken up and my brain is still fuzzy.
If there's a way to toggle viewing what angle the rotator or hinge is at, this may prove or disprove my hypothesis.

**Comment by Battlepixel** [comment]
> However, accessing hinges/rotators directly (setting angle in F menu) did work despite obstructions. After leaving controls turrets also returned to resting position from manually entered angles despite not being able to move while in control.

I have the same problem with my turrets:

As you can see in the picture, they no longer align themselves to the target but are mostly stuck. They only fire when the target flies through the line of fire. I haven't come to the test for a long time, but the turrets of the attached blueprint were still working 2 months ago
![Starship EVO_2020_10_08_22_05_22_232](https://user-images.githubusercontent.com/43222403/95508267-ff7ad200-09b2-11eb-87af-7a347b575fd6.jpg)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5351097/output_log.txt)
[Lancer94.zip](https://github.com/tsunamayo/Starship-EVO/files/5351099/Lancer94.zip)

**Comment by WILDCATreactor** [comment]
> I've found with my own turrets that when they collide with other parts of the ship they stop completely, but it seems that the angle I'm turning them still increases. So that I have to move the mouse back the same distance after they stopped moving, before the turret will move again.
> And I have had a turret get stuck on my Triavrium ship during development (It's on the workshop). I had to spend a little while in external view with tab toggled so I could view all round the ship without moving. It was like I was unwinding a twist on the turret until it moved again.
> 
> It's like the rotator or hinge angle is allowed to carry on moving/changing after the turret has locked.
> You get a similar effect when rotating objects in **Blender** that have rotation limits set.
> Example;
> 
> * I set a -45 to 45 degree rotation limit on a object.
> * I then rotate that object, with the attempt to go past 45 degrees and see it stop at 45 as intended.
> * But if I look in the info panel for that object, I see that I've gone past 45, to say 60, due to just moving the mouse.
> * So when I go to move the object back to somewhere between the limits, there's a small delay while the angle is reduced to the maximum limit again before allowing the object to rotate.
> 
> It could be that Kaisers turrets have reached an angle limit due to collision, but the rotators still record changes in their angles as the mouse or view changes. So the turret could look like it's sitting at 120 degree vertical, but the rotator is actually at 2034 or something and needs to be unwound to below 120 again.
> 
> Hope that all makes sense, I've not long woken up and my brain is still fuzzy.
> _If there's a way to toggle viewing what angle the rotator or hinge is at, this may prove or disprove my hypothesis._
> Edit: Just spotted Asnro's comment about pressing F to view the angle on the rotators. Although that is from a recent update that wasn't released when I was building my ship originally.

You can reproduce this on any turret with snag points somewhere in its rotation, worse, vertical and horizontal snags wind and unwind separately, so you could unwind a horizontal snag but still have one on the vert axis.  I generally find jiggling the mouse to be more effective than trying to "unwind" a snagged turret.

**Comment by tsunamayo** [comment]
Okay thanks for the feedback.
To give you an update I understood issue with the Kaiser turrets, it was because he was using clipping with children entity a lot, with several children entity build on top of the turret axes. I now take correctly this into account, but his design will be stuck as it will detect the collisions...
@Battlepixel I will have a look into this.
Cheers

**Comment by tsunamayo** [comment]
@Battlepixel issue fixed for 20w45b. Thanks
