### ISSUE TITLE
[Bug] Cannot delete logic links that lead to Query Gates

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3067]
What the title says. I can link the mechanisms to Query Gates but I cannot unlink them afterwards.
Version 41C

![image](https://user-images.githubusercontent.com/63756057/95810939-10f11080-0d0a-11eb-839a-7d7ab8a70061.png)

**Comment by tsunamayo** [comment]
Fixed for 20w42a. 
Btw on your turret, I now deal correctly with multi children entity. Unfortunately it means they are stuck because you used clipping! Btw children clipping is also fixed, it wont impact your hull (just the turret), but you wont be able to use it further... Sorry mate, but that is great to have guy like you to push the envelope, that make the game progress!
Cheers

**Comment by Kaiser-Indrasil** [comment]
Yeah, as long as it leads to the overall improvement of the game, I'm willing to make sacrifices like these.
Thanks for appreciating me
