### ISSUE TITLE
Unstuck message keeps appearing every five seconds.

### ISSUE THREAD

**Issue by N3XTGEN82** [tsunamayo/Starship-EVO#3183]
If you just stand still for a few seconds it keeps popping up. Even sometimes when i am not stuck it keeps showing up and comes up multiple times. I feel it should be a small message that only shows once less frequently and maybe only once per time you open a world. So if you log in it shows up once and not again until you quit and re enter or something.

**Comment by tsunamayo** [comment]
Hi, it should only appears when you are stuck. Could I ask you something?
You go to a place where it happens when you simply stand still.
Then quit the game, zip your character save and send it my way - this way I will fix the issue.
C:\Users\[YOUR USERNAME]\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters
Thanks

**Comment by N3XTGEN82** [comment]
Nvm, it seems to be fixed since i last played
