### ISSUE TITLE
[Suggestion] Wedge Thin Tile

### ISSUE THREAD

**Issue by chacalik** [tsunamayo/Starship-EVO#3213]
### Short Description of the issue:
As the picture show, I would suggest wedge thin tile, that can be very useful for detailing.

![image](https://user-images.githubusercontent.com/4794243/98875939-fb335000-245b-11eb-9de0-8747d8a643f9.png)

It must be sizeable aswell, since it sizes only through X and Y, not Z.

**Comment by Sebateses** [comment]
Yes please, would be awesome. Would be great also if we could get tetras, corners and slopes in both half small block and thin tile not sure what the sizes are in a numerical sense.

**Comment by tsunamayo** [comment]
@Sebateses nope, thats why I dont want to give too much as after it is a never ending creep toward more and smaller shapes...
That is why I dont like the shape, after people would just want more of the tiny one...
Again thats the kind of shape that will better as mod for when I work on that. 
So I guess it will have to wait for mod support! (it is time consuming to make them because of the ollision shape logic)
Cheers
