### ISSUE TITLE
[CRASH] adding blocks to the front of ship crashes the game

### ISSUE THREAD

**Issue by Vicomt** [tsunamayo/Starship-EVO#3226]
### Short Description of the issue:
adding 32m scaffold/framework blocks to the frontmost part of the ship crashes the game

### Steps to reproduce the issue:
open the supplied world, add two sticks of framework/scaffold (whatever the block is called) to the front of the ship, causing it to recalculate it's extents.
watch it crash.

have we hit some kind of volumetric limit?
if so, can you tell us what the limits are?

### Environment
- Starship EVO version: 20w36b
- Graphics Card: GTX1070
- 32GB RAM

### Additional information:

[Vic Odyssey.zip](https://github.com/tsunamayo/Starship-EVO/files/5542550/Vic.Odyssey.zip)
RAM USE WHILE RUNNING ~5.4GB (less than minimum requirement)
[output_log.zip](https://github.com/tsunamayo/Starship-EVO/files/5542551/output_log.zip)

**Comment by tsunamayo** [comment]
Hi, @Vicomt how big is the ship? Thanks

**Comment by Vicomt** [comment]
I'll admit, it's big - but I didn't think it was *that*, it's about 1200x700x350... hang on
![20201115144907_1](https://user-images.githubusercontent.com/7197427/99502771-77a2c300-2975-11eb-9a1f-e505958f1cf9.jpg)

**Comment by tsunamayo** [comment]
Yes I guess you hit a resource limit because of the light texture. Which is weird as you are still at around 50% of the hard limit (1gb for a limit of 2gb) on the GPU side.

I do not set those limit they are from your GPU and Directx11:

https://docs.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-resources-limits
Texture3D U/V/W dimension | D3D11_REQ_TEXTURE3D_U_V_OR_W_DIMENSION (2048)

Resource size (in MB) for any of the preceding resources | min(max(128,0.25f * (amount of dedicated VRAM)), 2048) MB

So the ship is limited to 2048m in length and the texture size is limited to 2048 MB in your case as you have 8gb memory.

So it might be on the system memory side, but you tell me you have a 32bg memory so this is also surprising.

In any case this particular texture will be removed soon, so this problem will be naturally fixed over time. For now I will add a limit to the size so your game dont crash. But you wont have any lights for now... Cheers
