### ISSUE TITLE
[Bug] Moving the mouse in 6dof rolls character

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#3251]
### Short Description of the issue:
Just a quick one as you can see in the gif, simply moving around your mouse up and down can cause the character to roll. This means that you constantly have to correct your roll angle when moving/building outside of a gravity well
https://i.imgur.com/jb1kUNw.mp4

### Steps to reproduce the issue:
Move your mouse up and down

### Environment
- Starship EVO version: 20w47a
- Graphics Card: RX 580

As an aside, I find the new toggle key a step in the right direction, but not a good change overall. 6dof is not a comfortable mode to build in for me due to a few things - 
 - Input lag when rolling - when you take your finger off the roll key, the character keeps rolling for a moment leading to overcorrection 
 - Not being able to perfectly align to a grid easily. This might be a combination of the bug in this post and the input lag, but it's difficult and disorienting to orient yourself to a ship quickly. The old "Align to grid" function in the MMB menu was perfect for this, any chance we could have it back?
 - I suggest that toggling the jetback button (J by default) when outside of a gravity well toggles between 6dof and antigrav (maybe rename Antigrav to ~~6dof~~ or Locked?) It would be an easy way of locking your orientation, with the option to unlock it to perform 6dof manoeuvres

**Comment by Aiwii** [comment]
When I heard about the new toggle key feature I assumed it would let us cycle through all four movement modes I was not expecting automatic flip-flopping between Anti Grav and 6dof, especially when I don't use 6dof and I'm not a big fan of it (feel wise, it's still a great locomotion mode). It would be nice if we still had the option to use Anti Grav even in gravityless environments or at the very least prevent roll and lock orientation in place.

**Comment by Kaiser-Indrasil** [comment]
I agree, the new system feels like 1 step forward and one step back for me.
I also second Peach's suggestion to have the jetpack button toggle between the 6dof and -g modes when the player is beyond a gravity field, be it artificially generated or otherwise.

**Comment by tsunamayo** [comment]
Yeah the auto-roll on look up is perfectly normal, that is why I hate 6-dof. Have you watched a video of Space Engineers? They constantly have to re-align themselves because of that...
Not sure about the suggestion though, what is your use case really? Do you build in deep-space and want an axis lock? 
It is made to make the game simpler for newcomer, this is really something I need to address. 
Thanks

**Comment by ProPeach** [comment]
An axis lock yes, for situations like building in space, flying up to a new ship and orienting to it, staying in the axis of the ice rings of the gas giant etc... I know there's no "down" in space, but when you're around something that obviously has a preferred axis, it's natural to want to stay in that axis without needing to reorient every 20 seconds. The hotkey and autoswitch is a great way to keep it simpler for newcomers, I don't think an axis lock using the same hotkey is any extra complexity, especially as you now show the movement mode in that handy GUI element.

What are your thoughts on the "input" lag/sloppy roll movement and Align to Grid function? They'd really help make 6dof less of a chore

**Comment by tsunamayo** [comment]
I will check for the lag of the roll and fix it. Align to Grid is basically constantly ON, it is the anti-grav mode. Otherwise it dont really make much sense (you align to what?) thx

**Comment by tsunamayo** [comment]
btw @ProPeach you are not a Spengie player? I didnt kept track of who are. I think I am gonna force you (and me) to be a bit more used to 6 dof before doing further change.

**Comment by ProPeach** [comment]
Ah I see, I was talking about the old Align to Grid function in the middle mouse button access wheel that would align you to any grid you're looking at. Using that while in 6dof mode then locking your axis would be a tidy way to permanently lock yourself to a new grid, as it's difficult to cover a whole ship and the area around it in a gravity field to get the anti grav mode to start

I am yes, but either I've just gotten used to how nice not having to use 6dof mode or the SEVO and SE 6dof modes are slightly different in feel, but I really can't get used to it in this game as it currently is. I'm reinstalling SE now to see if I can find some ways to improve the 6dof experience

**Comment by tsunamayo** [comment]
@ProPeach cool keep me posted in term of feel. 
Also there is 6 way of aligning to a grid...

**Comment by ProPeach** [comment]
True, but all grids have a designated up/down to them shown by the codex and ship core. I can't remember there being any problems with the old Align to Grid MMB function, but then again it was a while ago so I could have rose tinted glasses.

The main difference with SE and SEVO that I can feel is the lag when taking your finger off the key which isn't present in SE, their roll rate is a little faster too but I don't think that makes too much of a difference. So hopefully we'll both feel better after that's been taken care of!

**Comment by Calvert4096** [comment]
There's an easy solution that allows both ease of use for new players as tsuna mentions, and choice for experienced players.  Have a hotkey cycle through modes three modes:

1. Auto (default; switches between fixed axis or 6dof based on location or gravity)
2. 6 dof
3. Fixed Axis

That way if new players are happy with the "auto" behavior, they never even have to bother with that hotkey.  If they do care, the option is there.  Maybe add some context sensitivity so that if you're looking at a grid while in "6dof" mode and switch to "fixed axis," the player's up-axis will re-align to whatever grid principal direction is currently closest to the player's current up-down axis.

**Comment by daOyster** [comment]
I just want to add that as a Space Engineers convert to this game, I personally find no problem with how the 6dof movement worked before the past movement update. For most people 6dof movement is very weird feeling at first and takes a bit to get used to since there aren't many games that feature it and thus most people never get used to having to keep track/adjust their roll axis periodically so it feels a bit weird to most.  

Personally I like the new movement toggle button, but as someone that liked used the 6dof mode when building, I don't like how it automatically switches to be aligned the moment you enter a gravity field. For a new player I get that could be helpful in some situations, but as someone who has gotten comfortable with 6dof movement it's very jarring to be suddenly forced to align to a gravity field without any action on my part to trigger it.

**Comment by tsunamayo** [comment]
Okay all, in the upcoming 21w03b you can now select whichever mode you like! Cheers
