### ISSUE TITLE
suggestion: activate 6dof movement in gravity fields

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3255]
the revamp of the locomotion does make locomotion less complex but it still has the issue where there are situations where even though you are in gravity you want to roll side to side, for example, if a ship is sideways/upside-down and you need to get in it without being affected by the conflicting gravity fields so that you can flip it over or disable its gravity. having the bind cycle between the modes or having a second bind for no longer re-orientating to gravity would be helpful. it is also nice to have the ability to stay locked to your previous gravity while in zero g, it makes it easier to keep a consistent perspective while building

**Comment by PFSCommissar** [comment]
I very much agree with this suggestion. The lack of rotation makes building much more difficult and is very irritating. I am now deleting gravity units from ships just so i can work on them.

**Comment by tsunamayo** [comment]
@PFSCommissar Did you played space engineers before? Funny how people coming from SE wants more  6dof and other wants less 6dof and wants to be able to switch to anti-grav even in 0g. I think I will just add a switch between 3 modes in grav, and 2 modes in 0g. Cheers

**Comment by PFSCommissar** [comment]
@tsunamayo i did play SE. If i may, I think it would be best to allow all modes whether in gravity or not. Then people can simply choose what works best for them. There's a substantial community of us former SE players and I think there's probably more on the way, and that's a feature that is very reflexive to us by this point. 

Practically speaking, I think it is much more difficult to work on anything low to the ground like hovercrafts or buildings without being able to rotate, especially if one is to see underneath them. Or for ships there are times when rotation is just the best way to get blocks into certain tight spots. I do understand that tight spots can also be accessed by just hitting F5, but even so some perspectives can be lost when one is constrained to a single orientation.

**Comment by Dwarf-LordPangolin** [comment]
I strongly support this suggestion, for two reasons:

Reason 1.
Tonight was actually the first time in my life I've gotten motion sickness, and it was due to not being able to force the game to stay in 6dof while working in an area where multiple gravity fields overlapped. It wasn't due to moving between two different gravity fields; I've done that before in Space Engineers, and it hasn't given me issues. It was the way the game yanks you from one orientation to another. It's rather disorienting. 🤢 

https://gfycat.com/phonyplasticisabellineshrike

To be clear: the actual walkway itself does not cause this effect, the transition there feels quite smooth and natural.

https://gfycat.com/happydisastrousbass

But as you can see from the first gif, while working on it, the player needs to move into areas that aren't meant to be used during gameplay, where the transition isn't gentle. The forced changes, sometimes quite rapid, are affecting me like nothing else has before. And if it's giving _me_ motion sickness, I can pretty much guarantee it'll give it to other folks; like I said, no game has ever given me that before, and I've got over 3k hours logged in SE.

Reason 2.
In addition to the motion sickness issue, the old system was honestly better from a building perspective. There were times I wanted to be able to view my work area from a specific angle, and I used 6dof for that, but there were also times I wanted to keep my viewpoint fixed relative to the ship's gravity field, and anti-grav was perfect for that. Being able to use both whenever desired was ideal for designing things.

Perhaps a single key could be bound to "Select Movement Mode," and holding it down would bring up a radial menu like MMB does; then the player could mouse over the desired mode and release the key to select it.

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin I see. Indeed I will give a way to select 6dof. Either by switched through the 3 modes or by having that radial menu.
But I think I should also address any kind of issue with the 6dof. Fix bugs and improve the movement, to not have any motion sickness. In your opinion what the game is lacking to get something like in SE? 
It is a popular request I will try to get it asap, I am stuck on some technical stuff atm.
Thanks

**Comment by Kaiser-Indrasil** [comment]
### 6DoF

Right now most of what the playerbase does, is build spaceships through the means of flying their character around and placing down blocks. I believe that the previous "-G" antigravity movement mode was the best overall, since your charecter's pivot alignment took after the last grid the player aligned to, and stayed that way, inside and outside the field of artificial gravity.

We have a few unused radial menu positions, so let's delegate one of them to switch between the alignment modes:
- The old "-G" mode
- The old "6DoF" mode

They would work only with the F5 "unstuck" movement modifier and with the jetpack, of course.
Standard walking mode would just align the character to the combined gravity vector affecting them.
----------------------------------------------------------------------------------------------------------------------------------------------
### Pivot point

In my opinion, putting the pivot point around the feet or even in the centre of mass of the character leads to motion sickness because when you pitch up and down, your head (and by extension, your 1st person camera) rocks forward and backward, which isn't a pleasant thing to experience.

IMHO the pivot point should be overlapping with the player's FPP camera.

Then again, some people would complain that it's not realistic, and instead the pivot point should be placed at the feet when using mag-lock boots (it's an SE thing) or in the centre of mass when using a jetpack. Speaking of which, I like the responsiveness of the Starship Evo "jetpack" much more than the slidey one in SE, despite being less realistic. It's just much more convenient to not wait for 5 seconds for your character to come at a full stop.

Back to the pivot, a drop-down list in the game options menu would be ideal.
It would let people move their character's pivot point to either the centre of mass or the head.

**Comment by tsunamayo** [comment]
Okay I have made the switch to the selection of 3 mode in a grav field, and two in 0 g. (none will "upgrade" itself to anti-grav in a 0g environment).
@Kaiser-Indrasil Actually the pivot point is already on the camera, not the center like before. It was a requested change some time ago.
For 21w03b, I will push the build soon. Still taking any feedback on any 6dof deficiency if you notice something.
Thanks all!
