### ISSUE TITLE
Turret Movement Bug

### ISSUE THREAD

**Issue by Regnion** [tsunamayo/Starship-EVO#3263]
### Short Description of the issue:
My turret will not rotate more than a degree or two, left or right. Additionally, I cannot elevate the guns. Previously (a month ago) this turret worked flawlessly. I swapped to Experimental, and the turret stopped working. I swapped back to regular, and stopped playing for a few weeks. Now I've tried to get the turret going again, and it's just not working. When I set it to return to the resting position, it spins comfortably and cleanly back to the resting position. When I take control again, it suddenly jumps 90 or even 180 degrees from the direction it was facing, and when I exit is spins the rest of the way all the way back to the resting position. The whole time, I am unable to move it or the gun myself (it may randomly move when I try, but inconsistently).

Other hover vehicles I spawn in via blueprint do this as well, including ones I did not build. I have not tested turrets on ships.

...

### Steps to reproduce the issue:
Unknown. Others are telling me their turrets are working just fine. Previous builds I've done also have broken turrets now. Doors and hatches work as normal.

...

### Environment
- Starship EVO version: 20w46b
- Graphics Card: NVIDIA GeForce GTX 970

### Additional information:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5578306/output_log.txt)

[TankExampleBlueprint.zip](https://github.com/tsunamayo/Starship-EVO/files/5578316/TankExampleBlueprint.zip)

**Comment by tsunamayo** [comment]
Hi, so it was related to a bug with the other decorative children entity (the two side pods, the hatch and the seat). It is fixed now, I am glad you took time to book this one it must have impact other builds.
Now your turret is stuck a bit because of the seat, which goes too much into the main frame, you will need to fix this.

![image](https://user-images.githubusercontent.com/6604318/100401235-407e9100-309c-11eb-80f3-1d9211f95caa.png)

You can check which entity is which with F3 / Physics / View Entities Colors

You can also check any collision baking issues by opening the second rotator collision map:

![image](https://user-images.githubusercontent.com/6604318/100401296-79b70100-309c-11eb-9bc1-70bbb7b23b11.png)

Now the behaviour is still twitch in camera mode, this is something else I need to address.

Thanks!

**Comment by tsunamayo** [comment]
Issue fixed for 20w48d btw. Cheers
