### ISSUE TITLE
[SUGGESTION] Fuel suggestion to not break existing builds.

### ISSUE THREAD

**Issue by Gliese-832-c** [tsunamayo/Starship-EVO#3315]
So, there have been many discussions about how the fuel system will work in the future. I have also seen hints in some of Tsuna's comments, that he is working on survival-related stuff right now, such as fuel. What I have also seen, is some people oppose fuel, because it would break existing builds. I'm all for fuel, it gives you an objective to do when flying around a lot, and also makes you plan out your missions a bit better, as to not get stranded in deep space. It also just makes the game more believable. You need stuff to do stuff. However, I recognize the issue of people not wanting to redo their builds, so I have a solution for this:

Give reactors an internal fuel buffer. It should definitely be smaller than dedicated fuel tanks, if one block of fuel tank holds X units of fuel, then one block of reactor should only hold 0.1X or so units of fuel. While this won't be enough to do roadtrips around the whole galaxy, it should be enough for a decent bit of flying, and it will not invalidate existing builds. Another reason for doing this is to allow for microfighters/microshuttles. I have heard from several people, that it has been said that fuel tanks will be either 3 bricks or 3 blocks in size. This will make designs of small fighters and shuttles very hard, if not impossible, so adding a small fuel buffer to reactors would fix that issue as well.

**Comment by Kaiser-Indrasil** [comment]
Agreed. Having a severely limited fuel capacity on a very compact build seems like a drawback, but I believe this is a good compromise between breaking old builds and not having fuel at all.

**Comment by nokturnihs** [comment]
That would be fine but I'd further restrict fuel to only be used for warp, not lightcruise or normal thrust. This would allow these existing builds to do smaller jumps before needing to refuel but also wouldn't become such a nuisance mechanic as to make it incredibly annoying. You're out of fuel you can't jump. You can still travel in lightcruise but that's not gonna get you across systems. Reactors damaged? Well so's fuel reserves. Should feed those survival/grind mechanics needs without too much of a problem. We still need models for fuel tanks and small block versions of shields and fuel, functional or not ATM so we can start building future-protected (Not proof) builds.

**Comment by nokturnihs** [comment]
Also just a suggestion but if you limit the fuel consumption to warp you don't NEED a fuel tank (optional) - that's the capacitor on the warp core.

**Comment by nokturnihs** [comment]
If you used the warp capacitor as the fuel tank could do something like:
Reactor size = warp distance per fuel unit (with upgrade modules to reduce charge time or fuel economy?)
Single block of capacitor = 1 fuel unit.
So say you had a base distance of 1LY per reactor size, with a 3 warp  core system with 3 capacitors you could travel 3LY three times or 9LY once before needing to refuel. Remember you'd still need power to run the warp core so smallish distances would be able to be spanned for a smallish amount of space. That equation would probably need refining (don't know if anything is that close to each other). It still allows small ships to jump to warp but with very small ranges. If you do micro block versions you could do like 0.1 LY per unit or something like that too without needing to work around big blocks.

**Comment by tsunamayo** [comment]
So yes thats is the plan, I want to have each consumer block to have a mini storage unit. I also plan to boost a bit thruster / reactor output so you can quickly replace say 3 thruster with 2 thruster and 1 tank for example.
@nokturnihs warp will need special fuel for sure. But I think that lightcruise and power would also need one, we will see how it goes.
For sure normal flight would not require anything.
If you are stranded in space you will be able to call for some help, at a cost of course. Or just die, respawn at a station and bring some fuel yourself...

**Comment by Kaiser-Indrasil** [comment]
I like your plan, especially the part about raising the thruster thrust

**Comment by 5URG3** [comment]
> So yes thats is the plan, I want to have each consumer block to have a mini storage unit. I also plan to boost a bit thruster / reactor output so you can quickly replace say 3 thruster with 2 thruster and 1 tank for example.

Thanks for clarifying this Tsuna. Fuel is the biggest issue for me when building at the moment as I don't want anything I publish to quickly become obsolete. This clarification, and the new update system, removes the issue. 

I guess I'd better finish up some of these builds then :D

**Comment by nokturnihs** [comment]
> So yes thats is the plan, I want to have each consumer block to have a mini storage unit. I also plan to boost a bit thruster / reactor output so you can quickly replace say 3 thruster with 2 thruster and 1 tank for example.
> @nokturnihs warp will need special fuel for sure. But I think that lightcruise and power would also need one, we will see how it goes.
> For sure normal flight would not require anything.
> If you are stranded in space you will be able to call for some help, at a cost of course. Or just die, respawn at a station and bring some fuel yourself...

So I guess Starship EVO will not be single-player friendly then if we have to either have other players to come rescue us or die and abandon ship should we run out of fuel for normal power (and/or lightcruise)? Are you planning on an AI controlled version of triple A or something like that? Just curious there because I don't play multiplayer in most of these games. How hardcore are you planning on making the survival mechanics? Food, water? Oxygen and airtight compartments? I know you mentioned airtight mechanics at one point and ammo for some weapons... Are you planning full on survival mechanics like sleep, air temperature and the like?

**Comment by tsunamayo** [comment]
@5URG3 so for now I wanted to have fuel for the reactor too, but I am still undecided to be honest. I might default to Void energy, or likely "mini fuel", aka uranium or equivalent, that is to say something that dont really require tank and tubing and that will last a longer time.
@nokturnihs So my approach is never to make something too punitive, too realistic and too repetitive. 
Airtight I definitely want to give it a shot, oxygen / food we shall see, I just need progress on the crew side.
For being stranded in space it will be a NPC yes. So at the end you will loose a bit of cash to pay for the rescue.

**Comment by Garrett-C** [comment]
I like the idea of fuel, I just don't like the idea of having to set up pipelines. If it works on the "If fuel block and consumer block are connected by any blocks they share fuel" Logic then it's sweet but having to use separate pipes is to Space Engineers imo.

**Comment by tsunamayo** [comment]
@Garrett-C not sure, how it works in SE? My plan was to create fuel circuit, where you can simply connect stuff together and they will find their way and transfer automatically.
The only trick is to make sure your debit is high enough.

for example:

collector __ tank __ thruster
                          |__ thruster

But you can put more collector if you want to harvest faster ect...

Also I want pipe to be buildable inside hull, so it is not a nightmare to design, and dont break air tightness.

**Comment by Garrett-C** [comment]
Space engineers works in a way that everything that needs a resource needs to have a physical pipe that connects it.

Personally I kind of see that as being quite a tedious process. It’s the sort of thing that will appeal to some people but not others.

I think the in wall pipes is a good way to ensure that people don’t have to alter their visual styles to get things to connect but I do worry that if you have to actually drag the in wall pipe into existence in some way it’s also going to become very tedious again.

It’s the sort of feature which is probably viable on like a 50m ship but once you start getting larger you need more fuel so you need bigger tanks which means you probably need multiple tanks and multiple engines so fuel lines become a nightmare to actually run. 

I would argue that fuel lines using the physical pipes or the invisible pipes should give a boost to the systems they connect to but shouldn’t be required. Like having them makes your engines more fuel efficient or makes them output more power or speed etc. So that you get rewarded for doing it but not doing it doesn’t kill your ship completely. 

I do have faith in you to come up with a good solution though so I am interested to see what you come out with.

**Comment by Kaiser-Indrasil** [comment]
I love the idea of a buff rather than a penalty, especially if an efficient piping system would give more of a boost for the ship's thrusters than having an equally sized area took by thrusters alone.

Also please note that in Space Engineers the calculations of the conveyor / pipe junctions take up a lot of CPU compute time, so my hope is that you can somewhat simplify them.

**Comment by nokturnihs** [comment]
Hey @tsunamayo  I wanted to +1 @Kaiser-Indrasil 's comment about Space Engineers choking hard with a lot of conveyors and pipes.... I'd stick with your logic linking method for all the things (though you should at least auto-link most "systems" to each other and allow people to unlink them or switch out "power groups", etc by re-linking (or something that auto-links at some point so we don't have to manually link EVERY thruster and engine and ....)

As far as oxygen goes - sounds cool, really want small brick support though because I like small bricks here and there on the outer hull (especially small ships and things like ramps, cargo lifts, etc). Either that or make systems that we can scale that do all that and are pre-made... (think that's more work but might save cpu usage/reduce calculations?) - If that's something you want to explore can try and throw together a wishlist of pre-made "door/mechanism" things that you could calculate towards airtight/atmosphere and would reduce child entity usage..... but it would require a lot more modeling at a guess....

Speaking of which, you should see if you can get the community's help on that using blueprints of items suitable for scaling, convert the blueprint into a mesh/model and save yourself some headache and work.....

**Comment by tsunamayo** [comment]
@nokturnihs yep I will be careful to make sure that I have something that does not take too much resources. My current spec/implementation plan precompute each route, so most of the work is done when you link something.
For the door yes that is why I made the builtin door and trap door! I plan to add a slanted version also for access door.
I dont quite think I can simply use blueprint to save work, most of the work is UV mapping and texture baking...
Cheers

**Comment by nokturnihs** [comment]
Oh that's sad about not being able to use player BP's for prefabs @tsunamayo - was hoping that would save you time! As for the slanted door - hell yes! Can we get some single small brick wide doors at some point bud and maybe some window-doors? Would love to reduce entity count for things like bathroom and shower doors or for smaller ship builds...

**Comment by nokturnihs** [comment]
Oh one other thing - it possible to make a scaling prefab elevator @tsunamayo? Might solve any crew issues and also make it possible to just have floor stops built-in. Not mandatory but would save peeps some time, help with logic performance?

**Comment by AlienXtream** [comment]
having an actual elevator would be nice. bit off topic for the original post though. best put in a new suggestion.

**Comment by Cpt-Fortius** [comment]
I hope it won't break thrusters on child entities..

Sometimes I put thrusters on child entities, (and sometimes they have to be built like that to build an accurate replica of certain ships) and they actually work as a kind of "vectored thrust" ; built with small thrusters, the more I rotate them away from pointing straight back, the more directional thrust they give, and less forward thrust.
It's brilliant, and I'm still surprised it works. Would be a shame to waste this feature if thrusters on child entities become useless.

Btw, what if the fuel was just fueling the reactor? Consumption still happens, and the system remains simple.
Pretty much any build could handle that.
Might even go without a fuel tank, and you put the fuel straight in the reactor?

If you need pipes to every thruster, that'd break some small builds, like when a thruster is put on a hinge, or a single-brick surface with no room to hide piping.

**Comment by sed-and-awk** [comment]
piping could be done using the existing connections system, ie the player just has to drag, but then armor blocks on the route to where they dragged get converted into piped armor blocks, allowing for them to be destroyed in combat. I don't know how hard that would be to code, but it would allow for both simplicity and be able to be added to existing builds, while still having some effect if damaged.

**Comment by tsunamayo** [comment]
We have fuel now, and you can use older blueprint without them if you want. Thanks
