### ISSUE TITLE
[BUG] Distortion in build when looked at from some distance, then dissapears when you get close

### ISSUE THREAD

**Issue by ultrak2k** [tsunamayo/Starship-EVO#3341]
### Short Description of the issue:
I noticed when  I was building something else, that one of my builds had gained strange brick protrusions - I was concerned it was corrupted somehow so I came closer to take a look, but it turns out that the bug disappeared when I drew near. the nature of the distortions also change as I rotate myself
...

### Steps to reproduce the issue:
Load into game
Go a bit away from build
Observe that it has been boofed
Go closer, and notice how it's wierdly okay
...

### Environment
- Starship EVO version:  20w49a
- Graphics Card:  Nvidia 840M

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![20201205210950_1](https://user-images.githubusercontent.com/43084360/101237870-fd2dbd80-3740-11eb-9d7e-bdf5a65da56b.jpg)
Different rotation:
![20201205212956_2](https://user-images.githubusercontent.com/43084360/101237886-1fbfd680-3741-11eb-9bc2-e3695d6c215e.jpg)
Closer:
![20201205213057_1](https://user-images.githubusercontent.com/43084360/101237894-2e0df280-3741-11eb-9b3f-97e9a22d8eb7.jpg)

Dissapearance distance:
![20201205213101_1](https://user-images.githubusercontent.com/43084360/101237899-3403d380-3741-11eb-886f-71b4f9fa49e7.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[I can't upload it, for some reason my output_log.txt is 91mb, is that normal?]
Take a google drive link: https://drive.google.com/file/d/1K9XXnKNizfVKlaa9oYnLq5eGk6LjseI3/view?usp=sharing

**Comment by tsunamayo** [comment]
@ultrak2k Hi, could you give me the blueprint so I can investigate? By the look of it is seems to have a massive brick count, so it wont look good from afar. Once a single brick is smaller or close to a single pixel, there is not much things the engine can do... 
Thats one other reason it is better to use large hull block for big ships ;)
Your log file is massive because there is a few ships inside the sun that are being destroyed - I guess following the Warp update. Could you recreate a new Character and reimport your blueprint? Thanks

**Comment by ultrak2k** [comment]
Seems like the issue isn't happening, even with the newer version of the build that has more bricks in a new world
Yeah I haven't played since before the warp update, so didn't know about that, whoops
Here's the blueprint anyway: 
[Scarlet Devil Mansion.zip](https://github.com/tsunamayo/Starship-EVO/files/5651295/Scarlet.Devil.Mansion.zip)
