### ISSUE TITLE
New use to the Ship heat

### ISSUE THREAD

**Issue by Krasskat** [tsunamayo/Starship-EVO#3373]
### Short Description of the issue:You could add space cold damage to the player and the solution will be to put a heat transformer block

...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by AlienXtream** [comment]
space isn't actually cold. sorta. its a misconception. space is a vacuum. there is no physical medium to it. its not a total vacuum though, there is a tiny amount of particles spread very far apart. these particles are so thinly spread that the little energy they have is spread over a large distance. thats where the misconception comes from. space isn't cold, it just has very little thermal energy cos it has so little in it. if you were to be exposed to the vacuum of space you would actually overheat. in the atmosphere we lose heat by conduction and convection, which requires something to transfer said heat to (i.e, the air). without an atmosphere the only way for heat to leave your body is from infrared emission which is extremely slow compared to the heat you gain just from your bodies chemical reactions. its a real problem too. the ISS is actually quite warm because it cant radiate heat fast enough. a lot of the engineering that goes into it is to keep that heat from cooking the astronauts on board (as well as oxygen and airtightness).

**Comment by tsunamayo** [comment]
So some element will be added to the survival, but heat is not one of them (at least for now, maybe with planetary tech?)
