### ISSUE TITLE
[Questions] NPC Ship Requirements, Old Feedback information

### ISSUE THREAD

**Issue by SabreMania** [tsunamayo/Starship-EVO#3374]
Greetings Tsuna,

Back in January, you asked the community to provide you with ships that you could add into the game, to make it more lively and to start working on factions. To guide us a little, you provided us with this google doc here https://docs.google.com/document/d/e/2PACX-1vT_lv2Ru060nvEa0ggMOLI-v6H1i9snbAt-1lJFe9a2UugRO9C3LaHXzRrBMDl4_chXgpInBaw4iOCc/pub originating from this post here https://github.com/tsunamayo/Starship-EVO/issues/1569. 

Me and many in the community have started to disagree with each other on the relevance of the information provided within. Some believe that those requirements are still valid, while others believe they are either out of date, or soon will be. However, it's difficult to tell what you think without asking you directly, hence, this github post. Personally, I dislike to ask these kinds of things since it can take away development time from the game just to clarify a few things for us, but there are very significant boundaries to respect in relations to ship building that are not nessecearely as clear cut into the game as they are in this google doc.

**Comment by matejkar** [comment]
Well i believe i have the largest collection of capital ships in the community, at least from what i've checked.
Currently counting about 40 ships total, of which 20 are capital ships. Now following the building of these ships i've come up with my entire fictional universe very similar to the star wars universe. I can go into detail about the universe, but thats not why i am here. 
I want to share my classification system for the universe and after that the steam collections containing those ships.
The ships in the universe are not particularly amazing looking or detailed, or impressive on the inside, only some basic grey hallways with blast doors, working stations, medbays, reactor rooms, engine rooms etc.
My classification system for the universe is different for the 2 main factions: Empire and Federations. But only in ship classifications, not dimensions.
Classification system:
- sub 50 meters: strike craft (fighters, bombers, interceptors, light transports etc.)
- corvettes: 50-75 meters long
- frigates: 75-120 meters long
- cruisers (multiple subclasses): 120-210 meters long
- destroyers: 100-250m long
- battlecruisers: 210 - 280 meters long
- battleships: 280 - 340 meters long
- carriers: same size as battleships
- dreadnoughts: 340-500 meters long
- sector dreadnoughts: 500-800 meters long
- super dreadnoughts: 800+ meters long
- space stations: all sizes

The Federation has the same system but only has a few differences:
- Battlecruiser class is replaced by the Battlecarrier class with the same dimensions
- Battleship class is replaced by the Pocket dreadnought class with the same dimensions
- No Sector dreadnoughts and Super dreadnoughts

Im really proud of the collection i have and i am quite fast in building these ships, takes me about 2-3hrs to build a 100-120m long ship.

Here is the collection with all of the ships i've built and their collections, i also got some "followers" who joined my and are building ships for this fictional universe, and their ships are in the collections inside this collection:
https://steamcommunity.com/sharedfiles/filedetails/?id=2318013193

the collection currently holds 36 items, of which 31 are my own ships (so not 40).
Once again i am very satisfied with how my ships have turned out and my main goal is to create a large collection of capital ships that are easy to use for everyone. I have made my capital ships quite slow for their size because i wanted to make them feel larger then they actually are. The ships and factions have their own gimmicks and if i went into more detail, this post would be too long.
So if (when) the dev sees this, and is interested in more details about my stuff will happily make an entire new post about what my universe is and how it works.

**Comment by KINGrimson** [comment]
> Well i believe i have the largest collection of capital ships in the community, at least from what i've checked.
> Currently counting about 40 ships total, of which 20 are capital ships. Now following the building of these ships i've come up with my entire fictional universe very similar to the star wars universe. I can go into detail about the universe, but thats not why i am here.
> I want to share my classification system for the universe and after that the steam collections containing those ships.
> The ships in the universe are not particularly amazing looking or detailed, or impressive on the inside, only some basic grey hallways with blast doors, working stations, medbays, reactor rooms, engine rooms etc.
> My classification system for the universe is different for the 2 main factions: Empire and Federation. But only in ship classifications, not dimensions.
> Classification system:
> 
> * sub 50 meters: strike craft (fighters, bombers, interceptors, light transports etc.)
> * corvettes: 50-75 meters long
> * frigates: 75-120 meters long
> * cruisers (multiple subclasses): 120-210 meters long
> * destroyers: 100-250m long
> * battlecruisers: 210 - 280 meters long
> * battleships: 280 - 340 meters long
> * carriers: same size as battleships
> * dreadnoughts: 340-500 meters long
> * sector dreadnoughts: 500-800 meters long
> * super dreadnoughts: 800+ meters long
> * space stations: all sizes
> 
> The Federation has the same system but only has a few differences:
> 
> * Battlecruiser class is replaced by the Battlecarrier class with the same dimensions
> * Battleship class is replaced by the Pocket dreadnought class with the same dimensions
> * No Sector dreadnoughts and Super dreadnoughts
> 
> Im really proud of the collection i have and i am quite fast in building these ships, takes me about 2-3hrs to build a 100-120m long ship.
> 
> Here is the collection with all of the ships i've built and their collections, i also got some "followers" who joined me and are building ships for this fictional universe, and their ships are in the collections inside this collection:
> https://steamcommunity.com/sharedfiles/filedetails/?id=2318013193
> 
> the collection currently holds 36 items, of which 31 are my own ships (so not 40).
> Once again i am very satisfied with how my ships have turned out and my main goal is to create a large collection of capital ships that are easy to use for everyone. I have made my capital ships quite slow for their size because i wanted to make them feel larger then they actually are. The ships and factions have their own gimmicks and if i went into more detail, this post would be too long.
> So if (when) the dev sees this, and is interested in more details about my stuff will happily make an entire new post about what my universe is and how it works.

 i think your post has NOTHING to do with what he asked, try and stay ontopic

**Comment by matejkar** [comment]
well i've read the post u linked in your original post, and since i read about building faction stuff, i've decided to share what i did. I know its not totally on topic but i think the dev might still look for stuff related to the post he did about faction building.
Sry if it seems like its off topic, i just tought we are more connected to that dev's post, not this one specifically

**Comment by tsunamayo** [comment]
@SabreMania Hi, so what I lack is actually data to start to iterate on the requirements. Right now I am in post holomap / warp dev hell, as soon as it is finished I will start to iterate on pirate skirmish and fight. I will then have a much better idea of what are the attention point to make great ship to be integrated to the game. I still think the doc is relevant for now, I dont plan to go higher than 150m for now for example.
I also want to make the fuel update before I ask people to spend time on the ships as it will be impactful to some extent (it should not be too hard to convert ship that being said). Thanks
@matejkar thats is impressive! That beeing said those ships are way too big for gameplay at this stage. Cheers

**Comment by SabreMania** [comment]
@tsunamayo Thank you very much for responding to this thread. I will admit, when I asked about the document's relevancy, I was focusing a little more on the size of hallways (3m or more), them being made out of blocks, and what may be the most important, the child entity limit. At the time, you left it fairly vague, only precising that you will put a child entity limit at some point in the game, but we don't have any approximation on it. If this has changed, the community and myself would very much like to hear about it.

If not, then shucks, but I won't press on it. I hope that you will get out of your development hell, I wish you best of luck, and a Merry Christmas to come!

**Comment by tsunamayo** [comment]
So no limit for now, just dont overuse them. 2m high hallway are fine but I feel they are too claustrophobic. I think the best is 3m with some pipe gribbling on top... Thanks
