### ISSUE TITLE
[Exploit] Hull blocks have same stats except for variable mass

### ISSUE THREAD

**Issue by YellowMiner** [tsunamayo/Starship-EVO#3397]
### Short Description of the issue:

All hull block shapes have same stats except for mass.

This encourages to use the triangle corner to bulk out empty space and the square end of the 1/3 for walls instead of full blocks.

It means extra triangles to draw, probably bad for the collision engine, and while it's annoying to set up, someone someday will abuse it. (and at up to 92% mass reduction for same heat dissipation or other stats, there's good reason to)

Have the stats of each hull block shape proportional to it's mass instead.

### Environment
- Starship EVO version: 20w50a

**Comment by YellowMiner** [comment]
As a side question, is there a technical reason for bricks behaving like full size blocks (The rounded and rounded corner blocks, full size girders, plank and transparent cube, which all snap to the voxel grid like hull blocks) to not have any hull type stats ? Would make sense for the rounded ones at least, and maybe the girders.

**Comment by nokturnihs** [comment]
So I noticed a few other things in relation to that - Heat dissipation between hull and brick is weird - so the small bricks only seem to provide 1 set amount of heat dissipation per block - and since heat dissipation is only a 5 point difference between block and brick, if you set it up properly you could dissipate a lot of heat with "small brick" dots that are in the corners of each block. I'm not sure this is intended but it sucks for ships made almost completely out of small bricks as they receive nowhere near the heat dissipation as a block ship of the same size - for example a 4x1x1 shape of blocks will dissipate 25 heat per - for 100 heat. a small brick ship that's 4x1x1 will dissipate 20 heat per BLOCK grid (which can contain 4x4x4 small bricks) so it's total is 80 heat dissipated - but it's only calculated in 1m (one block) segments. So if you were instead to take a 4x0.25x0.25 meter shape made out of small bricks it'd also dissipate 80 heat. 

Also as far as I can tell the small power generators are more efficient at the cost of additional heat....  a 0.75x1x0.25 small brick generator creates more power than a single 1m generator but does produce more heat.

I've attached screenshots to illustrate....

![20210104141119_1](https://user-images.githubusercontent.com/7344403/103580969-5a2fa700-4e98-11eb-9ae4-2bd76c13311f.jpg)
![20210104141107_1](https://user-images.githubusercontent.com/7344403/103580973-5ac83d80-4e98-11eb-9b7b-77813d2fe2e9.jpg)
![20210104141058_1](https://user-images.githubusercontent.com/7344403/103580974-5b60d400-4e98-11eb-8838-9b7cd37a3497.jpg)
![20210104141045_1](https://user-images.githubusercontent.com/7344403/103580976-5bf96a80-4e98-11eb-8a6a-e88179eff7a2.jpg)
![20210104141035_1](https://user-images.githubusercontent.com/7344403/103580977-5c920100-4e98-11eb-9550-cecde6967cd1.jpg)
![20210104141027_1](https://user-images.githubusercontent.com/7344403/103580978-5c920100-4e98-11eb-9069-e84ed6550117.jpg)
![20210104141016_1](https://user-images.githubusercontent.com/7344403/103580981-5c920100-4e98-11eb-8f90-5d4368938cfa.jpg)
![20210104140953_1](https://user-images.githubusercontent.com/7344403/103580982-5d2a9780-4e98-11eb-8edb-7293699af264.jpg)
![20210104140907_1](https://user-images.githubusercontent.com/7344403/103580984-5d2a9780-4e98-11eb-9a7a-8c5c7fd1ddd1.jpg)
![20210104140857_1](https://user-images.githubusercontent.com/7344403/103580985-5dc32e00-4e98-11eb-84ad-61c381877831.jpg)
![20210104140846_1](https://user-images.githubusercontent.com/7344403/103580986-5dc32e00-4e98-11eb-9c1e-967fe7e4131a.jpg)
![20210104140838_1](https://user-images.githubusercontent.com/7344403/103580987-5e5bc480-4e98-11eb-9efd-6baeaf393162.jpg)
![20210104140826_1](https://user-images.githubusercontent.com/7344403/103580988-5e5bc480-4e98-11eb-88da-9a6a817081da.jpg)
![20210104140655_1](https://user-images.githubusercontent.com/7344403/103580989-5ef45b00-4e98-11eb-956e-5b7197220a43.jpg)
![20210104140648_1](https://user-images.githubusercontent.com/7344403/103580990-5ef45b00-4e98-11eb-8ad8-f68171dca304.jpg)
![20210104140635_1](https://user-images.githubusercontent.com/7344403/103580991-5f8cf180-4e98-11eb-86c6-5358aed8bfc6.jpg)

**Comment by nokturnihs** [comment]
Shit... sorry about the order - still.... you get the idea.

Oh - and added here because his thing about mass exploits also works similar here except you could do almost the same thing (slightly less efficient) with small generators and small bricks) for a massive mass reduction.

**Comment by nokturnihs** [comment]
Made a Quick Reference ship to show more details.
The base ship:
![20210104144530_1](https://user-images.githubusercontent.com/7344403/103584422-85b59000-4e9e-11eb-8cbe-ccf19a5b75d9.jpg)
With big reactors
![20210104144612_1](https://user-images.githubusercontent.com/7344403/103584442-8f3ef800-4e9e-11eb-936c-5205c45ce8b1.jpg)
With small reactors
![20210104144636_1](https://user-images.githubusercontent.com/7344403/103584465-9a922380-4e9e-11eb-8095-39cb5ba074c7.jpg)
With 15 large blocks for heat dissipation on small reactor ship
![20210104144833_1](https://user-images.githubusercontent.com/7344403/103584501-ac73c680-4e9e-11eb-878a-2012b705083d.jpg)
![20210104144840_1](https://user-images.githubusercontent.com/7344403/103584510-b1387a80-4e9e-11eb-9de1-b2b0f233edd1.jpg)
![20210104144849_1](https://user-images.githubusercontent.com/7344403/103584520-b5fd2e80-4e9e-11eb-8db4-8a60b8833f2d.jpg)

Now using small bricks for heat dissipation (only occupy the same grid space as the blocks from above
![20210104145244_1](https://user-images.githubusercontent.com/7344403/103584570-d0cfa300-4e9e-11eb-91ea-f0a3303375fb.jpg)
![20210104145256_1](https://user-images.githubusercontent.com/7344403/103584597-de852880-4e9e-11eb-90d8-fe351ed1b8d5.jpg)
![20210104145330_1](https://user-images.githubusercontent.com/7344403/103584661-f78dd980-4e9e-11eb-94a9-9c430681d329.jpg)

And now adding adding one new small brick layer in the unoccupied spaces....
![20210104145442_1](https://user-images.githubusercontent.com/7344403/103584733-21470080-4e9f-11eb-9c69-04271b5305ef.jpg)
![20210104145452_1](https://user-images.githubusercontent.com/7344403/103584743-27d57800-4e9f-11eb-9428-6610ab0bafbc.jpg)

You'll notice the last has zero impact on weight or movement stats but drops heat by a LOT.

So.... yeah....

**Comment by tsunamayo** [comment]
So all stats should scale now! Thanks
