### ISSUE TITLE
[SUGGESTION] A voxel method that works with bricks.

### ISSUE THREAD

**Issue by cloudrambler** [tsunamayo/Starship-EVO#3412]
I have been thinking about the challenging aspects of NPC pathfinding and airtightness, as they share a common problem; how can a voxel based logic method allow for brick based constructions? I think there is a reasonable solution.

The essence of the problem is that we need bricks for critical surfaces. Assuming we build ships with voxel based interior voids and paths etc., the walls, windows, canopies, and also the floors, will in many cases, still be made with bricks. So we (the players who want to keep you inspired by building cool ships today) need to understand a plausible rule set for how the game will interpret bricks as voxels, once those mechanics are included.

My suggestion is like this:

1. The game treats any voxel that is 25% occupied as "FILLED".
2. Unless that voxel contains ANY damage, in which case it would be treated as "UNKNOWN".
3. The pathfinding and airtightness algorithms can include brick filled voxels provided they are "FILLED".

This would allow brick built ships to support pathfinding and airtightness, provided the properly aligned floor voxels and enclosing voxels are respectively occupied to at least 25% and not damaged. Then any damaged floor voxel would not be safe to walk on, and any damaged enclosing voxel would not be counted in the airtightness check.

Clearly this method does not guarantee a perfect visual interpretation, as players could construct functional voxels that did not contain realistic surfaces. However I suggest two factors that would permit this method to work anyway.

A. There are no significant game exploits to be gained by having a 25% occupied voxel that looks wrong.
B. Most players will endeavour to make their ships look proper, regardless of the technical flexibility available.

The outcome which I believe most vocal players desire is this:

We can make ships that contain bricks for critical surfaces, knowing that they are structurally inferior to blocks, but which nonetheless provide necessary design details. We can understand that the game will treat those surfaces as functional floors and enclosures, provided they are 25% occupied and undamaged. It is then up to the discretion of each player to ensure that those voxels are filled in such a way as to visually represent the function that the game will assign.

I believe that if this method could be sanctioned, it would give the playing community a clear rule set to work with and pave the way for the game methods to be implemented directly into those existing design assets.

**Comment by TIKIRobo** [comment]
This method could totally work for O2 but AI pathfinding Is dependent on the floor always being the same height iirc so idk if this method would work for the AI

**Comment by tsunamayo** [comment]
Thanks for the suggestion, let me sink that through a bit. I have other idea to explore too. Cheers

**Comment by AlienXtream** [comment]
might be best to employ multiple solutions. a simple and fast one that precomputes pathing for a ship for AI that is far away/non visible but still needs to simulate (i.e other side of a ship navigating to where the player is. dont need nice looking pathing as long as it gets there). a more advanced pathfinding that allows for avoiding small obstacles (simplified pathfinding would just no clip through. seems bad due to doors but that's part of the precomputing determining where is accessible based of the slowest pathfinding and making paths for that). and lastly a more precise pathing method that takes into account 3D movement inside ships for 0G and AI 6doF.

 mode could be set based of context. i.e areas close to the player (and likely in line of sight) should use mode 2 so that AI can look like they are aware of their environment (e.g side stepping past a narrow gap). the effects of this would be only visual and could be disabled completely on the clients end (always simple AI or something). when the AI leaves the players range AND FoV then it uses mode 1 where the AI is basically just following fixed rails (basic walk animation for distant AI/always simple AI on). 
 
 mode 3 would be only used in special cases like scripted events. what do i mean by scripted events? well, not story stuff but like being able to interact with the AI crew during specific scenarios. things like exploring a derelict ship in 0G or crawling through a service hatch and helping each other through. stuff like that. 
 
 
 now, i know this is complex and by no means easy but its definitely possible and way be worth considering much later down the line.
 
 also, on a side note, the player controller and animation handler would need a major rework (practically a total rewrite) to make anything like this possible but i think that making use of procedural animation methods on top of some base handcrafted ones is a must for a game where things are so variable (would also mean that clambering in and out of seats/cockpits would become viable). ofc that's just my opinion and i know that the trade off for such a versatile system is that instead of needing to make thousands of animations you have to spend that time programming so it's ultimately up to you what approach you go with
