### ISSUE TITLE
[Bug?] Purple gas giant [21w01a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#3455]
### Short Description of the issue:
The gas giant has a purple-ish color to it now.

### Steps to reproduce the issue:
![20210108014422_1](https://user-images.githubusercontent.com/33041786/103988044-0ac8cf80-5153-11eb-9770-cffbd6be4e6c.jpg)

Not sure if this one is a bug either, or if purple gas giants were added with the other new planet varieties.

### Environment
- Starship EVO version: 21w01a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5785818/output_log.txt)

**Comment by AlienXtream** [comment]
planets are procedural so unless its ALL planets this is intended behaviour

**Comment by Kaiser-Indrasil** [comment]
It's intentional, as seen in #3356 .
Right now with the yellow-ish texture covering the gas giants it looks weird but keep in mind that these are just placeholders for now.

**Comment by Dwarf-LordPangolin** [comment]
Huh. If this is the new planet, that's fine, it just looked different enough from the old look that I thought it might be a texture bug.

![Old Planet](https://user-images.githubusercontent.com/33041786/104071793-849e9e80-51cf-11eb-90c4-b7649b2dbe4e.jpg)

**Comment by cloudrambler** [comment]
The pink hue on the ice rings seems to be a refraction of the star light through the ice crystals (or a simulation of that phenomena). As you fly around the gas giant, the pink colouration moves to align with the star; similar to how rainbows are always opposite from the sun when viewed on earth. Its actually very beautiful and ties the space together really well because the planets appearance changes based on the relative position of the viewpoint with respect to the light source (star).

**Comment by tsunamayo** [comment]
Yeah it is not an issue ;) I dont want to spend too much time tweaking as I will replace them at one point! Cheers
