### ISSUE TITLE
[Question] Floating block behaviour to stay?

### ISSUE THREAD

**Issue by ColdSpiral** [tsunamayo/Starship-EVO#3474]
When a block (B) has been placed, connected to the main or child entity by another block (A), and then block A is deleted, block B remains in place, moving with the entity as if it is still attached. This is especially noticeable when the base entity is a slider, piston etc., causing the block to move with no visible connection.
I assume the same applies to blocks disconnected by damage, which is expected as the blocks are still part of the ship and will be reconnected by repair.

Is this intended behaviour through to release? 
I'd like to make use of the feature for some interesting designs (hovering stairs, wings etc), but not if blocks no longer attached to the main entity are deleted with the parent, as is the case with child entities (i.e. deleting a rotor also deletes anything attached to the rotor).

To reproduce: 
1. Place a series of three separate blocks. In the example I have connected them to a slider for illustrative purposes.
![1 Connected](https://user-images.githubusercontent.com/33015413/104544722-8dceb600-567c-11eb-95c5-7b47e6b6cf46.jpg)
2. Delete the striped block (A), which connected the wooden block (B), to the grey block on the slider (entity). 
![2 Disconnected](https://user-images.githubusercontent.com/33015413/104543524-b5704f00-5679-11eb-94cb-9556211b7637.jpg)
3. The wooden block remains attached to the entity, and will move with the slider.
![3 Moving](https://user-images.githubusercontent.com/33015413/104543526-b608e580-5679-11eb-874e-1c74d44759d2.jpg)

Re-iterating that I don't necessarily feel this is a bug or otherwise _needs_ to be changed, but I would like clarification on whether it's something you expect to change in the future.

- Starship EVO version: All through to current - 21w02b(exp)

**Comment by tsunamayo** [comment]
@ColdSpiral I am not sure yet, on one side it is really needed otherwise stuff would just collapse while you delete something, on the other it would be really great for combat and wreck scrapping if ship could split...
So I guess what I would do at best:
1) player made gap does not separate (so you are good to go)
2) Only damage could trigger a split.
Most likely it will be never implemented anyway...
Cheers

**Comment by cloudrambler** [comment]
@tsunamayo I suspect the consequences of subdividing the grid due to damage would be difficult to manage efficiently. So I have an alternative proposal. When a ship is damaged and voxels are temporarily deleted from the grid, any remaining voxel clusters that are below a certain size would also be deleted by default. So the ship would only ever contain larger elements (still and always in relative location) with the clutter of broken fragments cleared by the filter.

This would look neater, without having to change the base grid mechanic.

The size of voxel cluster to filter is up for debate, but perhaps anything less than 8 voxels would be fair game to lose. If you wanted, there could even be a mechanism where voxel clusters separated by damage disappear over time, depending on how large they are. They could flash when they are about to become finally detached, giving the player an opportunity to recover them by repairing a bridge to the primary cluster. This would make the repair aspect more strategic, and also make boxy ships easier to repair (statistically) than spindly fragile ones; which is thematic.

In terms of game lore, you could surmise that the larger parts are held in place by some default ship-wide magnetic support grid (like maglocks but as an embedded network), where the smaller chunks would not have a working "mag-node" and so get lost with the other damaged voxels. Of course any designed-in separations would have such mag-nodes embedded deliberately.
