### ISSUE TITLE
Suggestion - Implement the option to turn on zero g movement when building a ship outside the ring.

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Starship-EVO#3499]
Main reason being - motion sickness.

Prior to this feature being removed (for what I saw to be streamlining reasons as choosing a movement mode isn't so intuitive) I never used the 6DOF movement, as without the ability to maintain a constant "horizon" line, gradually losing my orientation in space would make me feel nauseous and force me to stop playing. 

Using zero g avoided this as the mouse would cap out looking vertically up or down maintaining a visual "horizon" with what I was building.

Obviously removing the automatic movement switch isn't an ideal solution, but could 0-g in space be re-implemented as an option in the menus please? Building everything really close to the ring isn't always practical. I'm sure there are others besides me who've experienced this effect of 6DOF

**Comment by TIKIRobo** [comment]
one good comprise could just be some sort of align to surface so that you can always stay locked to your ship's rotation

**Comment by ZachZent** [comment]
![image](https://user-images.githubusercontent.com/36980446/105267123-9e849d80-5b4e-11eb-9d32-6ab4f7f8f79b.png)
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA supportively

It really is needed though

**Comment by Aiwii** [comment]
I also agree. Ever since the removal of the zero-g movement mode I have been having severe night tremors that disturb not only my sleep but my kind neighbours also. I had one yesterday and had to reimburse 6 houses for the damages I caused. Without the zero-g movement mode, I have to confine all my building activities to within the universal gravity of the ring otherwise I may start losing it. This is not ideal but I must do so to avoid the tremors and maintain my sanity. My wallet cannot afford another incident. Please Tsuna, reimplement zero-g movement mode. Think about my neighbours, you wouldn't want to put them through this.

**Comment by schlid** [comment]
Jokes aside using 6dof genuinely does make me feel ill

> I also agree. Ever since the removal of the zero-g movement mode I have been having severe night tremors that disturb not only my sleep but my kind neighbours also. I had one yesterday and had to reimburse 6 houses for the damages I caused. Without the zero-g movement mode, I have to confine all my building activities to within the universal gravity of the ring otherwise I may start losing it. This is not ideal but I must do so to avoid the tremors and maintain my sanity. My wallet cannot afford another incident. Please Tsuna, reimplement zero-g movement mode. Think about my neighbours, you wouldn't want to put them through this.

**Comment by cloudrambler** [comment]
This subject was discussed a few weeks ago #3430. It got a little side-tracked but there were some conclusions.

**Comment by schlid** [comment]
> This subject was discussed a few weeks ago #3430. It got a little side-tracked but there were some conclusions.

fair, had a read so good he's on the positive side of the argument. I think I'll close the issue and tag it there.
