### ISSUE TITLE
Larger Weapon

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#3530]
After the currently critical Bugs have been resolved. it would be very beneficial to introduce 3x3x (X) or 2x2x(X) weapon blocks, which generate a significant (x10) more damage while consuming significant more energy (x10), in order to avoid something like that:
![Starship EVO_2021_01_26_21_08_01_492](https://user-images.githubusercontent.com/43222403/105899561-1b19ef00-601b-11eb-926f-dcd4189ed4f1.jpg)

With larger weapon blocks, the required number of barrels and main turrets on corvettes and cruisers would be reduced. That would be an advantage not only visually, but also in terms of performance. 
These weapons should have a long range (8km) but hit small targets very poorly. This can be due to high weight -> 1) slow rotation rate of the turrets or 2) slow projectiles (is probably difficult - range is currently defined by speed, since all projectiles have the same lifetime until despawn)

This could also be achieved with a weapon addon which multiplies(x10) the damage and energy consumption. For Option 2) This add-on would need to have a huge mass in order to significantly slow down the rotation rates of the turrets.

**Comment by tsunamayo** [comment]
Hi, so what size are your ship? We will see how the meta evolve but some people are building way to big...

**Comment by matejkar** [comment]
@tsunamayo as an active capital ship builder i definetly agree that we need larger weapons. Larger ships in general die far to slowly.
Another suggestion i would like to make are new kinds of weapons:
1. ION weapon - same lengths as the laser weapon, deals no hull damage, but deals massive shield damage, and reduces a ship's power when hitting it.
2. PROJECTILE weapons - rockets, missiles, torpedoes. Idk how exactly would those work, but in my mind rockets are fast and unguided, but don't deal a lot of damage, good on strike craft and against them. Missiles are mounted weapons, base block is 1x1x1m and could be stretched up to 4x4x4, they home in on a target, have strong homing capabilities, longer range and greater damage output, but they cannot reliably hit small ships. Torpedoes have weak homing capablities, they have the longest range and the greatest damage output, and they deal lots of both hull and energy damage (ie. like possible Ion weapons they reduce the energy of the targeted ship upon hitting it), the base block is 1x1x1 and could be stretched only length-wise up to a length 4 weapon.

these are one of the things the game does need in my opinion, since this game feels kind of empty with just lasers and beams for weapons.

**Comment by Battlepixel** [comment]
> Hi, so what size are your ship? We will see how the meta evolve but some people are building way to big...

![Starship EVO_2021_01_27_17_06_11_775](https://user-images.githubusercontent.com/43222403/106019087-88cd2600-60c2-11eb-8f2d-a42043a01567.jpg)

**Comment by tsunamayo** [comment]
@Battlepixel We now have larger weapons with neovox. Thanks
