### ISSUE TITLE
[Dev Asks] New paint / material workflow

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#3701]
So I will start the voxel removal dev. I can improve a few things as I will update the brick format and I will no longer limited by having to pack tightly data for the voxel format.

In particular I would like to:
- bring custom color back.
- add a material paint tool.

This material paint tool follows the discussion that started in a previous dev asks where people wanted a wood texture.
This tool would work like paint, but: 
 - it would change the property of the block, like mass, heat dissipation and armor. I need this anyway so people can swap out different hull type, as I dont want to duplicate each hull block for each metal variant.
 - It would require mined material, but would swap the previous material back into player inventory.

I could then create various hull metal needed for gameplay and add some decorative one like gold and wood. Maybe carbon if I can make it look good.
That mean that the current metal paint would become material paint.
This would also replace the primary secondary paint (easier for me tech-wise). For example in the case of a seat: the cushion takes the color of the paint, and the seat metal frame takes the color of the metal / material used.
One downside is regarding framed windows: we have to choose between paint the frame or paint the glass. I choose paint the frame, but I will add frameless windows soon where you will be able to paint the glass.

Do you guys see any issue with that?

**Comment by ProPeach** [comment]
- Custom colour coming back 
Yahoooo!!

- Material paint
Yippee!

This all sounds perfect, including the mechanism for switching out properties and materials using the same paint workflow. We talked about it a little in that armour alloy thread, but this really is the simplest and smoothest way to switch out alloys and materials without duplicating blocks in the codex. Should be a lot faster with the paint changes coming from killing voxels too!

I see no issues with this approach, go for it!

**Comment by Aiwii** [comment]
Sounds good

**Comment by MagicalAbyss** [comment]
I would like to see something related to the paint size and depth options, specially for material paint. 

As for right now: 
- Very difficult to paint on **stacked** hull blocks/bricks even with no-clip mode due to **obscured vision**.
- Time consuming with fixed **1 block/brick size**, good for smaller ships(cat 0 - 2), bad for larger ships. (cat 3+)

**Comment by tsunamayo** [comment]
@MagicalAbyss voxel paint is disappearing, so not sure to understand. Also regarding stack/depth not sure to see what you are proposing. I would say paint first then build on top...

**Comment by MagicalAbyss** [comment]
> I would say paint first then build on top...

But this do not work when you want to upgrade/retrofit a built ship. Like you said, voxel paint is disappearing, I don't know if the new tool gonna be similar or completely different, so I'm unable to provide any suggestions but problems from current tool.

**Comment by tsunamayo** [comment]
well with no longer voxel paint it become much easier to do so, you just need see a patch of the brick you want to replace. If not possible then I guess no clip mode is necessary...

**Comment by pinesh** [comment]
material paint is a brilliant move forward for that easy greeble look. Harkens back to the days of Tech blocks!

**Comment by ExodistSKY1** [comment]
This sounds wonderful! I am looking forward to custom colors again!!!

and the Materials! if it is the easiest way to add more in and it frees up/ saves room I think that is best for the future!

**Comment by ZachZent** [comment]
All of this sounds great and will make the building even better. The only thing I'm slightly... not concerned but less then happy with is is the last point with the framed windows. Between the option of painting the frame or painting the glass, the frame is the correct option. However given that we can paint the glass of boarderless windows, it may seem odd to have some windows gold tinted while the framed ones are default. This is mostly concerning the canopies. Unless I'm mistaken that all glass will have a boarderless version including canopies which makes my "concern" a non-issue.

And as an aside for painting glass, it would be cool if you painted them one of the metallic colors the window becomes more tinted rather than just gold colored.

**Comment by Regnion** [comment]
How about NO glass borders? We can make our own frames with bricks or blocks, there is no need for an additional frame to come with the glass, especially when that frame only obstructs vision on smaller builds, like fighters, small transports, and corvettes. You can't even use glass in a 0.25m space because our smallest glass block is a minimum of .50m tall and wide. That is unnecessary, and has been extremely limiting and exhausting on numerous occasions.

While I understand wanting glass to look realistic and framed, it is toxic for smaller builds. Frame-free bricks, at least, should be added. The existed glass pieces could easily be removed and replaced by the five standard block shapes we already have, and without creating the collision issues found on the angled glass pieces, which also awkwardly stick out.

There is no need for a glass block shape discrepancy of this caliber when we already have perfectly fine block shapes.

We have 5 brick shapes for building, please give us the identical 5 for glass. We can do the frames, and this would also make them paintable.

**Comment by tsunamayo** [comment]
@Regnion yes that was the plan all along. Framed and frameless version of the glass bricks. I will make a 0.25cm with 1/4 thickness (so 6cm), and a 1m with 0.25 thickness. I think for people that dont want to spend 100h on their build it is cool to have framed versions. Also you cant do a real framed wedge on your own.
As for borderless canopy, well with 0.25m mini glass I think you will be able to make your own prefab, that might be better.
Also @ZachZent I didnt think about paint gold a window, but now that you said it it might look sexy...

**Comment by ZachZent** [comment]
Something like this. Reflective (though not actually reflective in game because that is a nightmare for programming) from a far, see through up close. Same with the other metallic colors. That way if you want the basic color windows, you use the color wheel. When you want one that is tinted, you go with metallic

![image](https://user-images.githubusercontent.com/36980446/113248991-d278ef00-9272-11eb-9aae-9c736d35aa45.png)
![image](https://user-images.githubusercontent.com/36980446/113248780-757d3900-9272-11eb-8eda-2aaa8dba9eed.png)

**Comment by Kaiser-Indrasil** [comment]
> @Regnion yes that was the plan all along. Framed and frameless version of the glass bricks. I will make a 0.25cm with 1/4 thickness (so 6cm), and a 1m with 0.25 thickness. I think for people that dont want to spend 100h on their build it is cool to have framed versions. Also you cant do a real framed wedge on your own.
> As for borderless canopy, well with 0.25m mini glass I think you will be able to make your own prefab, that might be better.

@tsunamayo I don't think I've ever seen anyone complaining about the borderless tetra glass block.
However, there were quite a few people complaining about the bordered glass pieces. And not only seasoned builders, but new players, too.
Having the borders on glass actually takes me more time to hide them within the window frame (left window in the pic below).
Also, it's impossible to have an illusion of curved glass because there are borders in the way (right window in the pic below).

![image](https://user-images.githubusercontent.com/63756057/113312520-4adac100-9302-11eb-9ce2-c744e26c1530.png)

This is another reason why I think we should get rid of the glass borders altogether and have the recolorable glass instead. There That way, there would be just one material to work with in their case.

**Comment by ProPeach** [comment]
> This is another reason why I think we should get rid of the glass borders altogether and have the recolorable glass instead. There That way, there would be just one material to work with in their case.

I don't think we need to get rid of bordered glass altogether when we can just have both bordered and borderless as Tsuna is talking about, they both have their uses

**Comment by TIKIRobo** [comment]
My one suggestion would be when "painting" heavy armor on you should also be able to pick from some textures, that way not every heavy armor battleship has the same texture of armor

**Comment by BigBadKangaroo** [comment]
Would love to get some custom colors on my ships!

Regarding the material paint: will you be able to color blocks that have the same shining effect like the silver/gold/copper colored blocks just with some other colors?
![20210402150821_1](https://user-images.githubusercontent.com/81495956/113418226-5ba03b00-93c5-11eb-8408-bbc7b70ba758.jpg)
like the left side, but with different colors like blue/green/red etc?

**Comment by Kadzar** [comment]
Bit late to the conversation here, but I'm wondering if the material paint system might allow for some kind of scaffold block, as in a kind of block that doesn't provide any stats but temporarily stands in to help plot out the shape of a ship when you don't have all the necessary materials, which would be useful once survival comes along.

Regardless, I really like this idea. Also, does this mean blocks could be placed already having a certain paint/material set?
