### ISSUE TITLE
[Dev Asks] Brick scale

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#3702]
Another topic related to the voxel refactor is block scale.
I will be able to give block of larger scale, ie 4m , 16m, maybe more.

Now I have two path to do this:
1) duplicate blocks. 
2) add a new scale parameter in the brick data.

=> the scalable or multi scale bricks would be the hull brick, the construction, pipe and system. 

Each have their pros and cons. 
1) **duplicate blocks**:
+ doesnt requires a new keybind. 
+I could manage the increase codex size with a simple filter button: if you are working at a smaller scale you simply toggle them out. 
+ It is also dont require any migration code
- I will need to add by hand a lot more block in code...

**2) scale parameter.**
+ more powerfull
+ allow a finer granularity: 0.25, 0.5,1,2,4 for example instead of 0.25,1,4. I dont think it is really needed as you can rescale block up to 16x time!
+ greatly reduce codex simplicity
- require some migration code.
- require a new keybind, bigger learning curve. 

Tell me if you see any more things!

**Comment by ProPeach** [comment]
I vote option 2.

Scrolling through the codex for the exact block you want in the exact scale would be a little painful, even with some helpful filter options. The workflow would be -
Open codex > click filter > find block > drag block to hotbar, maybe replacing another useful block if you're already using all three hotbars which I find to be very full already.

Compared to the potential of just hitting a hotkey without even looking at the keyboard and *instantly* getting the size you want, maybe with a bit of scrolling through the hotbar using more hotkeys, number 2 is vastly superior in terms of user interaction. 
I completely understand not wanting to overloaded the player with a lot of hotkeys though. However, I think that can be solved with better hints or documentation. A small key in the bottom corner of the screen that shows some handy keybinds like toggling mirror, scaling a block or rotate an axis that dissapears when you switch to an empty slot on your hotbar for example.
Hotkeys take a minute to learn, and are the fastest form of input on the fly during building. GUIs are slower, clumsier and less accurate.

Add to that the possibility of more sizes, numbers 2 is the clear winner in my opinion.

**Comment by tsunamayo** [comment]
yeah the more I think about it the more I want option 2. 
There are many advantages: for example I wanted to do new framed windows: a 1m wide with 0.25m thick border, and a 0.25 wide with mini border (0.25/4 wide), as it would make more sense. This is the same brick, just at different scale. 
Or if you want a (mostly) spherical tank. Sure you dont get as much granularity as if it were stretched, but a 0.25, 0.5,1,2,4 is not that bad.
One think that will be tricky though is the stats balancing.

**Comment by ProPeach** [comment]
Personally I'd much prefer the border was kept a constant thin thickness throughout the scaling levels, but I can understand if that's not an option.
That's a great point with the tank, I'm sure there are loads of ways to use the scaling options purely aesthetically

**Comment by tsunamayo** [comment]
@ProPeach it would make little sense, you need think border if you are doing say a 200m wide station module. You are not gonna see that 6cm wide border very far... Also it would look stupid to have a 1m think wall of glass and a 6cm border. I wanted that change because it feels for natural to have the border and the glass thickness be the same.

**Comment by ProPeach** [comment]
Yes that's true, I had in mind a large viewing window on a yacht or similar that you'd want perfect visibility from, but in that case you can just use the borderlands glass you mentioned in the other thread so that's solved.

On a similar note, do you think there is a solution for being able to see the side of borderlands glass through adjacent glass bricks? You can see the issue with the current small glass side triangles, it looks like a border from most angles so could get in the way of the borderless look

**Comment by ProPeach** [comment]
Ah also, did you have any more thoughts on increasing the stretch limit itself? Say to 32x or 64x instead of the current 16x etc. That could have to potential to improve ship performance more, as we could use fewer larger stretched bricks instead of more smaller ones. Larger scales would help with that in a lot of cases, but not all

**Comment by ExodistSKY1** [comment]
Option 2

**Comment by Regnion** [comment]
Option 2, but on to to other comment about glass-

How about NO glass borders? We can make our own frames with bricks or blocks, there is no need for an additional frame to come with the glass, especially when that frame only obstructs vision on smaller builds, like fighters, small transports, and corvettes. You can't even use glass in a 0.25m space because our smallest glass block is a minimum of .50m tall and wide. That is unnecessary, and has been extremely limited and exhausting on numerous ocassions.

While I understand wanting glass to look realistic and framed, it is toxic for smaller builds. Frame-free bricks, at least, should be added. The existed glass pieces could easily be removed and replaced by the five standard block shapes we already have, and without creating the collision issues found on the angled glass pieces, which also awkwardly stick out.

There is no need for a glass block shape discrepancy of this caliber when we already have perfectly fine block shapes.

**Comment by Garrett-C** [comment]
Just to be chaotic... Option 1.

Nah option 2 does sound good. I can see it being a bit odd on something like the fuel tanks which work at a weird scale currently but should be fine.

**Comment by Briaireous** [comment]
Option two for me, would love it if stretch could be greater than 16x or at the very least allow the prefab doors stretch greater than 4x their size

**Comment by TIKIRobo** [comment]
option 2 but instead of using hot keys to make it larger and smaller you could instead use the radial menu so that you could still only have one block in the codex and not have to spam the hotkey to change the size a lot

**Comment by BigBadKangaroo** [comment]
> 
> 
> option 2 but instead of using hot keys to make it larger and smaller you could instead use the radial menu so that you could still only have one block in the codex and not have to spam the hotkey to change the size a lot

Really like the idea of that!

**Comment by 5URG3** [comment]
Option 2.

I like the idea of Ctrl+Scroll for changing block size.

**Comment by SnowyBirdot** [comment]
I very much support option 2. That sounds excellent.
