### ISSUE TITLE
Manual Grid Adjustment

### ISSUE THREAD

**Issue by JimStarluck** [tsunamayo/Starship-EVO#3770]
Having played both the stable release and the "No Voxel" branch, I've fairly consistently found myself moderately frustrated at the way blocks will keep trying to snap to grid alignment, despite all attempts to manipulate them into off-grid positions. I already feel like this will be exacerbated by the scaling blocks always trying to snap to one-block-width positions; if I need a big block to move over a tiny amount, it may lead to a major headache getting it to cooperate.

At first I was going to ask if we could have blocks snap to points smaller than their width -- maybe 1/2 width, maybe 1/4 -- but then a much more elegant solution occurred to me:

A Tool that lets you move the grid around. Re-align it on the fly, as you need it.

It would probably have to be limited to 1/8 block increments, but just being able to pick where larger blocks will want to align to would be immensely useful.

**Comment by tsunamayo** [comment]
Hi @JimStarluck , thanks for the feedback. Other players reported the same, but at this stage I need to understand the problematic better to give the best solution.
So could you please give me more examples when you need a finer grid? What kind of blocks you need to offset, it which situations? 
Cheers

**Comment by JimStarluck** [comment]
It's not any one specific block, but whenever I find that I want or need to place a block anywhere outside its native grid alignment, it's as if it... resists being offset.

Here's an example.

![image](https://user-images.githubusercontent.com/77904316/117732302-a596f080-b1bd-11eb-8c81-7aaca670f6fc.png)

The two grey blocks here are both 8x8x8, both placed against the end of the lattice girders. The upper block is aligned to its native grid, but because the lower lattice girder is offset by 1 meter, so is the lower block.

If I try to place another 8x8x8 adjacent to the lower block, however, I get this:

![image](https://user-images.githubusercontent.com/77904316/117732414-daa34300-b1bd-11eb-91aa-e47734f8ce8f.png)

The new block wants to align to the same grid as the upper block, instead of lining up with the bottom block. If I want to build off of that bottom block at all, I have to keep fiddling with the new blocks to get them to stay aligned to it, usually by placing a bunch of filler blocks to limit their placement, then deleting those afterwards. It's a big hassle to get things to cooperate.

What I have in mind would be a tool, along the lines of Symmetry and Copy-Paste, which allows you to click and drag the points of the grid, to go from this:

![image](https://user-images.githubusercontent.com/77904316/117732953-bd22a900-b1be-11eb-9606-1892705ba830.png)

...to this:

![image](https://user-images.githubusercontent.com/77904316/117733091-fbb86380-b1be-11eb-84f7-5390aae682e7.png)

Then you can build off the cube without having the blocks fighting you every step of the way.

**Comment by tsunamayo** [comment]
@JimStarluck okay understood, but the big question mark is why you need to build that? I mean what are you trying to build? I will add a vertical lock for hull block, so you will not be able to place the first offseted block - unless you activate a toggle in the upcoming building options. 
It makes sense to give vertical freedom for seat, weapon or other system, but less for construction blocks.
I think the confusion comes from this - at least for this particular case.

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Not really - many new players explained their confusion as to why they can't place any and all blocks, especially the hull blocks, at an offset. In terms of the new dynamic grid, we are expecting offset blocks to make their own local grids - sort of like the child entities do, but without, you know, an actually new entity.

That's why using pistons has been the go-to way to offset 1m blocks in brick (0.25m) increments, in any axis of the 3-dimensional space, not only vertically.

Introducing 3D local grid offset would alleviate the issue of over-using pistons, ultimately improving performance thanks to smaller number of child entities.

It would also make building more intuitive, especially since new players are asking us more experienced players, why can't they build lightcruise engines on a brick grid. 😏

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil I understood, at this point if you want to help me show me the stuff those player are trying to build!
System I get it, I will add a finer grid by default. But construction block it is still not clear. Your proposed solution has some drawback, imagine you built a wall at an offset. You dont really know / forgot it has an offset, it dont shows up well, and you start building on it only to realise your stuff do not align. 
It will add confusion and frustration too. With this system instead of having one grid you need to keep track / memorize potentially many more...

**Comment by ProPeach** [comment]
The goal of these offset systems we've been suggesting is the opposite of that, it's to ensure that wherever you've placed something, it doesn't matter because everything can be offset. At that point nothing is really "offset" as there are no multiple grids to offset from. In stead of keeping track of every local grid (1x, 2x, 4x, 8x, 16x, 32x, lots of grids!), you can place anything anywhere.

The main issue isn't just offsetting in one block in one direction (like a seat for height), it stems from needing to keep building off a block has been offset in one or more directions.

Here, I've started building in 16x, and build a 2:1 slope (black). Then, I extended the slope a little further in a smaller 4x  because my design called for it (orange).
![image](https://user-images.githubusercontent.com/27857711/117741372-3ab7da80-b1fa-11eb-987e-efa6222e39a3.png)

What I'd like to do is place a 2:1 32x slope here, to continue the edge. I want to keep using the 32x grid for convenience at scale and performance
![image](https://user-images.githubusercontent.com/27857711/117741464-781c6800-b1fa-11eb-9bf7-566be0c6f644.png)

But I can't continue the edge I was creating because it is no longer on the 32x grid
![image](https://user-images.githubusercontent.com/27857711/117741420-5de28a00-b1fa-11eb-8512-dc87b1b827ee.png)

This is the kind of issue that having multiple scaled grids creates. I'm not sure what you mean when you say this system has one grid, in my eyes it feels like it has a separate grid for every different scale, which is where these issues arise.

I hope we're getting better at conveying the problem, this kind of thing can be tough

**Comment by JimStarluck** [comment]
This particular example came from me re-evaulating an in-progress build. I was doing multiple layers of armor with space for equipment & systems in-between. The armor layers as I've been building them are all odd numbers of meters thick.

I was trying to see if I could re-arrange things to exploit the newer, larger blocks, but with the way I had it set up, each of the armor layers were offset from the blocks that were closest to them in thickness. I could use a smaller block size, of course, but that would mean I'd wind up having to use a greater number of blocks to fill the same space, simply because the geometry worked out that it didn't line up with the right size of block.

That said, I've run into these kinds of situations consistently since I started playing the game: moments where getting the exact shape I want/need is immensely frustrating because it doesn't *quite* line up with the grid, and I have to beat the blocks into submission to get the desired geometry.

**Comment by Kaiser-Indrasil** [comment]
Uncle Ulty made [an actually amazing suggestion](https://github.com/tsunamayo/Starship-EVO/issues/3771#issuecomment-836958389) on how to solve it efficiently.

No need for local grids when you can just change the grid size itself with a button.
I would assign the button "G" instead of "Y", simply because it's not used by the game yet and it's closer to the WASD section.
"G" to increase grid size, and "Shift+G" to decrease the grid size.

@tsunamayo Here's a personal example. When building my fighter was already an experienced builder, so I knew I had to place the key blocks first - like lightcruise engines - and only then move onto brick-based hull.

However, what if I started building the other way around, as in, bricks first, big blocks later? I would probably run into a scenario like this one below, where I can't fit a lightcruise engine neatly into the hole.

![image](https://user-images.githubusercontent.com/63756057/117741756-0b559d80-b1fb-11eb-8c42-b39826f110d6.png)

It isn't a theoretical scenario, too. Back when I first started working on the Astero, I started building with bricks and only then realised that my engines are misaligned.
I literally wasted 3 whole days building it wrong, had to scrap it and start all over.

**Comment by ProPeach** [comment]
Staying with Lightcruise thrusters for second, even now with a smaller 0.5m size, you can't place your thruster along the centreline on a ship because the 0.5x scale sticks to the 0.5m grid. Being able to place this on the 0.25m grid would solve this.
![image](https://user-images.githubusercontent.com/27857711/117742235-31c80880-b1fc-11eb-9080-84f4f0ac6e46.png)

It sounds like some of your future offsetting tools will do exactly that which is perfect, I'm just trying to help explain some different use cases.

**Comment by tsunamayo** [comment]
The basic rule of multi-grid is to start with the highest possible grid and then proceed with the smaller grid details.
I think it make sense. Like you dont start to put up chairs and table and then build the wall of your house. 
In the case of lightcruise that fits in a smaller brick size build - it is a valid user case. It should be taken care by the smallest grid for system.
=> maybe it will time to get some hint during the loading screen, and that could be a nice first rule to show!

@JimStarluck Retrofitting an existing ship wont work - it is a case of starting at a small grid and then moving on to the bigger one. It wont work - not a big deal, use the bigger blocks for your next ship! 

@ProPeach Yes I know in that very case, but of course the logical and natural way of having several grid is the have them "fits" together (just like lego is doing), instead of having their origin align. 
Once you know the largest grid you know all the smaller one (and dont need to keep track of the smallest grid, you only track the largest one). But yes, when you know the smallest one there are several ways of "creating" the largest one (hence get confused, I guess if you work for long time small and you forgot about the largest one). 
But if your hull is made out of the largest grid blocks you should not forgot about the largest grid, just like when you where mixing 0.25cm bricks and 1m blocks. Your hull is made of blocks. If you just have a few big block inside your ship then I can understand the frustration, but then you shouldn't have just only one or two big blocks (apart from systems! I think we well spotted that need for finer grid for system).

Thats is why I dont like the suggested proposition (ie target grid instead of global grid), what should I do when you put a 2m block onto an 1m or smaller one? There is several way of doing that.  I get it that would be natural for offset building but that is not a very solid rule. In your example case (thanks a lot for that), just build at 4x, period! Block can be rescaled, the multi-grid system is not made to be that intricate honestly.

Cheers guys

**Comment by ProPeach** [comment]
The problem is players building ships don't follow basic rules, they build chaotically. Sure they'll likely block out a rough shape in a chose scale, that was easy back when we just had 1m to choose blocks. But now there are 9 different sizes with separate grids. Players will use a large shape for a large part, a smaller shape for a smaller part. These parts will not always be even grid sizes apart.

Lego is a brilliant example of why different sized pieces need a common, smaller interval, not multiple different grid sizes. All the large Lego cockpit pieces etc are not on their own grid, they can be placed anywhere on your Lego build, even "offset" using a Lego tile which is thinner than a Lego stud

The issue isn't forgetting about the largest grid, it's about having to remember it all the time, and having to keep in mind each separate grid in every part of your ship.

But the smaller grid interval will help with that, being able to set your placement interval to 1m while placing 4x blocks for example. The problem then becomes once you've placed for example a 4x block off the 4x shipwide grid using a 1m placement interval, if you want to place another 4x shape on it and align to it perfectly, you're forced to keep using a 1m interval setting. This means you have to be very precise where your mouse is pointing, which is an even bigger problem at larger scales. Imagine trying to place a 32m block on another 32m block, and having to point exactly at the 1x1m square to get them to line up. That is why @Kaiser-Indrasil's local grid in #3768 or my smart toggle idea in #3753 is so important, to lock blocks to similarly sized faces. You wouldn't need a GUI list (which is very slow to use) to switch interval sizes or vertical locks, because the game does it for you. This emulates Lego, and how it perfectly integrates pieces of all different sizes and shapes.

In regards to placing a larger block on a smaller block, if you give the player a constant result to follow, they'll get the hang of it very quickly. For example, the larger shape always places below and to the right of the target block like this:
![image](https://user-images.githubusercontent.com/27857711/117748713-735eb080-b208-11eb-8d45-66beb8ea87e9.png)

More use cases for a local grid effect are offsetting with tiles and thin tiles at any scale, but especially small scales which make small details a dream to design.

Offsetting in the old, voxel based build system was a bit of an expert trick yes. But now there are 9 different grid sizes rather than 2, having parts of your build offset will happen whether a player tries to or not and I think the game needs to be smarter about it and more streamlined to cater to that.

**Comment by tsunamayo** [comment]
> The issue isn't forgetting about the largest grid, it's about having to remember it all the time, and having to keep in mind each separate grid in every part of your ship.
There is no separate grid in different part of the ship, it is the same everywhere... I guess this is where there is the confusion maybe. You seems to imply that people maybe would want to "spawn offsets" (for a lack of a better word) everywhere? 

For now what I see:
 - Offset for systems => valid use case. System are not building block, they are leaf block more often that not.
 - Offset for building blocks. I dont really see much use for now! Maybe decorate a chair or something like that?
 
I dont appears to me that people where limited by having hull blocks to comply to the 1m grid (no offset for hull blocks in previous builds). Like it is not a request that popped often if at all...

Now if people build chaotically, starting at a smaller scale then moving on the upper scale I guess that's on the builder, Building requires planning.

I dont really like your solution for the placement on smaller target grid. I think it is very arbitrary and would trigger a lot more confusion (and I dont see how to code that). Like it means that depending on how your are oriented related it would place differently!

What about the following rule: the starter block define the maximum grid. ie you spawn a 2m starting block, you will be able to place 4m+ block at 2m interval. I could add a way to change the max grid in the entity definition (maybe even adding a builtin offset if you realize the origin is not where you need). It could also apply for children entity that would have a grid from their mechanism size. You dont build 8m block onto a tiny mechanism. 
Having to target the right space is finicky only if you are really building at that scale. If you are popping a few oversized blocks onto a smaller build is seems manageable to me (because you will be naturally closer).

cheers mate

**Comment by ProPeach** [comment]
> There is no separate grid in different part of the ship, it is the same everywhere... I guess this is where there is the confusion maybe. You seems to imply that people maybe would want to "spawn offsets" (for a lack of a better word) everywhere?

I suppose "offset" is a confusing word it use in general - offset to what?
If a player builds a section of their ship at 4x scale, then builds a segment in 1x scale and wants to switch back to 4x scale to keep building on that, they'd want their 4x blocks to conform to the 1x scale parts in front of them, not the 4x part on the other side of the ship. That's what I mean by having to keep track of different grids. This is solved by the 1m grid toggle you have planned.

> I dont appears to me that people where limited by having hull blocks to comply to the 1m grid (no offset for hull blocks in previous builds). Like it is not a request that popped often if at all...

So larger hull pieces are fine at 1m grid. The issue never arose in the past as at the main hull scale, there was nothing to be offset from, it was all 1m grid. The scalable pieces disrupt that, allowing us to mix sizes that when mixed, cause issues with subsequent blocks aligning with them. 

On the other hand, offsetting was a huge part of how we used bricks in the past. Being able to place a brick half tile, then build off of it in multiple directions that were now consistently offset by a half brick is incredible, and it's a big part of how we build at small scales and was unique to the old bricks.
In this new branch, that functionality is gone - we can offset in one direction thanks to a lack of vertical lock, but not in another afterwards. This is true for all scales, 0.25m to 1m to 32m because there is now no separate brick/block logic. This is the functionality that we're requesting be implemented at all scales with a local grid lock/whatever you want to call it, and we're asking about it now because now every shape follows the same old block logic, not the old brick logic. It means that there's no such thing as being misaligned to a grid, because you can place any brick on any surface and have it line up perfectly.

> I dont really like your solution for the placement on smaller target grid. I think it is very arbitrary and would trigger a lot more confusion (and I dont see how to code that). Like it means that depending on how your are oriented related it would place differently!

I meant a constant placement relative to the orientation of the ship (starter block defined), rather than relative to the player. Like every block would have its starting anchor point in the same location in that case, so that the player can learn it and utilize it.

Personally I don't like the idea that the starter block defining the max grid. I think that it introduces too much variation and nuance to building - different ships would have different grid limits? Even if you can change the max grid, there are already so many different grid elements to keep track of and learn already.

The smaller grid toggle prevents players being frustrated they can't place blocks in most places with a little extra work, but the local grid lock removes any pain from the grid at all. Players could mix different scales or offsets without having to worry that they're doing something in the wrong order or having to worry about the different scales, which has been used to fantastic effect with bricks for all of the games history. 

I really appreciate you talking this through with us, thank you for your time as always o/

**Comment by tsunamayo** [comment]
I see. So there is two philosophies, the block/hull/frame philosophy, where I think it is important to align stuff globally. Ie when you build a bridge from two side you want to see each side meets, and not have a mismatch because you built at on offset along the way without realizing it.
Then the brick/detail philosophy where you want from freedom but still want to align locally.
I guess you guys where using the offset / half tile more than I realized. You have some build where I can check this?

I still think the fitting of a larger block onto a smaller one needs a clear answer. Also I am not sure how to implement the whole thing cleanly. It seems to add tons of complexity...

**Comment by ProPeach** [comment]
I hope you don't mind SW builds, it's all I've been able to make for a long while 😝

The nose and guns of this bp are offset vertically to centre them. The nose by a 1/4th of a brick, the guns by a 1/2 brick
https://steamcommunity.com/sharedfiles/filedetails/?id=2186636546

A lot of the detail on the arms and wing hubs is offset on this one
https://steamcommunity.com/sharedfiles/filedetails/?id=2350179471

Various details of this one are offset, as well as large parts of the interior
https://steamcommunity.com/sharedfiles/filedetails/?id=2350208314

The fins here are offset by a tile
![image](https://user-images.githubusercontent.com/27857711/117761182-d65b4200-b21e-11eb-8336-154a757696aa.png)
[U-Wing.zip](https://github.com/tsunamayo/Starship-EVO/files/6456633/U-Wing.zip)

This one has a lot of offset details and some larger panels. Pretty much any time anyone uses a pipe with a half pipe element, they're offsetting in at least one direction
[CR90 Engine Block.zip](https://github.com/tsunamayo/Starship-EVO/files/6456646/CR90.Engine.Block.zip)
For example, most of these elements are at least half a brick off the "regular" grid
![image](https://user-images.githubusercontent.com/27857711/117761774-df004800-b21f-11eb-9c87-928952d68935.png)

This door and the greeble to the right of it extensively use offsets for depth
![image](https://user-images.githubusercontent.com/27857711/117762000-3a323a80-b220-11eb-8522-86c678920c5a.png)

A lot of these things are perhaps hard to notice that they're offset, because once you start offsetting the "grid" follows you when working with bricks. A really simple thing to with that is have a build an odd number of bricks wide by offsetting a brick by a half brick sideways etc.
You see that a lot in this bp, the engine pods etc and some centerline greeble
https://steamcommunity.com/sharedfiles/filedetails/?id=2186624792

**Comment by Kaiser-Indrasil** [comment]
Offsets are a MASSIVELY prevalent technique I employ in my builds. Just look how many use cases I have for it, and it's just a tip of the iceberg. I used the Legacy branch for readibility reasons:

[SoE MEEP - Multi-Environment Escape Pod](https://github.com/tsunamayo/Starship-EVO/files/6460003/SoE.MEEP.-.Multi-Environment.Escape.Pod.zip):

![image](https://user-images.githubusercontent.com/63756057/117828498-c3219400-b269-11eb-99e3-7a19f9680237.png)
![image](https://user-images.githubusercontent.com/63756057/117828938-33c8b080-b26a-11eb-93ed-2c777f3e109f.png)
![image](https://user-images.githubusercontent.com/63756057/117829070-4f33bb80-b26a-11eb-87d7-bb4c8cf3c033.png)
![image](https://user-images.githubusercontent.com/63756057/117829415-a46fcd00-b26a-11eb-9da4-781522c9ca63.png)
![image](https://user-images.githubusercontent.com/63756057/117830075-3677d580-b26b-11eb-9091-1c2496e55a49.png)
![image](https://user-images.githubusercontent.com/63756057/117830443-8e164100-b26b-11eb-9e39-2f10e273848f.png)

[TAC-1 Terran Advanced Cargo containter](https://github.com/tsunamayo/Starship-EVO/files/6460012/TAC.1.zip):

![image](https://user-images.githubusercontent.com/63756057/117831217-45ab5300-b26c-11eb-8dc6-b983000aed14.png)
![image](https://user-images.githubusercontent.com/63756057/117831481-84410d80-b26c-11eb-8970-f4985eb113bc.png)
![image](https://user-images.githubusercontent.com/63756057/117831661-b05c8e80-b26c-11eb-8906-1c28ce3b1c7a.png)
![image](https://user-images.githubusercontent.com/63756057/117831798-d5e99800-b26c-11eb-8316-745693e6e24d.png)
![image](https://user-images.githubusercontent.com/63756057/117832126-1f39e780-b26d-11eb-8afd-2008f827356a.png)
![image](https://user-images.githubusercontent.com/63756057/117832382-590aee00-b26d-11eb-9065-df309c146aa4.png)

[Gallente Hobgoblin light fighter drone](https://github.com/tsunamayo/Starship-EVO/files/6460070/Hobgoblin.zip):

![image](https://user-images.githubusercontent.com/63756057/117832733-a8511e80-b26d-11eb-9868-c2d558d06b54.png)
![image](https://user-images.githubusercontent.com/63756057/117832945-d59dcc80-b26d-11eb-80e7-aaf9069b6da2.png)

[Sisters of Eve frigate](https://github.com/tsunamayo/Starship-EVO/files/6460080/Astero.-.Sisters.of.Eve.frigate.-.EVE.Online.zip):

![image](https://user-images.githubusercontent.com/63756057/117836134-578ef500-b270-11eb-98f5-8f9774e1c252.png)
![image](https://user-images.githubusercontent.com/63756057/117836763-c5d3b780-b270-11eb-9aa2-99718326507c.png)
![image](https://user-images.githubusercontent.com/63756057/117836863-dd12a500-b270-11eb-9f9a-16126ff6b330.png)
![image](https://user-images.githubusercontent.com/63756057/117837031-029fae80-b271-11eb-9db6-585f388983d7.png)
![image](https://user-images.githubusercontent.com/63756057/117837444-5dd1a100-b271-11eb-8b0d-5908a68a5b92.png)
![image](https://user-images.githubusercontent.com/63756057/117838978-b35a7d80-b272-11eb-88ca-ca60cc200f18.png)
![image](https://user-images.githubusercontent.com/63756057/117839408-1c41f580-b273-11eb-9877-e795feb163a1.png)
![image](https://user-images.githubusercontent.com/63756057/117840101-c1f56480-b273-11eb-877c-d39f5e7e3f0c.png)
![image](https://user-images.githubusercontent.com/63756057/117840846-6b3c5a80-b274-11eb-817a-22b7ee5df741.png)
![image](https://user-images.githubusercontent.com/63756057/117848760-8363a800-b27b-11eb-9e40-e192f4feaa8a.png)
![image](https://user-images.githubusercontent.com/63756057/117848994-c7ef4380-b27b-11eb-934b-4e4d37a53d88.png)
![image](https://user-images.githubusercontent.com/63756057/117849263-0be24880-b27c-11eb-84a6-7235a09878af.png)

**Comment by schlid** [comment]
Haven't been paying much attention to the new branch but to hear offsetting is going to disappear is incredibly disappointing. When building smaller ships offsetting allowed for a much greater level of detail that is otherwise unachievable.
If offsetting were to disappear so would much of the subtlety and nuance of many small ships and interiors.

**Comment by schlid** [comment]
Also worth noting how are you meant to recess a button into a surface without using offsets :') 
![image](https://user-images.githubusercontent.com/31857052/118282257-024c2100-b4c6-11eb-998d-aa2c9db16599.png) - pic courtesy of Indrasil

**Comment by Womble-TC** [comment]
If brick offset gets removed, I will be sad for serveral days

**Comment by glorbo703** [comment]
If brick offset gets removed, I will uninstall computer

**Comment by PopkaAkula** [comment]
![image](https://user-images.githubusercontent.com/37738021/118301609-9082d000-b4e3-11eb-8a3d-77b17d7505fa.png)

I wouldn't have been able to build this without offsetting.

Please don't get rid of it, offsetting is fundamental in building detail with bricks.

**Comment by AlienXtream** [comment]
@tsunamayo i think you are overthinking it a bit on the whole thing. imo the solution is quite simple. have both. have blocks snap to their scaled grid by default BUT have it so you can use a modifier key (ctl, shift, alt) to override that and snap to the small 1/8 increments. that way you have the alignment of a fixed snapping size to deal with your bridge example AND the freedom for detailed and niech cases.

**Comment by Kaiser-Indrasil** [comment]
1/8m for all sizes would be quite unwieldy for bigger blocks.
I'm a big advocate for the separation of block size and grid size.
You could switch the grid sizes with G and Shift+G.
Of course, every time you would change the block size, the grid size would change itself to be the same as the block size.
People who'd rather want their blocks to align neatly would never have to use it.
Meanwhile, folks like me who breathe offsets, would use it all the time.
It's a win-win.

**Comment by Garrett-C** [comment]
I mean surely a dynamic system where the grids operate based on other grids is more user-friendly than a fixed grid where blocks should fit in a spot but are offset in a way you have no control over...

Why not have the game look at the block in your hand and the one you are looking at and have you place on the smaller of the 2 grids? It's a dynamic solution which maintains offsets, doesn't require a key bind and would be easy to understand why things are placing the way they are.

**Comment by tsunamayo** [comment]
@Garrett-C yeah I want to give the choice of two mode, the local grid and the global grid. Local grid like you described, how brick used to work, and global is how hull block used to work. Local is also messy and could introduce all sort of misalignments - so it is good to have global. Also what the game is supposed to do when you build onto a brick that has a smaller grid? There are several way of placing it - so there is no right way of doing it. Sometime the target grid is also not evident to see - especially with the new border look.
People keeps bugging me saying the local grid is arbitrary and "you need to remember all the grids" (while I say there is just the largest one and you defined it with the starter block), but with local there is as many grid as there is block in your ship...

@schlid I never said I wanted to remove offset, I said I wanted to use the same system as copy/paste... And also give smaller grid setting in an upcoming F1 / Build mode menu. I have written that many time so I dont know where it comes from...

**Comment by Garrett-C** [comment]
> @Garrett-C yeah I want to give the choice of two mode, the local grid and the global grid. Local grid like you described, how brick used to work, and global is how hull block used to work. Local is also messy and could introduce all sort of misalignments - so it is good to have global. Also what the game is supposed to do when you build onto a brick that has a smaller grid? There are several way of placing it - so there is no right way of doing it. Sometime the target grid is also not evident to see - especially with the new border look.
> People keeps bugging me saying the local grid is arbitrary and "you need to remember all the grids" (while I say there is just the largest one and you defined it with the starter block), but with local there is as many grid as there is block in your ship...
> 
> @schlid I never said I wanted to remove offset, I said I wanted to use the same system as copy/paste... And also give smaller grid setting in an upcoming F1 / Build mode menu. I have written that many time so I dont know where it comes from...

I mean honestly yeah the way brick offset works currently is probably the best way to do it yeah so that sounds good. Would that only be for blocks of the same size though? The issue currently seems to be that if you go to use say a 16x16 block currently it is on an arbitrary grid of it's own and as such often won't line up with your build. 

I do think perhaps something like what you have for systems currently could work to an extent, where there is a finer control. I mean I can see why this wouldn't always be ideal, placing a 16x16 block at 0.5m increments would be very tedious, but it would mean that players aren't left annoyed at why a block isn't going into a space it should fit in. 

I guess the easiest option programmatically may be a key which when held gives you a fine placement control however I do get that you don't want the building to require loads of hotkeys. That's sort of why I suggested that maybe the game just defaults to selecting the smallest grid between the held block and the block you are looking at. Not a perfect solution I agree but it does give the player control without needing a hotkey. 

I definitely think there is a better way of doing it and hopefully, you come up with one but I do hope that it's one where you have more control of blocks than you currently do.

**Comment by tsunamayo** [comment]
@Garrett-C you are trying to refit a ship started with 1m blocks with 16m blocks so it will never work - forget it. This is something I will have to write in my patch note as a lot of people gets frustrated. Use bigger block on new ships!
You have to start with the higher scale and then proceed to smaller detail thereafter, not the other way around. Hence the multi-grid starter block.

**Comment by Garrett-C** [comment]
> @Garrett-C you are trying to refit a ship started with 1m blocks with 16m blocks so it will never work - forget it. This is something I will have to write in my patch note as a lot of people gets frustrated. Use bigger block on new ships!
> You have to start with the higher scale and then proceed to smaller detail thereafter, not the other way around. Hence the multi-grid starter block.

I just don't think that's a good mentality or approach to the building though. That's a system that will just annoy players. Nobody builds like that currently and the idea that people are now going to start building in such a structured way is a very flwaed one. The idea that there is a definitive way to build will never work. I believe peach said it best a while back, platers are chaotic. They will build things in weird orders and it is going to be frustraiting when you get halfway through a build and then try to use a larger block and nolonger can. 

The multi grid starter block really doesn't solve anything. If you can use it to move grids like I believe you mentioned then it could help, despitre being a very clunky way of doing it, but the idea of saying "You can't use blocks bigger than the starterblock" is just going to result in people using bigger starter blocks incase they decide they need big grids. 

At the end of the day I think the issue here is mostly that while building from big down to small would make sense and make things easier it's just not a realistic assumption of how people build.

**Comment by tsunamayo** [comment]
You can build bigger than your original grid, it is just the grid origin might not be where the player wanted it because the player only specified a lower grid at the beginning. 
Say you build a fighter with 0.25m bricks. Then change your mind and want a corvette and start to use 1m block. Well the grid might not be where you want because you lay down only the 0.25 cm origin. I can always give a grid offset setting in the entity codex if it is necessary.

The multi-grid starter block precisely solve that problem. It seems that you think I should get grid of the global grid entirely?
 
I still think you guys think it is major big deal because all you had done for now it trying to retrofit existing ships. Let me finish that update, then have you guys start building new ships and will we see how it goes. 
Solid feedback comes from solid use case, retrofitting existing ship is not the goal of this update.

Supposing that the player knows beforehand what he is gonna build, then start on the hull before moving onto details doesnt seems too much of a stretch. You will always run up into issues if you start details first - thats the builder responsibility, not mine.
Still chaotic builders will be able to use the local grid all the time, so they should be happy. But I think we should not give up on the global grid. People have been using a grid in every game out there, it is useful for normal gents who like to build their hull before their shower ;)

**Comment by Garrett-C** [comment]
> You can build bigger than your original grid, it is just the grid origin might not be where the player wanted it because the player only specified a lower grid at the beginning.
> Say you build a fighter with 0.25m bricks. Then change your mind and want a corvette and start to use 1m block. Well the grid might not be where you want because you lay down only the 0.25 cm origin. I can always give a grid offset setting in the entity codex if it is necessary.
> 
> The multi-grid starter block precisely solve that problem. It seems that you think I should get grid of the global grid entirely?
> 
> I still think you guys think it is major big deal because all you had done for now it trying to retrofit existing ships. Let me finish that update, then have you guys start building new ships and will we see how it goes.
> Solid feedback comes from solid use case, retrofitting existing ship is not the goal of this update.
> 
> Supposing that the player knows beforehand what he is gonna build, then start on the hull before moving onto details doesnt seems too much of a stretch. You will always run up into issues if you start details first - thats the builder responsibility, not mine.
> Still chaotic builders will be able to use the local grid all the time, so they should be happy. But I think we should not give up on the global grid. People have been using a grid in every game out there, it is useful for normal gents who like to build their hull before their shower ;)

I don't think that's quite right. The issue is that this building sequence you picture isn't really accurate to how everyone builds.

For example some people may choose to block out a skeletal frame of their ship first, this big to little build order you are picturing works fine there. But not everyone builds like that. 

Personally I choose a feature that I have an idea for like a thruster array or a bridge for example. I build that up and then I work on building more of the ship around that. That approach won't really be very compatible with these uncontrollable grids that larger blocks conform to. 

Picture spending a day or two building up a cool bridge for your ship, then you got to start to build the ship around it and you find out thay you can no longer use 16x16 blocks because the grid won't line up. That feeling is going to suck and is going to make building using these different grids quite infuriating for players. 

The nee scales are great, I have been an advocate for stupidly large ships since day one and I can't express how glad I am that this new tech really opens the door for things like that in a realistic way, however with this weird grid stuff it sort of feels like we haven't really ditched voxels. 

I get that it's not a 3D modeling software, so we shouldn't expect to be able to do everything we can imagine doing, and I can't even begin to imagine how complex it could be to get the code to work right, but honestly without some way to fix the grid so you have more control over where you place larger blocks, building is just going to become more clunky and less intuitive. 

I get where you are coming from when you say that the issue is from us trying to retrofit older ships but I don't think you are realising that in the process of building new ships you often have to go back and make changes. This will lead to this same issue at some point and it is going to really annoy people when it does. 

Obviously I don't really know much about the technicalities of getting it to work on the back end. Is that part of the issue? I can imagine a global grid being a lot easier to program for. 

I do think something like giving the player some way to move the grid a bit could be a good solution like yoj suggested. Maybe it could even be included in the advanced build mode menu you mentioned. It's not the sort of tool players will probably use for every part of a build but it would help reduce frustrations by allowing players to make adjustments to the grid. Maybe you have some other thoughts on good ways to do this.

**Comment by tsunamayo** [comment]
I said 10x time that I was going to give a local grid toggle ;) It should satisfy you guys. 
Regarding your example, I dont see how the global grid could not help you. Build your bridge. Then build the front end. When these two part meets, with the global grid you are guaranteed to have those two fit! Whereas with a local grid and offset bonanza you are almost guaranteed that have mismatch as you start to join stuff. 
Global grid is just like blocks used to work. Surely it was not game breaking...
Now some guys apparently never used block like Kaiser. But from what I gather it was very extreme replica build, with a lot of decorative children entities, smoothed curve everywhere, for something thats takes several hundred of hours of committed build. I can let this way be my blueprint for a standard build, I need to give something easier for newcomers.

**Comment by Garrett-C** [comment]
> I said 10x time that I was going to give a local grid toggle ;) It should satisfy you guys.
> Regarding your example, I dont see how the global grid could not help you. Build your bridge. Then build the front end. When these two part meets, with the global grid you are guaranteed to have those two fit! Whereas with a local grid and offset bonanza you are almost guaranteed that have mismatch as you start to join stuff.
> Global grid is just like blocks used to work. Surely it was not game breaking...
> Now some guys apparently never used block like Kaiser. But from what I gather it was very extreme replica build, with a lot of decorative children entities, smoothed curve everywhere, for something thats takes several hundred of hours of committed build. I can let this way be my blueprint for a standard build, I need to give something easier for newcomers.

It's more that you would finsh yout bridge and then go to build the hull underneath it with say a 4x4 block only to find that the 4x4 grid locks those blocks say 3 blocks too high cutting into the bottom of the bridge. If you see what I mean. 

I do think you sound like you have some ideas on resolving these issues hopefully so looking forward to what you come up with. 

I think the best solution is to see what you have up your sleeves, try it out and then give you new feedback from there. Excited to see it.
