### ISSUE TITLE
Bug Found (Shipyart point direction and randomly collision)

### ISSUE THREAD

**Issue by ArthKriger** [tsunamayo/Starship-EVO#3786]
Hello again, So, I've working alot with ship yars, make what it looks right, but I found to many issues in this part. First, I try to land it's everthing right but keeps saying autopilot trying to landing. after a huge wile not moving its says welcome. then, some time for no reason, my small ship bee land, start to kick on the mother ship, like colision or somthing, I go there and try to remove, after I press unlock it shoots me for into space. For 2 times I buge the map and lost everthing. I belive isntead of been put some number as as a whay to tell to the sips to do would be more simple, lik efter o place the shipyard, show us a draw with some square of the area of if like 5 per 5 radios, and we dran the front arros on that square. and done. so you should take betther look to the shipyeard.

**Comment by Kaiser-Indrasil** [comment]
"BugFound" is a very vague title. Try to be more specific with the future reports so that we can find and categorise them more easily.
Pictures showing the issue would help, as well as a zipped world folder containing the scenario you've described.
You can find it in the following directory:
`C:\Users\`**_your username_**`\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters`
You can zip it up without any 3rd party software like this:

![image](https://user-images.githubusercontent.com/63756057/119232352-dd3a5c80-bb1c-11eb-8ead-532346138f01.png)

**Comment by ArthKriger** [comment]
[ArthKriger.zip](https://github.com/tsunamayo/Starship-EVO/files/6526733/ArthKriger.zip)

Sorry for that. And for my Inglish as well. 

I will take in considerate next time. 

I delete the previous character, becouse, some who, I end up inside the sun. 

But,on that one, you will see where my shipyard is, the first time I made it, was to use with the landing gear on. after the colision problem, and at new map, I no longer cand land with my landing gear on. only off, If I try it with it on, will start to colision again. then, the front of my small ship, ends inside a small door, I try it like 5 times, was ok, but then, the next trials, my sheep keeps going or to much left or to much right. As no straight line. 

was again thanks for you ammazing work.

**Comment by tsunamayo** [comment]
@ArthKriger Hi, I tested it, it is now fixed. Cheers!
