### ISSUE TITLE
[Suggestion] Copy/Paste tweaks

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Starship-EVO#3799]
### Short Description of the issue:

With the new scaling abilities I think that when using the copy/paste tool to select an area it needs to select in increments of whatever grid size you have active.

So if I had the 1m grid active then when selecting it should move in 1m increments instead of how it currently moves in .25m increments. (When selecting)

This adjustment is a must have I feel since it can be impossible at times to accurately select larger regions, especially with the neovox update.

======================================

In addition we should also be able to see the size of our selection, similar to how we can see the dimensions of what we're stretching

...

**Comment by VentgirlJoanne** [comment]
To add to this, the increments it gets nudged should also be manually scalable. Right now it seems to default to the grid of the largest cube in the selection which means you often can get infuriating moments where it's impossible place the object in allignment at all (see video). I suggest you should either have the ability to choose what the snap grid is manually with T while pasting, or default to the smallest size rather than largest to avoid impossible paste positions.

https://user-images.githubusercontent.com/79483516/121758871-37618880-caf1-11eb-97f5-9475e8bd40e4.mp4
