### ISSUE TITLE
[Bug] Multitool gets cursed when moving away from the active grid

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3829]
Version: 21w21b

Moving away from the grid I was building, the Multitool's model started glitching out.
The farther away you are from that grid, the stronger the effect.

https://user-images.githubusercontent.com/63756057/120686653-1ff32180-c499-11eb-84ff-2b11d7cf6951.mp4

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil I cant reproduce that one. Do you reproduce all the time? Could you send me the log? (send one each time ;) ) It might be because your session was broken too, as it looks like the origin recenter that should happens each frame was not working. Looks like floating point precision issue.
Thanks!

**Comment by Kaiser-Indrasil** [comment]
Yeah, it's probably a session-specific thing since it hasn't happened to me since then.
And yeah, if I ever see it again, I'll make sure to provide you with the log this time 😏

**Comment by tsunamayo** [comment]
Okay, lets book another issue when you see it, to make sure I dont miss the report. Cheers
