### ISSUE TITLE
[Bug] (experimental) Damage doesn't happen to the surface of ships when shooting them with larger weapons

### ISSUE THREAD

**Issue by wick-3d** [tsunamayo/Starship-EVO#3831]
### Short Description of the issue:
the surface of ships will go unharmed while the innards will get a bit roughed up.
-Kind of happens with the formerly 'large' beam weapons but not to nearly the same extent
-has happened on multiple blueprints, isn't specific to one blueprint.
...

### Steps to reproduce the issue:
make a huge beam/laser weapon. Shoot a ship.
...

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
Outside: https://cdn.discordapp.com/attachments/271723356795961345/850169311582224394/unknown.png
Inside: https://media.discordapp.net/attachments/271723356795961345/850169347179806781/unknown.png

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6595039/Player.log)

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Kaiser-Indrasil** [comment]
Haven't seen the old build in a while.

It's not gonna be fixed because an entirely new sticker-based system has been built from the ground up.

I'd suggest you test things out on the Experimental branch and see how it works there.

**Comment by Kaiser-Indrasil** [comment]
A blueprint, or better yet, a world file, would really help with this issue, since it seems to be working fine on my end.
I mean, it's not perfected yet but when it comes to perpendicular shots and big flat surfaces, it's working as intended:

![image](https://user-images.githubusercontent.com/63756057/120806235-81b99700-c53e-11eb-8bae-3cb783be70c6.png)

It's got some trouble with smaller blocks lumped together at weird angles but it works to a degree:

![image](https://user-images.githubusercontent.com/63756057/120806333-a3b31980-c53e-11eb-94ad-0da84b42327c.png)

**Comment by wick-3d** [comment]
> A blueprint, or better yet, a world file, would really help with this issue, since it seems to be working fine on my end.
> I mean, it's not perfected yet but when it comes to perpendicular shots and big flat surfaces, it's working as intended:
> 
> ![image](https://user-images.githubusercontent.com/63756057/120806235-81b99700-c53e-11eb-8bae-3cb783be70c6.png)
> 
> It's got some trouble with smaller blocks lumped together at weird angles but it works to a degree:
> 
> ![image](https://user-images.githubusercontent.com/63756057/120806333-a3b31980-c53e-11eb-94ad-0da84b42327c.png)

You misunderstand, I am REFERRING to the new experimental branch. Neovox, etc.
I don't believe it's specific to a world file or blueprint either. However, I will double check for you. I'll make a new world and double check.

To restate the issue: On the experimental branch (latest as of this post), When shooting ships with big scaled guns, damage will ignore the outer shell of the ship and proceed to only damage the innards.

**Comment by wick-3d** [comment]
Here is a short video I've made demonstrating what I'm talking about: https://youtu.be/MaKxEm41Zug
Sadly I didn't get as extreme of results as when it first happened but I'm confident it should give you an idea.

**Comment by tsunamayo** [comment]
@wick-3d I understand, yes you are correct in this instance it wont quite work. It is made to work with flat hull, 3d layer wont give a good visual appearance due to the inner working of the tech. I dont think it is too much of an issue, as you would only see the hole while perfectly aligned anyway.
The beam / laser wont collide with the backface of the hull, once it pierced it moves to the next brick.
So it is a no fix... Thanks
