### ISSUE TITLE
[BUG] Player Station Generation Can Go Wrong 

### ISSUE THREAD

**Issue by TIKIRobo** [tsunamayo/Starship-EVO#3838]
https://user-images.githubusercontent.com/56371294/120894875-75314f00-c5cf-11eb-90ea-36b4db9217b1.mp4

as seen here the station keeps on growing, while this does look quite cool it is also killing my fps and so i try to despawn it, when i do it just pops into multiple segments that grow independently. Unfortunately I forgot to grab the log so i will do that if it happens again.

A suggestion that could go with this is adding in some sort of size option so that you can pick the max number of modules/rooms it will have      

![image](https://user-images.githubusercontent.com/56371294/120895471-dce89980-c5d1-11eb-9be2-74261a735945.png)
also it seems that stations don't generate vertically and as seen in this photo they like to clip parts into each other, some of this might be because i only have a 6 way connector, two corridors, a 90 degree turn and a landing pad

**Comment by tsunamayo** [comment]
@TIKIRobo I cant reproduce, could you send me your modules? thx

**Comment by CurioInventorium** [comment]
The modules I'm using seem to generate okay, except there doesn't seem to be any collision checking sometimes.
The station name isn't used when landing on one of the shipyard modules, just the default AC Clark is shown.

Also this ship I had been flying around in kept getting repositioned randomly. I think it was because the shipyard that was spawning in had had the ship land on the original at some point and I may have saved the shipyards blueprint with the ship docked. I remember in the past with having issues phantom ships spawning with shipyards if something was docked on them at the time.

Anyway here's some pictures of the stations spawned.
![20210607004051_1](https://user-images.githubusercontent.com/51359034/120944645-87c19a80-c72d-11eb-9a5e-3fc1acd2582b.jpg)
![20210607005044_1](https://user-images.githubusercontent.com/51359034/120944649-8bedb800-c72d-11eb-9e4b-d77cd5ed819d.jpg)

**Comment by TIKIRobo** [comment]
@tsunamayo yeap here you go! I also find it hard to replicate sometimes so it might just be a rare thing or due to the other things in my world like the large ship in the background 
Hub:
[6hub.zip](https://github.com/tsunamayo/Starship-EVO/files/6605399/6hub.zip)
Corridor:
[corrridor.zip](https://github.com/tsunamayo/Starship-EVO/files/6605401/corrridor.zip)
Joint: 
[joint.zip](https://github.com/tsunamayo/Starship-EVO/files/6605403/joint.zip)
Landing pad:
[shipyar.zip](https://github.com/tsunamayo/Starship-EVO/files/6605414/shipyar.zip)
"Turret":
[turret.zip](https://github.com/tsunamayo/Starship-EVO/files/6605405/turret.zip)

**Comment by tsunamayo** [comment]
Issue fixed for 21w22a. Thanks all!
