### ISSUE TITLE
[Video Guide] ? - Helping Your Players Design - 6 Rules for Design Tools - Extra Credits

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#3899]
I've watched so many game design theory videos and I figured that I might as well start posting the more appropriate ones here.
I'm not sure if you like this way of learning, @tsunamayo , or if you already know some, if not most of the topics covered in the video (I'm sure you do), so let me know if you'd like me to keep recommending these or not.
Even if not a game designer by trade myself, I still like to watch them because of how informative and entertaining they are.
So let me know what you think and let's go with the first one on designing the design tools in games:
[Helping Your Players Design - 6 Rules for Design Tools - Extra Credits](https://www.youtube.com/watch?v=ihwd_CY_U1E)

**Comment by CurioInventorium** [comment]
I think the most important thing to learn is; Stabilise added features before adding more.
Otherwise you get an endless list of problems, some of which are linked together in a spaghetti mess.

From my experience some years ago trying to make a small game for the iPad, I kept refactoring the game engine all the time when I had a new idea. In the end I'd spent nearly two years working on it, with no content and no money left. I had utterly failed.
And it wasn't even that complicated a game. Just a matching-pair card game to perform actions in combat and a basic AI to fight back.

**Comment by tsunamayo** [comment]
Thanks mate I will watch this when I can...
