### ISSUE TITLE
[Question] Tutorial Station

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Starship-EVO#3906]
Today a new player came to the Discord asking many questions. While we were able to answer all the questions, the large number of basic questions that the very dated tutorial didn't have demonstrates that we need to build the new tutorial station very soon. If just one player on Discord asks those questions, imagine how many are unable to get an answer being all on their own.

If you want to come on the Discord to discuss this at a later time, I'm all for it, but until then/if you want to keep it here, I have a few questions about what you are looking for. Nothing super specific or definitive, but hopefully will establish a basic vision on what for when we eventually start building.

1. What type of station do you want? Modular, semi-modular, single entity?
* Modular is the type of station from DwarfLordPangolin already in game. Basic modules generated together for "infinite" variability.
* Semi-modular is when you have modules to be put together in a semi-specific way and usually has an end point. 
![image](https://user-images.githubusercontent.com/36980446/123586156-2a06f800-d799-11eb-909a-edba5f33d8ee.png)
For example, you have your central sphere (green) connected to a ring (yellow) with module attachment points to the extensions (red). You can swap out some parts like the extensions (red) with for example shipyards, but the shape is set. Additionally, station generation can happen in stages with some only having the sphere, some having sphere and rings, etc.
* Single entity is as is, a single build with no module attachments. Plus and downsides are obvious

2. Are you looking for the equivalent of the two buildings on the torus, tutorial only, or something more?
What do you want in this station past the tutorial? Just a hangar for the player to fly off or do you want shops, cargo bays, and so on that will make a more lived-in station. Wouldn't be functional (yet?) but would be very impressive for the new player.
![image](https://user-images.githubusercontent.com/36980446/123602613-ca671780-d7ad-11eb-8d74-9fed6cc516ca.png)
Imagine walking out of the tutorial and seeing something like this overlooking the torus

3. In line with question 2, do you have a general idea size of the station?
A kilometer long mega station, a small outpost, etc? Not important yet, but scale is nice.

4. What style of station are you thinking of?
Geometric like No Man's Sky, realistic like The Expanse, utilitarian like Halo or Babylon 5, smooth like the Orville or Star Trek, rings like a lot of sci-fi, etc.

**Comment by Garrett-C** [comment]
I mean with so many things in flux this tutorial station would also be out of date in no time I suspect. Better not to rush it out.

**Comment by ZachZent** [comment]
The question was more about what type of station he wants, not what would go in the tutorial specifically. The station, especially the exterior, can be started soon enough, barring any upcoming major building changes like neovox. If the station's shell is completed, a tutorial can built inside of it when the time is right versus building an entire station out from the tutorial. It may actually be good to build the station and leave a very large empty space in the middle. That way a separate tutorial build can be copied/moduled inside of it. Then when the tutorial needs to be updated, a new tutorial can be copied/moduled in without needing to rebuild everything around it.

**Comment by Garrett-C** [comment]
Yeah my response was more to say I don't think it's worth putting much focus into it yet because anything done now will need a lot of reworking a year from now, as the current tutorial shows.

I don't even think it's worth building the exterior of it yet because it's not known how much space will be needed. For example if a large room is needed for a tutorial on mechs that would potentially be tough to fit into a station not designed for it. 

Better to design the actual tutorial and then design the building around it. For example you likely want a linear section to start the tutorial to cover the basics. How long should this part of the station be? It depends on how long that part of the tutorial should be which isn't yet known. 

Or look at the non linear bit of the tutorial how many branches would there be? How much space would be needed for each of those etc. These questions can't be answered until the actual tutorial is planned out. Hence there is no point building a station and just hoping that everything will eventually fit into it correctly. 

If you build too big you end up with long walks between parts of the tutorial. If you build too small you end up needing a new station. As such there isn't any point building an exterior yet. 

Now if tsuna wants another temporary tutorial that could be started but it would present the same issues as the current one because it will be out of date in a few months after it's added.

**Comment by tsunamayo** [comment]
Yeah I need a new tutorial before I put neovox into the default branch.
I want to simply use an empty hub module from newer bigger stations.
Then the tuto part would be built onto a children entity platform that could be loaded / reloaded / unloaded at will.
That way I can swap out the main frame, add some sort of lock to the main frame so newcomer dont delete it, load different tutorials and so on.
Also it wont be text screen based but would be used the to be added mission framework.
Also it wont be base on the torus but on a space station.

But for sure we would have to redo / improve it in the future, thats painful but I dont think we can cut it...

Cheers

**Comment by Garrett-C** [comment]
That's fair. I imagine then you will probably not want to go too overboard on the physical design then on it for now then. Get the functionality down and then it can be made to look good in the future when it's more solid. 

Can just spawn a couple of example builds beside it for now to show new players what can be done.

**Comment by ZachZent** [comment]
Sounds good, a modular station with a empty module where tutorials can be pasted inside. Solves most of the questions, especially since you are looking for a large station. However since there has been no new stations since the station contest and all of those are quite out of date and rather small, are you looking for a new station to be built?

Is there a style of station you are looking for? Or maybe style you personally like to see? Some reference for building, obviously doesn't/shouldn't be super fancy but a No Man's Sky style station is quite different from a Expanse style station both inside and out.
