### ISSUE TITLE
[suggestion] gravity auto-bounds

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3922]
basically it would be a button that when pressed changes the settings for a gravity generator so that it's bounds are perfectly squared around the ship, the user could then make manual adjustments to make it perfect but it would make setting up gravity slightly less tedious

**Comment by tsunamayo** [comment]
@amplified1 Hi, I am not sure to understand... gravity has a maximum size. Maybe do you want it to not extend beyond the ship bound?

**Comment by ZachZent** [comment]
At this point we just need a shipwide gravity net generator to the ship's bounds. Neovox allowing ships to get to a stupidly large size, be much simpler for the player to place, power, and leave it to work as intended. 16x16x16 individual ranges in 500m+ ships and stations and you will fly out of a ship without them, it is a massive pain no matter how user friendly the controls are.

**Comment by amplified1** [comment]
yeah I think it makes more sense to just have a really large max value and just scale the power and heat draw.

**Comment by cloudrambler** [comment]
Agree we need a larger / full ship gravity generator, but still don't like the idea of it just being a rectangle, as that would leave gravity outside ship in some areas. I don't want gravity throwing me off my ship if I try to access the exterior hull.

**Comment by CurioInventorium** [comment]
This could be a coding nightmare to do, but how about gravity decals? They could work along side the existing gravity block system.

Since the character is about 2m tall, each decal would only project a three meter high gravity area above it (or along the normal of the decal). So that the character jumping wouldn't immediately jump out of the field.

Stretch the decal to 3m x 4m on the floor, and you get a 3 x 4 x 3 (high) gravity area.
The default 3m high would also help with placing blocks on top of the decals.

Place the decal on the wall and you've got sideways gravity.

Whether they can be hooked up to the logic system or not, or some sort of global grid power the same way turrets are powered is a coding issue I suppose.

**Comment by amplified1** [comment]
I think that would possibly cause issues as the game moves into a survival stage since it doesn't really make sense to have a sticker work like the gravity generator

**Comment by CurioInventorium** [comment]
That's why I mentioned that they would work along side the existing gravity block. These would be useful in small areas, or long catwalks where a standard gravity requirement and no config needed.
The power to toggle them could be tied into the global grid power.

The idea's been used in a Sci-Fi series of books by Neil Asher. Where in some ship/station areas they use gravity floor tiles rather than gravity generators.

In-game there's already a system in place for setting the armour level of a block just by using the paint system, so why not use decals for controlling where gravity is.

I agree with your point on having larger gravity areas. It really drags down my enthusiasm for doing a large build if I have place (and configure) gravity blocks at regular intervals. The range needs to be similar to the shipyard blocks range.
