### ISSUE TITLE
Space Ship Short Cuts Problems

### ISSUE THREAD

**Issue by Xenos93** [tsunamayo/Starship-EVO#4054]
### Short Description of the issue:

Spaceship have shortcut blocks linked to Yoke, when hoping out of the yoke, 1 and 2 keys still triggers associated parts.

### Steps to reproduce the issue:

Link shortcut block to yoke link it to a switch, link switch to logic blocks ( all of them "work" to trigger the issue ), interact with yoke, hop out of yoke, press shortcuts ( in this case 1 and 2 ).

### Environment
- Starship EVO version: 21w07a
- Graphics Card: NVidia GTX 1070 Ti

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/6836537/Player.log)

[First Ship MkV.zip](https://github.com/tsunamayo/Starship-EVO/files/6836542/First.Ship.MkV.zip)

**Comment by Kaiser-Indrasil** [comment]
I'm assuming that you've built it on the Stable branch, as I could see no issue when I tried it out on the Experimental.
My recommendation would be to switch to the Experimental branch for the time being, since it's most up-to-date, including bug fixes.
On top of that, Stable branch doesn't receive bug fixes the way Experimental branch does, and the persistent issues will only get fixed once the two branches merge.
Here's how you can switch to the Experimental branch:

![Experimental Branch](https://user-images.githubusercontent.com/63756057/126074370-0045bb3d-54f2-442b-8afd-e79b0b18120e.png)

**Comment by tsunamayo** [comment]
@Xenos93 Hi, Kaiser is right, I am working hard to have this in the default branch but we need new tutorials first. Thanks

**Comment by Xenos93** [comment]
Thank you a lot, i'll switch on the Experimental version right now ! :D
