### ISSUE TITLE
Game crashes when starting a new game

### ISSUE THREAD

**Issue by aRasid-cz** [tsunamayo/Starship-EVO#4133]
### Short Description of the issue:

Game crashes when I want to create a new character and play the game.

### Steps to reproduce the issue:

Crash will occure every time I try start a game

### Environment
- Starship EVO version: 21w07a
- Graphics Card: GTX 1070-ti

### Additional information:

[Starship EVO.zip](https://github.com/tsunamayo/Starship-EVO/files/7040628/Starship.EVO.zip)

**Comment by tsunamayo** [comment]
@aRasid-cz Hi, sorry to hear this.
Could you please give me your config spec: CPU + RAM? Thanks

**Comment by aRasid-cz** [comment]
Hi, here it is. 
CPU Intel core i5 4460

RAM DDR3 24 Gb, 3200 MHz

**Comment by tsunamayo** [comment]
@aRasid-cz Hi, could you please send me (zipped to be able to attach it) the content of the folder
C:/Users/Petr/AppData/Local/Temp/Moonfire Entertainment/Starship EVO/Crashes
Did you played the game fine before or are you a new player? Thanks

**Comment by aRasid-cz** [comment]
Hi, I am new player. Just bought the game and after first attempt it crashed. :)

Here is the zip file.
[Starship EVO-temp.zip](https://github.com/tsunamayo/Starship-EVO/files/7075043/Starship.EVO-temp.zip)

**Comment by tsunamayo** [comment]
@aRasid-cz okay sorry of the slow update it takes some time on my side. One last thing, do you have a fixed PC or a laptop (if laptop then which brands) ? some people had issue on some laptop.
Also are your Windows / directx / gfx drivers up to date?
 Thanks

**Comment by aRasid-cz** [comment]
No problem, I guess you must be quite overwhelmed with taking care of development and fixing bugs. I'm patient, no worries. 

To your question. I'm using desktop pc and everything is up to date (I checked that, when encountered crash for the first time).

**Comment by tsunamayo** [comment]
@aRasid-cz after some investigation it looks like it could be a bug on unity side. I have updated the Unity version as this might fix the issue. You will tell me once the next patch is out (in experimental!)

**Comment by aRasid-cz** [comment]
Thanks, hopefully this will fix my issue. I'll let you know if there are any changes.

**Comment by AnunnakiNibiru** [comment]
Hi.

I have probably the same problem.
I bought the game today, and I am unable to get pass character creation window ("Steam" >>> "Starship Evo" >>> (game starts fine) >>> "Play" >>> "Create a new character"). The "Character Selection" window is empty, so I am forced to create new one.
I put in name (every time I need to add another one, first one was "Anunnaki Nibiru", because previous one is occupied, and there is seed shown.
C:\Users\rbilk\OneDrive\Desktop\Starship EVO\AppData.LocalLow.Backup\Save_Data\Characters\Anunnaki Nibiru
"Instances"
"PlayerEntities"
Both are empty.
When I click on the button "Play with this Character", it seems the game is doing something (shows cartoon image), but after maybe 5 seconds, new small window named "Starship EVO - Unity xxxx (version?)" appears ... on it progressing progressbar, and both windows disappears (crash to desktop).

It happens every time.
I tried 2K and 4K resolution, AA and no AA, windows and fullscreen, no difference, always the same crash to desktop on the same spot.
I tried first original game, than switched to [experimental] (early-access 21W35a). Also tried to delete folder: "C:\Users\rbilk\AppData\LocalLow\Moonfire Entertainment\Starship EVO", even reinstalling game and checking via STEAM for corrupted files.
Still, the same issue every time.

I attached 7zip file with crash/error/logs.

I am experienced in PC/HW/OS/Security/Programming/Networks and etc., so if there is any way how I can help you investigate this issue let me know. Even my English is not as good, I can share my screen with you if you wish to see it or "troubleshoot" it on my PC, anything that can help you make progress with this phenomenal game! (via Zoom, TeamViewer, Webex, or any other you chose).

(latest Windows10, all updates, latest graphic card drivers/sw, no issues in any other program/games).

[Starship EVO crash related files.zip](https://github.com/tsunamayo/Starship-EVO/files/7116032/Starship.EVO.crash.related.files.zip)

**Comment by tsunamayo** [comment]
@aRasid-cz Hi could you please try in the new version 21w36a? If it still does not work could you please try to turn off Head Bobbing in the option menu? Thanks

**Comment by aRasid-cz** [comment]
Hi, unfortunately I couldn't get to pc last week. I'll try it this week and let you know. ;)

**Comment by aRasid-cz** [comment]
@tsunamayo When I turn off Head bobbing, game finally works fine. With head bobbing enabled game still crashes though.

Thanks for your help!

**Comment by tsunamayo** [comment]
@aRasid-cz Okay, head bobbing has been deactivated as I wanted to change the approach as it has some unwanted effect (besides  the crash). I will move the player gun instead. Thanks
