### ISSUE TITLE
[Bug] Pipes do not need to be connected to the tank to satisfy pipe flow in reactors

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4142]
### Short Description of the issue:
Pipes can be broken and the reactor still reads that the pipe flow is sufficient.

### Steps to reproduce the issue:
- Spawn the attached bp. The reactor flow rate is currently sufficient
![711980_20210830153334_1](https://user-images.githubusercontent.com/27857711/131356803-b4f3036a-64b3-4c4b-a587-60bfec1e6cef.png)

- (Optional) Check that the flow rate is updating by reducing the flow rate to the tank
![711980_20210830153121_1](https://user-images.githubusercontent.com/27857711/131356706-7ab41eb9-2e15-46b4-b739-1d234732c2be.png)

- Cut the pipes to the tank. As long as there are large enough pipes next to the reactor, it will still read as sufficient 
![image](https://user-images.githubusercontent.com/27857711/131357459-f523f87f-2cbc-4b1d-aacf-6dc2f48e62db.png)

### Environment
- Starship EVO version: 21w34a
- Graphics Card: RX 580

### Additional information:
[Mistral - Fuel Test.zip](https://github.com/tsunamayo/Starship-EVO/files/7077492/Mistral.-.Fuel.Test.zip)

**Comment by tsunamayo** [comment]
@ProPeach okay so actually the way the sufficient check works is simply by looking at pipes plugged into the reactor. If your pipe is plugged into nothing it cant know it. I wont solve that as at one point people would build much complex piping system with logic ect, so that is a battle I cant win anyway. 
The system is purely local, the only thing stored for each pipe is a pipe adjacent Left id and a pipe adjacent Right id. Tank and reactor uses the same data, so they actually not storing their adjacent pipes (as they can have more than 2).
I could work on a debug view that shows flow ect, but I will leave it like this for now...
Btw second screenshot should not work too (as of yet as the 6-way is not yet functional)
Cheers

**Comment by ProPeach** [comment]
Interesting! I did wonder if it was for performance reasons, I suppose we'll see how this affects things as fuel becomes more mature. Thanks for explaining as always o/
