### ISSUE TITLE
Older blueprints not spawning in game

### ISSUE THREAD

**Issue by Servomotor** [tsunamayo/Starship-EVO#4184]
### Short Description of the issue:
The blueprints attached will not spawn in game when I use the starter block to spawn them. 

NOTE: All three of these blueprints are early workshop blueprints, some of the first things I made and submitted to the workshop. The S35 ship was the first ship I made in Starship Evo, it was the same ship I used in that video "Low Evo Rider" that had the spaceship bouncing to that Low Rider song. LOL
...

### Steps to reproduce the issue:
Log into game. Place a Starter Block, use F to choose blueprint to spawn it (but does not spawn)
...

### Environment
- Starship EVO version: 21w37a
- Graphics Card: EVGA RTX 2080

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
[Servo Blueprints Not Spawning on EXPERIMENTAL.zip](https://github.com/tsunamayo/Starship-EVO/files/7190218/Servo.Blueprints.Not.Spawning.on.EXPERIMENTAL.zip)

**Comment by tsunamayo** [comment]
@Servomotor Hi, so I think they might be too old. I have done many many update to the blueprint format, and keeping 100% compatibility is unfortunately not realistic. But you can install an older build and save them to the new format. I think that the pre-neovox legacy build could do the trick - then import that blueprint into the latest build. Dont forget to create a new character otherwise it will likely mess your existing world. thx

**Comment by Servomotor** [comment]
Understandable. I did as you suggested and it worked. The blueprints are saved under current experimental. 

Thank you!
