### ISSUE TITLE
Game always crashes when loading a new save

### ISSUE THREAD

**Issue by tmkillingsworth0522** [tsunamayo/Starship-EVO#4198]
### Short Description of the issue:
Whenever I try to create a new game, the whole game crashes. I've never actually gotten into the game. I tried several months ago and tried again today, but had the same issue as before.
...
### Steps to reproduce the issue:
I open the game through steam, click on play, create a new character, play with this character. Loading screen comes up with some very nice concept art, then a window opens up with a loading bar and the game crashes. I looked through other tickets and found people with similar issues, but never solutions. I tried changing my graphics settings and turning off head bobbing, but it still crashes.
...
- Starship EVO version: Whatever the most recent version is on Steam. I can't find any information on what version this is.
- Graphics Card: Intel UHD Graphics 630

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7229103/Player.log)

**Comment by TIKIRobo** [comment]
If i had to guess (Tsuna will be able to say for certain ofc) but the reason this is happening is because you do not have a "real" graphics card and are instead running the game on an integrated graphics card that is way below minimum specs, so, unfortunately this is most likely not a bug but instead an issue with your pc. 
if you upgrade your pc then it should work however i understand that might not be possible and so you might be better off waiting until you get a better pc.

**Comment by tsunamayo** [comment]
@tmkillingsworth0522 Yes I am really sorry TIKIRobo is right, your GFX card is well below minimum spec. Thanks for your understanding.
