### ISSUE TITLE
[Suggestion] Spaceship Control Options

### ISSUE THREAD

**Issue by Raeffi** [tsunamayo/Starship-EVO#4289]
I dont know if im the only one but its hard for me to control ships with the massive mouse deadzone in the center and the continous spin when moving the mouse to the edge of the screen.

I suggest adding an optional alternative way of controlling ships like Empyrion Galactic Survival / Space Engineers where there is no deadzone and the ship only turns while the mouse is moved.

**Comment by ProPeach** [comment]
Reducing the deadzone to something very small would be a quick fix to make flight feel far more responsive

**Comment by ProPeach** [comment]
Reducing the deadzone to something very small would be a quick fix to make flight feel far more responsive

**Comment by tsunamayo** [comment]
Well I am not sure on how those game are working - are there like Avorion? 
Starship evo has the control of Elite Dangerous. Problem is there is not a single control scheme in spacesim game... So whatever I choose people not used to it will have a hard time - and I cant afford to code two stuff.

**Comment by ZachZent** [comment]
I thought you said the controls were based from Everspace, though that was awhile ago

**Comment by Raeffi** [comment]
> Well I am not sure on how those game are working - are there like Avorion? Starship evo has the control of Elite Dangerous. Problem is there is not a single control scheme in spacesim game... So whatever I choose people not used to it will have a hard time - and I cant afford to code two stuff.

I dont have Avorion but I think the only difference is the way the mouse input is handled, the rest is the same. (The mouse in those games is directly used to spin the spacecraft like the camera in a FPS game, which allows for extremely fast and precise control at the cost of having to lift your mouse when you need to spin a lot)

However i messed with the settings and the sensitivity being too high by default also plays a role in this, setting it to ~50 makes it bearable to a complete noob like me, maybe that would be a good default value.

**Comment by Kaiser-Indrasil** [comment]
I think it's not needed since we have gimballed weapons exactly for that purpose

**Comment by Raeffi** [comment]
> I think it's not needed since we have gimballed weapons exactly for that purpose

Would still be nice to have the "linear" mouse motion option and an adjustable deadzone

**Comment by tsunamayo** [comment]
@Raeffi What ship did you used? The mini repair ship? Some ship have just too high a agility value I cant control them either. @ZachZent  Yes it is the same as Everspace too...
I think it make much more sense when it come to fly near terrain.
Is Space Engineers working like Avorion?

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo Only slightly so.
They're similar only in a way of using the mouse like a cursor, instead of a joystick like in Everspace, ED, Star Citizen, or Starship Evo.
In SE, your cursor is slaved to your ship's agility, so you can't move it faster than your ship's rotation speed, and it always points directly ahead of your ship.
Avorion has a different (and imo, better than SE's) approach where you can move your crosshairs freely, and the ship and turrets just catch up to it, even if it means a 180 degrees turn. They always follow your cursor.

**Comment by ProPeach** [comment]
If you're aiming for something like Elite, the deadzone feeling is pretty important. This comment has a clip attached that shows how sensitive it is in Elite because of its tiny deadzone - https://github.com/tsunamayo/Starship-EVO/issues/1749#issuecomment-613475315
The orange arrow shows the approximate location of the mouse cursor, and there seems to be a linear increase in turn rate from pretty much the moment the cursor is away from the middle of the screen. This results in a very accurate and natural feeling when controlling the ship.

Currently in SEVO, the deadzone is huge so you have to move the mouse a lot and are constantly over compensating for movement. It's difficult to steer your ship accurately without focussing on it a lot

**Comment by Raeffi** [comment]
> @Raeffi What ship did you used? The mini repair ship? Some ship have just too high a agility value I cant control them either.

Yes i used that one
