### ISSUE TITLE
Keyboard mapping does work

### ISSUE THREAD

**Issue by HijackHornet** [tsunamayo/Starship-EVO#4325]
### Short Description of the issue:
Cant change controls in the keymap pannel
...

### Steps to reproduce the issue:
Just bought the game. I started it, start a game, and while in the tutorial room i try to map the keys to an AZERTY lzyout without success.
...

### Environment
- Starship EVO version: 21w48b
- Graphics Card: RTX 3080

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/7656248/Player.log)
I have litterally 5 minutes playtime and thats my second bug repport. It doesnt look promising so far :/

**Comment by Kaiser-Indrasil** [comment]
Do you have a gamepad?
Try turning it on, and then remapping the keys, or turning it off, and then remapping them as well.

I've had a very similar problem and managed to fix the issue this way.

**Comment by HijackHornet** [comment]
> 

I have 2 flight sim controller connected. This shouldnt prevent remapping as they are not handle as keyboard. If it is indeed why its not working, an easy fix would probably to separate the keyboard and the controller mappings.

**Comment by tsunamayo** [comment]
@HijackHornet Hi again,
So I managed to reproduce the issue.

It happens when one of your joystick axis is not at 0 (typically the thruster on a joystick)
We actually have a message that asks the player to put the particular axis down to 0, the problem is that it was tested and was working for control already set at Axis (ie when instead of using two keybinds it use a controller axis), but indeed it is not displayed for keybinds! 
It is a miss on my side, I will make sure to display that message all the time.

**Comment by tsunamayo** [comment]
@HijackHornet So I did the change, now message will be displayed for all keybinds. Fix for 21w49a. 
Cheers
