### ISSUE TITLE
[Bug] Handheld clipping is inconsistent

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#4447]
### Short Description of the issue:
Clipping is "allowed" on handhelds which is fantastic, but sometimes collision checks still prevent you from placing bricks that clip.

Here, I can't place a cube that clips into the slope
![image](https://user-images.githubusercontent.com/27857711/147990097-80fccdcb-ea72-45b6-b99d-779d2ddbfa9d.png)
But if I place the slope first then place the clipped slope second, it is allowed
![image](https://user-images.githubusercontent.com/27857711/147990071-942076fb-fdaf-4a46-a8c6-810ae7c740bf.png)

It'd be great if there were simply no clipping checks to worry about here

### Steps to reproduce the issue:
- Replicate the examples in the pictures with the attached blueprint

### Environment
- Starship EVO version: 22w01a
- Graphics Card: RX 580 8GB

[Clipping Showcase.zip](https://github.com/tsunamayo/Starship-EVO/files/7804478/Clipping.Showcase.zip)

**Comment by tsunamayo** [comment]
@ProPeach Clipping is not allowed on handheld, this is a bug ;)
By the way I will nuke those by going 1/4m due to popular request... so dont loose too much time on those!
Thanks

**Comment by ProPeach** [comment]
Wait, really? I thought we talked about clipping on handhelds before and it was decided that it'd be better if clipping was allowed for those 🤔
Yeah no problem on that, I was just killing some time

**Comment by ProPeach** [comment]
Huh, looking back I can't find anywhere you said clipping is allowed to be fair, just a thread #2217 talking about the possibility. Gotta admit I had it in my head that it was intentional, as did a lot of us I think. It's just such a fun ability to have in handhelds where you're already limited on size

**Comment by pinesh** [comment]
I really hope you reconsider clipping for handhelds. It's essentially a requirement in order to fit the reactor bloc anywhere reasonable and allows for all sorts of wonderful shapes!
![image](https://user-images.githubusercontent.com/14081996/147994918-1700ba50-5b63-4421-8503-46566110c082.png)
_Clipping permits weapon covers, smooth surfaces and even fake ammo!_

![image](https://user-images.githubusercontent.com/14081996/147994965-f5a7fcf8-de16-43ed-b5c6-4b0bee8afc81.png)
_tight angles for mug based optics, tiles inside cylinders and even muzzle breaks_ 

![image](https://user-images.githubusercontent.com/14081996/147995015-c6a30f4a-5778-4cb0-888b-c67f90f46c48.png)
_detailed stocks and more optics_

![image](https://user-images.githubusercontent.com/14081996/147995067-ec451d95-0af0-4bef-aff5-405676f5fb5d.png)
_tight shapes with the bevel blocks_

![image](https://user-images.githubusercontent.com/14081996/147995100-765f2998-2ea2-4c54-b7dc-25bf8bacd928.png)
_and pistol sized pistols! note the corrugated pipes clipping into the hollow wedges_

clipping permits even small details like valve covers and detailed frames
![image](https://user-images.githubusercontent.com/14081996/147995157-5607461f-8fa6-4b10-87ac-f6cd2299e0e5.png)
![image](https://user-images.githubusercontent.com/14081996/147995184-e12c1def-e825-4232-a1f9-ea08a1183729.png)
![image](https://user-images.githubusercontent.com/14081996/147995257-bdfdc50d-e66f-4765-a0cb-714301d08a48.png)

**Comment by kynamats** [comment]
> @ProPeach Clipping is not allowed on handheld, this is a bug ;) By the way I will nuke those by going 1/4m due to popular request... so dont loose too much time on those! Thanks

I'd beg you to keep clipping, while its out of the normal build mechanics, achieving 'superior' detail on handhelds will be hard without it.

While the other comment here showcases it more effectively, see attached pistol for an example.
![image](https://user-images.githubusercontent.com/89156468/147995376-43a2bfb7-6400-43a6-b801-6f70f13f6718.png)

**Comment by tsunamayo** [comment]
Well then we get into the old discussion (again...), like how do I prevent people from stacking systems ect...
Then for sure it would trigger some more discussion like if you can have it on handheld why cant we have it on ship?
So with a 0.25x a 1/8 size, you can make some pretty tiny details dont you think guys? Also you can deal with system block (and logical gate, that I think the biggest plus) much better as they would be tiny...
Cheers

**Comment by pinesh** [comment]
> Well then we get into the old discussion (again...), like how do I prevent people from stacking systems ect... Then for sure it would trigger some more discussion like if you can have it on handheld why cant we have it on ship? So with a 0.25x a 1/8 size, you can make some pretty tiny details dont you think guys? Also you can deal with system block (and logical gate, that I think the biggest plus) much better as they would be tiny... Cheers

I think the most straightforward way to deal with it would be to prevent systems from being placed on a handheld and to bring back handle stats. This would prevent handhelds from getting too powerful, remove challenges with fueling handhelds and could even cover heat. Doing so could keep all handhelds balanced with each other regardless of size?

**Comment by ProPeach** [comment]
Is it possible to prevent systems from clipping into other systems and leave it out for the rest of the bricks? So you can clip a hull shape into a reactor, but not a reactor into another reactor. This would prevent the systems stacking being used maliciously to get more power in a handheld.
I do totally sympathise with the return of this old debate hah, but I think here we have a bit of a unique situation in that people will understand if you can only do this kind of thing on the tiny handhelds.

Having the Handle itself provide the power source would be a neat idea as it puts a hard limit on weapons max power (either one handle worth or two).

**Comment by kynamats** [comment]
I think both the above comments have said it well, but I also agree there needs to be some limit on clipping to stop it being abused and to blend the experience of building on ships and handhelds. It's fine for them to be different, but it also needs to be very clear to the player how exactly the rules have changed. I appreciate it's a really tough thing to balance though!
