### ISSUE TITLE
Children Entity get spawned at the wrong place

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#4495]
Okay guys so I have noticed that some CE can randomly spawn at the wrong place.
I have suspicion it is linked to unspawning stuff but I am lacking a clear reproductible case at this stage.
Does anybody saw this too?
Thanks

**Comment by Regnion** [comment]
![20220118223818_1](https://user-images.githubusercontent.com/13087952/150268090-8ae6ce84-94ab-497e-8aa4-dedd3da3579e.jpg)
![20220118224051_1](https://user-images.githubusercontent.com/13087952/150268103-4f2cd7b4-357d-4c4d-b122-0da532b63018.jpg)
![20220118224209_1](https://user-images.githubusercontent.com/13087952/150268111-ed0bed61-c3ad-4bd8-a809-c0ff38d4495a.jpg)

Hey Tsuna. I haven't been able to replicate it reliably. All these instances were same world, same game. When I restarted, the issue was resolved. I don't know what caused it originally, but I had just used the copy/paste tool and the block removal area tool. Could be related.

**Comment by Regnion** [comment]
To add on to this, this is a trap door that was placed inside the small ship on the back of the big one. The door was in the frame, but when I open it, it goes waaay out to here.

![20220119211912_1](https://user-images.githubusercontent.com/13087952/150272742-09f0f1e3-8821-4d22-8fbd-5200eeb9ffc9.jpg)

Also the ends of rotors, pistons, and hinges are spawning away from the base. It's possibly all related.

**Comment by tsunamayo** [comment]
@Regnion okay I was able to fix the issue. Thankfully it should not corrupt anything - but I will push a build asap.
Thanks
