### ISSUE TITLE
Multiplayer spawning Crashes

### ISSUE THREAD

**Issue by silverszi** [tsunamayo/Starship-EVO#4511]
### Short Description of the issue:
Spawning any ship in multiplayer with another player in causes an immediate crash for the connected player
And a weird desync for the host, ok sometimes host is unaffected, can't tell why.
### Steps to reproduce the issue:
Open a session to multiplayer
Spawn any blueprint, placing a new starter block DOES NOT cause any issues
Crash for any connected players
Desync issue or no issue for host
### Environment
v22w04a
GPU: NVIDIA Geforce GTX 1070

### Additional information:
Everything stays in the same spot in render, it looks like you can't move away from anything BUT the entity bounds still exist and you can move relative to them, even collide with the entities.
![image](https://user-images.githubusercontent.com/80038133/150955015-ceb2350c-df42-4d94-a793-cbc0f10d0df4.png)
![image](https://user-images.githubusercontent.com/80038133/150955330-99afeee8-8882-4346-8c7c-08d111168bd6.png)

github is giving me issues uploading the log file 
it's 70MB i need help with that

**Comment by silverszi** [comment]
https://drive.google.com/file/d/1AfnSef2CVIog2E31H1z7BkLU3nGj2ay9/view?usp=sharing
log file in question

**Comment by silverszi** [comment]
Note: smaller ships can be spawned completely fine the crash and then the desync only occur with anything that isn't a small hover

**Comment by silverszi** [comment]
I think this is another issue caused by this.
Using fast move keys after someone crashes i as host get left not being able to move and can only jitter between the point i am stuck at and as far away as i can move with fast movement.
https://user-images.githubusercontent.com/80038133/150960299-537f3113-5d9b-4fed-921c-e0eb68fa0112.mp4

**Comment by tsunamayo** [comment]
@silverszi Hi, could you send me the blueprint that you cant spawn? I can spawn on my side... Thanks

**Comment by tsunamayo** [comment]
@silverszi So I manage to reproduce. Issue was not with large ship but with ship with the older legacy save format. Fixed for 22w04a!
Just a few tips as I would enjoy if you could continue to post fixes for multiplayer!
- if a particular blueprint is causing issues just send the blueprint 
- also once the first issue appeared the game will break and the log will fill rapidly. At that point it is best to quit to windows and report the bug otherwise as you saw the log file will become massive. Also what happens after that is not really relevant, so no need to spend time describing it!
- 
Cheers
