### ISSUE TITLE
[Bug] Fuel Info and Connectors

### ISSUE THREAD

**Issue by PFSCommissar** [tsunamayo/Starship-EVO#4650]
### Short Description of the issue:

This report concerns 2 issues:

1. Fuel flow is displaying inconsistently. As you can see in the screenshot below, some flows are shown, while others are not.
2. It's also possible that connectors are not allowing fuel to flow. If two of them are adjacent to each other, no flow is shown coming out. 

![20220325155843_1](https://user-images.githubusercontent.com/67161181/160192949-4c643503-2339-493e-a5fe-f3667bef438c.jpg)

### Environment
- Starship EVO version: 22w12a
- Graphics Card: Nvidia Geforce GTX 1650

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/8353541/output_log.txt)

**Comment by PFSCommissar** [comment]
in further testing, apparently connectors will stop allowing flow if two of them are put next to each other

**Comment by tsunamayo** [comment]
@PFSCommissar Hi, so the Tank 6-ways (the connector) are not pipe, they are tanks. So you need a special flat Tank Join in order to link them together.
So the bad boy in the middle is not doing anything. The description should hopefully make this clear, I will also explain that when I do a Fuel tutorial.
Also fuel flow display exactly the last fuel amount sent, so are you sure some fuel is actually sent but not displayed? You can check more info with F3/ Performance / Show Command Debug Info. I would say there is actually no fuel being transfered!
Cheers

**Comment by tsunamayo** [comment]
Deprecated with the new tech. Also 6way are now acting like proper pipe now. Cheers
