### ISSUE TITLE
Hinge noise persists after deletion of hinge.

### ISSUE THREAD

**Issue by SL-Nokz** [tsunamayo/Starship-EVO#4692]
I was able to re-create this error a few times in a row successfully. Basically whenever you have a Hinge, and you activate it (it is moving) and delete it after activation (while the hinge is moving) The noise it makes will continuously play until you exit the game and reload your world.

You can only hear it close to the area where the hinge was but if you keep coming back to the area the noise will continuously play as if the block was still there and trying to move forever.

**Comment by Swiggzon** [comment]
this has happened to me as well in earlier builds, it also happens if you access the hinge menu while it is still moving, this seems to cause the hinge to stop moving, but its like the game is still waiting for the hinge to reach its designated angle (which it never does) causing an endless sound loop

**Comment by tsunamayo** [comment]
@SL-Nokz Hi, issue will be fixed for 22w24a. @Swiggzon this seems to be fixed too. Thanks!
