### ISSUE TITLE
[Bug] Fuel not transferring through systems [22w23a]

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Starship-EVO#4733]
### Short Description of the issue:
Fuel will not pass through one system block to pipes on the other side.

### Steps to reproduce the issue:
Place a fuel tank, reactor, and lightcruise engine. Connect them with pipes, connecting the fuel tank to the reactor, and the reactor to the lightcruise engine. Reload the blueprint to avoid issues from #4732. The lightcruise engine will not refill itself, even though there is a connection between it and the rest of the fuel system.

### Environment
- Starship EVO version: 22w23a
- Graphics Card: AMD Radeon RX 5600 XT

### Additional information:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8886892/Player.log)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Okay so this wont work by design. Is it something that feels important? 
If I where to change the reactor / engine behavior to allow this, it would mean that their internal tank wont try to fill themselves up to 100% when plugged to a standard tank, but would instead form an equilibrium just like tanks are doing between them.
I need to give it more thought.
I could also give a special pipe that force pushing in a direction, or only allow a flow in a direction.

Thanks

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin Hi, so with the new fuel logic implementation this will work. Cheers
