### ISSUE TITLE
Build Tutorial Crashing

### ISSUE THREAD

**Issue by Verzerrung** [tsunamayo/Starship-EVO#4754]
### Short Description of the issue:

... I get to the "Basic Building Training" mission. Click start on the Training Center for that mission. Hit Close window. Walk up to the floating wedge brick on the platform. The block highlights blue. Interaction text says to hit "F" to pick up the wedge brick. The game immediately closes with no indication of why or delay. 

I repeated this process two more times and had the same result. The fourth time though I kept tabbing in and out while looking up how to submit this report. I ended up standing around prior to starting the tutorial and again before attempting to pick up the block. I don't know how long, but it wasn't more than 5 minutes each. When i do get to picking up the block, it does not crash the game.

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 22x25b
- Graphics Card: Gigabyte 2080 Super
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/8976434/Player.log)

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Verzerrung Hi, thanks for booking the issue.
I would very much want to fix the issue, unfortunately I am unable to reproduce. 
I have a few questions/request to be able to investigate:
- Does it happens exactly when you look at the item stand and is about to pick it, or is it a bit more random?
- it seems that the log file is from a valid session. Could you reproduce the bug, and then send the log right away (otherwise it will get overwritten)

Thanks a lot
