### ISSUE TITLE
BUG:Data input in piston-rotors to the 4th decimal place precision. 

### ISSUE THREAD

**Issue by AsageSoftworks** [tsunamayo/Starship-EVO#4758]
Subgrid measurement issues when using 4 decimal places on stacked subgrids.

Tsuna, I love your game. I have purchased several copies to share it with friends over the last several years, and have spent nearly 2k hours in the game over that time. My favorite thing about the game is the ability to create mechanisms that use precision measurement to have flush edging with no clipping between 2 subgrids. Below are some examples.

![20220625150016_1](https://user-images.githubusercontent.com/43458562/175789056-1d8f8fc3-4823-4802-8dab-010c8e1ceb23.jpg)
![20220625150133_1](https://user-images.githubusercontent.com/43458562/175789057-660ee28c-df66-42ed-b983-dddbd58796dd.jpg)
![20220625150137_1](https://user-images.githubusercontent.com/43458562/175789058-90441653-64f6-4eb8-9986-af08d5747896.jpg)
![20220625150143_1](https://user-images.githubusercontent.com/43458562/175789059-5ba73487-7983-415b-8990-009c89fc19a8.jpg)
![20220625150150_1](https://user-images.githubusercontent.com/43458562/175789060-3ea4f850-ff71-4bd8-a61d-e352fb46bf04.jpg)
![20220625145957_1](https://user-images.githubusercontent.com/43458562/175789062-82c5b8c9-524b-4572-a77c-f22e7df13891.jpg)
![20220625150005_1](https://user-images.githubusercontent.com/43458562/175789063-a5f3488c-6793-42ff-918f-48a4ae7344b6.jpg)
![20220625150009_1](https://user-images.githubusercontent.com/43458562/175789065-ace7191e-5171-4e1d-9eed-f6542ac42831.jpg)

Now some issues have arisen, and I do not know if it is a bug with the current build or if it is an issue with the system as a whole. I have used Autodesk Autocad to plan all of these projects, as I do CAD work as an engineering technician in my career. Below is the CAD of the design I am currently using to plan a 250 panel 125km diameter ring station. 

![Screenshot 2022-06-25 145837](https://user-images.githubusercontent.com/43458562/175789131-84406b36-2a90-4698-85e0-f6baaa72ff78.png)

As you can see by these measurements, I am calculating out dimensions to ensure I use the in-game limit of 4 decimal place precision, this allows for me to create the flush mechanisms as I have shown above. Below is the issue I am facing.

![Screenshot 2022-06-25 145849](https://user-images.githubusercontent.com/43458562/175789162-f6d058d3-2863-49b6-aa5b-4186fe6db23d.png)
![20220625152312_1](https://user-images.githubusercontent.com/43458562/175789501-41f4e2b2-9985-4d63-bc37-b8eb2d40b0a3.jpg)

The top image is of my cad file, where the 2 panels meet, below it is the in game image where the two panels should meet. 
![20220625145743_1](https://user-images.githubusercontent.com/43458562/175789181-9277305b-6c0e-45c8-a95f-ff3e4db9e89d.jpg)
![20220625145746_1](https://user-images.githubusercontent.com/43458562/175789182-6f23dee9-0422-4dd1-ad40-6e87f6f26a46.jpg)
![20220625152326_1](https://user-images.githubusercontent.com/43458562/175789529-b0687578-46be-4896-8f3e-ec2c739313d1.jpg)
![20220625145753_1](https://user-images.githubusercontent.com/43458562/175789184-a3cfcbf3-1ad4-44a0-8dab-d556f68a4468.jpg)
Above are the in game piston and rotor setups used to create the angles and offsets needed to recreate the cad dimensions. One number was adjusted in my attempt to fix the issue. The variance in spacing is approximately .015m in distance from the designed dimensions, which I cannot account for construction error.

### Steps to reproduce the issue:

Follow the build guide and replicate from pictures, models and useable .dwg of the CAD can be provided. 
...

### Environment
- Starship EVO version: EA 22w25b
- Graphics Card: gtx 1070 integrated

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by cloudrambler** [comment]
Hi, this is interesting. I assume you have made similar structures before, and found the game geometry to be accurate enough; which is impressive.

I am exploring similar opportunities to create more complex subgrid geometry using Pythagorean Triples to ensure zero joint gaps, and it looks good there too.

In response to your question, I wanted to pose an alternate explanation other than the still possible "the game has changed". I have used AutoCAD a lot in the past, for engineering and architectural design. One thing I vaguely recall is that while AutoCAD is fiendishly precise, that precision may be relative to the scale toy are using, so the inherent mathematical errors for a 125km torus could be more than for the smaller rings you built before.

Alternatively the error may be within STEVO all along, and now that error is larger as a relative proportion of the whole construct size. It may not matter where the "error" actually is. What matters is that you are using two different computer systems, with each likely to have different inherent errors due to how they calculate these geometries, and further differing in how the small imprecisions are cumulatively handled. This will lead to small, but real and hopefully consistent discrepancies between the two methods. Then at large scales those relative errors are magnified enough that it becomes noticeable.

If it were me doing this, I would convert the AutoCAD model into a parametric model (using Excel or ant good parametric CAD), then you would be able to compute changes to the mechanism values to precisely correct for the standing error.

It would also help if you have all of your mechanisms driven from a single set of sequencer gates. That way you can make changes globally, and all of your joints should update in unison. In fact, if you can do that, then it may be most pragmatic to just start tweaking the sequencer values, one lsb at a time, and see what happens. If the change in physical result from changing one lsb is too much, then it may be that you are trying to exceed the relative precision of the game. Otherwise, if you can get small changes, you should be able to incrementally step toward the best fit.

**Comment by ProPeach** [comment]
In my builds when I transfer from CAD to ingame, I've noticed that sometimes a mechanism will not update its position if the change given is small
For example, changing a rotor from 0 to 20 degrees moves the rotor. However, changing from 20.389 degrees to 20.390 does not actually move the rotor.
So if I want a rotor at 20.390, I need to have the rotor at 18 degrees, then enter 20.390 to get it to move. It doesn't actually have trouble moving to this value of great precision if you use this method, but does had issues if you move it incrementally

**Comment by cloudrambler** [comment]
I find that even with large changes to positions, nothing happens until you cycle the sequencer gate on/off.

**Comment by tsunamayo** [comment]
@AsageSoftworks That is all very impressive! Indeed for such large build the existing threshold might have been too small. I had no idea you guys where using CAD and such. Are you using the docking port and module feature to spawn sub-part? 
I hope you does, it would be lot fast for you to iterate and also better for the engine.
So for next update I increased the precision x100 time. so the 15cm will become 0.15 cm, over a 125km build that seems acceptable.
Thanks a lot!
