### ISSUE TITLE
Handheld Weapon [Bug]

### ISSUE THREAD

**Issue by HigureKomori** [tsunamayo/Starship-EVO#4799]
### Short Description of the issue:

Hinges break literally the entire game

### Steps to reproduce the issue:

use hinges both making them move as well as having the handle on a tilted hinge

_(Screenshots, Videos, Error logs, Related issues)_

![20220802225723_1](https://user-images.githubusercontent.com/110147933/182774358-f98c5bb6-cb09-43d2-9500-ab3eb7705511.jpg)
![20220802225744_1](https://user-images.githubusercontent.com/110147933/182774363-0c300b7e-7a3a-4772-aec8-a7603297d680.jpg)
[M202A1.zip](https://github.com/tsunamayo/Starship-EVO/files/9257028/M202A1.zip) (right click to move the hinge)

**Comment by HigureKomori** [comment]
im also on the latest version my gpu is a RX 6600

So ive been getting constant crashes now from this even loading in a gun blueprint can break the game

**Comment by Kaiser-Indrasil** [comment]
@HigureKomori 

1. What version exactly? We need the **number**.
Point is, we don't know which version you're on, even if you say it's the latest one, since there's the main branch and the experimental one.

2. What **GPU driver** version do you use?

3. Please provide the **save file** that you can reliably crash on.
Go to this folder (replace the *USERNAME* with your username) and zip up the folder with your save.
> C:\Users\USERNAME\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Characters

4. Also, please provide the **Player.log** file located here:
> %UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\

---
On 22w30c Experimental the issue does not occur.
However, the weapon starts displacing abruptly once the player uses the hinge (right mouse button).

Steps to reproduce:

1. Load up the game
2. Use the save file provided
3. Pick up the weapon from the weapon stand
4. Click the right mouse button to open the front hatch of the weapon
5. Notice the weapon is being displaced abruptly
6. Go to 3rd person camera
7. Notice the weapon keeps shaking while drifting away from the character

[Save file](https://github.com/tsunamayo/Starship-EVO/files/9266183/M202A1.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9266204/Player.log)
Version | GPU | GPU Driver
--- | --- | ---
22w30c | 970M | 516.59

https://user-images.githubusercontent.com/63756057/183018981-225998d6-bf43-4e77-af57-deae64f4568e.mp4

**Comment by HigureKomori** [comment]
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9267566/Player.log)
Version is 22w30c
[Koneko Komori.zip](https://github.com/tsunamayo/Starship-EVO/files/9267580/Koneko.Komori.zip) So with my save which the crashes it seemed to displace me i had some builds going and ive completely lost where they are
as for the GPU Drive it seems to be 497.29 but its showing my other gpu i dont know how to check my new main gpu or if i need to go update it or if this is even what your looking for

And weapons with handles on hinges is what really breaking my game it also does have the player model grip them if its on hinges ill send that blueprint as well 
[GAU-X Avenger.zip](https://github.com/tsunamayo/Starship-EVO/files/9267630/GAU-X.Avenger.zip)

**Comment by tsunamayo** [comment]
@HigureKomori Thanks a lot for the bug, I will have a look at it and keep you posted!
Francois

**Comment by tsunamayo** [comment]
@HigureKomori I can reproduce the issue, it is a bug indeed. The handle on a children entity on the other side is not supported, so I will do a check to prevent player from building it. Thanks

**Comment by HigureKomori** [comment]
thats a shame handles dont work for hinges having just vertical handles can be limiting to certain designs such as my gun i sent in the second Blueprint
