### ISSUE TITLE
[UI/UX] "Contextual Menu Open" and "Activate / Enter" bound to the same key by default

### ISSUE THREAD

**Issue by piotmetans** [tsunamayo/Starship-EVO#4856]
### Short Description of the issue:

Title says it all. By default, leaving a yoke requires navigation though the contextual menu and several button presses. I think this can make for a really clunky / confusing experience for a new player (and vets too haha).

### Environment
- Starship EVO version: 22w32a
- Graphics Card: RTX 2070 Super

**Comment by pinesh** [comment]
This ties in as the root cause of another open issue #4827

**Comment by tsunamayo** [comment]
@piotmetans Hi, no it is by design. I made sure that while in free look you can activate the contextual menu. You have no reason to activate stuff when not in free look so we are safe. I dont want to add plenty of keybind to remember, F is close and it is kind of the same thing (it is about interaction).
cheers
