### ISSUE TITLE
Fast Move Keys and Teleport to any ship options should be on by default in creative.

### ISSUE THREAD

**Issue by 5URG3** [tsunamayo/Starship-EVO#4863]
Given that virtually every builder I know enables Fast Move Keys and Teleport to any ship immediately when starting a new world, I think these options ought to be on by default in Creative mode. 

Obviously when a separate Survival mode arrives, they should be disabled.

**Comment by ProPeach** [comment]
Absolutely! The first thing I do every time I load up a world is toggle these options to on, I still meet new players who have never known about the fast move keys. I can't imagine what it would be like to only be able to move at 1x speed when you're working on something over 30m long, it must be a nightmare.

**Comment by 5URG3** [comment]
"I can't imagine what it would be like to only be able to move at 1x speed when you're working on something over 30m long, it must be a nightmare."

Damn, that's a scary thought...

**Comment by tsunamayo** [comment]
@5URG3 Hi, yes it make sense, the problem is newcomers. If I activate them by default then they get scared / lost while trying to teleport, or they can mash the fast/slow move key and get stuck. I got several bad reviews because of that mind you. I need to be careful on what can ruin the first hour of the game, it is really a weak point of the game unfortunately...

I think the best will be simply to save those settings.
As I dont want to save debug toggle (never a good idea), I will promote those settings to the F1 menu, it should not be too hard (but people will complain when the no longer see those toggles in F3, as some dont read patch notes ;), anyway... )

**Comment by tsunamayo** [comment]
@5URG3 Hi, okay done for 22w32b, those settings are now in F1, which mean they are save. 
Note that I do not save the fast speed value though.
In F3 I added a "NOW IN F1 MENU" so people are not lost, but F3 will not do anything. I will remove that in a few build.
