### ISSUE TITLE
[Suggestion] Expanding the transparent brick suite

### ISSUE THREAD

**Issue by PopkaAkula** [tsunamayo/Starship-EVO#4873]
### Short Description of the suggestion:

It would be cool if the the transparent brick lineup had the same shapes as the normal bricks. Having, for example, transparent tiles as an option would make building compact craft even easier since you wouldn't have to deal with full size transparent bricks eating up a lot of space.

**Comment by ProPeach** [comment]
This is one use case of a Half Tile Brick - 
![image](https://user-images.githubusercontent.com/27857711/185669060-b9965a4e-e62c-4959-83d2-141912eea415.png)

On the left is a 1/8th thick panel using the current brick glass, which results in the borders between glass being very visible.
With a half Glass Tile, as well as the new Tile Thin Triangles (I've substituted that brick for a glow triangle due to #4872), you can use a single Glass Tile for the whole pane of glass then use the triangle pieces to cover parts of it to achieve this shaped window all within a 1/8th thickness.

**Comment by tsunamayo** [comment]
@PopkaAkula Hum honestly not a fan at all of these exponential brick multiplication, I want to keep the codex small.
In the particular case of tile / thin tile, I dont like those at first as we have 1/8 scale already.
On top of that those are made to be stretch over surfaces, which is a bit useless to do with transparent tile. Imo those are not the right way to solve the problem your are pointing @ProPeach as you would need to place some sort of scafolding brick first in order to place them.
I would say use a full transparent brick and then use a thin tile triangle placed over the transparent on the bottom left. 
Cheers

**Comment by Uncle-Ulty** [comment]
@tsunamayo , instead of adding new glass bricks, and creating tons of new bricks, making the codex look crowded and confused. Would it be possible to add "glass material paint" to make some bricks transparent?

with this material paint, we could transform most of the current bricks into glass versions. The transparency color would be settled using standard color. This "glass paint" would be exclusive to painting bricks, not decals.

Is it possible?

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, Nope it is not possible unfortunately! But I will try to make "borderless" (no side border) glass instead. Thanks
