### ISSUE TITLE
[Suggestion] Dummy NPC crew (for cool pics -.^)

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4900]
My suggestion is simple: There should be a way to spawn a character on a seat. Something simple: 
-you click on a seat, toggle: spawn NPC (yes/no), 
-on a second row you can select which one you want to spawn.
-the current character model is enough

we already have this effect on enemy ships. When we spawn an enemy ship, a character is spawned on the ship's pilot seat. I just want a way to control that on every seat.

Done, now you have an NPC / fake player that can improve the game immersion, and that will allow us to make fantastic photos with several characters, even when we aren't on multiplayer

**Comment by cyberjasse** [comment]
I like this suggestion because it would bring more life in the game even if the NPC does not walk . Life is what it miss the most for me in space sandbox game that I know excepted starbound or no man sky.
In survival mode, the NPC could give the ship a small bonus or allows you to craft things or whatever but it brings life and make a purpose for making large ship.

**Comment by Jorpis-Jorah** [comment]
Sounds legit, I follow this

**Comment by tsunamayo** [comment]
@Uncle-Ulty Well NPC crew is gonna be a big dev, hopefully I can get to this but this will be post survival for sure! Thanks
