### ISSUE TITLE
Corrupted save without any reason

### ISSUE THREAD

**Issue by cyberjasse** [tsunamayo/Starship-EVO#4901]
### Short Description of the issue:
here is a corrupted save. When I want to load the save , the loading screen is displayed and it took forever. There is no softlock but it does not load too. i did not have lot of things in it. I Just build things and traveled in the same planetary system. Last time, I quited the game normally with one of the button in the pause menu to quit the save. I have no idea about what would cause this.

Since there is no timestamp in the log file, I am note 100% sure that the logs is about this problem or during the last time I played. There are some crash report in it. A end of stream exception and some null references.
...

### Steps to reproduce the issue:

...

### Environment
- Starship EVO version: 22w33a
- Graphics Card: 

### Additional information:
The save
[jason tuto.zip](https://github.com/tsunamayo/Starship-EVO/files/9491700/jason.tuto.zip)

The log file
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9491703/Player.log)

**Comment by Kaiser-Indrasil** [comment]
My save became corrupted as well.
The save was renamed to "Create a new character" and the world became a black void with no ability to place blocks down.

[Save file](https://github.com/tsunamayo/Starship-EVO/files/9495608/22w31a.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9495627/Player.log)

**Comment by daOyster** [comment]
I've also had this happen to me. For me I've experienced it twice. Both times it occurred after I backed out to the main menu instead of exiting to desktop directly. The first time it gave me a blank world floating in space, when I exited to desktop and came back the ring re-spawned but no builds spawned in. Before panicking I checked the player entities folder and nothing was deleted in there so I was able to recover my work in progress builds from there to a new world.

The second time it happened on new character, I used alt+f4 when I spawned into space again to keep it from saving. This seemed to have allowed everything to spawn back in correctly the next time I loaded the world afterwards to check.

The only thing I noticed both times shared in common was that I exited to the title screen and then tried to load the world back up which I normally don't do.

**Comment by cyberjasse** [comment]
I sometimes exit to the main menu and other times exit to the desktop . I probably exited to the main menu before my save become corrupted but it does not happened the other time I exited to the main menu so if it is the cause then it is not a systematic bug.

**Comment by tsunamayo** [comment]
@cyberjasse Hi, you will be able to load your save in 22w38c. 
@Kaiser-Indrasil Unfortunately I dont know what happened with yours, it is can no longer load the entity position. It will just restart a player in next update, sorry I hope it was not important (if it is, you can still try to load individual ship)
Cheers

**Comment by Kaiser-Indrasil** [comment]
@tsunamayo No worries, I've been saving my WIPs all along, so no work has been lost.
