### ISSUE TITLE
Thrust & Acceleration Inconsistencies

### ISSUE THREAD

**Issue by TheWanderer05** [tsunamayo/Starship-EVO#4907]
I'll preface this by saying I don't know if this is a balance issue or a bug.

While building a new ship and flying it around, I noticed that acceleration in different directions are inconsistent. For example, my ship has six 1/8m x 1/8m circular engines and six 1/4 x 1/4m circular engines for reverse thrust. It has two 1/4m x 1/4m circular engines and four 1/8m x 1/8m circular engines per side for lateral thrust. The ship should accelerate faster in reverse, but it accelerates much faster laterally. Even if the left and right engine clusters were combined for lateral thrust, the ship should accelerate faster longitudinally than laterally. I believe that either longitudinal thrust is underpowered, or lateral thrust is overpowered.

Game version: 22w33a
Graphics card: RTX 3070

Player log:
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/9539307/Player.log)

Ship blueprint (if it is relevant):
[Mining Testbed.zip](https://github.com/tsunamayo/Starship-EVO/files/9539305/Mining.Testbed.zip)

**Comment by kynamats** [comment]
This is because only thrusters pointing backwards count as forward/reverse thrust, any other direction than that will contribute to the agility thrust pool instead, which governs braking and lateral movement. So your 'reverse' thrusters aren't actually functioning in reverse but rather contributing to lateral thrust. It's a bit counter intuitive, but if you interact with the starship computer you can see the thrust amounts, which will help.

**Comment by tsunamayo** [comment]
Hi, @kynamats is right. In order to give player the most creative freedom we use a simplified model, as the game is not supposed to be realistic. It is explained in the tutorial, and I will add a knowledge base soon. Thanks
