### ISSUE TITLE
[BUG] Mined ores aren't affected by artificial generated gravity 22w38b experimental

### ISSUE THREAD

**Issue by Uncle-Ulty** [tsunamayo/Starship-EVO#4927]
Mined ores aren't affected by artificially generated gravity. This makes the conveyor belt useless on spacecraft and stations because the conveyor belt doesn't push the ore to the destination.

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, It works fine over here, is it still the case in 22w38c? Thanks

**Comment by DrizztCode** [comment]
hi - i got to the bottom of this one - it is coz the collector still has a "grabbing" field when set to expel, based on the range setting - so in gravity, this should be set to 0

but i am sure this holding field feature will have many cool uses even if it was not intended :-)
(tractor beams anyone? :-))

but yes, range set to 0 means just the expel speed will control the behaviour - low for belts, high if firing into a collector

i made a few short videos showing that it can be reproduced, as well as the effects of range and speed

please note that gravity is set to down in the 1st video, but i had the gravity generator tool selected so that the field would show, so please ignore the sideways arrow on that - i jump to show gravity is on anyway lol :-)

https://youtu.be/c2UiKVv19Gs (reproduce in space)
https://youtu.be/Uf_V67BPvrw (reproduce on habitat)
https://youtu.be/tFg4mFVOfhc (playing around with range and speed)

anyway - while it can be reproduced i don't see it as a bug, now that i understand what is going on - just lots of features that we all need to play around with to get the behaviour we want - so yes, in gravity, range set to zero does the trick :-)

**Comment by tsunamayo** [comment]
@Uncle-Ulty Hi, I think it might have corrupted rocks, although I can be sure 100%. Please tell if you ever reproduce that issue! Cheers
