### ISSUE TITLE
Turret Rotor limits

### ISSUE THREAD

**Issue by TwoNiner29** [tsunamayo/Starship-EVO#4963]
Hey tsuna, I have a suggestion,

Often time when building turrets, I come across an issue where the turret barrels try to rotate too much and cause the turret to break because the barrels clip into the ship itself.

![20221019024415_1](https://user-images.githubusercontent.com/66531332/196518484-891ee610-3819-40cd-b633-a0bb3936351a.jpg)
![20221019024537_1](https://user-images.githubusercontent.com/66531332/196518496-dae542f7-7755-4242-a2a9-0725aeb3953a.jpg)
![20221019024544_1](https://user-images.githubusercontent.com/66531332/196518501-b0181565-18b6-44f1-89c2-1b1e39c7fb7d.jpg)

here is what I mean, the problem could be fixed if there was a limiter to the angle at which the turret barrels could rotate so they do not clip into other blocks. Here is what the turrets are supposed to look like when they don't clip.
![20221011185920_1](https://user-images.githubusercontent.com/66531332/196518993-dafe534d-5175-4725-bcb5-77ff7498c44f.jpg)

I hope this suggestion finds you well!

**Comment by tsunamayo** [comment]
@TwoNiner29 Hi, is there any quirk on your turret build, or is it a simple two rotor / hinge setup? You can debug the collisions points with the link tool by clicking on the secondary rotor / hinge.
Now to be honest the turret workflow is such a pain in the ass, a lot of bug and time spent on making it work properly. Dealing with all the case is really hard. It also makes the game freeze when you step into the ship, and cannot be well integrated to the new physics engine.

So I was thinking of simply trashing it, and doing something closer to what you are suggesting: either "paint" the cloud of valid point by hand, or use the min/max value of each rotor/hinge (and maybe give a nice 3D gizmo for the player to do so).

The problem is that it will "break" the collision of all existing turrets. Not that bad as turrets will still work, they would just clip inside the ship.

Is it a new Hammerhead? Still looking absolutely stunning, hard to believe it is my game lol...
Cheers

**Comment by ProPeach** [comment]
Sounds like a cool feature! It would be nice to finally stop turrets clipping in to hull like that and to set consistent limits.

I do see a potential issue where players intentionally don't set up limits to gain an advantage, or set limits which give their turrets more range of motion than they should otherwise have. You could perhaps reduce this and encourage players to set reasonable limits by removing the current safety that prevents turrets from shooting their own ship.
It's not really a huge issue to be honest, I'd take more reliable turrets any day even if it resulted in more possible clipping

**Comment by NEURALDELVERM** [comment]
In my issue I proposed a solution that could help with this issue and others. It is only for the builder's convenience, not the end user's benefit. Limits would be good, as well as some form of GUI or shader element to allow you to see places of conflict, but maybe what we need is less friction when turrets and things collide near each other. As collision is, it is SUPER sticky, so when you land, you are anchored down pretty well, which on landing gear is good, but when my sleek ship comes to a halt upon grazing a solid anything, it stops and the trajectory goes crazy.
If the angle of attack is greater than 45 degrees between entities they do not stop against each other, they slide against each other. So doors with flush insets won't randomly get caught, hinged objects won't get caught on objects moved with pistons, because it would slide instead of collide, and the winning actuator is based on speed and/or size. Not sure how that could be implemented easily, either.

**Comment by tsunamayo** [comment]
@TwoNiner29 Hi, so I finally implemented custom azimuthal / elevation min/max. I hope you are doing good! Cheers

**Comment by TwoNiner29** [comment]
Thanks @tsunamayo !!

**Comment by tsunamayo** [comment]
@TwoNiner29 By the way are you still willing to help a bit with some builds? Cheers

**Comment by TwoNiner29** [comment]
@tsunamayo of course, what do you need?

**Comment by tsunamayo** [comment]
@TwoNiner29 Thanks, I will open a new post on the github to let you know!
