### ISSUE TITLE
Warp fails to initialize from lightcruise

### ISSUE THREAD

**Issue by piotmetans** [tsunamayo/Starship-EVO#5137]
### Short Description of the issue:
While in lightcruise, it seems like a ship will point in the direction of the target system after initiating a warp jump, however it will not start warping. Warp still works normally from a complete standstill from what I've been testing.

### Steps to reproduce the issue:
1.  Pilot a ship and select coordinates to warp to.
2.  Enter lightcruise.
3.  Warp to your target
4.  The ship will redirect to the target, but will not being warping

### Environment
- Starship EVO version: 23w28b
- Graphics Card: RTX 2070 Super

### Additional information:

I used a completely new world/character and Surge's 'RAZORFACE' for the test if that helps any.
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12059791/Player.log)

Quick video demonstration. For the first warp, I initiated while in Lightcruise. For the second (successful) warp, I initiated from a standstill.

https://github.com/tsunamayo/Starship-EVO/assets/660015/be833a96-e571-407f-9db9-d6b9537595f5

**Comment by DrizztCode** [comment]
yup - i noticed this one too - it says warp initializing but you just continue at lightcruise
it does let you cancel, then cancel lightcruise, then warp

i expect it is because warp enables lightcruise in some fashion as part of its initialization, which it can't do when you are already at lightcruise, so is getting stuck at that stage (but thankfully in an active loop, so the cancel still works - good state machine safety there :))

**Comment by tsunamayo** [comment]
@piotmetans Hi, issue will be fixed for 23w39a. Thanks
