### ISSUE TITLE
1fps RTX 2080 unplayable

### ISSUE THREAD

**Issue by zaaubu** [tsunamayo/Starship-EVO#5172]
### Short Description of the issue:
when I launch the game it is at around 10fps in the menu, then when I load a save it takes minutes and task manager says 100% gpu usage, when the save is loaded it's at around 1 fps and is obviously unplayable, this issue did not occur a couple years ago when I played this game before.

### Steps to reproduce the issue:
don't know?

### Environment
- Starship EVO version: 24w29c
- Graphics Card: RTX 2080

### Additional information:

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12105590/Player.log)

**Comment by Kaiser-Indrasil** [comment]
Check in your nvidia control panel if you're using the dedicated RTX 2080 GPU or an integrated one built in your CPU.

**Comment by zaaubu** [comment]
It is a dedicated GPU, msi brand.

**Comment by DrizztCode** [comment]
i have an RTX 2060 6GB (and a Ryzen 5 3600 with 16GB DDR4) and my frame rate is fine (no overclocked components)

i get 100% GPU usage but that is pretty normal (i assume most 3D games are trying to push data through the card as fast as possible to get the best possible framerate)

possibly you have a driver issue, or something else is causing your system's resources to be bottlenecked

i assume you are not having problems with other graphics heavy games?

obviously it could be a strange interaction with this specific game

i am sure the dev will be requesting more information

but i wanted to mention my situation since i have a lesser version of the same graphics card generation

good luck

**Comment by zaaubu** [comment]
I don't think it's a game issue, I restarted my PC and it's running fine now, other games weren't doing it though so IDK.

**Comment by tsunamayo** [comment]
@zaaubu Okay thanks for the update!
