### ISSUE TITLE
Broken ship_preview

### ISSUE THREAD

**Issue by Battlepixel** [tsunamayo/Starship-EVO#5173]
### Short Description of the issue:
"ship".png ,"ship"_preview.png and "ship"_bloom.png are broken if you save an entity.
### Steps to reproduce the issue:
save your build

### Environment
- Starship EVO version:  23w29c
- Graphics Card: 4080

### Additional information:
if I save a ship or module i get:
![Test](https://github.com/tsunamayo/Starship-EVO/assets/43222403/06a8a603-05b3-444c-8fc1-cc6fbe098127)

but I should get something like this (older game Version):
![Sparrow Typ D](https://github.com/tsunamayo/Starship-EVO/assets/43222403/d045f33e-48d4-4690-9c91-ae89c0b12afe)

**Comment by DrizztCode** [comment]
note to dev:

i think this is very recent (possibly version c and later) - i noticed that my most recent blueprint did not have a preview and assumed it was a glitch that would be fixed by a reload - but i just noticed that it has no preview

it is possible the preview is just very very zoomed out since i recall i was seeing tiny previews at one point very recently

i will confirm by making some new blueprints - but looks like is a very recent bug

thanks for all the great work! :-)

**Comment by Crimson-Artist** [comment]
been having this issue since the planet update went live. Its annoying but at least the blueprints still load up

**Comment by tsunamayo** [comment]
@Battlepixel Hi, this is closed for 23w30a. Thanks
