### ISSUE TITLE
[Suggestion] Option to make the pipe part of Pistons invisible

### ISSUE THREAD

**Issue by Crimson-Artist** [tsunamayo/Starship-EVO#5185]
When pistons extend a grey pipe appears to connect the two halves. This pipe does not have a hitbox and can be walked through so it already does not effect gameplay. Wouldn't it be great if we had the option to render that pipe invisible so the two halves act more like floating platforms. This could be a option from the [F] context menu.
![20221217161805_1](https://github.com/tsunamayo/Starship-EVO/assets/112352428/9f8e3abc-2f3b-427d-8437-132d102c00bc)

**Comment by ProPeach** [comment]
You can place the piston on any part of your ship, then build you platform on that piston entity anywhere else on your ship to make things look like a floating platform. I don't really think a dedicated option would see much use personally.

**Comment by Crimson-Artist** [comment]
> You can place the piston on any part of your ship, then build you platform on that piston entity anywhere else on your ship to make things look like a floating platform. I don't really think a dedicated option would see much use personally.

some builds may not have space to place the piston elsewhere. its would be more straight forward to just be able to toggle the pipe on or off.

**Comment by BigBadKangaroo** [comment]
There could be an option inside the menu of the piston itself to "show piston pipe On/Off" 

Could be useful for "alien" ships to give the feeling of floating elevators etc

**Comment by Majikmonster** [comment]
The pipe already disappears if you can see the child entity half but not the base mechanism half of the piston, like how beams on the laser sensors vanish if the sensor brick isn't in frame. It's rather jarring and is probably unintended behavior. It wouldn't hurt to have 1 less thing to render, and not needing to hide the piston would be a benefit to compact builds everywhere. I see no downside to providing the option, and we don't know how much it would be used or not because we've never had the option available. Let's try it and find out. It can always be revoked later if it ends up being more trouble than it's worth.

**Comment by tsunamayo** [comment]
@Crimson-Artist Hi, I prefer to keep the physicality of the thing. I will try to fix the hitbox issue instead!
@Majikmonster Nope the culling bug has been fixed. Thanks
