### ISSUE TITLE
The pressurisation system is unreliable

### ISSUE THREAD

**Issue by SovietSponge** [tsunamayo/Starship-EVO#5303]
### Short Description of the issue:
The coverage of the life support brick is unreliable, sometimes the particles stop bouncing before actually finding every part of a complex area and leave said area only partially pressurised.
Sometimes the particles will stop in the middle of a doorway and declare the area to be leaking.
I'd suggest making it so the particles bounce around until they either designate the full area a life support brick can cover, or until they don't find a new spot for a few seconds, should significantly help with this issue.

### Steps to reproduce the issue:
turn the life support system on/off multiple times in a room with slightly complex passages
### Environment
- Starship EVO version: 23w41a
- Graphics Card: RTX3060Ti

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![image](https://github.com/tsunamayo/Starship-EVO/assets/66131361/41a3631f-5d9d-4263-a3da-65edb967d9be)
![example](https://github.com/tsunamayo/Starship-EVO/assets/66131361/f3632669-891a-4ab7-8ad9-395169127acb)

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/12894853/Player.log)
[example.zip](https://github.com/tsunamayo/Starship-EVO/files/12894867/example.zip)
I've attached the blueprint i was testing on

**Comment by tsunamayo** [comment]
@SovietSponge Hi, thanks for the bp I will have a look at it.
Btw what you suggest is exactly what I am doing already.
Cheers

**Comment by tsunamayo** [comment]
@SovietSponge Hi, I see this is a particularly adverse example because of the stairs. Particle have to bounce and find the stairs, multiple time. This is just unlikely...
 I would suggest placing several life-support systems, one every floor or every two floors should be enough.
 I might add a setting but I do not want to change the base search time until I see more examples, on ships that could be used for survival (as this is a survival mechanic).
Cheers
