### ISSUE TITLE
Volunteering 3D asset work for the project

### ISSUE THREAD

**Issue by Juice1box** [tsunamayo/Starship-EVO#5401]
Hello, a moderator on the discord server said this would be the best way to get the developer's attention. I wanted to contact you about possibly creating 3D models/props for Starship EVO. I noticed while playing the game that some of the blocks, while they look great and certainly get the job done, could benefit from slightly higher fidelity along with at least a bit more material and texture work. I think a potential revamp of these assets could lead to a stronger visual style/tone for the game as a whole. If we could set up a more robust way of messaging, I can send my previous work on some other projects and hopefully we can work something out. I of course am not asking for money- I just love what this project is doing and want to contribute.

**Comment by tsunamayo** [comment]
Hi, thanks a lot for contacting me, you can ask the mods for my personal address so we can get in touch. Unfortunately I do not plan to redo the bricks, the workflow is quite complicated because of how the texture works, with specials rules on how uvs are layed-out, and some really tricky stuff for stretching. 
Cheers
