### ISSUE TITLE
[Bug] Missions Board GUI opens up when loading a world

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Starship-EVO#5462]
### Short Description of the issue:
When I join a world, this GUI is open immediately
![image](https://github.com/tsunamayo/Starship-EVO/assets/27857711/f5a6e6bf-1263-4435-a111-937022006f5f)

### Steps to reproduce the issue:
- Load a world

### Environment
- Starship EVO version: 24w05a
- Graphics Card: RX 6700XT

**Comment by asanagisae** [comment]
I see value in being able to access the mission board without having to dock to the station, take the elevator, and find the mission kiosk. Additionally, it can be difficult finding a station in a new system since they don't show up as a target like ring worlds - you have to visually get within < 1km to be able to see it.

However, for survival, I imagine most of my time spent at a station will not be with bounty contracts. I'll be refuelling, repairing, trading ores, crafting, etc.

And in creative mode, 99.275% of the time I spend building instead of flying, and I certainly do not test combat until I'm almost done. If I want to take on a combat mission, teleporting to the station is available in creative mode.

For those reasons, perhaps we could explore an alternate solution to having the mission board pop up on world load? Maybe if you tag yourself as a bounty hunting class, the game will show you the bounties available in a system so you can clear them and hop to the next system? But if you're not a bounty hunter, these alerts don't show?

**Comment by tsunamayo** [comment]
@ProPeach Hi, well I have loaded plenty of world and I didnt saw this. Do you get this also when creating a new world?

**Comment by tsunamayo** [comment]
@asanagisae This is a bug ^^

**Comment by asanagisae** [comment]
I got it when creating a new world.
24w05a, main build

![image](https://github.com/tsunamayo/Starship-EVO/assets/10069469/2757e505-f155-4aa7-bb8f-19355e088bd8)

**Comment by tsunamayo** [comment]
@asanagisae @ProPeach Okay I can reproduce, for some reason it is one of those not in the editor only in build bug, so it slipped through.

**Comment by tsunamayo** [comment]
@ProPeach Okay so I fixed the issue and reuploaded the build as it was a regression. Thanks
