### ISSUE TITLE
Steam Achievements-tied tutorial system feedback

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#5525]
Regarding [your questions and remarks](https://github.com/tsunamayo/Starship-EVO/issues/5464#issue-2124320616) in #5464, I wanted to address the following point:

> An help for beginner is of course needed. I dont want a full blow tutorial, I will most likely use tied the progression help with the achievements system on steam.

I feel like the players wouldn't like this solution, as most of them don't like to be forced to go out of the game in search of basic gameplay info. I remember being frustrated with my first hours of playing Minecraft and Space Engineers because they didn't have good in-game tutorials.

[In this video, Game Maker's Toolkit](https://youtu.be/-GV814cWiAw?t=85) provides examples of great tutorial practices, if you want to take a look.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil so here what I meant by achievement based:

I will have a window tracking the player progression. If the player dont really understand what to do next they can refer to that.
There will be a list of "technological" tier showcasing what to do: ie build an hovercraft to explore more easily, build a h2 farm to make fuel for a spaceship.
Instead of just having a list and letting the player understand himself what has been done or not, I will have each of this milestone tracked and "unlocked" by the player, which 100% similar to what achievement does. Ie run 5km in a hovercraft, craft 100kg of h2 and so on. 
Then you can click on a milestone to get the relevant page of the help, for example on the hovercraft one.
These milestones would be regular steam achievements, because why not? I would add other achievements too. 

There no way I am doing a tight mission based like the previous tutorial, ie go there, do that. It almost killed the game because of the negative reviews, it was really super stressful as I had very little input on what to fix as newcomers are more likely to give up or leave a  neg review rather than create a github case. Lesson learned - I am just not able to tackle this as a solo dev on such a complicated game.

Cheers

**Comment by Kaiser-Indrasil** [comment]
Okay, as long as the player is able to have the achievements tracked within the game itself, without having to break immersion and going outside the game, I think it's fine.

I think Minecraft did a similar thing with its achievement tree, where it represents different milestones.

I'm optimistic it will work based on how you described it.
