### ISSUE TITLE
Walking feels laggy

### ISSUE THREAD

**Issue by Kaiser-Indrasil** [tsunamayo/Starship-EVO#5529]
This issue has been present in the game for years and has been brought attention to by many novice players and I think that I finally have a tangible way of showing exactly what's wrong with the feel of walking in the game.

Both the key presses and key releases introduce a highly noticeable latency which might be perceived and described by players as the character drifting or sliding.

The issue is best visible on the video below.

The movement curves - both acceleration and deceleration - feel alright, but the input lag is what sabotages the movement so badly.

https://github.com/tsunamayo/Starship-EVO/assets/63756057/277abbfb-ddb0-4b13-a65f-54cbc7f9eb37

**Comment by ProPeach** [comment]
It definitely feels like the player takes an additional step or two *after* you release the key. It's only really noticeable when you're walking around, which is why it has perhaps not seen so much attention before with people flying around in creative

**Comment by tsunamayo** [comment]
Yes I am not satisfied at all with the character locomotion, this seems to be another pb, like latency within the game. I investigated that back in the day, there are some hard Unity limitation that I cant really fix. What are your fps @Kaiser-Indrasil? The lower the fps the more sensible it be, because there are several frames between your input and the action happening on screen.
 The release is another thing I can try to improve though.
Cheers

**Comment by Kaiser-Indrasil** [comment]
I am getting solid 60 fps, but the issue persisted even before the cap, when I had double the fps.

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil @ProPeach Hi, is it better in the recent update? I changed the code to improve that. Also Kaiser what is the soft you used to overlay your keyboard input?

**Comment by tsunamayo** [comment]
@Kaiser-Indrasil @ProPeach Okay I found your soft Kaiser, also I dug a bit deeper, indeed there is a 6 frames delay - at 60fps, so 0.1s - not quite a second of course (that would have been unplayable), but definitely noticeable. I will improve that!
