### ISSUE TITLE
[Survival Mode] Assemblers can't work simultaneously 

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5581]
### Short Description of the issue:
If you place 2 assemblers connected with the cargo they don't work at the same time

### Steps to reproduce the issue:
build 2 assemblers
set them for construction

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

https://github.com/tsunamayo/Starship-EVO/assets/93534629/d87d9792-a8c7-400c-be82-c1aeb1acacb9

[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14387016/Player.log)

[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/14387019/Player-prev.log)

[Outpost.zip](https://github.com/tsunamayo/Starship-EVO/files/14387022/Outpost.zip)

**Comment by tsunamayo** [comment]
@surajnairpv Hi, so I managed to get this working, the problem is with your piping. With small pipe they will take a given time before they can be used again to transfer another item. So only one assembler gets its query working, the other one have to wait for the transfer to be completed. With each assembler having its own piping there is no wait.
I will see if it makes sense to make the time-out shorter.
Thanks

**Comment by surajnairpv** [comment]
Okay thanks for letting me know, will try this out
