### ISSUE TITLE
Can water from the ring worlds be processed?

### ISSUE THREAD

**Issue by Aranhanauta** [tsunamayo/Starship-EVO#5620]
### Short Description of the issue:

Due to my low FPS, the game always crashes when I try to land on planets, especially those with vegetation.

I thought that the only way to get water then would be in the Habitats rings, however, I positioned two fuel collectors in the water in a lake in the ring, connected to a tank, however, the tank would not fill.

We know that the terrain of the Habitats rings do not generate ores, does this happen with water too?

### Steps to reproduce the issue:

Position a fuel pickup in "scoop" mode in the water in a Habitat ring attached to a tank configured to store water.

Attach a panel to the tank configured to store water and observe whether the tank will fill.

Other players have also reported this same issue.

### Environment
- Starship EVO version: 
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by Huttrem** [comment]
@Aranhanauta yeah, if you need hydrogen get it from clouds and for oxygen it refill in space station for free, i do also play wit low fps

**Comment by DrizztCode** [comment]
> @Aranhanauta yeah, if you need hydrogen get it from clouds and for oxygen it refill in space station for free, i do also play wit low fps

i can't get it to refill am oxygen tank on the station - the refuelling station said the correct amount (although i don't think it specified the gas type) - and every time i clicked it took the credits - but when i returned to my ship the tank was empty

can you confirm that you have been able to refill O2 at a space station please? otherwise i will raise a bug report (gonna do one for the station continually taking the credits anyway - but want to keep these issues together)

thanks :-)

**Comment by Huttrem** [comment]
@DrizztCode you dont refill the oxygen tanks, the life support do, so you use bottle from life support and refill your oxygen tanks
the life support auto refill if you are close to statation you can build some life supports so easy to get more oxygen

**Comment by DrizztCode** [comment]
> @DrizztCode you dont refill the oxygen tanks, the life support do, so you use bottle from life support and refill your oxygen tanks the life support auto refill if you are close to statation you can build some life supports so easy to get more oxygen

hi - thanks - i have not found the life support refilling near a station - that's why i tried with an oxygen tank

i have not tried hooking pipes from the life support to an oxygen tank - so i will see if that works - but that won't change much if the station does not fill either of them - it will just mean i can fill the tanks from the bottles instead of the life support unit

and the station refuelling kiosk does seem to read the O2 tank - it even charges credits to refill it - but just keeps charging the credits without refilling it - but maybe it is just confused and is trying to fill it with H2, but the tank is set to O2

anyway - thanks for the info - i assume you are playing on survival? or are you playing on creative with the oxygen feature enabled? (since that may make a difference)

**Comment by Huttrem** [comment]
@DrizztCode no survival, life support is supposed to magically refill went you are close to the space station, if is not doing it is bug

**Comment by DrizztCode** [comment]
> @DrizztCode no survival, life support is supposed to magically refill went you are close to the space station, if is not doing it is bug, i run a test and is working fine here

ok thanks - i shall have a play on Creative and see if it behaves differently - and then i will likely log a ticket, since there are some other weird things with the life support unit (sometimes it gets "stuck" and you need to either add and remove a block on the ship to get it to work, or actually remove and rebuild the life support unit itself to get it to pressurise) - plus i want to request a 'depressurise' feature so we can make airlocks and not lose O2 every time we open a door. Also would be good to be able to attach life support to O2 tanks - and then we could possibly use the tanks as airtight walls (since we can't run pipe into airtight spaces)

anyway - thanks for the clarification :-)
