### ISSUE TITLE
[Survival Beta] What I hate about containers the most.

### ISSUE THREAD

**Issue by Jimvanhazendonk** [tsunamayo/Starship-EVO#5637]
### Short Description of the issue:

When I remove a container by accident that still contains items, the items disappear. This is a real PITA.
The container I removed had all my ingots, which took me hours to collect and smelt. :(

Would it not be better just like in Minecraft that when you remove a container that still has items the items gets dropped on the floor or something.

A resource scanner would massively help locate certain ores.
An "undo last action" would also solve this issue, obviously.
...

Otherwise, thus far great game. 
Still struggling to understand the basics things... like how to create fuel and when I have fuel how to refuel things.
For some reason when I build a Hovercraft the reactor has no fuel and the tanks I add to them also.
Have not been able to use a vehicle so far for this reason... except if I do something wrong. I watched some YouTube video how to build but no cigar.
Could someone tell me some basics?

**Comment by DrizztCode** [comment]
just FYI - that issue with the containers has been raised as issue #5635

as far as fuel goes - pipes are what you need - and an electrolyser - and a wind turbine (or solar panel) - and a fuel scoop

ok - that's quite a lot lol

so i can make a video about it - but here's the basics:

1. build an electrolyser
2. connect that electrolyser (using pipes) to a fuel scoop that is submerged in water
3. if everything is going well when you use the link tool and click on the electrolyser, you should see it filling with water and converting it to H2 and O2
4. you can then create fuel tanks and attach them to the electrolyser (again with pipes)
5. use F to interact with the tanks to change one to oxygen storage (they always start as hydrogen)
6. you can then use gas bottles to transfer fuel from tanks on the base to tanks on your ship
7. the tanks on your ship need to be connected to the reactors (you cannot directly input fuel to a reactor with a bottle)

ok - i'm sure that was not a great explanation

when i get a chance i shall make a video showing it (but it will just be a visual recording of gameplay - i am not a proper youtuber lol)

**Comment by DrizztCode** [comment]
here are some pics of a basic setup that may help:
![20240303184713_1](https://github.com/tsunamayo/Starship-EVO/assets/104569043/28054c0a-5dd0-4fbd-b3d7-53e9dd4bfd93)
![20240303184720_1](https://github.com/tsunamayo/Starship-EVO/assets/104569043/2384535e-a3f4-4f1c-9600-3b96fbf0d2bf)
![20240303184728_1](https://github.com/tsunamayo/Starship-EVO/assets/104569043/b0087e5a-8842-41d4-8e4c-8710487806bd)
![20240303184749_1](https://github.com/tsunamayo/Starship-EVO/assets/104569043/858fc93f-2bdf-48d7-8857-ba8f8ed7c07f)

**Comment by Jimvanhazendonk** [comment]
> just FYI - that issue with the containers has been raised as issue #5635
> 
> as far as fuel goes - pipes are what you need - and an electrolyser - and a wind turbine (or solar panel) - and a fuel scoop
> 
> ok - that's quite a lot lol
> 
> so i can make a video about it - but here's the basics:
> 
> 1. build an electrolyser near the sea on a base with power
> 2. connect that electrolyser (using pipes) to a fuel scoop that is submerged in water
> 3. if everything is going well when you use the link tool and click on the electrolyser, you should see it filling with water and converting it to H2 and O2 (and it should have a blue or green light)
> 4. you can then create fuel tanks and attach them to the electrolyser (again with pipes)
> 5. use F to interact with the tanks to change one to oxygen storage (they always start as hydrogen)
> 6. you can then use gas bottles to transfer fuel from tanks on the base to tanks on your ship
> 7. the tanks on your ship need to be connected to the reactors (you cannot directly input fuel to a reactor with a bottle)
> 
> ok - i'm sure that was not a great explanation
> 
> when i get a chance i shall make a video showing it (but it will just be a visual recording of gameplay - i am not a proper youtuber lol)

thank you for the explanation!
I Had just a pipe in the water without a fuel scoop. it did not come into my mind to use it since on the wiki it says its used in space to scoop "fuel"... or I did miss some text text somehow.
I will give it a try and let you know :)
As for your post, I had not seen it but I'm happy I'm not the only one annoyed by this. I had to struggle to continue the playing. Especially since moving around by foot is soo slow even with the jetpack.

Would be great of some people, you and others create some videos about survival tricks. not a lot of content about S.Evo online

**Comment by DrizztCode** [comment]
> thank you for the explanation! I Had just a pipe in the water without a fuel scoop. it did not come into my mind to use it since on the wiki it says its used in space to scoop "fuel"... or I did miss some text text somehow. I will give it a try and let you know :)

i have not actually been on the wiki (usually wikis are on 3rd party hosting sites and i have enough companies trying to advertise to me lol - so Github is my limit :-))

but as for it not saying that it is used for the electrolyser - it is a relatively new mechanic - and so previously the fuel scoop was only used for harvesting fuel in space

i tend to read the release announcement for a particular mechanic or block if i am having trouble with it - and then searching for the term here on the issues board may well help

plus i may also have figured it was the only thing that could possibly suck up a liquid lol :-)

but most likely i saw a pic or read something in a post

anyway - i am glad my tips helped :-)
(at least i hoped they helped)

>As for your post, I had not seen it but I'm happy I'm not the only one annoyed by this. I had to struggle to continue the playing. Especially since moving around by foot is soo slow even with the jetpack.

i wouldn't say i'm annoyed by the cargo issue - it's just a bug or unintended feature - the whole point of Early Access and the survival mode beta is to report the bugs and make suggestions and point any other weird things lol

i agree it is dangerous to be able to delete a whole container load of stuff with one bad click - especially because sometimes the player can start sliding at any moment lol

i do think there is an argument for a way to lock the delete function with a keypress - so it does not work till unlocked

but that is a further discussion

the priority in this regard would be to have a decision box pop up when the player tries to delete a block that has a non empty inventory - and then they can say yes if they actually want to destroy the inventory, or no if they want to empty it first

and maybe there can be an option to not have the dialog and always have the contents spawn in the world - but likely that could cause some major issues with large numbers of items spawning

so again - discussion needed about the best way forward, with Tsuna being the final arbiter of how it gets done - we are just helping :-)

also as for the movement - Tsuna has said that he wants to work on it - but again there are many things to consider

are you using the boost mode? that is the fastest way to travel in gravity in survival mode - holding shift

and if you are in creative mode you can use the fast move keys (press F1 and activate the option and then the [ and ] keys will increase your move speed up to insane levels lol)

> Would be great of some people, you and others create some videos about survival tricks. not a lot of content about S.Evo online

like i say i am not a youtube creator - i tend to just make videos to show bugs

i may well make a few short videos of gameplay for some basic stuff

but it would just be with game audio and no commentary or editing - since like a say - i am youtube watcher not a creator lol :-)

**Comment by tsunamayo** [comment]
@Jimvanhazendonk Hi, thanks I will fix that issue indeed. I also plan to add an help page on the fuel crafting once things are stable enough. Cheers

**Comment by tsunamayo** [comment]
@Jimvanhazendonk Hi, issue is fixed for 24w10a. Cheers

**Comment by Jimvanhazendonk** [comment]
@DrizztCode 
> but as for it not saying that the fuel scoop is used for the electrolyser - it is a relatively new mechanic - and so previously the fuel scoop was only used for harvesting fuel in space
It made sense afterwards. I tried it and it worked instantly. I was the only thing missing in my puzzle. Also with the transfer of fuel with the bottles. I had enough plates still in my parts container to create some. whith those I was able to refuel my hovercraft and start looking for ores again that I lost in the container deletion. Thank you :)
I'm happy that I dont have to walk again. The Boost does help a bit but I find a bit annoying that is has to recharge. It should last a little longer in my opinion.
for longer distances I use the "no clip" to go a little higher and move in the direction I want to go. 
 
@tsunamayo  
> Hi, issue is fixed for 24w10a. Cheers
The speed with which you work is exemplary
The game you created is amazing. it's addicting!
Merci beaucoup!

**Comment by tsunamayo** [comment]
@Jimvanhazendonk No pb merci ^^

**Comment by DrizztCode** [comment]
> It made sense afterwards. I tried it and it worked instantly. I was the only thing missing in my puzzle. Also with the transfer of fuel with the bottles. I had enough plates still in my parts container to create some. whith those I was able to refuel my hovercraft and start looking for ores again that I lost in the container deletion. Thank you :)

happy to help :-)

> I'm happy that I dont have to walk again. The Boost does help a bit but I find a bit annoying that is has to recharge. It should last a little longer in my opinion. for longer distances I use the "no clip" to go a little higher and move in the direction I want to go.

i find that the boost sort of always works - if i just hold shift and move forward it keeps boosting, since it always recharges, and only needs a tiny bit to do a boost - is kind of like the "Vegetable Soup Exploit" in Skyrim, that allows infinite power attacks

anyway - i am sure there will be some changes to the movement system going forward

hope you're having fun :-)
