### ISSUE TITLE
[Query] Can we create these thrusters? turn vertically when flying up then turn horizontal to move forward.

### ISSUE THREAD

**Issue by surajnairpv** [tsunamayo/Starship-EVO#5799]
### Short Description of the issue:
I noticed there is no over drive options in the thrusters where we can keep them on constant thrust irrespective of the navigation controls like how Space Engineers has. Is there a possibility of creating this kind of thruster that rotate facing up to go up and rotates side ways to go forward like on this video.
https://www.youtube.com/watch?v=eCEMNB_Ll9Q
skip to 8:52 

if possible let me know how it can be done, thanks

**Comment by TIKIRobo** [comment]
I'm a little confused about what you're asking I mean you can make rotating thrusters, there are plenty of examples of this on the workshop, but automatically rotating thrusters that don't use a keybind would likely require some more options on the event gate. unless you are asking for the ability to force thrusters on which is not possible, maybe you could explain yourself better or instead head to the discord server and ask for help there? you'll get a much faster response if you ask on the discord

**Comment by asanagisae** [comment]
I'm not sure what you're asking for. VTOLs _are_ in this game, and they do have a functional impact on your ship's flight. You trigger them with a button exactly the same as in your video around 8:52, you just have to configure your ship to respond to that button (the same as in Space Engineers).

https://github.com/tsunamayo/Starship-EVO/assets/10069469/f1c7dc46-1993-4e85-bff4-d51247685104

You set it up with the link tool this way:

Yoke > Event Gate > On/Off Switch > Sequencer > Rotor or Hinge

The Event Gate is set to listen on "Hotkey 1 pressed" or similar.

The Switch keeps track of which position the VTOLs are in.

The Sequencer tells your rotor or hinge how far to turn.

**Comment by Crimson-Artist** [comment]
As others have said in this thread is very possible to do this with logic. However if you are asking for thrust recalculations you can also do that with logic. Thrust calculations are done the moment you take control of a ship. When thrusters are pointing downwards they give you enhanced turning but unless you force a recalculation they will continue to give that plus to turn speed even if the thrusters have changed directions. link a button to a not gate then link the not gate to the thrusters to have a manual thruster recalculation. You should link this to the circuit responsible for changing the positions of the arms so that thrust is always recalculated whenever the arms shift.

Also you can automate the transformation if you use the volumetric sensor to sense the ground. The "Trigger on item enter" will go off if the sensor senses rocks that spawn on the surface of planets. Just give the sensor a wide range and it should automatically trigger the change when your ship gets close to the ground. also note that this only applies to planets and maybe asteroids. the sensor can not pick up rocks on the habitat

**Comment by tsunamayo** [comment]
@Crimson-Artist yes for now only lightcruise is being recomputed live, I will also adds normal thrust computation. I hope that answer your question @surajnairpv

**Comment by surajnairpv** [comment]
Thanks for the response guys @TIKIRobo @asanagisae @Crimson-Artist @NoxyNixie , 
I had tried creating a ship like this before but for some reason wasn't able to activate the thrusters that rotate. Will surely try out your suggestions.
