### ISSUE TITLE
[Bug] Ship still spinning out of control upon spawn

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5830]
### Short Description of the issue:

Ships with power cells spin out of control when spawned. This is the old reported issue, now closed, but the issue persists.

Another user ran into this issue, probably after your fix was pushed. I'll see if I can get them to elaborate.

This was marked fixed in #5809 for 24w25a. I am seeing the issue in 24w25b [mech]. Could it be that the fix wasn't included?

### Steps to reproduce the issue:

1. Place a new starter block in the air (not on terrain), not near terrain
2. Use it to spawn in a ship with a power cell base on a CE with a power cell already installed
3. Observe as it spirals away

### Environment

I tested on: 24w25b [mech]

### Additional information:

https://github.com/tsunamayo/Starship-EVO/assets/10069469/e6f97082-070d-4b5e-9243-0d787f6ca9f5

Here's the blueprint for convenience:

[Galapagos.zip](https://github.com/user-attachments/files/15959757/Galapagos.zip)

**Comment by Tackietacktack** [comment]
hi tsuna, have the same bug. 
I think it could be something with the docking connector.
in this zip are two ships.
Confix is the small one which is docking on the ashinger carrier.
Sometimes i don´t can docked on because something is there but invisble.
can it be that the failur comes if we close the game with docked entries? or save the ship with docked entries?




https://github.com/tsunamayo/Starship-EVO/assets/97230091/a5634beb-9d68-47b0-8af1-474e1a4c1aa2

[ashinger and confix.zip](https://github.com/user-attachments/files/15959990/ashinger.and.confix.zip)

**Comment by tsunamayo** [comment]
@asanagisae Hi, okay I think it should be right this time in 24w26a. Cheers
