### ISSUE TITLE
[Suggestion]  Warp core building limitations and in efficenties in fuel attachement

### ISSUE THREAD

**Issue by darkvoid305** [tsunamayo/Starship-EVO#5898]
I have a suggestion regarding the new fuel and distance mechanics related to the warp core.

Currently, you need two things to make your ship jump: the warp core, of course, and the fuel. This is logical and clear; however, the way fuel works feels a bit strange. In a car, the amount of fuel determines how far you can travel. In Starship Evo, the distance is determined by the size of the warp core. I feel this creates a creative building limitation and also feels a bit odd gameplay-wise.

To address this, if possible and if the issue is recognized, I suggest the following:

1. Calculate the minimum warp core size needed for a ship based on its size. This would mean that the warp core multiblock would still exist but have a different reason for being scaled up. with a minimum size to make sure it is actualy still usefull to all ships currently if you just add one warp core block it wont be usefull at all i suggest a minimum size that allows for 2 ly jumps for the ship size.

2. Add some distance modifications for warp cores, similar to how you have adjustments for the guns. efficiency modifiers

3. to solve a small building limit issue: currently, when you build your giant warp core into your ship and want to travel, you have to attach the warp fuel directly on top of the warp core. Could we make it so that the fuel could be supplied through pipes, as shown in the following picture?

4. make it so that the fuel in the ship isnt deciding how many jump you can do but how many time the max distance of the engine can be chained together into a potential single jump (like how in cars the more fuel you have the farther you can travel)

I hope this input has been usefull in some regard

![sugestion](https://github.com/user-attachments/assets/9e1b586b-9428-473d-bebc-50c516fef2ac)

**Comment by tsunamayo** [comment]
@darkvoid305 Hi, thanks for the input.
I dont quite agree with the initial premise though. Having warp range being determined by the number of warp core is not likely to change.
Otherwise we would get a tricky and boring design decision for the ship builder as it means that for a given ship mass you need to build a core of a single size. Less would work, more would be useless.
- It is confusing and frustrating for newcomer if they didnt put enough warp core and the ship is not jumping.
- It is painful if later on you want to add more mass on your ship
- It is boring as it removes a design decision (how many warp core can I build)
- It is more complex as you would need another addon.

Thanks

**Comment by asanagisae** [comment]
Say your warp drive has 50 Ly range and your final destination is 50 Ly away. There is an incredible amount of value in visiting 10 systems along the way compared to jumping directly to the destination. Combat-type ships can check more mission boards and clear them, mining ships can haul a lot more ore, traders can score a lot of deals, etc.

The total distance you travel is less important compared to the systems you stop in: that is, the _number_ of jumps is more significant than the total distance of the jumps, unless your goal is to cross the galaxy. Warp pearls represent access to one system's resources, untouched and ripe for your taking. It's the cost of opening the fabric of space to cross great distances, it's not about the distance itself.

As for maximum distance, many other blocks in SEVO (reactors, shields, thrusters, etc.) have varying performance based on the scale of the blocks. You can use bigger scales (1m instead of 1/2m), taking up more space, but reducing the heat generated by the block. Warp cores are no different. There would be more consistency within the game if warp cores continued to control warp distance based on the size and scale of the blocks. It is not odd at all when taken within the context of SEVO.

The design decisions for the player are very interesting in the current game. Do I want a ship to be tanky with shields? Do I want it to travel fast within a system? Do I want to cross the galaxy in fewer jumps than anyone else? No ship can do it all, and you have to make a decision. It also means you will outperform ships that choose to divide their focus between other areas.

However, I do believe there were plans to connect Warp Cores to Cargo Containers with tubes so that Void Pearls can be transferred to the Warp Containers automatically. So the answer to your point 3 should be "yes".
