### ISSUE TITLE
[Survival] [Suggestion] Stone transfer to Arc furnace

### ISSUE THREAD

**Issue by Vandrid** [tsunamayo/Starship-EVO#5903]
The Arc furnace does not pull stone from storage container like other ores.

**Comment by asanagisae** [comment]
Stone can be used to craft decorative stone hull blocks. Some players might prefer to use stone for that at some phase during their play through.

However, it would definitely be nice if the Arc Furnace had the option to pull stone from cargo like other ores, including some of the larger rocks you can pick up from the surface.

**Comment by tsunamayo** [comment]
Hi, I see, I guess I could have an option in the furnace setting.

**Comment by Dwarf-LordPangolin** [comment]
I agree that an option to enable this would be very useful. asanagisae is correct in that sometimes you want stone to be reserved for other uses, but it's also true that sometimes you want to make a lot of silicon.

This is honestly something that applies to a lot of resources, because you might want more control over what goes through your conveyors. Instead of adding a toggle specifically to the arc furnace, would it be more efficient in the long term to add a "filter" block for the Conveyors that can whitelist or blacklist which items can pass through it? That would allow more precise sorting of conveyor networks, so things can be connected without necessarily being accessible to the whole network. Space Engineers has [something like this](https://spaceengineers.fandom.com/wiki/Conveyor_Sorter), and it's very useful.

**Comment by tsunamayo** [comment]
> I agree that an option to enable this would be very useful. asanagisae is correct in that sometimes you want stone to be reserved for other uses, but it's also true that sometimes you want to make a lot of silicon.
> 
> This is honestly something that applies to a lot of resources, because you might want more control over what goes through your conveyors. Instead of adding a toggle specifically to the arc furnace, would it be more efficient in the long term to add a "filter" block for the Conveyors that can whitelist or blacklist which items can pass through it? That would allow more precise sorting of conveyor networks, so things can be connected without necessarily being accessible to the whole network. Space Engineers has [something like this](https://spaceengineers.fandom.com/wiki/Conveyor_Sorter), and it's very useful.

Yes I think that would be the most elegant way to do indeed, I wanted to add a filter tube for a while.

**Comment by tsunamayo** [comment]
@Vandrid Hi, issue fixed for 24w34a. I will work on the filter soonish.
