### ISSUE TITLE
[bug] Trees inside container 

### ISSUE THREAD

**Issue by Tackietacktack** [tsunamayo/Starship-EVO#5921]
### Short Description of the issue:
after restart the game, i have tree in container but i dont know why

https://github.com/user-attachments/assets/1161e702-db49-43d7-916f-f913fcf4e596

...

### Environment
- Starship EVO version: 24w30b
- Graphics Card: 

### Additional information:

[blalal.zip](https://github.com/user-attachments/files/16487976/blalal.zip)

[Player.log](https://github.com/user-attachments/files/16487974/Player.log)

**Comment by asanagisae** [comment]
I've had this issue before. I haven't tried to determine exact steps, but generally it happens when I have an item collector connected to a cargo container on a ship, and I fly the ship around a planet surface trying to scoop up ores I mined. It's more likely to happen if I increase the collector's range to several hundred (meters?).

**Comment by Tackietacktack** [comment]
That's right, collector has 300m range.
One possiblity is that I was fly near by ground between trees.

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, this is a bug with collectors, I still need to reproduce it to understand what went wrong. I keep you posted.

**Comment by tsunamayo** [comment]
@Tackietacktack Hi, I finally reproduce, issue fixed for 24w35a. Cheers
