### ISSUE TITLE
World Child Entity Limit? / Saving Bug

### ISSUE THREAD

**Issue by talrey** [tsunamayo/Starship-EVO#839]
### Short Description of the issue:
I have a build in my world that uses a _lot_ of child entities - they're all for moving parts, I promise!

I noticed that at some point, trying to place any more on that ship caused the "child half" of a slider / hinge / rotator to not appear, and the game no longer saved the ship (my character saved, but the save icon did not appear). Now, having heard rumors of a "child entity limit" I wondered if I had encountered it - I don't know if it's even in the game yet - and decided to see exactly how many child entities it would take to recreate the issue.

Having done that, I decided to work on a different ship while I considered how to reduce the count on the "problem ship". However, placing only a few rotators on the new ship was enough to cause the same behavior! It seems as though I've hit some kind of soft limit on the total number of entities in my world, because I can still fly around, build, and use menus - I just can't save any ships.

### Steps to reproduce the issue:

I'm not entirely sure beyond "have a ton of child entities in a world, try to place more"... Sorry.

### Environment
- Skywanderers version: Experimental, 18w20a
- Graphics Card: Nvidia GeForce GTX 970

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2056349/output_log.txt)

**Comment by Sullos** [comment]
I too am experiencing this same problem.
After building a ship will many child entities on it, to be able to achieve a shape that isn't achievable with any other methods.
I of course know your stance on this sort of building Tsuna, however, your game is the only game that allows me to build a ship like this...
![711980_20180601164755_1](https://user-images.githubusercontent.com/33239800/40825702-cdcd59dc-65bb-11e8-9cd4-a0089e5482bc.png)

I truly want to build this ship, but I simply can't finish it with this "soft limit" on child entities.

And I hope that something can be done about it - that wont stop me from completing it.
Its a long time dream of mine to build the Enterprise.
I hope I haven't caused any physical or emotional pain by using so many child entities Tsuna.
Thanks

Version: Stable
Graphics Card: Nvidia Geforce GTX 980Ti

**Comment by tsunamayo** [comment]
Hi guys, could you please send me your blueprint so I can view how entity are used and confirm it is coming from this? 
It would help also to find back-up solutions for when the time come to fight children entity spam. 
Thanks

**Comment by Sullos** [comment]
Hey Tsuna, below is an attached zip file with the 2 ships I had in the world at the time.
One of them is a near complete Bomber, as you will have seen a while ago. However most of the child entities on it are functional.
Along with an In progress Enterprise, I was working on the Enterprise at the time, and after placing a few child entities, you should encounter the bug.
I do hope seeing these builds doesn't cause too much pain seeing how child entities are being used.

As for solutions, I have only two which I believe are most appropriate.
1. Perhaps prevent clipping of bricks and blocks inside of each other to a degree. Blocks can only be placed so long as they only clip less than 50% into the block they are clipping into.- However I feel this solution might be difficult to implement and may not work as well as anticipated.
2. This one I feel is the best option - have child entities per ship limited, but only as a server setting.
The true problem I see with child entities is that many of them on large ships will cause frame rate drops for other players if they have a computer not as good as the other person with them.
By having a 'limit' on the amount of child entities per parent entity, I feel servers can be orientated towards particular play bases. 
I could run two servers, one server for smaller ships, people having fun, working together on multiple ships, and a server where people with very high end PC's can rule larger more complex, PC intensive ships. 
I know there is a desire for a limitation on child entities, but I only see child entities being a problem in multiplayer, if someone wants to cheat in singleplayer with a layered hull, let them. But only in multiplayer is it an issue. By having a server based setting saying 30 child entities per ship, people should want to design a ship as best they can with the limited child entities they have access to, rather than creating some gargantuan cheat machine.
This could work along side with a ship size limiter, no more than a particular mass for the amount of room it takes up. 
I just don't think there should be any limitations on the singleplayer, building for fun side of the game.

Also, again, sorry if the ships attached are an offense to your wonderful game. I can get carried away sometimes. Please don't let this reflect other peoples building styles though.
Thanks Tsuna
[Enterprise Blueprint.zip](https://github.com/tsunamayo/Skywanderers/files/2066512/Enterprise.Blueprint.zip)

**Comment by talrey** [comment]
I would attach my world as well, but I deleted basically every build in it except for the one I'm working on right now, and the issue has gone away. Because of this, I'm not sure if it would still be useful to upload my blueprint / save. I'll still do so if you want me to, and if the issue appears again I definitely will upload it!

**Comment by tsunamayo** [comment]
Yeah I think I know for the issue, it is more for me to see how you guys are making use of the children entity so I can come up with idea to replace their use. Thanks

**Comment by Tomatart** [comment]
i think rounded freeform would solve 90% of the issues from child entity spam, since it is pretty much always used to achieve round shapes. 
Perhaps if you released a basic type of rounded freeform, and allow the child entity spammers to explore it and see how effective of a replacement it could be. Based on their findings you could then improve the rounded freeform, or scrap it if it doesn't work well.

**Comment by Sullos** [comment]
@tsunamayo 
Thanks for the feedback, I really do like pushing the limits of a game, but that being said I feel like Enterprise isn't pushing the limits too much. I am trying my best to make sure the blocks don't clip, and in areas that are currently clipping that I will go over them again once more various forms of freeform are added.
Regarding option 1. 100% is a fair assessment, and I can see that being okay, because even with a very small amount of clipping people could probably find some way to exploit it. If it comes down to it, which I hope it doesn't, it could be a solution.
However, I still believe the server sided limitations is the answer. People will play on servers that they want to, set up the way they like. Many games do this already, not so much with a block clipping/child entity limiter, but rather say an Experience multiplier. Players go on a server with an experience gaining multiplier at a level they like.
Of course I respect your plans and I see that there are going to be reasons against it.

Tomatarts solution above is a good suggestion that I would love to try out. 
And not that the current freeform isn't enough. Its just that to achieve a curve like what can be achieved hinges, you need many freeform. And on an Enterprise level of curvature, I would need to put in 5x as much work.

All this aside, I was hoping to find out whether or not we could hopefully get a fix on the child entity limitation bug. As all child entity problems aside, I would like to try and finish the Enterprise even if it does just end up being a showpiece later on. 
Thanks Tsuna

**Comment by tsunamayo** [comment]
@Tomatart yes I agree rounded freeform would help. I just want to do the freeform update first to not build on the current tech as it will evolve. The freeform update could also be a solution to rounded case (not always), as you would be able to create basically custom shape and reuse / rotate them like every other block. But the round freeform would be the best solution for sure, I just need to think a bit more about it (not that easy)

@Sullos Ah yes I remember this one (the Mallacore), I would have to do something about the children entity blueprint for the reason you know ;-).

**Comment by Tomatart** [comment]
Another major thing with child entity vs freeform is that you cannot build off angled freeform faces. i understand that this is a limit of the block grid, but if ultimately there is no way to build off angled faces for details, (no more child entities for angles only freeform) then its honestly going to suck, because that means you cant detail anything with angles. 

So i dont know if you have any ideas for alternatives to allow building off angled faces, but that is something that i believe (an im sure many others will agree) should be an important thought moving forward.

**Comment by Name11ess** [comment]
Child entities can be really important to connect two angled "walls", which can sometimes only be done by merging them using child entities if we want them to be hollow.
