### ISSUE TITLE
Glow and Light blocks are missing.

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Starship-EVO#959]
### Short Description of the issue:
The Light and Glow blocks are no longer in the game. I used these blocks alot, especially the glow blocks. please bring them back 😭 
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: 
- Graphics Card: GTX 1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by ultrak2k** [comment]
I can confirm that the light blocks and glow blocks are indeed missing from the codex, please bring them back my star is looking sad

**Comment by tsunamayo** [comment]
Okay, just fyi I wanted to create a scalable "large" light / glow block with a form factor similar to the identity block (so a flat thing). Would that work for you?

**Comment by Tomatart** [comment]
Not for how i was using it, I would place them in indents on ships and cover them in bricks to create small glowing parts that didn't actually give off light. Here are a couple screen shots of how I used them: 
![screenshot 108](https://user-images.githubusercontent.com/26846110/47552175-f0c7ad00-d8b8-11e8-9034-16151702b177.png)
![screenshot 125](https://user-images.githubusercontent.com/26846110/47552179-f32a0700-d8b8-11e8-838a-36ae5d0d168e.png)

**Comment by Tomatart** [comment]
I know the light block is probably tricky because it actually gives off light, and that may need to be done specially to prevent lag, But if the glow blocks work differently, i say just keep that as a regular freeformable block, and adding a freeform brick version, just like with the regular blocks and bricks. with wedge variations ect.

**Comment by Rizzo911** [comment]
I was also using these quite extensively in Star Trek style builds for glowing parts like the deflector array and nacelles. I was actually hoping this was going to become a standard block/texture for all the shapes and rather than  borders, just allow it to glow a single color texture, similar to piecing together the standard hull blocks or when you first place them down and they are white, now borders. I don't need the lights version, but could we at least get a colorable glow texture version of the standard hull shapes. It would make them much more versatile.
